"""Actual1460 startup -> original835 -> continuous1198 producer/header/shear.

The source seeds/metadata/root and original spectra are actually produced.
Matching rows, inverse permutation, count and packed data are generic physical
entry arrays, not a feasible selected SeedChunk witness. Within1198 no host
writes, precomputed conjugate spectrum or prepared shear scales are supplied.
"""
from pathlib import Path
from copy import deepcopy
from math import gcd
from functools import reduce
import hashlib,json
from uniform_seed_cyclotomic_engine import Poly,F,scalar,execute,direct_dft
# Extend the versioned engine locally for the small cyclotomic subfields
# generated by these fixtures. General six-C scale inverses need not have a
# rational norm. Exact Euclid followed by product verification replaces that
# restricted diagnostic path; the shared engine file remains unchanged.
original_inverse=Poly.inverse
def polynomial_add(a,b,factor=F(1)):
    c=dict(a)
    for k,v in b.items():
        c[k]=c.get(k,F(0))+factor*v
        if not c[k]:del c[k]
    return c
def polynomial_mul(a,b):
    c={}
    for i,u in a.items():
        for j,v in b.items():c[i+j]=c.get(i+j,F(0))+u*v
    return {k:v for k,v in c.items()if v}
def polynomial_div(a,b):
    a=dict(a);q={};degree=max(b);lead=b[degree]
    while a and max(a)>=degree:
        k=max(a)-degree;v=a[max(a)]/lead;q[k]=q.get(k,F(0))+v
        a=polynomial_add(a,{j+k:w*v for j,w in b.items()},F(-1))
    return q,a
def exact_small_inverse(self):
    assert self.c,'zero scalar divisor'
    norm=self*self.conjugate()
    if set(norm.c)=={0}:return original_inverse(self)
    stride=reduce(gcd,self.c.keys(),self.D);d=self.D//stride
    if d&(d-1)==0:modulus={d//2:F(1),0:F(1)}
    elif d==3:modulus={2:F(1),1:F(1),0:F(1)}
    else:
        assert d%3==0 and (d//3)&(d//3-1)==0 and d>=6
        modulus={d//3:F(1),d//6:F(-1),0:F(1)}
    assert max(modulus)<=128,('fixture subfield exceeds explicit bound',d)
    a,b=modulus,{k//stride:v for k,v in self.c.items()};u,v={}, {0:F(1)}
    while b:
        quotient,remainder=polynomial_div(a,b)
        a,b=b,remainder;u,v=v,polynomial_add(u,polynomial_mul(quotient,v),F(-1))
    assert set(a)=={0}
    _,reduced=polynomial_div({k:w/a[0]for k,w in u.items()},modulus)
    ans=Poly(self.D,{stride*k:w for k,w in reduced.items()})
    assert self*ans==Poly(self.D,{0:1})
    return ans
Poly.inverse=exact_small_inverse
ROOT=Path(__file__).resolve().parents[1]
P=ROOT/'logs/uniform-bytecode/conjugate-packed-matching'
programs=json.loads((P/'programs.json').read_text());spec=json.loads((P/'spec.json').read_text())
CODE=programs['producer'];START=programs['startup'];OLD=programs['originalRank']
assert [len(CODE),len(START),len(OLD)]==[1198,1460,835]
def relocate(row,base,end):
    op,*args=row
    if op=='halt':return ['jump',end]
    if op=='jump':args[0]+=base
    if op=='branch':args[2]+=base;args[3]+=base
    return [op,*args]
assert CODE[:763]==[relocate(i,0,763)for i in programs['spectrum']]
assert CODE[775:1197]==[relocate(i,775,1197)for i in programs['matching']]
assert CODE[763]==['lit',2211,0]and CODE[764:775]==[['add',1640+i,2200+i,2211]for i in range(11)]
assert not any(i[0]in('input','root','output')for i in CODE)
def plan(K,a,e,S,d):
    N=spec['widths'][K];g=spec['counts'][K];cg=spec['convolutionGates'][K]
    shape=6*(3*K*N+2*N)+2*a
    A=S+6*N+20;C=A+6*N+g+24
    conv=d+3*g+20;tape=conv+5*cg+20;depth=tape+5*shape+20
    order=depth+e+1+shape+20;directory=order+shape+20
    negative=C+7*N+20;constants=negative+7*N+20
    return dict(K=K,N=N,g=g,cg=cg,shape=shape,e=e,S=S,A=A,C=C,d=d,conv=conv,tape=tape,depth=depth,
      order=order,directory=directory,negative=negative,constants=constants,natEnd=directory+shape+2,scalarEnd=constants+6)
def kernel_reference(D,N,a,e,i0,j0,split,h,g):
    z=Poly(D);one=Poly(D,{0:1});delta=lambda i:one if i==0 else z
    v=lambda i:-h[i0+i-split];w=lambda j:g[split-j0-j]
    def matrix(i,j):
        ans=z
        for l in range(split-(j0+j)):ans=ans+h[i0+i-(j0+j)-l]*g[l]
        return ans
    right=[w,lambda j:matrix(0,j)-v(0)*w(j),delta]
    left=[v,delta,lambda i:z if i==0 else matrix(i,0)-v(i)*w(0)]
    out=[]
    for b in range(3):
        out.append([right[b](j)if j<e else z for j in range(N)])
        out.append([left[b](i)if i<a else z for i in range(N)])
    return out
def reference_bank(D,N,kernels):
    omega=Poly(D,{1:1})**(D//N)
    return [omega**j for j in range(N)]+[a[0]for v in kernels for a in direct_dft(omega,[(z,False)for z in v])]
def original_header(s,j,a,e,split,p):
    s['pc']=0;s['nat'][1120]=j
    s['nat'][1121:1138]=[p['K'],a,e,split,0,split,p['S'],p['A'],p['d'],p['C'],p['conv'],p['tape'],p['depth'],p['order'],p['directory'],p['negative'],p['constants']]
def producer_header(s,j,a,e,split,p,V,c):
    s['pc']=0;s['nat'][1820]=V;s['nat'][1821]=j
    for r,value in {484:a,485:e,486:split,487:0,488:split,490:p['S'],525:p['K'],527:p['A'],528:p['d'],529:p['C'],563:p['conv'],564:p['tape'],675:p['depth']}.items():s['nat'][r]=value
    for i,v in enumerate(c):s['nat'][2200+i]=v

def frame(before,after,p,V,c):
    L,packed,dest,inv,rows,C,T,CP,V,mu,bar=c
    nat_ranges=[(p['d'],3*p['g']),(p['conv'],5*p['cg']),(p['tape'],5*p['shape']),(p['depth'],p['shape']+p['e']+1)]
    scalar_ranges=[(p['S'],6*p['N']),(p['A'],6*p['N']+p['g']+5),(p['C'],7*p['N']+1),(V,7*p['N']),(mu,2),(packed,L),(dest,L)]
    for i,value in before['nh'].items():
        if not any(b<=i<b+n for b,n in nat_ranges):assert after['nh'].get(i)==value,('Nat outside',i)
    for i,value in before['sh'].items():
        if not any(b<=i<b+n for b,n in scalar_ranges):assert after['sh'].get(i)==value,('Scalar outside',i)
    assert after['out']==before['out']and after['roots']==before['roots']
    assert after['nat'][100:107]==before['nat'][100:107]
    assert after['nat'][894]==before['nat'][894]

cases=[];covered=set();controls=[];witnesses=[]
for model in spec['models']:
 n=model['n'];D=model['masterOrder'];B=(n+2)**19
 base=dict(pc=0,nat=[0]*2300,nh={},sh={},sr={},out={},roots=[])
 inputs=[scalar(D,i+1,1-i)[0]for i in range(n)]
 startupTicks,_,_=execute(START,base,B,1000000,D,n,inputs)
 assert base['roots']==[D]
 poolEnd=model['conjugatePool']+5*sum(model['radices']);dirEnd=model['conjugateDirectory']+2*model['axisCount']
 for j,r in enumerate(model['radices']):
  for K in range(3):
   N=spec['widths'][K];a=e=split=1
   if r>=3 and N>=2:e=split=2;a=min(2,r-2)
   old=plan(K,a,e,poolEnd+100,dirEnd+100)
   originalState=deepcopy(base);original_header(originalState,j,a,e,split,old)
   originalTicks,_,_=execute(OLD,originalState,B,10000000,D,n)
   seedBase=originalState['nh'][model['directory']+2*j]
   h=[originalState['sh'][seedBase+3*r+i][0]for i in range(r)]
   g=[originalState['sh'][seedBase+4*r+i][0]for i in range(r)]
   values=reference_bank(D,N,kernel_reference(D,N,a,e,split,0,split,h,g))
   assert [originalState['sh'][old['C']+i]for i in range(7*N)]==[(z,False)for z in values]
   work=plan(K,a,e,old['scalarEnd']+100,old['natEnd']+100)
   V=work['C']+7*N+20;mu=V+7*N+20;bar=mu+1
   for M in [0,1,3]:
    L=2*M+3;packed=bar+40;dest=packed+L+40
    inv=work['natEnd']+100;rows=inv+L+40
    # Natbank source geometry is disjoint from the producer; test the actual
    # frozen low-bank theorem case with placements below fresh work Natbanks.
    inv=old['natEnd']+10;rows=inv+L+5
    assert rows+3*M<work['d']
    c=[L,packed,dest,inv,rows,old['C'],old['negative'],old['constants'],V,mu,bar]
    s=deepcopy(originalState)
    for q in range(120):s['sr'][q]=scalar(D,F(q-9,13),F(7-q,17),True)
    for q in range(work['S'],V+7*N):s['sh'][q]=scalar(D,q%7-2,3-q%11,True)
    for q in range(work['d'],work['depth']+work['shape']+e+1):s['nh'][q]=(q*7+19)%79
    phi=[(i+2)%L for i in range(L)]
    labels=[];coeff=[];matchingTicks=9*L+21
    for i in range(M):
      # Include actual zero kernel entries, negative bank, normalization, and
      # real constants. These are generic matching rows, not selected rows.
      kind,index=[('p',N+1 if N>1 else 6),('n',0),('c',2)][i%3]
      index%=7*N
      if kind=='p':pointer=old['C']+index;z=values[index];matchingTicks+=386
      elif kind=='n':pointer=old['negative']+index;z=-values[index];matchingTicks+=388
      else:pointer=old['constants']+index;z=scalar(D,[1,-1,F(1,N),F(-1,N),F(5,4),F(4,5)][index])[0];matchingTicks+=385
      labels.append((kind,index));coeff.append(z)
      for f,v in enumerate([phi[2*i],phi[2*i+1],pointer]):s['nh'][rows+3*i+f]=v
    data=[]
    for i in range(L):
      z=Poly(D,{1+i%3:1})+scalar(D,F(i+1,7),F(3-i,11))[0]
      tag=[False,True,False,True][i%4]
      if M and i==0:z=-coeff[0]*(Poly(D,{2:1})+scalar(D,F(2,7),F(-3,11))[0])
      if M and i==1:z=Poly(D,{2:1})+scalar(D,F(2,7),F(-3,11))[0]
      data.append((z,tag));s['sh'][packed+i]=(z,tag)
      s['sh'][dest+i]=scalar(D,19-i,3+i,True);s['nh'][inv+i]=phi[i]
    s['sh'][mu]=scalar(D,99,-71,True);s['sh'][bar]=scalar(D,-9,91,True)
    s['sh'][dest+L+19]=scalar(D,13,-17,True);s['nh'][rows+3*M+19]=37
    s['nat'][894]=M;producer_header(s,j,a,e,split,work,V,c)
    before=deepcopy(s);ticks,pcs,peak=execute(CODE,s,B,10000000,D,n)
    assert s['pc']==1197 and s['nat'][1640:1651]==c
    assert [s['sh'][V+i]for i in range(7*N)]==[(v.conjugate(),False)for v in values]
    assert [s['sh'][old['C']+i]for i in range(7*N)]==[(v,False)for v in values]
    want=deepcopy(data)
    for i,z in enumerate(coeff):
      left,right=data[2*i:2*i+2];flag=left[1]or right[1]
      want[2*i]=(left[0]+z*right[0],flag);want[2*i+1]=(right[0],flag)
    assert [s['sh'][packed+i]for i in range(L)]==want
    scatter=[None]*L
    for i in range(L):scatter[phi[i]]=want[i]
    assert [s['sh'][dest+i]for i in range(L)]==scatter
    assert all(s['nh'][inv+i]==phi[i]for i in range(L))
    assert all(s['nh'][rows+3*i+f]==before['nh'][rows+3*i+f]for i in range(M)for f in range(3))
    for directory in [model['directory'],model['conjugateDirectory']]:
      assert all(s['nh'][directory+i]==before['nh'][directory+i]for i in range(2*model['axisCount']))
    for pool in [model['pool'],model['conjugatePool']]:
      assert all(s['sh'][pool+i]==before['sh'][pool+i]for i in range(5*sum(model['radices'])))
    frame(before,s,work,V,c);covered.update(pcs)
    cases.append(dict(n=n,axis=j,radix=r,K=K,M=M,length=L,chargedSteps=ticks,maximumWord=peak,startupTicks=startupTicks,originalRankTicks=originalTicks,sixCCalls=6*M))
    if n==1 and j==0 and K==1 and M==3:witnesses.append((before,work,c,D,n,B))
    print('continuous1198',len(cases),n,j,K,M,ticks,flush=True)
assert witnesses and any(c['M']==0 for c in cases)and any(c['sixCCalls'] for c in cases)
assert set(range(763,1198))<=covered
state,work,c,D,n,B=witnesses[0]
def reject(name,u,limit=10000000):
    try:execute(CODE,u,B,limit,D,n)
    except (AssertionError,KeyError):controls.append(name)
    else:raise AssertionError(name+' accepted')
for name,bank,address in [('missing-master','sh',0),('missing-original-positive','sh',c[5]+work['N']+1),
  ('missing-packed-data','sh',c[1]),('missing-inverse','nh',c[3]),('missing-row-coefficient','nh',c[4]+2)]:
    u=deepcopy(state);del u[bank][address];reject(name,u)
u=deepcopy(state);u['sh'][c[5]+work['N']+1]=(u['sh'][c[5]+work['N']+1][0],True);reject('data-tagged-coefficient',u)
u=deepcopy(state);u['nat'][2200]=B+1;reject('initial-word-guard',u)
reject('charged-tick-budget',deepcopy(state),10)
result=dict(status='PASS',instructions=1198,exactCases=len(cases),successfulCases=len(cases),negativeControls=controls,
  visitedPCs=len(covered),allNewCallerPCsVisited=True,unvisitedPCs=sorted(set(range(1198))-covered),cases=cases,
  scope='Actual1460 single-root startup and835 original coefficient bank. Continuous1198 derives conjugate spectra, charges12headers, performs actual six-C shears and inverse scatter. Generic physical matching rows/count/inverse/data supplied at entry: these tests do not instantiate actual selected SeedChunk.Result/Packed hypotheses. Universal Lean execution derives those interfaces from genuine selected postconditions. No fullDFT or startup-to-high-packed-data theorem.',
  arithmetic='Versioned exact sparse Q[eta]/Phi_D engine plus local exact small-subfield Euclidean inverse (degree<=128), each inverse product verified; no floats.',
  hashes={str(path.relative_to(ROOT)):hashlib.sha256(path.read_bytes()).hexdigest()for path in
    [ROOT/'lean/UniformConjugatePackedMatchingPreparation.lean',ROOT/'verification/ExportConjugatePackedMatchingBytecode.lean',Path(__file__),ROOT/'scripts/uniform_seed_cyclotomic_engine.py',P/'programs.json',P/'spec.json']})
(P/'fixtures.json').write_text(json.dumps(result,indent=2)+'\n')
print(json.dumps({k:result[k]for k in ['status','exactCases','visitedPCs','negativeControls','unvisitedPCs']},indent=2))
