import UniformMatchingPhaseSeek
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformMatchingPhaseControl.dispatch_execution
#print axioms ExactFourierCircuits.UniformMatchingPhaseControl.dispatch_execution._proof_1_1
#print axioms ExactFourierCircuits.UniformMatchingPhaseControl.dispatch_execution._proof_1_2
#print axioms ExactFourierCircuits.UniformMatchingPhaseControl.seek
#print axioms ExactFourierCircuits.UniformMatchingPhaseControl.seek._proof_1_1
#print axioms ExactFourierCircuits.UniformMatchingPhaseControl.seek._proof_1_2
#print axioms ExactFourierCircuits.UniformMatchingPhaseControl.seek._proof_1_3
#print axioms ExactFourierCircuits.UniformMatchingPhaseControl.seek._proof_1_4
#print axioms ExactFourierCircuits.UniformMatchingPhaseControl.seek._proof_1_5
#print axioms ExactFourierCircuits.UniformMatchingPhaseControl.skipped_dispatch
#print axioms ExactFourierCircuits.UniformMatchingPhaseControl.skipped_dispatch._proof_1_1
#print axioms ExactFourierCircuits.UniformMatchingPhaseControl.skipped_dispatch._proof_1_10
#print axioms ExactFourierCircuits.UniformMatchingPhaseControl.skipped_dispatch._proof_1_2
#print axioms ExactFourierCircuits.UniformMatchingPhaseControl.skipped_dispatch._proof_1_3
#print axioms ExactFourierCircuits.UniformMatchingPhaseControl.skipped_dispatch._proof_1_4
#print axioms ExactFourierCircuits.UniformMatchingPhaseControl.skipped_dispatch._proof_1_5
#print axioms ExactFourierCircuits.UniformMatchingPhaseControl.skipped_dispatch._proof_1_6
#print axioms ExactFourierCircuits.UniformMatchingPhaseControl.skipped_dispatch._proof_1_7
#print axioms ExactFourierCircuits.UniformMatchingPhaseControl.skipped_dispatch._proof_1_8
#print axioms ExactFourierCircuits.UniformMatchingPhaseControl.skipped_dispatch._proof_1_9
