import UniformPowerMachine
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformPowerMachine.Frame
#print axioms ExactFourierCircuits.UniformPowerMachine.Frame.trans
#print axioms ExactFourierCircuits.UniformPowerMachine.LoopInvariant
#print axioms ExactFourierCircuits.UniformPowerMachine.LoopInvariant.eq_1
#print axioms ExactFourierCircuits.UniformPowerMachine.accumulatorState
#print axioms ExactFourierCircuits.UniformPowerMachine.accumulatorState.eq_1
#print axioms ExactFourierCircuits.UniformPowerMachine.bounded_power_correct
#print axioms ExactFourierCircuits.UniformPowerMachine.canonical_power
#print axioms ExactFourierCircuits.UniformPowerMachine.canonical_power._proof_1_2
#print axioms ExactFourierCircuits.UniformPowerMachine.canonical_power_log
#print axioms ExactFourierCircuits.UniformPowerMachine.dependent_register_preserved
#print axioms ExactFourierCircuits.UniformPowerMachine.entered
#print axioms ExactFourierCircuits.UniformPowerMachine.entered.eq_1
#print axioms ExactFourierCircuits.UniformPowerMachine.executes_bounded
#print axioms ExactFourierCircuits.UniformPowerMachine.frame_refl
#print axioms ExactFourierCircuits.UniformPowerMachine.halfState
#print axioms ExactFourierCircuits.UniformPowerMachine.halfState.eq_1
#print axioms ExactFourierCircuits.UniformPowerMachine.initialized
#print axioms ExactFourierCircuits.UniformPowerMachine.initialized.eq_1
#print axioms ExactFourierCircuits.UniformPowerMachine.initialized_frame
#print axioms ExactFourierCircuits.UniformPowerMachine.initialized_frame._proof_1_1
#print axioms ExactFourierCircuits.UniformPowerMachine.initialized_frame._proof_1_2
#print axioms ExactFourierCircuits.UniformPowerMachine.initialized_frame._proof_1_3
#print axioms ExactFourierCircuits.UniformPowerMachine.initialized_invariant
#print axioms ExactFourierCircuits.UniformPowerMachine.initializes
#print axioms ExactFourierCircuits.UniformPowerMachine.inputState
#print axioms ExactFourierCircuits.UniformPowerMachine.inputState.eq_1
#print axioms ExactFourierCircuits.UniformPowerMachine.inputState_bound
#print axioms ExactFourierCircuits.UniformPowerMachine.iterations
#print axioms ExactFourierCircuits.UniformPowerMachine.iterations._proof_1
#print axioms ExactFourierCircuits.UniformPowerMachine.iterations._unsafe_rec
#print axioms ExactFourierCircuits.UniformPowerMachine.iterations.eq_1
#print axioms ExactFourierCircuits.UniformPowerMachine.iterations.eq_def
#print axioms ExactFourierCircuits.UniformPowerMachine.iterations_log
#print axioms ExactFourierCircuits.UniformPowerMachine.iterations_log._proof_1_1
#print axioms ExactFourierCircuits.UniformPowerMachine.iterations_log._proof_1_2
#print axioms ExactFourierCircuits.UniformPowerMachine.iterations_log._proof_1_3
#print axioms ExactFourierCircuits.UniformPowerMachine.iterations_log_succ_bound
#print axioms ExactFourierCircuits.UniformPowerMachine.iterations_log_succ_bound._proof_1_1
#print axioms ExactFourierCircuits.UniformPowerMachine.iterations_log_succ_bound._proof_1_2
#print axioms ExactFourierCircuits.UniformPowerMachine.iterations_log_succ_bound._proof_1_3
#print axioms ExactFourierCircuits.UniformPowerMachine.iterations_log_succ_bound._proof_1_4
#print axioms ExactFourierCircuits.UniformPowerMachine.iterations_step
#print axioms ExactFourierCircuits.UniformPowerMachine.iterations_zero
#print axioms ExactFourierCircuits.UniformPowerMachine.loopCost
#print axioms ExactFourierCircuits.UniformPowerMachine.loopCost._proof_1
#print axioms ExactFourierCircuits.UniformPowerMachine.loopCost._unsafe_rec
#print axioms ExactFourierCircuits.UniformPowerMachine.loopCost.eq_1
#print axioms ExactFourierCircuits.UniformPowerMachine.loopCost.eq_def
#print axioms ExactFourierCircuits.UniformPowerMachine.loopCost_iterations
#print axioms ExactFourierCircuits.UniformPowerMachine.loopCost_iterations._proof_1_1
#print axioms ExactFourierCircuits.UniformPowerMachine.loopCost_iterations._proof_1_2
#print axioms ExactFourierCircuits.UniformPowerMachine.loopCost_iterations._proof_1_3
#print axioms ExactFourierCircuits.UniformPowerMachine.loopCost_iterations._proof_1_4
#print axioms ExactFourierCircuits.UniformPowerMachine.loopCost_step
#print axioms ExactFourierCircuits.UniformPowerMachine.loopCost_zero
#print axioms ExactFourierCircuits.UniformPowerMachine.loop_correct
#print axioms ExactFourierCircuits.UniformPowerMachine.loop_correct._proof_1_2
#print axioms ExactFourierCircuits.UniformPowerMachine.loop_correct._proof_1_3
#print axioms ExactFourierCircuits.UniformPowerMachine.parityState
#print axioms ExactFourierCircuits.UniformPowerMachine.parityState.eq_1
#print axioms ExactFourierCircuits.UniformPowerMachine.power_correct
#print axioms ExactFourierCircuits.UniformPowerMachine.power_count_exact
#print axioms ExactFourierCircuits.UniformPowerMachine.program
#print axioms ExactFourierCircuits.UniformPowerMachine.program.eq_1
#print axioms ExactFourierCircuits.UniformPowerMachine.roundCost
#print axioms ExactFourierCircuits.UniformPowerMachine.roundCost.eq_1
#print axioms ExactFourierCircuits.UniformPowerMachine.roundState
#print axioms ExactFourierCircuits.UniformPowerMachine.roundState.eq_1
#print axioms ExactFourierCircuits.UniformPowerMachine.round_exponent
#print axioms ExactFourierCircuits.UniformPowerMachine.round_frame
#print axioms ExactFourierCircuits.UniformPowerMachine.round_frame._proof_1_10
#print axioms ExactFourierCircuits.UniformPowerMachine.round_frame._proof_1_11
#print axioms ExactFourierCircuits.UniformPowerMachine.round_frame._proof_1_8
#print axioms ExactFourierCircuits.UniformPowerMachine.round_frame._proof_1_9
#print axioms ExactFourierCircuits.UniformPowerMachine.round_invariant
#print axioms ExactFourierCircuits.UniformPowerMachine.round_power_invariant
#print axioms ExactFourierCircuits.UniformPowerMachine.round_power_invariant._proof_1_1
#print axioms ExactFourierCircuits.UniformPowerMachine.round_power_invariant._proof_1_2
#print axioms ExactFourierCircuits.UniformPowerMachine.round_runs
#print axioms ExactFourierCircuits.UniformPowerMachine.round_values
#print axioms ExactFourierCircuits.UniformPowerMachine.specified_root_extract
#print axioms ExactFourierCircuits.UniformPowerMachine.square_pow
#print axioms ExactFourierCircuits.UniformPowerMachine.squaredState
#print axioms ExactFourierCircuits.UniformPowerMachine.squaredState.eq_1
#print axioms ExactFourierCircuits.UniformPowerMachine.step_bound
#print axioms ExactFourierCircuits.UniformPowerMachine.step_bound._proof_1_14
#print axioms ExactFourierCircuits.UniformPowerMachine.step_bound._proof_1_15
#print axioms ExactFourierCircuits.UniformPowerMachine.step_bound._proof_1_2
#print axioms ExactFourierCircuits.UniformPowerMachine.step_bound._proof_1_3
#print axioms ExactFourierCircuits.UniformPowerMachine.step_bound._proof_1_4
#print axioms ExactFourierCircuits.UniformPowerMachine.step_bound._proof_1_5
#print axioms ExactFourierCircuits.UniformPowerMachine.step_bound._proof_1_6
#print axioms ExactFourierCircuits.UniformPowerMachine.step_bound._proof_1_7
#print axioms ExactFourierCircuits.UniformPowerMachine.totalCost_log_bound
#print axioms ExactFourierCircuits.UniformPowerMachine.totalCost_log_bound._proof_1_1

open Lean Elab Command in
run_cmd do
 let env ← getEnv
 for (name, _) in env.constants.toList do
  if "_private.UniformPowerMachine.".isPrefixOf name.toString then
   let axs ← collectAxioms name
   logInfo m!"{name} depends on axioms: {axs.toList}"
