import UniformResidualOrientationArithmetic
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformResidualOrientationArithmetic.boolCode
#print axioms ExactFourierCircuits.UniformResidualOrientationArithmetic.boolCode.eq_1
#print axioms ExactFourierCircuits.UniformResidualOrientationArithmetic.norm_one_scanner
#print axioms ExactFourierCircuits.UniformResidualOrientationArithmetic.orientation_code
#print axioms ExactFourierCircuits.UniformResidualOrientationArithmetic.orientation_code_of_matching_nat
#print axioms ExactFourierCircuits.UniformResidualOrientationArithmetic.orientation_is_one
#print axioms ExactFourierCircuits.UniformResidualOrientationArithmetic.scannerWeight
#print axioms ExactFourierCircuits.UniformResidualOrientationArithmetic.scannerWeight_eq
#print axioms ExactFourierCircuits.UniformResidualOrientationArithmetic.scanner_cast
#print axioms ExactFourierCircuits.UniformResidualOrientationArithmetic.scanner_mod_four
#print axioms ExactFourierCircuits.UniformResidualOrientationArithmetic.weight_one_of_scanner
#print axioms ExactFourierCircuits.UniformResidualOrientationArithmetic.weight_three_of_scanner
