import UniformActualCalendarRectangleAtomResult
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformActualCalendarRectangleAtomResult.result
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleAtomResult.result._proof_1
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleAtomResult.result._proof_10
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleAtomResult.result._proof_11
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleAtomResult.result._proof_12
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleAtomResult.result._proof_13
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleAtomResult.result._proof_14
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleAtomResult.result._proof_15
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleAtomResult.result._proof_16
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleAtomResult.result._proof_17
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleAtomResult.result._proof_18
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleAtomResult.result._proof_2
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleAtomResult.result._proof_3
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleAtomResult.result._proof_4
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleAtomResult.result._proof_5
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleAtomResult.result._proof_6
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleAtomResult.result._proof_7
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleAtomResult.result._proof_8
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleAtomResult.result._proof_9
