import UniformFastPhysicalCRTArithmetic
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.carry_remove_le
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.carry_value
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.digits
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.digits.eq_1
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.digits_bound
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.digits_cycle
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.digits_eq
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.digits_zero
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.front
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.front.eq_1
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.front_bound
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.front_current
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.front_final
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.front_initial
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.front_success
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.front_update_mod
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.front_value_bound
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.increment_mod
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.increment_mod._proof_1_1
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.normal
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.normal_bound
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.normal_eq
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.place_reverse
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.place_reverse._proof_1_1
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.reverse
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.reverse.eq_1
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.reverse_list
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.reverse_list._proof_1_2
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.reverse_positive
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.reverse_product
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.term_le
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.value
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.value_bound
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.value_encoded
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.value_update
