import UniformLinearMachine

#print axioms ExactFourierCircuits.UniformLinearMachine.Ready
#print axioms ExactFourierCircuits.UniformLinearMachine.prefix_runs
#print axioms ExactFourierCircuits.UniformLinearMachine.row_runs
#print axioms ExactFourierCircuits.UniformLinearMachine.ValidSchedule
#print axioms ExactFourierCircuits.UniformLinearMachine.ValidSchedule.runs
#print axioms ExactFourierCircuits.UniformLinearMachine.ValidSchedule.pc
#print axioms ExactFourierCircuits.UniformLinearMachine.ValidSchedule.counters
#print axioms ExactFourierCircuits.UniformLinearMachine.interpreted_schedule
#print axioms ExactFourierCircuits.UniformLinearMachine.prepared_ready
#print axioms ExactFourierCircuits.UniformLinearMachine.prepared_schedule
