import UniformActualCalendarAsymptotics
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformActualCalendarAsymptotics.actual_clocks_bound
#print axioms ExactFourierCircuits.UniformActualCalendarAsymptotics.exponent_shift
#print axioms ExactFourierCircuits.UniformActualCalendarAsymptotics.kernelEnvelope
#print axioms ExactFourierCircuits.UniformActualCalendarAsymptotics.kernelEnvelope_bound
#print axioms ExactFourierCircuits.UniformActualCalendarAsymptotics.kernelEnvelope_isBigO_paper
#print axioms ExactFourierCircuits.UniformActualCalendarAsymptotics.kernelEnvelope_isBigO_working
#print axioms ExactFourierCircuits.UniformActualCalendarAsymptotics.kernelEnvelope_isBigO_working._proof_1_1
#print axioms ExactFourierCircuits.UniformActualCalendarAsymptotics.kernelEnvelope_nonneg
#print axioms ExactFourierCircuits.UniformActualCalendarAsymptotics.wholeConstant
#print axioms ExactFourierCircuits.UniformActualCalendarAsymptotics.wholeConstant._proof_1
