import UniformFourierAxisPrepareMachine
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.Boundary.program
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.Epoch.program
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.Lookup.program
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.Ranges.program
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.beforeBoundary
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.beforeBoundary.eq_1
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.beforeBoundary_length
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.beforeDecision
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.beforeDecision.eq_1
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.beforeDecision_length
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.beforeEpoch
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.beforeEpoch.eq_1
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.beforeEpoch_length
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.beforeFooter
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.beforeFooter.eq_1
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.beforeFooter_length
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.beforeRanges
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.beforeRanges.eq_1
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.beforeRanges_length
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.beforeWorkspace
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.beforeWorkspace.eq_1
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.beforeWorkspace_length
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.boundary_code
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.code_138
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.code_139
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.code_140
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.code_141
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.decision
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.decision.eq_1
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.epoch_code
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.footer_code
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.halt_at
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.lookup_code
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.nat_segment_block
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.program
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.program.eq_1
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.program_length
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.ranges_code
#print axioms ExactFourierCircuits.UniformFourierAxisPrepareMachine.workspace_code
