import UniformTransposeRectangleRender
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformTransposeRectangleRender.correction
#print axioms ExactFourierCircuits.UniformTransposeRectangleRender.correction.eq_1
#print axioms ExactFourierCircuits.UniformTransposeRectangleRender.correction_length
#print axioms ExactFourierCircuits.UniformTransposeRectangleRender.correction_matrix
#print axioms ExactFourierCircuits.UniformTransposeRectangleRender.correction_restricted
#print axioms ExactFourierCircuits.UniformTransposeRectangleRender.reverse_flatten_matrix
#print axioms ExactFourierCircuits.UniformTransposeRectangleRender.upperChunk
#print axioms ExactFourierCircuits.UniformTransposeRectangleRender.upperChunk_length
#print axioms ExactFourierCircuits.UniformTransposeRectangleRender.upperChunk_matrix
#print axioms ExactFourierCircuits.UniformTransposeRectangleRender.upperChunk_restricted
#print axioms ExactFourierCircuits.UniformTransposeRectangleRender.upperPair
#print axioms ExactFourierCircuits.UniformTransposeRectangleRender.upperPair._proof_1
#print axioms ExactFourierCircuits.UniformTransposeRectangleRender.upperPair._proof_2
#print axioms ExactFourierCircuits.UniformTransposeRectangleRender.upperPair._proof_3
#print axioms ExactFourierCircuits.UniformTransposeRectangleRender.upperPair.congr_simp
#print axioms ExactFourierCircuits.UniformTransposeRectangleRender.upperPair_length
#print axioms ExactFourierCircuits.UniformTransposeRectangleRender.upperPair_matrix
#print axioms ExactFourierCircuits.UniformTransposeRectangleRender.upperPair_restricted
#print axioms ExactFourierCircuits.UniformTransposeRectangleRender.upperSelected
#print axioms ExactFourierCircuits.UniformTransposeRectangleRender.upperSelected._proof_1
#print axioms ExactFourierCircuits.UniformTransposeRectangleRender.upperSelected._proof_2
#print axioms ExactFourierCircuits.UniformTransposeRectangleRender.upperSelected_length
#print axioms ExactFourierCircuits.UniformTransposeRectangleRender.upperSelected_matrix
#print axioms ExactFourierCircuits.UniformTransposeRectangleRender.upperSelected_restricted
