import UniformInitialCoreRetention
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformInitialCoreRetention.initial_execution_with_header
#print axioms ExactFourierCircuits.UniformInitialCoreRetention.initial_execution_with_header._proof_1_1
#print axioms ExactFourierCircuits.UniformInitialCoreRetention.initial_execution_with_header._proof_1_2
#print axioms ExactFourierCircuits.UniformInitialCoreRetention.initial_execution_with_header._proof_1_3
#print axioms ExactFourierCircuits.UniformInitialCoreRetention.initial_execution_with_header._proof_1_4
#print axioms ExactFourierCircuits.UniformInitialCoreRetention.initial_execution_with_header._proof_1_5
#print axioms ExactFourierCircuits.UniformInitialCoreRetention.initial_execution_with_header._proof_1_6
