import UniformInitialLocalPreparation

#print axioms ExactFourierCircuits.UniformInitialLocalPreparation.axis
#print axioms ExactFourierCircuits.UniformInitialLocalPreparation.radix
#print axioms ExactFourierCircuits.UniformInitialLocalPreparation.localTime
#print axioms ExactFourierCircuits.UniformInitialLocalPreparation.head
#print axioms ExactFourierCircuits.UniformInitialLocalPreparation.program
#print axioms ExactFourierCircuits.UniformInitialLocalPreparation.head_length
#print axioms ExactFourierCircuits.UniformInitialLocalPreparation.program_length
#print axioms ExactFourierCircuits.UniformInitialLocalPreparation.startup_code
#print axioms ExactFourierCircuits.UniformInitialLocalPreparation.argument_at
#print axioms ExactFourierCircuits.UniformInitialLocalPreparation.local_code
#print axioms ExactFourierCircuits.UniformInitialLocalPreparation.halt_at
#print axioms ExactFourierCircuits.UniformInitialLocalPreparation.setAxis
#print axioms ExactFourierCircuits.UniformInitialLocalPreparation.setAxis_saved
#print axioms ExactFourierCircuits.UniformInitialLocalPreparation.setAxis_metadata
#print axioms ExactFourierCircuits.UniformInitialLocalPreparation.word_setup
#print axioms ExactFourierCircuits.UniformInitialLocalPreparation.preparationBudget
#print axioms ExactFourierCircuits.UniformInitialLocalPreparation.preparation_execution
#print axioms ExactFourierCircuits.UniformInitialLocalPreparation.startupBudget_isBigO_input
