import UniformSectorPhysicalBinaryAction
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformSectorPhysicalBinaryAction.batchCoordinate
#print axioms ExactFourierCircuits.UniformSectorPhysicalBinaryAction.batchCoordinate_value
#print axioms ExactFourierCircuits.UniformSectorPhysicalBinaryAction.batch_entries
#print axioms ExactFourierCircuits.UniformSectorPhysicalBinaryAction.highPoint
#print axioms ExactFourierCircuits.UniformSectorPhysicalBinaryAction.highPoint.eq_1
#print axioms ExactFourierCircuits.UniformSectorPhysicalBinaryAction.highPoint_value
#print axioms ExactFourierCircuits.UniformSectorPhysicalBinaryAction.physicalMatrix_cast
#print axioms ExactFourierCircuits.UniformSectorPhysicalBinaryAction.physicalMatrix_high
#print axioms ExactFourierCircuits.UniformSectorPhysicalBinaryAction.physicalMatrix_zero
#print axioms ExactFourierCircuits.UniformSectorPhysicalBinaryAction.physicalSector
#print axioms ExactFourierCircuits.UniformSectorPhysicalBinaryAction.physicalSector_one
#print axioms ExactFourierCircuits.UniformSectorPhysicalBinaryAction.physicalSector_one._proof_1_1
#print axioms ExactFourierCircuits.UniformSectorPhysicalBinaryAction.physicalSector_two
#print axioms ExactFourierCircuits.UniformSectorPhysicalBinaryAction.physicalSector_value
#print axioms ExactFourierCircuits.UniformSectorPhysicalBinaryAction.sectorMatrix_physical
#print axioms ExactFourierCircuits.UniformSectorPhysicalBinaryAction.sectorTensor_physical
#print axioms ExactFourierCircuits.UniformSectorPhysicalBinaryAction.sectorTensor_physical._proof_1_1
#print axioms ExactFourierCircuits.UniformSectorPhysicalBinaryAction.sectorTensor_physical._proof_1_2
