import UniformCacheLowRequestLoop
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformLocalStoredRequestLoop.loop_low
#print axioms ExactFourierCircuits.UniformLocalStoredRequestLoop.loop_low._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalStoredRequestLoop.loop_low._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalStoredRequestLoop.loop_low._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalStoredRequestLoop.loop_low._proof_1_4
