import UniformSixCCorrectedReplay
import Lean
set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformSixCCorrectedReplay.Registers
#print axioms ExactFourierCircuits.UniformSixCCorrectedReplay.execution_cross_matrix
#print axioms ExactFourierCircuits.UniformSixCCorrectedReplay.fullWord_cross_matrix
#print axioms ExactFourierCircuits.UniformSixCCorrectedReplay.fullWord_cross_matrix._proof_1
#print axioms ExactFourierCircuits.UniformSixCCorrectedReplay.fullWord_cross_matrix._proof_2
#print axioms ExactFourierCircuits.UniformSixCCorrectedReplay.fullWord_outside
#print axioms ExactFourierCircuits.UniformSixCCorrectedReplay.logicalIndex
#print axioms ExactFourierCircuits.UniformSixCCorrectedReplay.logicalIndex_domain
#print axioms ExactFourierCircuits.UniformSixCCorrectedReplay.logicalIndex_domain._proof_1_1
#print axioms ExactFourierCircuits.UniformSixCCorrectedReplay.logicalIndex_domain._proof_1_2
#print axioms ExactFourierCircuits.UniformSixCCorrectedReplay.numeric_physical
#print axioms ExactFourierCircuits.UniformSixCCorrectedReplay.physicalIndex
#print axioms ExactFourierCircuits.UniformSixCCorrectedReplay.physicalIndex_bound
#print axioms ExactFourierCircuits.UniformSixCCorrectedReplay.replayPort
