import UniformCanonicalCacheSlotGeometry
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotGeometry.persistent_bounds
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotGeometry.persistent_bounds._proof_1_1
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotGeometry.persistent_bounds._proof_1_2
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotGeometry.persistent_bounds._proof_1_3
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotGeometry.persistent_bounds._proof_1_4
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotGeometry.phase_slot_arithmetic
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotGeometry.phase_slot_arithmetic._proof_1_1
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotGeometry.phase_slots
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotGeometry.slot_bounds
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotGeometry.slot_bounds._proof_1_1
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotGeometry.slot_bounds._proof_1_2
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotGeometry.slot_bounds._proof_1_3
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotGeometry.slot_bounds._proof_1_4
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotGeometry.slot_bounds._proof_1_5
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotGeometry.slot_bounds._proof_1_6
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotGeometry.slot_bounds._proof_1_7
