import UniformActualCalendarRectanglePhaseResult
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformActualCalendarNativeRectangle.snapshot.congr_simp
#print axioms ExactFourierCircuits.UniformActualCalendarRectanglePhaseResult.Result
#print axioms ExactFourierCircuits.UniformActualCalendarRectanglePhaseResult.Result._sizeOf_1
#print axioms ExactFourierCircuits.UniformActualCalendarRectanglePhaseResult.Result._sizeOf_inst
#print axioms ExactFourierCircuits.UniformActualCalendarRectanglePhaseResult.Result.casesOn
#print axioms ExactFourierCircuits.UniformActualCalendarRectanglePhaseResult.Result.ctorIdx
#print axioms ExactFourierCircuits.UniformActualCalendarRectanglePhaseResult.Result.matrix
#print axioms ExactFourierCircuits.UniformActualCalendarRectanglePhaseResult.Result.mk
#print axioms ExactFourierCircuits.UniformActualCalendarRectanglePhaseResult.Result.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformActualCalendarRectanglePhaseResult.Result.mk.inj
#print axioms ExactFourierCircuits.UniformActualCalendarRectanglePhaseResult.Result.mk.injEq
#print axioms ExactFourierCircuits.UniformActualCalendarRectanglePhaseResult.Result.mk.noConfusion
#print axioms ExactFourierCircuits.UniformActualCalendarRectanglePhaseResult.Result.mk.sizeOf_spec
#print axioms ExactFourierCircuits.UniformActualCalendarRectanglePhaseResult.Result.noConfusion
#print axioms ExactFourierCircuits.UniformActualCalendarRectanglePhaseResult.Result.noConfusionType
#print axioms ExactFourierCircuits.UniformActualCalendarRectanglePhaseResult.Result.rec
#print axioms ExactFourierCircuits.UniformActualCalendarRectanglePhaseResult.Result.recOn
#print axioms ExactFourierCircuits.UniformActualCalendarRectanglePhaseResult.Result.snapshot
#print axioms ExactFourierCircuits.UniformActualCalendarRectanglePhaseResult.Result.source
#print axioms ExactFourierCircuits.UniformActualCalendarRectanglePhaseResult.phase_result
#print axioms ExactFourierCircuits.UniformActualCalendarRectanglePhaseResult.phase_result._proof_1
#print axioms ExactFourierCircuits.UniformActualCalendarRectanglePhaseResult.phase_result._proof_2
#print axioms ExactFourierCircuits.UniformActualCalendarRectanglePhaseResult.phase_result._proof_3
