import UniformCacheLowWholeExecution
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformAxisCacheWholeExecution.execution_low
#print axioms ExactFourierCircuits.UniformAxisCacheWholeExecution.execution_low._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheWholeExecution.execution_low._proof_1_2
#print axioms ExactFourierCircuits.UniformAxisCacheWholeExecution.execution_low._proof_1_3
#print axioms ExactFourierCircuits.UniformAxisCacheWholeExecution.execution_low._proof_1_4
#print axioms ExactFourierCircuits.UniformAxisCacheWholeExecution.execution_low._proof_1_5
#print axioms ExactFourierCircuits.UniformAxisCacheWholeExecution.execution_low._proof_1_6
