import UniformDirectLeafForestInitialization
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformDirectLeafForestInitialization.completed_outside
#print axioms ExactFourierCircuits.UniformDirectLeafForestInitialization.completed_outside._proof_1_1
#print axioms ExactFourierCircuits.UniformDirectLeafForestInitialization.completed_outside._proof_1_2
#print axioms ExactFourierCircuits.UniformDirectLeafForestInitialization.invariant
#print axioms ExactFourierCircuits.UniformDirectLeafForestInitialization.invariant._proof_1_1
#print axioms ExactFourierCircuits.UniformDirectLeafForestInitialization.invariant._proof_1_2
#print axioms ExactFourierCircuits.UniformDirectLeafForestInitialization.sources
#print axioms ExactFourierCircuits.UniformDirectLeafForestInitialization.sources._proof_1_1
#print axioms ExactFourierCircuits.UniformDirectLeafForestInitialization.sources._proof_1_2
#print axioms ExactFourierCircuits.UniformDirectLeafForestInitialization.sources._proof_1_3
#print axioms ExactFourierCircuits.UniformDirectLeafForestInitialization.sources._proof_1_4
#print axioms ExactFourierCircuits.UniformDirectLeafForestInitialization.sources._proof_1_5
#print axioms ExactFourierCircuits.UniformDirectLeafForestInitialization.sources._proof_1_6
#print axioms ExactFourierCircuits.UniformDirectLeafForestInitialization.sources._proof_1_7
