import UniformDirectLeafCacheFinish
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformDirectLeafCacheFinish.execution
#print axioms ExactFourierCircuits.UniformDirectLeafCacheFinish.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformDirectLeafCacheFinish.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformDirectLeafCacheFinish.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformDirectLeafCacheFinish.execution._proof_1_4
