import UniformRecursivePaddingExecution
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.action_remaining
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.execution
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.execution._proof_1_10
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.execution._proof_1_11
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.execution._proof_1_12
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.execution._proof_1_13
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.execution._proof_1_14
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.execution._proof_1_15
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.execution._proof_1_16
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.execution._proof_1_17
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.execution._proof_1_18
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.execution._proof_1_19
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.execution._proof_1_21
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.execution._proof_1_7
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.execution._proof_1_8
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.execution._proof_1_9
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.execution._simp_1_2
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.execution._simp_1_20
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.execution._simp_1_3
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.printed_actual_in
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.printed_actual_out
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.record_actual
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.record_columns
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.remaining
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.remaining._proof_1
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.remaining._proof_2
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.remaining.eq_1
#print axioms ExactFourierCircuits.UniformRecursivePaddingExecution.remaining_length
