import UniformAxisCacheSelectedPreparation
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformAxisCacheSelectedPreparation.Selected
#print axioms ExactFourierCircuits.UniformAxisCacheSelectedPreparation.Selected.axisIndex
#print axioms ExactFourierCircuits.UniformAxisCacheSelectedPreparation.Selected.casesOn
#print axioms ExactFourierCircuits.UniformAxisCacheSelectedPreparation.Selected.control
#print axioms ExactFourierCircuits.UniformAxisCacheSelectedPreparation.Selected.frontiers
#print axioms ExactFourierCircuits.UniformAxisCacheSelectedPreparation.Selected.mk
#print axioms ExactFourierCircuits.UniformAxisCacheSelectedPreparation.Selected.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformAxisCacheSelectedPreparation.Selected.radix
#print axioms ExactFourierCircuits.UniformAxisCacheSelectedPreparation.Selected.rec
#print axioms ExactFourierCircuits.UniformAxisCacheSelectedPreparation.Selected.recOn
#print axioms ExactFourierCircuits.UniformAxisCacheSelectedPreparation.Selected.source
#print axioms ExactFourierCircuits.UniformAxisCacheSelectedPreparation.Selected.withPC
#print axioms ExactFourierCircuits.UniformAxisCacheSelectedPreparation.control_transport
#print axioms ExactFourierCircuits.UniformAxisCacheSelectedPreparation.control_transport._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheSelectedPreparation.control_transport._proof_1_2
#print axioms ExactFourierCircuits.UniformAxisCacheSelectedPreparation.control_transport._proof_1_3
#print axioms ExactFourierCircuits.UniformAxisCacheSelectedPreparation.control_transport._proof_1_4
#print axioms ExactFourierCircuits.UniformAxisCacheSelectedPreparation.control_transport._proof_1_5
#print axioms ExactFourierCircuits.UniformAxisCacheSelectedPreparation.control_transport._proof_1_6
#print axioms ExactFourierCircuits.UniformAxisCacheSelectedPreparation.control_transport._proof_1_7
#print axioms ExactFourierCircuits.UniformAxisCacheSelectedPreparation.execution
#print axioms ExactFourierCircuits.UniformAxisCacheSelectedPreparation.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheSelectedPreparation.natAt
#print axioms ExactFourierCircuits.UniformAxisCacheSelectedPreparation.scalarAt
