import UniformAxisCacheRequestSource
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformAxisCacheRequestSource.nodeRequests
#print axioms ExactFourierCircuits.UniformAxisCacheRequestSource.nodeRequests._proof_1
#print axioms ExactFourierCircuits.UniformAxisCacheRequestSource.nodeRequests.eq_1
#print axioms ExactFourierCircuits.UniformAxisCacheRequestSource.node_length
#print axioms ExactFourierCircuits.UniformAxisCacheRequestSource.node_rows
#print axioms ExactFourierCircuits.UniformAxisCacheRequestSource.requests
#print axioms ExactFourierCircuits.UniformAxisCacheRequestSource.requests.eq_1
#print axioms ExactFourierCircuits.UniformAxisCacheRequestSource.requests_length
#print axioms ExactFourierCircuits.UniformAxisCacheRequestSource.requests_rows
#print axioms ExactFourierCircuits.UniformAxisCacheRequestSource.source
#print axioms ExactFourierCircuits.UniformAxisCacheRequestSource.source._proof_1_3
#print axioms ExactFourierCircuits.UniformAxisCacheRequestSource.source._proof_1_4
#print axioms ExactFourierCircuits.UniformAxisCacheRequestSource.source._simp_1_2
#print axioms ExactFourierCircuits.UniformAxisCacheRequestSource.source_append
#print axioms ExactFourierCircuits.UniformAxisCacheRequestSource.source_append._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheRequestSource.source_append._proof_1_2
#print axioms ExactFourierCircuits.UniformAxisCacheRequestSource.source_append._proof_1_3
#print axioms ExactFourierCircuits.UniformAxisCacheRequestSource.source_append._proof_1_4
#print axioms ExactFourierCircuits.UniformAxisCacheRequestSource.source_append._proof_1_5
#print axioms ExactFourierCircuits.UniformAxisCacheRequestSource.source_of_nodes
#print axioms ExactFourierCircuits.UniformAxisCacheRequestSource.source_of_nodes._simp_1_2
#print axioms ExactFourierCircuits.UniformAxisCacheRequestSource.table_rowSource
