import UniformFastPhysicalCRTCycle
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.normal.eq_1
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTArithmetic.value.eq_1
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.enter_carry
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.enter_carry._proof_1_1
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.enter_carry._proof_1_2
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.enter_carry._proof_1_4
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.enter_carry._proof_1_5
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.execution
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.loop
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.loop._proof_1_1
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.loop._proof_1_10
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.loop._proof_1_11
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.loop._proof_1_12
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.loop._proof_1_13
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.loop._proof_1_14
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.loop._proof_1_16
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.loop._proof_1_17
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.loop._proof_1_18
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.loop._proof_1_19
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.loop._proof_1_2
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.loop._proof_1_20
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.loop._proof_1_21
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.loop._proof_1_3
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.loop._proof_1_4
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.loop._proof_1_5
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.loop._proof_1_6
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.loop._proof_1_7
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.loop._proof_1_8
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCycle.loop._proof_1_9
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTMachine.carryInit.eq_1
