import UniformMatchingCoefficientValueBridge
import Lean
set_option linter.auxLemma false
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.ForwardLeaf
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.ForwardLeaf.eq_1
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.arbitrary_rational_rejected_fixture
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.arbitrary_rational_rejected_fixture._simp_1_1
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.conjugateValue
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.conjugateValue.eq_1
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.conjugateValue.eq_2
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.conjugateValue.eq_3
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.conjugateValue.match_1
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.conjugateValue_eq
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.crossWord_leaf
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.cross_bucket_leaf
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.cross_rational_domain
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.cross_selected_value
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.forward_conjugate_value
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.forward_decoder_negative_normalization_address
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.forward_decoder_negative_normalization_address._proof_1_1
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.forward_decoder_negative_value_fixture
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.forward_rational_iff
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.forward_source
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.forward_value
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.gate_leaf
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.gate_leaf._simp_1_1
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.inverseReference
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.inverseReference._proof_1
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.inverseReference.eq_1
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.inverseReference.eq_2
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.inverseReference.match_1
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.inverse_conjugate_value
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.inverse_reciprocal_address
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.inverse_reciprocal_width_gt_one
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.inverse_reciprocal_width_gt_one._proof_1_1
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.inverse_reciprocal_width_one
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.inverse_source
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.inverse_value
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.inverse_width_one_fixture
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.inverse_width_two_fixture
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.mapped_source
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.natSweep_leaf
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.natSweep_leaf._simp_1_1
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.negative_normalization_forward_rejected_fixture
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.negative_normalization_forward_rejected_fixture._simp_1_1
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.produced_mapped_value
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.produced_sources
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.producer_bank_size
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.producer_bank_size._proof_1_1
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.reciprocal_cast
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.reference_leaf
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.reference_leaf._simp_1_1
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.reverseCode_value
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.seedBank
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.seedWord_leaf
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.seed_labels_value
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.seed_result_pair_values
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.seed_result_pair_values._proof_1
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.seed_result_pair_values._proof_2
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.selectedReference
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.selectedReference._proof_1
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.selectedReference._proof_2
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.selectedReference_leaf
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.selected_labels_value
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.selected_row_execution
open Lean Elab Command in
run_cmd do
 let env ← getEnv
 let names := env.constants.toList.map Prod.fst |>.filter (fun name =>
   "_private.UniformMatchingCoefficientValueBridge.".isPrefixOf name.toString)
 let names := names.toArray.qsort (fun a b => a.toString < b.toString)
 for name in names do
  let axioms ← collectAxioms name
  logInfo m!"'{name}' depends on axioms: {axioms.toList}"
  for ax in axioms do
   unless ax == `propext || ax == `Quot.sound || ax == `Classical.choice do
    throwError m!"Forbidden axiom {ax} in {name}"
