import UniformFinalCacheSource
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformFinalCacheSource.execution_source
#print axioms ExactFourierCircuits.UniformFinalCacheSource.execution_source._proof_1_1
#print axioms ExactFourierCircuits.UniformFinalCacheSource.execution_source._proof_1_2
#print axioms ExactFourierCircuits.UniformFinalCacheSource.execution_source._proof_1_3
#print axioms ExactFourierCircuits.UniformFinalCacheSource.execution_source._proof_1_4
