import UniformFinalCacheAsymptotics
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformFinalCacheAsymptotics.axisSize
#print axioms ExactFourierCircuits.UniformFinalCacheAsymptotics.cacheBudget
#print axioms ExactFourierCircuits.UniformFinalCacheAsymptotics.cacheBudget.eq_1
#print axioms ExactFourierCircuits.UniformFinalCacheAsymptotics.cacheBudget_isLittleO_input
#print axioms ExactFourierCircuits.UniformFinalCacheAsymptotics.cacheBudget_isLittleO_input._proof_1_1
#print axioms ExactFourierCircuits.UniformFinalCacheAsymptotics.cacheUnit
#print axioms ExactFourierCircuits.UniformFinalCacheAsymptotics.logSize
#print axioms ExactFourierCircuits.UniformFinalCacheAsymptotics.logSize.eq_1
#print axioms ExactFourierCircuits.UniformFinalCacheAsymptotics.logSize_isBigO_log
#print axioms ExactFourierCircuits.UniformFinalCacheAsymptotics.logSize_isBigO_log._proof_1_1
#print axioms ExactFourierCircuits.UniformFinalCacheAsymptotics.logSize_isBigO_log._proof_1_2
#print axioms ExactFourierCircuits.UniformFinalCacheAsymptotics.logSize_isBigO_log._proof_1_3
#print axioms ExactFourierCircuits.UniformFinalCacheAsymptotics.maxBudget_bound
#print axioms ExactFourierCircuits.UniformFinalCacheAsymptotics.maxBudget_bound._proof_1_1
#print axioms ExactFourierCircuits.UniformFinalCacheAsymptotics.maxBudget_bound._proof_1_2
#print axioms ExactFourierCircuits.UniformFinalCacheAsymptotics.maxBudget_bound._proof_1_3
#print axioms ExactFourierCircuits.UniformFinalCacheAsymptotics.maxBudget_bound._proof_1_4
#print axioms ExactFourierCircuits.UniformFinalCacheAsymptotics.maxBudget_bound._proof_1_5
#print axioms ExactFourierCircuits.UniformFinalCacheAsymptotics.maxBudget_isBigO_log_thirteen
#print axioms ExactFourierCircuits.UniformFinalCacheAsymptotics.maxBudget_isBigO_log_thirteen._proof_1_1
