import UniformAlternateFourierSchedule
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformAlternateFourierSchedule.assembly
#print axioms ExactFourierCircuits.UniformAlternateFourierSchedule.assembly.eq_1
#print axioms ExactFourierCircuits.UniformAlternateFourierSchedule.assembly_matrix
#print axioms ExactFourierCircuits.UniformAlternateFourierSchedule.schedule
#print axioms ExactFourierCircuits.UniformAlternateFourierSchedule.schedule._proof_1
#print axioms ExactFourierCircuits.UniformAlternateFourierSchedule.schedule._proof_2
#print axioms ExactFourierCircuits.UniformAlternateFourierSchedule.schedule.congr_simp
#print axioms ExactFourierCircuits.UniformAlternateFourierSchedule.schedule.eq_1
#print axioms ExactFourierCircuits.UniformAlternateFourierSchedule.schedule_length
#print axioms ExactFourierCircuits.UniformAlternateFourierSchedule.schedule_length._proof_1_5
#print axioms ExactFourierCircuits.UniformAlternateFourierSchedule.schedule_matrix
#print axioms ExactFourierCircuits.UniformAlternateFourierSchedule.schedule_restricted
#print axioms ExactFourierCircuits.UniformAlternateFourierSchedule.schedule_restricted._simp_1_3
#print axioms ExactFourierCircuits.UniformAlternateFourierSchedule.schedule_restricted._simp_1_4
#print axioms ExactFourierCircuits.UniformAlternateFourierSchedule.schedule_restricted._simp_1_5
#print axioms ExactFourierCircuits.UniformAlternateFourierSchedule.specified
#print axioms ExactFourierCircuits.UniformAlternateFourierSchedule.specified._proof_1
#print axioms ExactFourierCircuits.UniformAlternateFourierSchedule.specified._proof_2
#print axioms ExactFourierCircuits.UniformAlternateFourierSchedule.specified.eq_1
#print axioms ExactFourierCircuits.UniformAlternateFourierSchedule.specified_length
#print axioms ExactFourierCircuits.UniformAlternateFourierSchedule.specified_matrix
#print axioms ExactFourierCircuits.UniformAlternateFourierSchedule.specified_matrix._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalFourierLayers.Nschedule.eq_1
#print axioms ExactFourierCircuits.UniformLocalFourierLayers.symmetric.congr_simp
