import UniformSixCCorrectedReplay
import Lean
set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformSixCWholeReplay.base_withPC
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.dirty_flag
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.dirty_flag._proof_1_1
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.dirty_height
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.dirty_height._proof_1_1
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.execution
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.execution._proof_1_10
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.execution._proof_1_11
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.execution._proof_1_12
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.execution._proof_1_13
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.execution._proof_1_14
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.execution._proof_1_15
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.execution._proof_1_16
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.execution._proof_1_17
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.execution._proof_1_18
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.execution._proof_1_19
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.execution._proof_1_20
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.execution._proof_1_21
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.execution._proof_1_7
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.execution._proof_1_8
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.execution._proof_1_9
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.halfCost
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.heightCost
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.height_call
#print axioms ExactFourierCircuits.UniformSixCWholeReplay.source_flag
