import BinaryProjection
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.BinaryProjection.Orthonormal
#print axioms ExactFourierCircuits.BinaryProjection.basis_projection_same_space
#print axioms ExactFourierCircuits.BinaryProjection.dot_projection_of_mem_span
#print axioms ExactFourierCircuits.BinaryProjection.dot_sub_right
#print axioms ExactFourierCircuits.BinaryProjection.frameExponent
#print axioms ExactFourierCircuits.BinaryProjection.frameExponent.eq_1
#print axioms ExactFourierCircuits.BinaryProjection.frameExponent_direct_sum
#print axioms ExactFourierCircuits.BinaryProjection.frameMap_eq_of_span_eq
#print axioms ExactFourierCircuits.BinaryProjection.frameProjection_add
#print axioms ExactFourierCircuits.BinaryProjection.frameProjection_direct_sum
#print axioms ExactFourierCircuits.BinaryProjection.frameProjection_eq_of_span_eq
#print axioms ExactFourierCircuits.BinaryProjection.frameProjection_fixed_of_mem_span
#print axioms ExactFourierCircuits.BinaryProjection.frameProjection_generator
#print axioms ExactFourierCircuits.BinaryProjection.frameProjection_mem_span
#print axioms ExactFourierCircuits.BinaryProjection.frameProjection_remainder_mem_orth
#print axioms ExactFourierCircuits.BinaryProjection.frameProjection_smul
#print axioms ExactFourierCircuits.BinaryProjection.frameProjection_sumFamily
#print axioms ExactFourierCircuits.BinaryProjection.frameProjection_unique
#print axioms ExactFourierCircuits.BinaryProjection.frameSpan
#print axioms ExactFourierCircuits.BinaryProjection.frameSpan.eq_1
#print axioms ExactFourierCircuits.BinaryProjection.frameSpan_decomposes_residual
#print axioms ExactFourierCircuits.BinaryProjection.frameSpan_decomposes_residual._abel_1_1
#print axioms ExactFourierCircuits.BinaryProjection.frameSpan_disjoint_residual
#print axioms ExactFourierCircuits.BinaryProjection.frameSpan_nondegenerate
#print axioms ExactFourierCircuits.BinaryProjection.frame_orth
#print axioms ExactFourierCircuits.BinaryProjection.frame_ratio_decreasing
#print axioms ExactFourierCircuits.BinaryProjection.frame_ratio_increasing
#print axioms ExactFourierCircuits.BinaryProjection.frame_unit
#print axioms ExactFourierCircuits.BinaryProjection.nested_basis_ratio_decreasing
#print axioms ExactFourierCircuits.BinaryProjection.nested_basis_ratio_increasing
#print axioms ExactFourierCircuits.BinaryProjection.nested_frame_ratio_decreasing
#print axioms ExactFourierCircuits.BinaryProjection.nested_frame_ratio_increasing
#print axioms ExactFourierCircuits.BinaryProjection.projectionMap
#print axioms ExactFourierCircuits.BinaryProjection.projectionMap._proof_1
#print axioms ExactFourierCircuits.BinaryProjection.projectionMap_eq_of_span_eq
#print axioms ExactFourierCircuits.BinaryProjection.residual_exponent_decreasing
#print axioms ExactFourierCircuits.BinaryProjection.residual_exponent_increasing
#print axioms ExactFourierCircuits.BinaryProjection.signedWords_eq_of_span_eq
