import UniformGenericPhysicalCoordinate
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformGenericPhysicalCoordinate.castval
#print axioms ExactFourierCircuits.UniformGenericPhysicalCoordinate.digits
#print axioms ExactFourierCircuits.UniformGenericPhysicalCoordinate.digits._f
#print axioms ExactFourierCircuits.UniformGenericPhysicalCoordinate.digits._sunfold
#print axioms ExactFourierCircuits.UniformGenericPhysicalCoordinate.digits._unsafe_rec
#print axioms ExactFourierCircuits.UniformGenericPhysicalCoordinate.digits.match_1
#print axioms ExactFourierCircuits.UniformGenericPhysicalCoordinate.digitsEquiv
#print axioms ExactFourierCircuits.UniformGenericPhysicalCoordinate.digits_undigits
#print axioms ExactFourierCircuits.UniformGenericPhysicalCoordinate.index
#print axioms ExactFourierCircuits.UniformGenericPhysicalCoordinate.index._proof_1
#print axioms ExactFourierCircuits.UniformGenericPhysicalCoordinate.listCoordinate
#print axioms ExactFourierCircuits.UniformGenericPhysicalCoordinate.list_value
#print axioms ExactFourierCircuits.UniformGenericPhysicalCoordinate.physical
#print axioms ExactFourierCircuits.UniformGenericPhysicalCoordinate.physical._proof_1
#print axioms ExactFourierCircuits.UniformGenericPhysicalCoordinate.physical_value
#print axioms ExactFourierCircuits.UniformGenericPhysicalCoordinate.shape
#print axioms ExactFourierCircuits.UniformGenericPhysicalCoordinate.undigits
#print axioms ExactFourierCircuits.UniformGenericPhysicalCoordinate.undigits._f
#print axioms ExactFourierCircuits.UniformGenericPhysicalCoordinate.undigits._sunfold
#print axioms ExactFourierCircuits.UniformGenericPhysicalCoordinate.undigits._unsafe_rec
#print axioms ExactFourierCircuits.UniformGenericPhysicalCoordinate.undigits.match_1
#print axioms ExactFourierCircuits.UniformGenericPhysicalCoordinate.undigits_digits
