import UniformLocalRequestFacts
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformLocalRequestGeometry.Geometry.binding
#print axioms ExactFourierCircuits.UniformLocalRequestGeometry.Geometry.end_before_leaf
#print axioms ExactFourierCircuits.UniformLocalRequestGeometry.Geometry.end_before_leaf._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalRequestGeometry.Geometry.end_before_leaf._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalRequestGeometry.Geometry.prefix_bound
#print axioms ExactFourierCircuits.UniformLocalRequestGeometry.Geometry.prefixes
#print axioms ExactFourierCircuits.UniformLocalRequestGeometry.Geometry.scalar_end
#print axioms ExactFourierCircuits.UniformLocalRequestGeometry.Geometry.scalar_end._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalRequestGeometry.Geometry.scalar_end._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalRequestGeometry.Geometry.source_retained
#print axioms ExactFourierCircuits.UniformLocalRequestGeometry.Geometry.source_retained._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalRequestGeometry.Geometry.source_retained._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalRequestGeometry.Geometry.source_retained._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalRequestGeometry.Geometry.source_retained._proof_1_4
#print axioms ExactFourierCircuits.UniformLocalRequestGeometry.Geometry.total
#print axioms ExactFourierCircuits.UniformLocalRequestGeometry.Geometry.total._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalRequestGeometry.Geometry.total._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalRequestGeometry.Geometry.workspaces
#print axioms ExactFourierCircuits.UniformLocalRequestGeometry.WorkspaceBound
#print axioms ExactFourierCircuits.UniformLocalRequestGeometry.low_before_cache
#print axioms ExactFourierCircuits.UniformLocalRequestGeometry.low_before_cache._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalRequestGeometry.low_before_cache._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalRequestGeometry.scalar_prior
#print axioms ExactFourierCircuits.UniformLocalRequestGeometry.scalar_prior._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalRequestGeometry.scalar_prior._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalRequestGeometry.small_budgets
#print axioms ExactFourierCircuits.UniformLocalRequestGeometry.small_budgets._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalRequestGeometry.workspace_end
