import UniformAxisCacheTimingConductor
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformAxisCacheTimingConductor.directory_transport
#print axioms ExactFourierCircuits.UniformAxisCacheTimingConductor.directory_transport._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheTimingConductor.execution
#print axioms ExactFourierCircuits.UniformAxisCacheTimingConductor.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheTimingConductor.execution._proof_1_10
#print axioms ExactFourierCircuits.UniformAxisCacheTimingConductor.execution._proof_1_11
#print axioms ExactFourierCircuits.UniformAxisCacheTimingConductor.execution._proof_1_12
#print axioms ExactFourierCircuits.UniformAxisCacheTimingConductor.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformAxisCacheTimingConductor.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformAxisCacheTimingConductor.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformAxisCacheTimingConductor.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformAxisCacheTimingConductor.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformAxisCacheTimingConductor.execution._proof_1_7
#print axioms ExactFourierCircuits.UniformAxisCacheTimingConductor.execution._proof_1_8
#print axioms ExactFourierCircuits.UniformAxisCacheTimingConductor.execution._proof_1_9
#print axioms ExactFourierCircuits.UniformAxisCacheTimingConductor.sources_transport
#print axioms ExactFourierCircuits.UniformAxisCacheTimingConductor.sources_transport._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheTimingConductor.sources_transport._proof_1_2
#print axioms ExactFourierCircuits.UniformAxisCacheTimingConductor.sources_transport._proof_1_3
