import UniformPermutationInversePreparation

#print axioms ExactFourierCircuits.UniformPermutationInversePreparation.inverseBase
#print axioms ExactFourierCircuits.UniformPermutationInversePreparation.setup
#print axioms ExactFourierCircuits.UniformPermutationInversePreparation.setup_length
#print axioms ExactFourierCircuits.UniformPermutationInversePreparation.program
#print axioms ExactFourierCircuits.UniformPermutationInversePreparation.program_length
#print axioms ExactFourierCircuits.UniformPermutationInversePreparation.input_code
#print axioms ExactFourierCircuits.UniformPermutationInversePreparation.setup_code
#print axioms ExactFourierCircuits.UniformPermutationInversePreparation.inverse_code
#print axioms ExactFourierCircuits.UniformPermutationInversePreparation.halt_at
#print axioms ExactFourierCircuits.UniformPermutationInversePreparation.Metadata
#print axioms ExactFourierCircuits.UniformPermutationInversePreparation.Metadata.fromReady
#print axioms ExactFourierCircuits.UniformPermutationInversePreparation.Metadata.transport_saved
#print axioms ExactFourierCircuits.UniformPermutationInversePreparation.Metadata.transport
#print axioms ExactFourierCircuits.UniformPermutationInversePreparation.setup_nat
#print axioms ExactFourierCircuits.UniformPermutationInversePreparation.setup_heap
#print axioms ExactFourierCircuits.UniformPermutationInversePreparation.setup_natHeap
#print axioms ExactFourierCircuits.UniformPermutationInversePreparation.setup_outputs
#print axioms ExactFourierCircuits.UniformPermutationInversePreparation.setup_roots
#print axioms ExactFourierCircuits.UniformPermutationInversePreparation.setup_registers
#print axioms ExactFourierCircuits.UniformPermutationInversePreparation.beta_fits
#print axioms ExactFourierCircuits.UniformPermutationInversePreparation.setup_peak
#print axioms ExactFourierCircuits.UniformPermutationInversePreparation.word_setup
#print axioms ExactFourierCircuits.UniformPermutationInversePreparation.preparationBudget
#print axioms ExactFourierCircuits.UniformPermutationInversePreparation.preparation_execution
#print axioms ExactFourierCircuits.UniformPermutationInversePreparation.preparationBudget_isBigO_input
