import UniformLocalFactorDispatchControl
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.branches
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.branches.eq_1
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.final_cacheHeaders
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.final_cacheHeaders._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.final_cacheHeaders._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.final_cacheHeaders._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.final_saved
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.final_saved._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.final_saved._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.final_saved._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.final_saved._proof_1_4
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.final_saved._proof_1_5
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.final_saved._proof_1_6
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.final_saved._proof_1_7
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.finish
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.finish._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.inverseSetup_nat
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.inverseSetup_safe
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.prepared_rowBase
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.select
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.select._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.select._proof_1_4
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.select._proof_1_5
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.select._proof_1_6
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.target
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.target.eq_1
