import UniformAlternateSynchronizedSchedule
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformAlternateSynchronizedSchedule.axisLayers
#print axioms ExactFourierCircuits.UniformAlternateSynchronizedSchedule.axisLayers.eq_1
#print axioms ExactFourierCircuits.UniformAlternateSynchronizedSchedule.inverse_beta_restores
#print axioms ExactFourierCircuits.UniformAlternateSynchronizedSchedule.local_length
#print axioms ExactFourierCircuits.UniformAlternateSynchronizedSchedule.ordinal
#print axioms ExactFourierCircuits.UniformAlternateSynchronizedSchedule.ordinal.eq_1
#print axioms ExactFourierCircuits.UniformAlternateSynchronizedSchedule.ordinal_eq
#print axioms ExactFourierCircuits.UniformAlternateSynchronizedSchedule.schedule
#print axioms ExactFourierCircuits.UniformAlternateSynchronizedSchedule.schedule.eq_1
#print axioms ExactFourierCircuits.UniformAlternateSynchronizedSchedule.schedule_length
#print axioms ExactFourierCircuits.UniformAlternateSynchronizedSchedule.schedule_product
#print axioms ExactFourierCircuits.UniformAlternateSynchronizedSchedule.selected_product
