import UniformFastPhysicalCRTEmission
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.Outside
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_constants
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_frame
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_frame._proof_1_10
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_frame._proof_1_11
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_frame._proof_1_12
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_frame._proof_1_13
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_frame._proof_1_14
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_frame._proof_1_15
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_frame._proof_1_16
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_frame._proof_1_17
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_frame._proof_1_18
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_frame._proof_1_19
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_frame._proof_1_2
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_frame._proof_1_20
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_frame._proof_1_21
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_frame._proof_1_3
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_frame._proof_1_4
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_frame._proof_1_5
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_frame._proof_1_6
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_frame._proof_1_7
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_frame._proof_1_8
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_frame._proof_1_9
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_heap
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_heap._proof_1_2
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_index
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_normal
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_outside
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_outside._proof_1_1
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_outside._proof_1_2
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_safe
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_safe._proof_1_2
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.emit_safe._proof_1_3
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.execution
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTEmission.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTMachine.emitBody.eq_1
