import UniformResidualExtendedPermutation
import Lean

-- Inventory uses defining-module provenance, including generated/private names.
set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.address_eq
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.address_eq._proof_1_2
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.complete_batches
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.complete_batches._proof_1_1
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.copiedArray
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.copiedMatrix
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.copied_array
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.fibers
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.fibers.eq_1
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.fibers_coordinates
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.fibers_flat
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.flat
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.flat.eq_1
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.flat_value
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.groups
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.groups._proof_1
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.groups._proof_2
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.groups_fibers
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.image
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.image.eq_1
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.image_high
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.image_high._proof_1_1
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.image_high._proof_1_2
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.image_high._proof_1_4
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.image_low
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.image_low._proof_1_1
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.image_low._proof_1_3
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.image_low._proof_1_4
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.image_small
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.padded_bits
#print axioms ExactFourierCircuits.UniformResidualExtendedPermutation.seed_groups_fit
