import UniformFinalOutputTail
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformFinalOutputTail.execution
#print axioms ExactFourierCircuits.UniformFinalOutputTail.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformFinalOutputTail.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformFinalOutputTail.execution._proof_1_3
