import UniformLocalBroadcastSemantics
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformColoring.earlierColors.eq_1
#print axioms ExactFourierCircuits.UniformLocalBroadcastSemantics.cross_broadcast_color_at
#print axioms ExactFourierCircuits.UniformLocalBroadcastSemantics.cross_broadcast_eq
#print axioms ExactFourierCircuits.UniformLocalBroadcastSemantics.cross_broadcast_eq._proof_1
#print axioms ExactFourierCircuits.UniformLocalBroadcastSemantics.cross_broadcast_eq._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalBroadcastSemantics.cross_broadcast_eq._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalBroadcastSemantics.cross_broadcast_eq._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalBroadcastSemantics.cross_broadcast_matching
#print axioms ExactFourierCircuits.UniformLocalBroadcastSemantics.cross_broadcast_matching._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalBroadcastSemantics.cross_broadcast_matching._proof_1_4
#print axioms ExactFourierCircuits.UniformLocalBroadcastSemantics.disjoint_colorBlocks
#print axioms ExactFourierCircuits.UniformLocalBroadcastSemantics.disjoint_color_at
#print axioms ExactFourierCircuits.UniformLocalBroadcastSemantics.disjoint_color_at._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalBroadcastSemantics.disjoint_coloring_zero
#print axioms ExactFourierCircuits.UniformLocalBroadcastSemantics.disjoint_coloring_zero._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalBroadcastSemantics.disjoint_greedy_zero
#print axioms ExactFourierCircuits.UniformLocalBroadcastSemantics.disjoint_neighbors
#print axioms ExactFourierCircuits.UniformLocalBroadcastSemantics.disjoint_neighbors._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalBroadcastSemantics.disjoint_neighbors._simp_1_1
#print axioms ExactFourierCircuits.UniformLocalBroadcastSemantics.disjoint_neighbors._simp_1_2
#print axioms ExactFourierCircuits.UniformLocalBroadcastSemantics.entry
#print axioms ExactFourierCircuits.UniformLocalBroadcastSemantics.entry._proof_1
#print axioms ExactFourierCircuits.UniformLocalBroadcastSemantics.entry._proof_2
#print axioms ExactFourierCircuits.UniformLocalBroadcastSemantics.entry.congr_simp
#print axioms ExactFourierCircuits.UniformLocalBroadcastSemantics.entry.eq_1
#print axioms ExactFourierCircuits.UniformLocalBroadcastSemantics.firstFree_empty
#print axioms ExactFourierCircuits.UniformLocalBroadcastSemantics.firstFree_empty._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalBroadcastSemantics.reference_some
