import UniformRecursivePreparedNativeRecords
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.exchange_prepared
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.marker_prepared
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.scalar_prepared
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.translation_prepared
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.translation_prepared._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.translation_prepared._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.translation_prepared._proof_1_3
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.translation_prepared._proof_1_4
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.translation_prepared._proof_1_5
