import UniformGlobalAxisIterationOutside
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformGlobalAxisIterationOutside.execution_outside
#print axioms ExactFourierCircuits.UniformGlobalAxisIterationOutside.execution_outside._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalAxisIterationOutside.execution_outside._proof_1_10
#print axioms ExactFourierCircuits.UniformGlobalAxisIterationOutside.execution_outside._proof_1_11
#print axioms ExactFourierCircuits.UniformGlobalAxisIterationOutside.execution_outside._proof_1_12
#print axioms ExactFourierCircuits.UniformGlobalAxisIterationOutside.execution_outside._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalAxisIterationOutside.execution_outside._proof_1_3
#print axioms ExactFourierCircuits.UniformGlobalAxisIterationOutside.execution_outside._proof_1_4
#print axioms ExactFourierCircuits.UniformGlobalAxisIterationOutside.execution_outside._proof_1_5
#print axioms ExactFourierCircuits.UniformGlobalAxisIterationOutside.execution_outside._proof_1_6
#print axioms ExactFourierCircuits.UniformGlobalAxisIterationOutside.execution_outside._proof_1_7
#print axioms ExactFourierCircuits.UniformGlobalAxisIterationOutside.execution_outside._proof_1_8
#print axioms ExactFourierCircuits.UniformGlobalAxisIterationOutside.execution_outside._proof_1_9
