import UniformRecursiveSmallExecution
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformRecursiveSmallExecution.execution
#print axioms ExactFourierCircuits.UniformRecursiveSmallExecution.finish_code
#print axioms ExactFourierCircuits.UniformRecursiveSmallExecution.frame_stack
#print axioms ExactFourierCircuits.UniformRecursiveSmallExecution.frame_stack._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveSmallExecution.frame_stack._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveSmallExecution.frame_stack._proof_1_3
#print axioms ExactFourierCircuits.UniformRecursiveSmallExecution.halt_code
#print axioms ExactFourierCircuits.UniformRecursiveSmallExecution.ready_branch
#print axioms ExactFourierCircuits.UniformRecursiveSmallExecution.ready_branch._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveSmallExecution.ready_literal
#print axioms ExactFourierCircuits.UniformRecursiveSmallExecution.ready_literal._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveSmallExecution.root_execution
#print axioms ExactFourierCircuits.UniformRecursiveSmallExecution.setup_code
#print axioms ExactFourierCircuits.UniformRecursiveSmallExecution.setup_follow
#print axioms ExactFourierCircuits.UniformRecursiveSmallExecution.start_bound
#print axioms ExactFourierCircuits.UniformRecursiveSmallExecution.start_bound._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveSmallExecution.zero_cell
