import UniformSynchronizedLayers
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformSynchronizedLayers.axes
#print axioms ExactFourierCircuits.UniformSynchronizedLayers.localSchedules
#print axioms ExactFourierCircuits.UniformSynchronizedLayers.localSchedules_length
#print axioms ExactFourierCircuits.UniformSynchronizedLayers.ofFn_slot
#print axioms ExactFourierCircuits.UniformSynchronizedLayers.padded
#print axioms ExactFourierCircuits.UniformSynchronizedLayers.padded.eq_1
#print axioms ExactFourierCircuits.UniformSynchronizedLayers.padded_calls
#print axioms ExactFourierCircuits.UniformSynchronizedLayers.padded_length
#print axioms ExactFourierCircuits.UniformSynchronizedLayers.padded_length._proof_1_2
#print axioms ExactFourierCircuits.UniformSynchronizedLayers.padded_matrix
#print axioms ExactFourierCircuits.UniformSynchronizedLayers.radix
#print axioms ExactFourierCircuits.UniformSynchronizedLayers.selectedSchedule
#print axioms ExactFourierCircuits.UniformSynchronizedLayers.selectedSchedule.eq_1
#print axioms ExactFourierCircuits.UniformSynchronizedLayers.selectedSchedule_action
#print axioms ExactFourierCircuits.UniformSynchronizedLayers.selectedSchedule_length
#print axioms ExactFourierCircuits.UniformSynchronizedLayers.selectedSchedule_product
#print axioms ExactFourierCircuits.UniformSynchronizedLayers.slot
#print axioms ExactFourierCircuits.UniformSynchronizedLayers.slot._proof_1
#print axioms ExactFourierCircuits.UniformSynchronizedLayers.slot_product
#print axioms ExactFourierCircuits.UniformSynchronizedLayers.tensorSchedule
#print axioms ExactFourierCircuits.UniformSynchronizedLayers.tensorSchedule.eq_1
#print axioms ExactFourierCircuits.UniformSynchronizedLayers.tensorSchedule_length
#print axioms ExactFourierCircuits.UniformSynchronizedLayers.tensorSchedule_product
#print axioms ExactFourierCircuits.UniformSynchronizedLayers.tensorSlot
#print axioms ExactFourierCircuits.UniformSynchronizedLayers.tensorSlot.congr_simp
