import UniformScalarPreparation

#print axioms ExactFourierCircuits.UniformScalarPreparation.Instruction.eval_conjugate
#print axioms ExactFourierCircuits.UniformScalarPreparation.Instruction.admissible_conjugate
#print axioms ExactFourierCircuits.UniformScalarPreparation.Program.eval_conjugate
#print axioms ExactFourierCircuits.UniformScalarPreparation.Program.admissible_conjugate
#print axioms ExactFourierCircuits.UniformScalarPreparation.Program.run_conjugate
#print axioms ExactFourierCircuits.UniformScalarPreparation.Program.eval_inverse_roots
#print axioms ExactFourierCircuits.UniformScalarPreparation.Program.admissible_inverse_roots
#print axioms ExactFourierCircuits.UniformScalarPreparation.Program.eval_rootsOfUnity
#print axioms ExactFourierCircuits.UniformScalarPreparation.Program.admissible_rootsOfUnity
#print axioms ExactFourierCircuits.UniformScalarPreparation.DAG.admissible_conjugate
#print axioms ExactFourierCircuits.UniformScalarPreparation.DAG.run_conjugate
#print axioms ExactFourierCircuits.UniformScalarPreparation.DAG.admissible_inverse_roots
#print axioms ExactFourierCircuits.UniformScalarPreparation.DAG.run_inverse_roots
#print axioms ExactFourierCircuits.UniformScalarPreparation.DAG.admissible_rootsOfUnity
#print axioms ExactFourierCircuits.UniformScalarPreparation.DAG.run_rootsOfUnity
#print axioms ExactFourierCircuits.UniformScalarPreparation.DAG.preparedKappa_eq
#print axioms ExactFourierCircuits.UniformScalarPreparation.DAG.preparedKappa_inverse_roots
#print axioms ExactFourierCircuits.UniformScalarPreparation.DAG.preparedKappa_ne_zero
#print axioms ExactFourierCircuits.UniformScalarPreparation.DAG.preparedSecond_ne_zero
#print axioms ExactFourierCircuits.UniformScalarPreparation.DAG.shearWord_matrix
#print axioms ExactFourierCircuits.UniformScalarPreparation.DAG.shearWord_calls
