import UniformDirectLeafForestCacheRetention
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformDirectLeafForestCacheRetention.cached_transport
#print axioms ExactFourierCircuits.UniformDirectLeafForestCacheRetention.cached_transport._proof_1_1
#print axioms ExactFourierCircuits.UniformDirectLeafForestCacheRetention.cached_transport._proof_1_2
#print axioms ExactFourierCircuits.UniformDirectLeafForestCacheRetention.cached_transport._proof_1_3
#print axioms ExactFourierCircuits.UniformDirectLeafForestCacheRetention.counts_transport
#print axioms ExactFourierCircuits.UniformDirectLeafForestCacheRetention.counts_transport._proof_1_1
#print axioms ExactFourierCircuits.UniformDirectLeafForestCacheRetention.counts_transport._proof_1_2
#print axioms ExactFourierCircuits.UniformDirectLeafForestCacheRetention.counts_transport._proof_1_3
#print axioms ExactFourierCircuits.UniformDirectLeafForestCacheRetention.counts_transport._proof_1_4
#print axioms ExactFourierCircuits.UniformDirectLeafForestCacheRetention.counts_transport._proof_1_5
#print axioms ExactFourierCircuits.UniformDirectLeafForestCacheRetention.counts_transport._proof_1_6
#print axioms ExactFourierCircuits.UniformDirectLeafForestCacheRetention.counts_transport._proof_1_7
#print axioms ExactFourierCircuits.UniformDirectLeafForestCacheRetention.earlier_bounds
#print axioms ExactFourierCircuits.UniformDirectLeafForestCacheRetention.earlier_bounds._proof_1
#print axioms ExactFourierCircuits.UniformDirectLeafForestCacheRetention.earlier_bounds._proof_1_1
#print axioms ExactFourierCircuits.UniformDirectLeafForestCacheRetention.earlier_bounds._proof_1_2
#print axioms ExactFourierCircuits.UniformDirectLeafForestCacheRetention.earlier_bounds._proof_1_3
#print axioms ExactFourierCircuits.UniformDirectLeafForestCacheRetention.earlier_bounds._proof_2
#print axioms ExactFourierCircuits.UniformDirectLeafForestCacheRetention.ranges_transport
#print axioms ExactFourierCircuits.UniformDirectLeafForestCacheRetention.ranges_transport._proof_1_1
#print axioms ExactFourierCircuits.UniformDirectLeafForestCacheRetention.ranges_transport._proof_1_2
#print axioms ExactFourierCircuits.UniformDirectLeafForestCacheRetention.ranges_transport._proof_1_3
#print axioms ExactFourierCircuits.UniformDirectLeafForestCacheRetention.ranges_transport._proof_1_4
#print axioms ExactFourierCircuits.UniformDirectLeafForestCacheRetention.ranges_transport._proof_1_5
#print axioms ExactFourierCircuits.UniformDirectLeafForestCacheRetention.ranges_transport._proof_1_6
#print axioms ExactFourierCircuits.UniformDirectLeafForestCacheRetention.ranges_transport._proof_1_7
