import UniformGlobalKernelDiagonalAssembly
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformGlobalKernelDiagonalAssembly.diagonal_code
#print axioms ExactFourierCircuits.UniformGlobalKernelDiagonalAssembly.halt_at
#print axioms ExactFourierCircuits.UniformGlobalKernelDiagonalAssembly.headerProgram
#print axioms ExactFourierCircuits.UniformGlobalKernelDiagonalAssembly.headerProgram.eq_1
#print axioms ExactFourierCircuits.UniformGlobalKernelDiagonalAssembly.header_code
#print axioms ExactFourierCircuits.UniformGlobalKernelDiagonalAssembly.header_code._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalKernelDiagonalAssembly.header_jump
#print axioms ExactFourierCircuits.UniformGlobalKernelDiagonalAssembly.header_jump._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalKernelDiagonalAssembly.header_length
#print axioms ExactFourierCircuits.UniformGlobalKernelDiagonalAssembly.kernel_code
#print axioms ExactFourierCircuits.UniformGlobalKernelDiagonalAssembly.programFor
#print axioms ExactFourierCircuits.UniformGlobalKernelDiagonalAssembly.programFor.eq_1
#print axioms ExactFourierCircuits.UniformGlobalKernelDiagonalAssembly.program_length
