import UniformRolePointwiseMachine
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.Changed
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.Frame
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.Frame.casesOn
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.Frame.mk
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.Frame.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.Frame.natHeap
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.Frame.natReg
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.Frame.outputs
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.Frame.rec
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.Frame.recOn
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.Frame.roots
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.Frame.scalar
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.Source
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.execution
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.execution._proof_1_10
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.execution._proof_1_11
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.execution._proof_1_13
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.execution._proof_1_14
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.execution._proof_1_15
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.execution._proof_1_8
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.execution._proof_1_9
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.halt_at
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.multiplied
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.multiplied.eq_1
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.pointwise_code
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.program
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.program_length
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.setup
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.setup.eq_1
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.setup_code
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.setup_frame
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.setup_frame._proof_1_10
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.setup_frame._proof_1_11
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.setup_frame._proof_1_12
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.setup_frame._proof_1_13
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.setup_frame._proof_1_14
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.setup_frame._proof_1_15
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.setup_frame._proof_1_16
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.setup_frame._proof_1_5
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.setup_frame._proof_1_6
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.setup_frame._proof_1_7
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.setup_frame._proof_1_8
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.setup_frame._proof_1_9
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.setup_length
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.setup_safe
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.setup_safe._proof_1_13
#print axioms ExactFourierCircuits.UniformRolePointwiseMachine.setup_values

open Lean Elab Command in
run_cmd do
 let env ← getEnv
 for (name, _) in env.constants.toList do
  if "_private.UniformRolePointwiseMachine.".isPrefixOf name.toString then
   let axs ← collectAxioms name
   logInfo m!"{name} depends on axioms: {axs.toList}"
