import UniformActualCalendarForestRegistry
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.block
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.block._proof_1
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.block.eq_1
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.block_get
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.data
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.data._proof_1
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.data._proof_2
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.data._proof_3
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.family
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.family._proof_1
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.family._proof_10
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.family._proof_11
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.family._proof_12
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.family._proof_13
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.family._proof_14
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.family._proof_15
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.family._proof_16
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.family._proof_17
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.family._proof_18
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.family._proof_19
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.family._proof_2
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.family._proof_3
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.family._proof_4
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.family._proof_5
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.family._proof_6
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.family._proof_7
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.family._proof_8
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.family._proof_9
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.is_leaf
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.is_leaf._proof_1
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.is_leaf._proof_1_1
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.record_bound
#print axioms ExactFourierCircuits.UniformActualCalendarForestRegistry.record_bound._proof_1_1
