import UniformFixedNetworkLiteralDecoderMachine
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.Frame
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.Frame.casesOn
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.Frame.mk
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.Frame.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.Frame.natReg
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.Frame.of_printer
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.Frame.outputs
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.Frame.pc
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.Frame.rec
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.Frame.recOn
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.Frame.roots
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.Frame.scalarHeap
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.Frame.scalarReg
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.Frame.trans
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.PrintedRecords.transport
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.PrintedRecords.transport._proof_1_1
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.PrintedRecords.transport._proof_1_2
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.continuation
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.continuation.eq_1
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.data_columns
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.data_columns._proof_1_1
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.data_columns._proof_1_2
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.data_columns._proof_1_3
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.data_columns._proof_1_4
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.data_columns_length
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.data_length_positive
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.data_length_positive._proof_1_1
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.execution
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.execution._proof_1_10
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.execution._proof_1_11
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.execution._proof_1_7
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.execution._proof_1_8
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.execution._simp_1_9
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.fixedProgram
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.fixed_execution
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.halt_at
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.header_columns
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patchBlock
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patchBlock.eq_1
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patchBlock_length
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patchBlock_length._proof_1_3
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patch_code
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patches
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patches._f
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patches._sunfold
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patches._unsafe_rec
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patches.eq_1
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patches.eq_2
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patches.eq_def
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patches.match_1
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patches_frame
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patches_length
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patches_length._proof_1_4
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patches_safe
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patches_safe._proof_1_4
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patches_safe._proof_1_5
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patches_safe._proof_1_6
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patches_safe._proof_1_7
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patches_safe._proof_1_8
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patches_safe._simp_1_9
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patches_spec
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patches_spec._proof_1_4
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patches_spec._proof_1_5
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patches_spec._proof_1_6
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patches_spec._proof_1_7
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patches_spec._proof_1_8
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.patches_spec._proof_1_9
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.placed_zero
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.printer_code
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.program
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.program.eq_1
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.program_length
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.program_length._proof_1_2
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.serialize_cons
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.serialize_length_cons
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.setup
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.setup.eq_1
#print axioms ExactFourierCircuits.UniformFixedNetworkLiteralDecoderMachine.setup_frame

open Lean Elab Command in
run_cmd do
 let env ← getEnv
 for (name, _) in env.constants.toList do
  if "_private.UniformFixedNetworkLiteralDecoderMachine.".isPrefixOf name.toString then
   let axs ← collectAxioms name
   logInfo m!"{name} depends on axioms: {axs.toList}"
