import UniformActualClockOuterFrameConstruction
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformActualClockOuterFrameConstruction.Spectrum.refl
#print axioms ExactFourierCircuits.UniformActualClockOuterFrameConstruction.Spectrum.trans
#print axioms ExactFourierCircuits.UniformActualClockOuterFrameConstruction.Spectrum.withPC
#print axioms ExactFourierCircuits.UniformActualClockOuterFrameConstruction.axis
#print axioms ExactFourierCircuits.UniformActualClockOuterFrameConstruction.axis._proof_1_1
#print axioms ExactFourierCircuits.UniformActualClockOuterFrameConstruction.axis._proof_1_2
#print axioms ExactFourierCircuits.UniformActualClockOuterFrameConstruction.axis._proof_1_3
#print axioms ExactFourierCircuits.UniformActualClockOuterFrameConstruction.axis._proof_1_4
#print axioms ExactFourierCircuits.UniformActualClockOuterFrameConstruction.low_two
#print axioms ExactFourierCircuits.UniformActualClockOuterFrameConstruction.low_two._proof_1_1
#print axioms ExactFourierCircuits.UniformActualClockOuterFrameConstruction.low_two._proof_1_2
#print axioms ExactFourierCircuits.UniformActualClockOuterFrameConstruction.low_two._proof_1_3
#print axioms ExactFourierCircuits.UniformActualClockOuterFrameConstruction.low_two._proof_1_4
#print axioms ExactFourierCircuits.UniformActualClockOuterFrameConstruction.low_two._proof_1_5
#print axioms ExactFourierCircuits.UniformActualClockOuterFrameConstruction.stride_bound
