import UniformMasterSynchronizedLayers

#print axioms ExactFourierCircuits.UniformMasterSynchronizedLayers.size
#print axioms ExactFourierCircuits.UniformMasterSynchronizedLayers.size_eq
#print axioms ExactFourierCircuits.UniformMasterSynchronizedLayers.radix_divides
#print axioms ExactFourierCircuits.UniformMasterSynchronizedLayers.localSchedules
#print axioms ExactFourierCircuits.UniformMasterSynchronizedLayers.localSchedules_matrix
#print axioms ExactFourierCircuits.UniformMasterSynchronizedLayers.localSchedules_length
#print axioms ExactFourierCircuits.UniformMasterSynchronizedLayers.schedule
#print axioms ExactFourierCircuits.UniformMasterSynchronizedLayers.schedule_length
#print axioms ExactFourierCircuits.UniformMasterSynchronizedLayers.schedule_product
#print axioms ExactFourierCircuits.UniformMasterSynchronizedLayers.coordinates
#print axioms ExactFourierCircuits.UniformMasterSynchronizedLayers.schedule_radices
#print axioms ExactFourierCircuits.UniformMasterSynchronizedLayers.schedule_action
#print axioms ExactFourierCircuits.UniformMasterSynchronizedLayers.ordinalMatrix
#print axioms ExactFourierCircuits.UniformMasterSynchronizedLayers.ordinalMatrix_entry
#print axioms ExactFourierCircuits.UniformMasterSynchronizedLayers.ordinalMatrix_action
#print axioms ExactFourierCircuits.UniformMasterSynchronizedLayers.inverse_beta_restores
