import UniformInitializedPreparedKernel
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformInitializedPreparedKernel.after_header
#print axioms ExactFourierCircuits.UniformInitializedPreparedKernel.after_header._proof_1_1
#print axioms ExactFourierCircuits.UniformInitializedPreparedKernel.after_header._proof_1_2
#print axioms ExactFourierCircuits.UniformInitializedPreparedKernel.code_space
#print axioms ExactFourierCircuits.UniformInitializedPreparedKernel.code_space._proof_1_1
#print axioms ExactFourierCircuits.UniformInitializedPreparedKernel.execution
#print axioms ExactFourierCircuits.UniformInitializedPreparedKernel.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformInitializedPreparedKernel.halt_at
#print axioms ExactFourierCircuits.UniformInitializedPreparedKernel.halt_at._proof_1_1
#print axioms ExactFourierCircuits.UniformInitializedPreparedKernel.halt_at._proof_1_2
#print axioms ExactFourierCircuits.UniformInitializedPreparedKernel.header_code
#print axioms ExactFourierCircuits.UniformInitializedPreparedKernel.kernel_code
#print axioms ExactFourierCircuits.UniformInitializedPreparedKernel.programFor
#print axioms ExactFourierCircuits.UniformInitializedPreparedKernel.programFor.eq_1
#print axioms ExactFourierCircuits.UniformInitializedPreparedKernel.program_length
#print axioms ExactFourierCircuits.UniformInitializedPreparedKernel.program_length._proof_1_2
#print axioms ExactFourierCircuits.UniformInitializedPreparedKernel.program_same
#print axioms ExactFourierCircuits.UniformInitializedPreparedKernel.ready_pc
#print axioms ExactFourierCircuits.UniformInitializedPreparedKernel.return_space
#print axioms ExactFourierCircuits.UniformInitializedPreparedKernel.return_space._proof_1_1
#print axioms ExactFourierCircuits.UniformInitializedPreparedKernel.sectors_positive
#print axioms ExactFourierCircuits.UniformInitializedPreparedKernel.sectors_positive._proof_1_1
#print axioms ExactFourierCircuits.UniformInitializedPreparedKernel.shift_bound
#print axioms ExactFourierCircuits.UniformInitializedPreparedKernel.shift_bound._proof_1_1
