import UniformNativeScheduleSemantics
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformFixedNetworkScheduleMachine.blockRecords.eq_1
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction._sizeOf_1
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction._sizeOf_inst
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.boundary
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.boundary.elim
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.boundary.inj
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.boundary.injEq
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.boundary.noConfusion
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.boundary.sizeOf_spec
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.casesOn
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.ctorElim
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.ctorElimType
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.ctorIdx
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.exchange
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.exchange.elim
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.exchange.sizeOf_spec
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.initial
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.initial.elim
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.initial.sizeOf_spec
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.macro
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.macro.elim
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.macro.inj
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.macro.injEq
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.macro.noConfusion
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.macro.sizeOf_spec
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.noConfusion
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.noConfusionType
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.padding
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.padding.elim
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.padding.sizeOf_spec
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.rec
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.recOn
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.record
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.record._proof_1
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.record._proof_2
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.record._proof_3
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.record.eq_1
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.record.eq_2
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.record.eq_3
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.record.eq_4
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.record.eq_5
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.record.eq_6
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.record.match_1
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.translation
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.translation.elim
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.translation.sizeOf_spec
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.word
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.word._proof_1
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.word._proof_2
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.word.eq_1
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.word.eq_2
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.word.eq_3
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.word.eq_4
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.word.eq_5
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.Instruction.word.eq_6
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.activeEmbedding
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.activeWord
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.activeWord.eq_1
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.activeWord_append
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.activeWord_flatten
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.blockAtM
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.compile
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.compile.eq_1
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.compile_actual
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.compile_append
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.compile_cons
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.compile_flatten
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.compile_simultaneous
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.compile_terminal
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.correctedAtM
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.correctedAtM_actual
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.correctedAtM_chronology
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.correctionAtM
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.instructions
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.instructions.eq_1
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.interpret
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.interpret.eq_1
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.interpret_actual
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.interpret_array
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.interpret_compile
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.lift_flatten
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.macro_block
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.macro_words
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.masterAtM
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.masterAtM_chronology
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.paddedAtM
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.paddedAtM_actual
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.paddingEmbedding
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.records_actual
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.semantic
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.terminal_records

open Lean Elab Command in
run_cmd do
 let env ← getEnv
 for (name, _) in env.constants.toList do
  if "_private.UniformNativeScheduleSemantics.".isPrefixOf name.toString then
   let axs ← collectAxioms name
   logInfo m!"{name} depends on axioms: {axs.toList}"
