import UniformDirectLeafCacheSemanticExecution
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.SemanticResult
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.SemanticResult._sizeOf_1
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.SemanticResult._sizeOf_inst
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.SemanticResult.casesOn
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.SemanticResult.ctorIdx
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.SemanticResult.endpoints
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.SemanticResult.mk
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.SemanticResult.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.SemanticResult.mk.inj
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.SemanticResult.mk.injEq
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.SemanticResult.mk.noConfusion
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.SemanticResult.mk.sizeOf_spec
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.SemanticResult.noConfusion
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.SemanticResult.noConfusionType
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.SemanticResult.rec
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.SemanticResult.recOn
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.SemanticResult.toResult
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.SemanticResult.unused
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.execution
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.execution._proof_1_10
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.execution._proof_1_11
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.execution._proof_1_12
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.execution._proof_1_7
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.execution._proof_1_8
#print axioms ExactFourierCircuits.UniformDirectLeafCacheSemanticExecution.execution._proof_1_9
