import UniformInverseMatchingFactorReload
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.reloadProgram
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.reloadProgram.eq_1
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.reloadProgram_length
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.reloadResult
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.reloadResult._proof_1_1
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.reloadResult._proof_1_2
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.reload_body_code
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.reload_execution
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.reload_execution._proof_1_1
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.reload_execution._proof_1_2
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.reload_execution._proof_1_3
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.reload_execution._proof_1_4
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.reload_execution._proof_1_5
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.reload_execution._proof_1_6
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.reload_execution._proof_1_7
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.reload_execution._proof_1_8
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.reload_halt
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.reload_setup_code
