import UniformCalendarPreparationOrder
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.LocalSources
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.LocalSources._sizeOf_1
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.LocalSources._sizeOf_inst
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.LocalSources.calls
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.LocalSources.casesOn
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.LocalSources.ctorIdx
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.LocalSources.factor
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.LocalSources.mk
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.LocalSources.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.LocalSources.mk.inj
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.LocalSources.mk.injEq
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.LocalSources.mk.noConfusion
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.LocalSources.mk.sizeOf_spec
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.LocalSources.noConfusion
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.LocalSources.noConfusionType
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.LocalSources.rec
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.LocalSources.recOn
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.LocalSources.records
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.allRows_position
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.callOrder
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.callOrder_event
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.foldValues_diagonal
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.matrix
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.position
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.position.congr_simp
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.position.eq_1
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.position_event
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.position_kernel
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.union
#print axioms ExactFourierCircuits.UniformCalendarPreparationOrder.union.congr_simp
