import UniformGlobalCalendarUnionRowsTable
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformGlobalCalendarUnionRows.execution_scalarFrame
#print axioms ExactFourierCircuits.UniformGlobalCalendarUnionRows.execution_table
#print axioms ExactFourierCircuits.UniformGlobalCalendarUnionRows.execution_table._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarUnionRows.execution_table._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalCalendarUnionRows.program_natOnly
#print axioms ExactFourierCircuits.UniformGlobalCalendarUnionRows.writeRows_get
#print axioms ExactFourierCircuits.UniformGlobalCalendarUnionRows.writeRows_get._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarUnionRows.writeRows_get._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalCalendarUnionRows.writeRows_get._proof_1_3
#print axioms ExactFourierCircuits.UniformGlobalCalendarUnionRows.writeRows_get._proof_1_4
#print axioms ExactFourierCircuits.UniformGlobalCalendarUnionRows.writeRows_get._proof_1_5
#print axioms ExactFourierCircuits.UniformGlobalCalendarUnionRows.writeRows_get._proof_1_6
#print axioms ExactFourierCircuits.UniformGlobalCalendarUnionRows.writeRows_get._proof_1_7
#print axioms ExactFourierCircuits.UniformGlobalCalendarUnionRows.writeRows_get._proof_1_8
#print axioms ExactFourierCircuits.UniformGlobalCalendarUnionRows.writeRows_get._proof_1_9
#print axioms ExactFourierCircuits.UniformGlobalCalendarUnionRows.writeRows_low
#print axioms ExactFourierCircuits.UniformGlobalCalendarUnionRows.writeRows_low._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarUnionRows.writeRows_low._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalCalendarUnionRows.writeRows_low._proof_1_3
#print axioms ExactFourierCircuits.UniformGlobalCalendarUnionRows.writeRows_low._proof_1_4
