import UniformActualCalendarAssembleEvents
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.assemble_make
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.assemble_make._proof_1_1
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.entries.eq_1
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.entries_length
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.global_bound
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.global_bound._proof_1_1
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.global_bound._proof_1_2
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.make_address_cast
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.make_address_mp
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.make_address_mpr
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.make_metadata_mp
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.make_metadata_mpr
