import UniformHadamardPairMachine
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformHadamardPairMachine.C_code
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.C_load_code
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.Constants
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.Constants.eq_1
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.Constants.protected
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.Constants.protected._proof_1_1
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.Constants.protected._proof_1_2
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.Protected
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.Protected.eq_1
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.Protected.trans
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.bounded_execution
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.bounded_execution._proof_1_1
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.bounded_execution._proof_1_10
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.bounded_execution._proof_1_11
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.bounded_execution._proof_1_12
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.bounded_execution._proof_1_13
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.bounded_execution._proof_1_14
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.bounded_execution._proof_1_15
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.bounded_execution._proof_1_16
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.bounded_execution._proof_1_17
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.bounded_execution._proof_1_18
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.bounded_execution._proof_1_19
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.bounded_execution._proof_1_2
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.bounded_execution._proof_1_20
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.bounded_execution._proof_1_21
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.bounded_execution._proof_1_22
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.bounded_execution._proof_1_5
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.bounded_execution._proof_1_6
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.bounded_execution._proof_1_7
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.bounded_execution._proof_1_8
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.constants_from_bank
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.contextFree
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.diagonal_load_code
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.factorization
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.first_diagonal_code
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.last_diagonal_code
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.left_value
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.left_value._simp_1_1
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.loadProgram
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.loadProgram.eq_1
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.loadState
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.loadState.eq_1
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.load_execution
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.load_execution._proof_1_1
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.load_execution._proof_1_2
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.load_execution._proof_1_3
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.load_execution._proof_1_4
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.preparation_constants
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.program
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.program.eq_1
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.program_length
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.protected_C
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.protected_diagonal
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.protected_diagonal._proof_1_1
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.protected_load
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.protected_load._proof_1_3
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.protected_load._proof_1_4
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.protected_reset
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.protected_right
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.protected_right._proof_1_3
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.protected_right._proof_1_4
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.reset
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.reset.eq_1
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.rightProgram
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.rightProgram.eq_1
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.rightState
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.rightState.eq_1
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.right_code
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.right_execution
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.right_execution._proof_1_1
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.right_execution._proof_1_2
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.right_execution._proof_1_3
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.right_value
#print axioms ExactFourierCircuits.UniformHadamardPairMachine.right_value._simp_1_1

open Lean Elab Command in
run_cmd do
 let env ← getEnv
 for (name, _) in env.constants.toList do
  if "_private.UniformHadamardPairMachine.".isPrefixOf name.toString then
   let axs ← collectAxioms name
   logInfo m!"{name} depends on axioms: {axs.toList}"
