import UniformInverseMatchingFactorGeometry
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.coefficient.eq_1
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.selectedIndex.eq_1
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.F.Config
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.F.Layout
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.coefficient
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.coefficient.eq_1
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.coefficient_address
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.coefficient_address._proof_1_1
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.coefficient_reference
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.coefficient_value
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.endpoints
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.forward_domain
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.forward_pointer
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.reference
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.reference.eq_1
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.reference_leaf
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.reverseIndex
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.reverseIndex._proof_1
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.reverseIndex._proof_2
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.reverseIndex.eq_1
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.reverseIndex_injective
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.reverseIndex_injective._proof_1_2
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.rows
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.rows.congr_simp
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.rows.eq_1
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.rows_geometry
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.rows_get
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.rows_get._proof_1
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.rows_length
#print axioms ExactFourierCircuits.UniformMatchingCoefficientValueBridge.selectedReference.eq_1
