import UniformDirectLeafHighExecution
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.Done
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.Done.args
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.Done.casesOn
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.Done.controls
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.Done.events
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.Done.inputs
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.Done.mk
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.Done.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.Done.natHigh
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.Done.natPrefix
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.Done.outputs
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.Done.pc
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.Done.rec
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.Done.recOn
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.Done.roots
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.Done.scalarOutside
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.loop
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.loop._proof_1_1
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.loop._proof_1_10
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.loop._proof_1_11
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.loop._proof_1_12
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.loop._proof_1_13
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.loop._proof_1_14
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.loop._proof_1_15
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.loop._proof_1_16
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.loop._proof_1_17
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.loop._proof_1_18
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.loop._proof_1_2
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.loop._proof_1_3
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.loop._proof_1_4
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.loop._proof_1_5
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.loop._proof_1_6
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.loop._proof_1_7
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.loop._proof_1_8
#print axioms ExactFourierCircuits.UniformDirectLeafHighExecution.loop._proof_1_9
