import UniformGlobalRolePackingLoop
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.NatOutside.prefix
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.NatOutside.prefix._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.NatOutside.prefix._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.NatOutside.refl
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.NatOutside.trans
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.banks_transfer
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.banks_transfer._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.banks_transfer._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.banks_transfer._proof_1_3
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.banks_transfer._proof_1_4
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.banks_transfer._proof_1_5
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.banks_transfer._proof_1_6
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.banks_transfer._proof_1_7
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.boot_cursor
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.execution
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.loop
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.loop._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.loop._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.loop._proof_1_3
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.loop._proof_1_4
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.loop._proof_1_5
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.loop._proof_1_6
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.loop._proof_1_7
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.loop._proof_1_8
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.preserve_filled
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.preserve_filled._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.preserve_filled._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.scalar_outside
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.scalar_outside._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.scalar_outside._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.source_transfer
#print axioms ExactFourierCircuits.UniformGlobalRolePackingMachine.source_transfer._proof_1_1
