import UniformRecursivePaddingFragments
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformRecursivePaddingFragments.finish_bits_generic
#print axioms ExactFourierCircuits.UniformRecursivePaddingFragments.finish_bits_generic._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursivePaddingFragments.finish_bits_generic._simp_1_2
#print axioms ExactFourierCircuits.UniformRecursivePaddingFragments.finish_bits_generic._simp_1_3
#print axioms ExactFourierCircuits.UniformRecursivePaddingFragments.init_bits_generic
#print axioms ExactFourierCircuits.UniformRecursivePaddingFragments.init_bits_generic._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursivePaddingFragments.init_bits_generic._simp_1_2
#print axioms ExactFourierCircuits.UniformRecursivePaddingFragments.init_bits_generic._simp_1_3
#print axioms ExactFourierCircuits.UniformRecursivePaddingFragments.next_bits_generic
#print axioms ExactFourierCircuits.UniformRecursivePaddingFragments.next_bits_generic._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursivePaddingFragments.next_bits_generic._simp_1_2
#print axioms ExactFourierCircuits.UniformRecursivePaddingFragments.next_bits_generic._simp_1_3
#print axioms ExactFourierCircuits.UniformRecursivePaddingFragments.residual_init_cursor_generic
#print axioms ExactFourierCircuits.UniformRecursivePaddingFragments.residual_init_cursor_generic._simp_1_1
#print axioms ExactFourierCircuits.UniformRecursivePaddingFragments.residual_init_cursor_generic._simp_1_2
#print axioms ExactFourierCircuits.UniformRecursivePaddingFragments.test_bits_generic
#print axioms ExactFourierCircuits.UniformRecursivePaddingFragments.test_bits_generic._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursivePaddingFragments.test_bits_generic._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursivePaddingFragments.test_bits_generic._simp_1_3
#print axioms ExactFourierCircuits.UniformRecursivePaddingFragments.test_bits_generic._simp_1_4
