import UniformForwardMatchingFactorGeometry
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformChunkMatchingPreparation.crossWord.congr_simp
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.coefficient
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.coefficient_address
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.coefficient_value
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.endpoints
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.rows
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.rows._proof_1
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.rows.eq_1
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.rows_geometry
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.rows_geometry._proof_1_1
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.rows_geometry._proof_1_2
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.rows_length
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.selectedEdge
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.selectedEdge._proof_1
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.selectedIndex
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.selectedIndex._proof_1
