import UniformLocalReplayStoredSlots
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformLocalReplayStoredSlots.chronology_count
#print axioms ExactFourierCircuits.UniformLocalReplayStoredSlots.generated_slot
#print axioms ExactFourierCircuits.UniformLocalReplayStoredSlots.generated_slot._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalReplayStoredSlots.generated_slot._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalReplayStoredSlots.generated_slot._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalReplayStoredSlots.phase_cover
#print axioms ExactFourierCircuits.UniformLocalReplayStoredSlots.phase_cover._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalReplayStoredSlots.phase_cover._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalReplayStoredSlots.phase_cover._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalReplayStoredSlots.phase_cover._proof_1_4
#print axioms ExactFourierCircuits.UniformLocalReplayStoredSlots.phase_cover._proof_1_5
#print axioms ExactFourierCircuits.UniformLocalReplayStoredSlots.phase_cover._proof_1_6
#print axioms ExactFourierCircuits.UniformLocalReplayStoredSlots.phase_slot
#print axioms ExactFourierCircuits.UniformLocalReplayStoredSlots.phase_slot._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalReplayStoredSlots.phase_slot._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalReplayStoredSlots.phase_slot._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalReplayStoredSlots.phase_slot._proof_1_4
#print axioms ExactFourierCircuits.UniformLocalReplayStoredSlots.slot_count
