import UniformFinalAxisCacheRectangle
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.Data.produced.eq_1
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.data.congr_simp
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.wholeFamily.congr_simp
#print axioms ExactFourierCircuits.UniformActualCalendarRegistry.Produced.cast.eq_1
#print axioms ExactFourierCircuits.UniformActualCalendarRegistry.Produced.mk.congr_simp
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRectangle.bounds
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRectangle.bounds._proof_1_1
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRectangle.bounds._proof_1_2
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRectangle.bounds._proof_1_3
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRectangle.bounds._proof_1_4
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRectangle.bounds._proof_1_5
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRectangle.entries_index
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRectangle.entries_index._proof_1_1
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRectangle.entries_index._proof_1_2
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRectangle.family
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRectangle.family._proof_1
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRectangle.family._proof_10
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRectangle.family._proof_11
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRectangle.family._proof_12
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRectangle.family._proof_2
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRectangle.family._proof_3
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRectangle.family._proof_4
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRectangle.family._proof_5
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRectangle.family._proof_6
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRectangle.family._proof_7
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRectangle.family._proof_8
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRectangle.family._proof_9
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRectangle.family.eq_1
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRectangle.family_make
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRectangle.whole
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRectangle.whole.congr_simp
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRectangle.whole_make
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRectangle.whole_make_eq
