import UniformGlobalClockAdvanceExecution
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformGlobalClockAdvanceExecution.axis_branch
#print axioms ExactFourierCircuits.UniformGlobalClockAdvanceExecution.axis_execution
#print axioms ExactFourierCircuits.UniformGlobalClockAdvanceExecution.axis_execution._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalClockAdvanceExecution.axis_execution._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalClockAdvanceExecution.axis_kept
#print axioms ExactFourierCircuits.UniformGlobalClockAdvanceExecution.clock_branch
#print axioms ExactFourierCircuits.UniformGlobalClockAdvanceExecution.clock_branch._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalClockAdvanceExecution.control_space
#print axioms ExactFourierCircuits.UniformGlobalClockAdvanceExecution.control_space._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalClockAdvanceExecution.halt_execution
#print axioms ExactFourierCircuits.UniformGlobalClockAdvanceExecution.tick_execution
#print axioms ExactFourierCircuits.UniformGlobalClockAdvanceExecution.tick_execution._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalClockAdvanceExecution.tick_execution._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalClockAdvanceExecution.tick_kept
