import UniformNativeHandlerSemantics
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformNativeHandlerSemantics.SemanticPresent
#print axioms ExactFourierCircuits.UniformNativeHandlerSemantics.actualDirections
#print axioms ExactFourierCircuits.UniformNativeHandlerSemantics.actualPairs
#print axioms ExactFourierCircuits.UniformNativeHandlerSemantics.arrayValues
#print axioms ExactFourierCircuits.UniformNativeHandlerSemantics.boundary_present
#print axioms ExactFourierCircuits.UniformNativeHandlerSemantics.boundary_values
#print axioms ExactFourierCircuits.UniformNativeHandlerSemantics.exchange_present
#print axioms ExactFourierCircuits.UniformNativeHandlerSemantics.exchange_record
#print axioms ExactFourierCircuits.UniformNativeHandlerSemantics.exchange_values
#print axioms ExactFourierCircuits.UniformNativeHandlerSemantics.initial_present
#print axioms ExactFourierCircuits.UniformNativeHandlerSemantics.initial_values
#print axioms ExactFourierCircuits.UniformNativeHandlerSemantics.roleMap
#print axioms ExactFourierCircuits.UniformNativeHandlerSemantics.scalar_present
#print axioms ExactFourierCircuits.UniformNativeHandlerSemantics.scalar_record
#print axioms ExactFourierCircuits.UniformNativeHandlerSemantics.scalar_values
#print axioms ExactFourierCircuits.UniformNativeHandlerSemantics.translation_present
#print axioms ExactFourierCircuits.UniformNativeHandlerSemantics.translation_record
#print axioms ExactFourierCircuits.UniformNativeHandlerSemantics.translation_values
#print axioms ExactFourierCircuits.UniformNativeScheduleSemantics.semantic.eq_1
