import GateFrames
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.GateFrames.Data
#print axioms ExactFourierCircuits.GateFrames.Data.B
#print axioms ExactFourierCircuits.GateFrames.Data.B.eq_1
#print axioms ExactFourierCircuits.GateFrames.Data.B_perp_basis
#print axioms ExactFourierCircuits.GateFrames.Data.P
#print axioms ExactFourierCircuits.GateFrames.Data.P.eq_1
#print axioms ExactFourierCircuits.GateFrames.Data.P_basis
#print axioms ExactFourierCircuits.GateFrames.Data.P_perp_basis
#print axioms ExactFourierCircuits.GateFrames.Data._sizeOf_1
#print axioms ExactFourierCircuits.GateFrames.Data._sizeOf_inst
#print axioms ExactFourierCircuits.GateFrames.Data.after_space
#print axioms ExactFourierCircuits.GateFrames.Data.at
#print axioms ExactFourierCircuits.GateFrames.Data.at.eq_1
#print axioms ExactFourierCircuits.GateFrames.Data.at_basis
#print axioms ExactFourierCircuits.GateFrames.Data.at_transition
#print axioms ExactFourierCircuits.GateFrames.Data.casesOn
#print axioms ExactFourierCircuits.GateFrames.Data.ctorIdx
#print axioms ExactFourierCircuits.GateFrames.Data.edges
#print axioms ExactFourierCircuits.GateFrames.Data.edges._proof_1
#print axioms ExactFourierCircuits.GateFrames.Data.entry
#print axioms ExactFourierCircuits.GateFrames.Data.entry.eq_1
#print axioms ExactFourierCircuits.GateFrames.Data.entry.eq_2
#print axioms ExactFourierCircuits.GateFrames.Data.entry.eq_3
#print axioms ExactFourierCircuits.GateFrames.Data.entry.eq_4
#print axioms ExactFourierCircuits.GateFrames.Data.entry_auxiliary_zero
#print axioms ExactFourierCircuits.GateFrames.Data.entry_basis
#print axioms ExactFourierCircuits.GateFrames.Data.finalLabels
#print axioms ExactFourierCircuits.GateFrames.Data.finalLabels._proof_1
#print axioms ExactFourierCircuits.GateFrames.Data.finalLabels_space
#print axioms ExactFourierCircuits.GateFrames.Data.finalSpace
#print axioms ExactFourierCircuits.GateFrames.Data.finalSpace._proof_1
#print axioms ExactFourierCircuits.GateFrames.Data.finalSpace.eq_1
#print axioms ExactFourierCircuits.GateFrames.Data.finalSpace.eq_2
#print axioms ExactFourierCircuits.GateFrames.Data.finalSpace.eq_3
#print axioms ExactFourierCircuits.GateFrames.Data.finalSpace.eq_4
#print axioms ExactFourierCircuits.GateFrames.Data.finalSpace_basis
#print axioms ExactFourierCircuits.GateFrames.Data.final_auxiliary_top
#print axioms ExactFourierCircuits.GateFrames.Data.final_bank_spaces
#print axioms ExactFourierCircuits.GateFrames.Data.forward_compatible
#print axioms ExactFourierCircuits.GateFrames.Data.future
#print axioms ExactFourierCircuits.GateFrames.Data.future_complement
#print axioms ExactFourierCircuits.GateFrames.Data.future_norm
#print axioms ExactFourierCircuits.GateFrames.Data.labels
#print axioms ExactFourierCircuits.GateFrames.Data.labels._proof_1
#print axioms ExactFourierCircuits.GateFrames.Data.labels_space
#print axioms ExactFourierCircuits.GateFrames.Data.large
#print axioms ExactFourierCircuits.GateFrames.Data.localAt
#print axioms ExactFourierCircuits.GateFrames.Data.localAt._proof_1
#print axioms ExactFourierCircuits.GateFrames.Data.localAt._proof_2
#print axioms ExactFourierCircuits.GateFrames.Data.localAt.eq_1
#print axioms ExactFourierCircuits.GateFrames.Data.localAt_basis
#print axioms ExactFourierCircuits.GateFrames.Data.local_transition
#print axioms ExactFourierCircuits.GateFrames.Data.mk
#print axioms ExactFourierCircuits.GateFrames.Data.mk._flat_ctor
#print axioms ExactFourierCircuits.GateFrames.Data.mk.inj
#print axioms ExactFourierCircuits.GateFrames.Data.mk.injEq
#print axioms ExactFourierCircuits.GateFrames.Data.mk.noConfusion
#print axioms ExactFourierCircuits.GateFrames.Data.mk.sizeOf_spec
#print axioms ExactFourierCircuits.GateFrames.Data.noConfusion
#print axioms ExactFourierCircuits.GateFrames.Data.noConfusionType
#print axioms ExactFourierCircuits.GateFrames.Data.prefixVector
#print axioms ExactFourierCircuits.GateFrames.Data.prefix_complement
#print axioms ExactFourierCircuits.GateFrames.Data.prefix_norm
#print axioms ExactFourierCircuits.GateFrames.Data.rec
#print axioms ExactFourierCircuits.GateFrames.Data.recOn
#print axioms ExactFourierCircuits.GateFrames.Data.reverse_compatible
#print axioms ExactFourierCircuits.GateFrames.Data.side_first_basis
#print axioms ExactFourierCircuits.GateFrames.Data.sinkEdges
#print axioms ExactFourierCircuits.GateFrames.Data.sinkEdges._proof_1
#print axioms ExactFourierCircuits.GateFrames.Data.sink_transition
#print axioms ExactFourierCircuits.GateFrames.Data.split
#print axioms ExactFourierCircuits.GateFrames.HasONBasis
#print axioms ExactFourierCircuits.GateFrames.HasONBasis._proof_1
#print axioms ExactFourierCircuits.GateFrames.J_support
#print axioms ExactFourierCircuits.GateFrames.Role
#print axioms ExactFourierCircuits.GateFrames.Role._sizeOf_1
#print axioms ExactFourierCircuits.GateFrames.Role._sizeOf_inst
#print axioms ExactFourierCircuits.GateFrames.Role.casesOn
#print axioms ExactFourierCircuits.GateFrames.Role.center
#print axioms ExactFourierCircuits.GateFrames.Role.center.elim
#print axioms ExactFourierCircuits.GateFrames.Role.center.inj
#print axioms ExactFourierCircuits.GateFrames.Role.center.injEq
#print axioms ExactFourierCircuits.GateFrames.Role.center.noConfusion
#print axioms ExactFourierCircuits.GateFrames.Role.center.sizeOf_spec
#print axioms ExactFourierCircuits.GateFrames.Role.ctorElim
#print axioms ExactFourierCircuits.GateFrames.Role.ctorElimType
#print axioms ExactFourierCircuits.GateFrames.Role.ctorIdx
#print axioms ExactFourierCircuits.GateFrames.Role.noConfusion
#print axioms ExactFourierCircuits.GateFrames.Role.noConfusionType
#print axioms ExactFourierCircuits.GateFrames.Role.proxyType
#print axioms ExactFourierCircuits.GateFrames.Role.proxyTypeEquiv
#print axioms ExactFourierCircuits.GateFrames.Role.rec
#print axioms ExactFourierCircuits.GateFrames.Role.recOn
#print axioms ExactFourierCircuits.GateFrames.Role.side
#print axioms ExactFourierCircuits.GateFrames.Role.side.elim
#print axioms ExactFourierCircuits.GateFrames.Role.side.inj
#print axioms ExactFourierCircuits.GateFrames.Role.side.injEq
#print axioms ExactFourierCircuits.GateFrames.Role.side.noConfusion
#print axioms ExactFourierCircuits.GateFrames.Role.side.sizeOf_spec
#print axioms ExactFourierCircuits.GateFrames.Role.x
#print axioms ExactFourierCircuits.GateFrames.Role.x.elim
#print axioms ExactFourierCircuits.GateFrames.Role.x.inj
#print axioms ExactFourierCircuits.GateFrames.Role.x.injEq
#print axioms ExactFourierCircuits.GateFrames.Role.x.noConfusion
#print axioms ExactFourierCircuits.GateFrames.Role.x.sizeOf_spec
#print axioms ExactFourierCircuits.GateFrames.Role.y
#print axioms ExactFourierCircuits.GateFrames.Role.y.elim
#print axioms ExactFourierCircuits.GateFrames.Role.y.inj
#print axioms ExactFourierCircuits.GateFrames.Role.y.injEq
#print axioms ExactFourierCircuits.GateFrames.Role.y.noConfusion
#print axioms ExactFourierCircuits.GateFrames.Role.y.sizeOf_spec
#print axioms ExactFourierCircuits.GateFrames.Transition
#print axioms ExactFourierCircuits.GateFrames.V_support
#print axioms ExactFourierCircuits.GateFrames.decomposes_space
#print axioms ExactFourierCircuits.GateFrames.edge_orthogonal
#print axioms ExactFourierCircuits.GateFrames.gateLabel
#print axioms ExactFourierCircuits.GateFrames.gateLabel.eq_1
#print axioms ExactFourierCircuits.GateFrames.gateLabel_hasONBasis
#print axioms ExactFourierCircuits.GateFrames.hasONBasis_bot
#print axioms ExactFourierCircuits.GateFrames.hasONBasis_label0
#print axioms ExactFourierCircuits.GateFrames.hasONBasis_label1
#print axioms ExactFourierCircuits.GateFrames.hasONBasis_label2
#print axioms ExactFourierCircuits.GateFrames.hasONBasis_label5
#print axioms ExactFourierCircuits.GateFrames.hasONBasis_line
#print axioms ExactFourierCircuits.GateFrames.hasONBasis_nondegenerate
#print axioms ExactFourierCircuits.GateFrames.hasONBasis_of_basis
#print axioms ExactFourierCircuits.GateFrames.hasONBasis_pair_perp
#print axioms ExactFourierCircuits.GateFrames.hasONBasis_residual
#print axioms ExactFourierCircuits.GateFrames.hasONBasis_space
#print axioms ExactFourierCircuits.GateFrames.hasONBasis_sum
#print axioms ExactFourierCircuits.GateFrames.hasONBasis_tensor
#print axioms ExactFourierCircuits.GateFrames.hasONBasis_top
#print axioms ExactFourierCircuits.GateFrames.hasONBasis_tripleTensor_perp
#print axioms ExactFourierCircuits.GateFrames.hasONBasis_tripleTensor_perp._proof_1_1
#print axioms ExactFourierCircuits.GateFrames.hasONBasis_triple_perp
#print axioms ExactFourierCircuits.GateFrames.instDecidableEqRole
#print axioms ExactFourierCircuits.GateFrames.instDecidableEqRole.decEq
#print axioms ExactFourierCircuits.GateFrames.instDecidableEqRole.decEq._proof_1
#print axioms ExactFourierCircuits.GateFrames.instDecidableEqRole.decEq._proof_10
#print axioms ExactFourierCircuits.GateFrames.instDecidableEqRole.decEq._proof_11
#print axioms ExactFourierCircuits.GateFrames.instDecidableEqRole.decEq._proof_12
#print axioms ExactFourierCircuits.GateFrames.instDecidableEqRole.decEq._proof_13
#print axioms ExactFourierCircuits.GateFrames.instDecidableEqRole.decEq._proof_14
#print axioms ExactFourierCircuits.GateFrames.instDecidableEqRole.decEq._proof_15
#print axioms ExactFourierCircuits.GateFrames.instDecidableEqRole.decEq._proof_16
#print axioms ExactFourierCircuits.GateFrames.instDecidableEqRole.decEq._proof_17
#print axioms ExactFourierCircuits.GateFrames.instDecidableEqRole.decEq._proof_18
#print axioms ExactFourierCircuits.GateFrames.instDecidableEqRole.decEq._proof_19
#print axioms ExactFourierCircuits.GateFrames.instDecidableEqRole.decEq._proof_2
#print axioms ExactFourierCircuits.GateFrames.instDecidableEqRole.decEq._proof_20
#print axioms ExactFourierCircuits.GateFrames.instDecidableEqRole.decEq._proof_3
#print axioms ExactFourierCircuits.GateFrames.instDecidableEqRole.decEq._proof_4
#print axioms ExactFourierCircuits.GateFrames.instDecidableEqRole.decEq._proof_5
#print axioms ExactFourierCircuits.GateFrames.instDecidableEqRole.decEq._proof_6
#print axioms ExactFourierCircuits.GateFrames.instDecidableEqRole.decEq._proof_7
#print axioms ExactFourierCircuits.GateFrames.instDecidableEqRole.decEq._proof_8
#print axioms ExactFourierCircuits.GateFrames.instDecidableEqRole.decEq._proof_9
#print axioms ExactFourierCircuits.GateFrames.instDecidableEqRole.decEq.match_1
#print axioms ExactFourierCircuits.GateFrames.instFintypeRole
#print axioms ExactFourierCircuits.GateFrames.instFintypeRole.match_3
#print axioms ExactFourierCircuits.GateFrames.instFintypeRole.match_5
#print axioms ExactFourierCircuits.GateFrames.invocationCoordinates
#print axioms ExactFourierCircuits.GateFrames.invocationCoordinates._proof_1
#print axioms ExactFourierCircuits.GateFrames.invocationCoordinates._proof_2
#print axioms ExactFourierCircuits.GateFrames.joinCoordinates
#print axioms ExactFourierCircuits.GateFrames.labelOfBasis
#print axioms ExactFourierCircuits.GateFrames.labelOfBasis._proof_1
#print axioms ExactFourierCircuits.GateFrames.labelOfBasis._proof_2
#print axioms ExactFourierCircuits.GateFrames.labelOfBasis._proof_3
#print axioms ExactFourierCircuits.GateFrames.labelOfBasis_space
#print axioms ExactFourierCircuits.GateFrames.reverseRowCoefficient
#print axioms ExactFourierCircuits.GateFrames.reverseRowCoefficient.eq_1
#print axioms ExactFourierCircuits.GateFrames.reverseRowCoefficient.eq_2
#print axioms ExactFourierCircuits.GateFrames.reverseRowCoefficient.eq_3
#print axioms ExactFourierCircuits.GateFrames.reverseRowCoefficient.eq_4
#print axioms ExactFourierCircuits.GateFrames.reverseRowCoefficient.eq_5
#print axioms ExactFourierCircuits.GateFrames.reverseRowCoefficient.eq_6
#print axioms ExactFourierCircuits.GateFrames.reverseRowCoefficient.eq_7
#print axioms ExactFourierCircuits.GateFrames.reverseRowCoefficient.eq_8
#print axioms ExactFourierCircuits.GateFrames.reverseRowCoefficient.eq_9
#print axioms ExactFourierCircuits.GateFrames.reverseRowCoefficient.match_1
#print axioms ExactFourierCircuits.GateFrames.reverse_row_support_common_gateLabel
#print axioms ExactFourierCircuits.GateFrames.reverse_row_support_common_label
#print axioms ExactFourierCircuits.GateFrames.rowCoefficient
#print axioms ExactFourierCircuits.GateFrames.rowCoefficient._sparseCasesOn_1
#print axioms ExactFourierCircuits.GateFrames.rowCoefficient._sparseCasesOn_1.else_eq
#print axioms ExactFourierCircuits.GateFrames.rowCoefficient._sparseCasesOn_2
#print axioms ExactFourierCircuits.GateFrames.rowCoefficient._sparseCasesOn_2.else_eq
#print axioms ExactFourierCircuits.GateFrames.rowCoefficient._sparseCasesOn_3
#print axioms ExactFourierCircuits.GateFrames.rowCoefficient._sparseCasesOn_3.else_eq
#print axioms ExactFourierCircuits.GateFrames.rowCoefficient._sparseCasesOn_4
#print axioms ExactFourierCircuits.GateFrames.rowCoefficient._sparseCasesOn_4.else_eq
#print axioms ExactFourierCircuits.GateFrames.rowCoefficient.eq_1
#print axioms ExactFourierCircuits.GateFrames.rowCoefficient.eq_2
#print axioms ExactFourierCircuits.GateFrames.rowCoefficient.eq_3
#print axioms ExactFourierCircuits.GateFrames.rowCoefficient.eq_4
#print axioms ExactFourierCircuits.GateFrames.rowCoefficient.eq_5
#print axioms ExactFourierCircuits.GateFrames.rowCoefficient.eq_6
#print axioms ExactFourierCircuits.GateFrames.rowCoefficient.eq_7
#print axioms ExactFourierCircuits.GateFrames.rowCoefficient.eq_8
#print axioms ExactFourierCircuits.GateFrames.rowCoefficient.eq_9
#print axioms ExactFourierCircuits.GateFrames.rowCoefficient.match_1
#print axioms ExactFourierCircuits.GateFrames.rowLabel
#print axioms ExactFourierCircuits.GateFrames.rowLabel.eq_1
#print axioms ExactFourierCircuits.GateFrames.rowLabel.eq_2
#print axioms ExactFourierCircuits.GateFrames.rowLabel.eq_3
#print axioms ExactFourierCircuits.GateFrames.rowLabel.eq_4
#print axioms ExactFourierCircuits.GateFrames.rowLabel_hasONBasis
#print axioms ExactFourierCircuits.GateFrames.row_support_common_gateLabel
#print axioms ExactFourierCircuits.GateFrames.row_support_common_label
#print axioms ExactFourierCircuits.GateFrames.subspaceCoordinates
#print axioms ExactFourierCircuits.GateFrames.subspaceCoordinates._proof_1
#print axioms ExactFourierCircuits.GateFrames.subspaceCoordinates._proof_10
#print axioms ExactFourierCircuits.GateFrames.subspaceCoordinates._proof_11
#print axioms ExactFourierCircuits.GateFrames.subspaceCoordinates._proof_2
#print axioms ExactFourierCircuits.GateFrames.subspaceCoordinates._proof_3
#print axioms ExactFourierCircuits.GateFrames.subspaceCoordinates._proof_4
#print axioms ExactFourierCircuits.GateFrames.subspaceCoordinates._proof_5
#print axioms ExactFourierCircuits.GateFrames.subspaceCoordinates._proof_6
#print axioms ExactFourierCircuits.GateFrames.subspaceCoordinates._proof_7
#print axioms ExactFourierCircuits.GateFrames.subspaceCoordinates._proof_8
#print axioms ExactFourierCircuits.GateFrames.subspaceCoordinates._proof_9
#print axioms ExactFourierCircuits.GateFrames.t
#print axioms ExactFourierCircuits.GateFrames.t_norm
#print axioms ExactFourierCircuits.GateFrames.tensorData
#print axioms ExactFourierCircuits.GateFrames.tensorData._proof_1
#print axioms ExactFourierCircuits.GateFrames.tensorData._proof_2
#print axioms ExactFourierCircuits.GateFrames.transitionToEdge
#print axioms ExactFourierCircuits.GateFrames.transitionToEdge._proof_1
#print axioms ExactFourierCircuits.GateFrames.transitionToEdge._proof_10
#print axioms ExactFourierCircuits.GateFrames.transitionToEdge._proof_11
#print axioms ExactFourierCircuits.GateFrames.transitionToEdge._proof_12
#print axioms ExactFourierCircuits.GateFrames.transitionToEdge._proof_13
#print axioms ExactFourierCircuits.GateFrames.transitionToEdge._proof_14
#print axioms ExactFourierCircuits.GateFrames.transitionToEdge._proof_2
#print axioms ExactFourierCircuits.GateFrames.transitionToEdge._proof_3
#print axioms ExactFourierCircuits.GateFrames.transitionToEdge._proof_4
#print axioms ExactFourierCircuits.GateFrames.transitionToEdge._proof_5
#print axioms ExactFourierCircuits.GateFrames.transitionToEdge._proof_6
#print axioms ExactFourierCircuits.GateFrames.transitionToEdge._proof_7
#print axioms ExactFourierCircuits.GateFrames.transitionToEdge._proof_8
#print axioms ExactFourierCircuits.GateFrames.transitionToEdge._proof_9
#print axioms ExactFourierCircuits.GateFrames.transition_increasing
#print axioms ExactFourierCircuits.GateFrames.transition_refl
#print axioms ExactFourierCircuits.GateFrames.transition_space
#print axioms ExactFourierCircuits.GateFrames.transition_symm
#print axioms ExactFourierCircuits.GateFrames.transition_tensor_left
#print axioms ExactFourierCircuits.GateFrames.transition_tensor_line
#print axioms ExactFourierCircuits.StageFrames.space.eq_1

open Lean Elab Command in
run_cmd do
 let env ← getEnv
 for (name, _) in env.constants.toList do
  if "_private.GateFrames.".isPrefixOf name.toString then
   let axs ← collectAxioms name
   logInfo m!"{name} depends on axioms: {axs.toList}"
