import UniformSixCCorrectedReplay
import Lean
set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformSixCContinuousReplay.broadcast_body
#print axioms ExactFourierCircuits.UniformSixCContinuousReplay.broadcast_body._proof_1_1
#print axioms ExactFourierCircuits.UniformSixCContinuousReplay.broadcast_body._proof_1_2
#print axioms ExactFourierCircuits.UniformSixCContinuousReplay.broadcast_header
#print axioms ExactFourierCircuits.UniformSixCContinuousReplay.broadcast_layout
#print axioms ExactFourierCircuits.UniformSixCContinuousReplay.broadcast_layout._proof_1_1
#print axioms ExactFourierCircuits.UniformSixCContinuousReplay.broadcast_layout._proof_1_2
#print axioms ExactFourierCircuits.UniformSixCContinuousReplay.broadcast_layout._proof_1_3
#print axioms ExactFourierCircuits.UniformSixCContinuousReplay.broadcast_layout._proof_1_4
#print axioms ExactFourierCircuits.UniformSixCContinuousReplay.half_execution
#print axioms ExactFourierCircuits.UniformSixCContinuousReplay.half_execution._proof_1_1
#print axioms ExactFourierCircuits.UniformSixCContinuousReplay.half_execution._proof_1_10
#print axioms ExactFourierCircuits.UniformSixCContinuousReplay.half_execution._proof_1_2
#print axioms ExactFourierCircuits.UniformSixCContinuousReplay.half_execution._proof_1_3
#print axioms ExactFourierCircuits.UniformSixCContinuousReplay.half_execution._proof_1_4
#print axioms ExactFourierCircuits.UniformSixCContinuousReplay.half_execution._proof_1_5
#print axioms ExactFourierCircuits.UniformSixCContinuousReplay.half_execution._proof_1_6
#print axioms ExactFourierCircuits.UniformSixCContinuousReplay.half_execution._proof_1_7
#print axioms ExactFourierCircuits.UniformSixCContinuousReplay.half_execution._proof_1_8
#print axioms ExactFourierCircuits.UniformSixCContinuousReplay.half_execution._proof_1_9
#print axioms ExactFourierCircuits.UniformSixCContinuousReplay.numeric_values
#print axioms ExactFourierCircuits.UniformSixCContinuousReplay.numeric_values._proof_1_1
#print axioms ExactFourierCircuits.UniformSixCContinuousReplay.phaseCost
