import UniformGlobalTensorDiagonalLoop
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.Banks.transfer
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.Banks.transfer._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.Filled
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.Filled.eq_1
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.Filled.step
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.Filled.step._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.Filled.step._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.RoleOutput.eq_1
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.Source.transfer
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.Source.transfer._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.boot.eq_1
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.boot_cursor
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.boot_frame
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.boot_frame._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.boot_frame._proof_1_3
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.boot_frame._proof_1_4
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.diagonal_values
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.execution
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.instruction_bound_radices_two
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.loop
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.loop._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.loop._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.loop._proof_1_5
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.loop._proof_1_6
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.loop._proof_1_7
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.loop._proof_1_8
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalMachine.tensorPermutation_identity
