import UniformFinalPhysicalTableGeometry
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformFinalPhysicalTableGeometry.Fits
#print axioms ExactFourierCircuits.UniformFinalPhysicalTableGeometry.Fits.alpha
#print axioms ExactFourierCircuits.UniformFinalPhysicalTableGeometry.Fits.alphaEnd
#print axioms ExactFourierCircuits.UniformFinalPhysicalTableGeometry.Fits.beta
#print axioms ExactFourierCircuits.UniformFinalPhysicalTableGeometry.Fits.casesOn
#print axioms ExactFourierCircuits.UniformFinalPhysicalTableGeometry.Fits.code
#print axioms ExactFourierCircuits.UniformFinalPhysicalTableGeometry.Fits.directory
#print axioms ExactFourierCircuits.UniformFinalPhysicalTableGeometry.Fits.inverseEnd
#print axioms ExactFourierCircuits.UniformFinalPhysicalTableGeometry.Fits.mk
#print axioms ExactFourierCircuits.UniformFinalPhysicalTableGeometry.Fits.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformFinalPhysicalTableGeometry.Fits.rec
#print axioms ExactFourierCircuits.UniformFinalPhysicalTableGeometry.Fits.recOn
#print axioms ExactFourierCircuits.UniformFinalPhysicalTableGeometry.Fits.volume
#print axioms ExactFourierCircuits.UniformFinalPhysicalTableGeometry.Fits.work
#print axioms ExactFourierCircuits.UniformFinalPhysicalTableGeometry.addresses
#print axioms ExactFourierCircuits.UniformFinalPhysicalTableGeometry.cache_before
#print axioms ExactFourierCircuits.UniformFinalPhysicalTableGeometry.fits
#print axioms ExactFourierCircuits.UniformFinalPhysicalTableGeometry.fits._proof_1_1
#print axioms ExactFourierCircuits.UniformFinalPhysicalTableGeometry.fits._proof_1_2
#print axioms ExactFourierCircuits.UniformFinalPhysicalTableGeometry.fits._proof_1_3
#print axioms ExactFourierCircuits.UniformFinalPhysicalTableGeometry.fits._proof_1_4
#print axioms ExactFourierCircuits.UniformFinalPhysicalTableGeometry.merged_before
#print axioms ExactFourierCircuits.UniformFinalPhysicalTableGeometry.nat_below
#print axioms ExactFourierCircuits.UniformFinalPhysicalTableGeometry.nat_below._proof_1_1
#print axioms ExactFourierCircuits.UniformFinalPhysicalTableGeometry.sources_before_directory
#print axioms ExactFourierCircuits.UniformFinalPhysicalTableGeometry.sources_before_directory._proof_1_1
