import UniformAxisCacheTransition
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformAxisCacheTransition.execution
#print axioms ExactFourierCircuits.UniformAxisCacheTransition.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformAxisCacheTransition.execution._simp_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheTransition.execution._simp_1_2
#print axioms ExactFourierCircuits.UniformAxisCacheTransition.result_withPC
