import UniformAxisCacheCanonicalRequests
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformAxisCacheCanonicalRequests.cache_room
#print axioms ExactFourierCircuits.UniformAxisCacheCanonicalRequests.cache_room._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheCanonicalRequests.cache_room._proof_1_2
#print axioms ExactFourierCircuits.UniformAxisCacheCanonicalRequests.canonical
#print axioms ExactFourierCircuits.UniformAxisCacheCanonicalRequests.canonical_length
#print axioms ExactFourierCircuits.UniformAxisCacheCanonicalRequests.capacity
#print axioms ExactFourierCircuits.UniformAxisCacheCanonicalRequests.geometry
#print axioms ExactFourierCircuits.UniformAxisCacheCanonicalRequests.geometry._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheCanonicalRequests.geometry._proof_1_2
#print axioms ExactFourierCircuits.UniformAxisCacheCanonicalRequests.length_bound
#print axioms ExactFourierCircuits.UniformAxisCacheCanonicalRequests.ordinary_intervals
#print axioms ExactFourierCircuits.UniformAxisCacheCanonicalRequests.ordinary_intervals._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheCanonicalRequests.ordinary_intervals._proof_1_2
#print axioms ExactFourierCircuits.UniformAxisCacheCanonicalRequests.ordinary_intervals._proof_1_3
#print axioms ExactFourierCircuits.UniformAxisCacheCanonicalRequests.source
#print axioms ExactFourierCircuits.UniformAxisCacheCanonicalRequests.time_room
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.Geometry.congr_simp
