import UniformFourierAxisOperationalCases
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Branch
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Branch.boundary
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Branch.casesOn
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Branch.inactive
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Branch.rec
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Branch.recOn
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Branch.tree
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Inputs
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Inputs.bound
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Inputs.casesOn
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Inputs.directory
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Inputs.duration
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Inputs.epoch
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Inputs.fit
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Inputs.head
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Inputs.input
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Inputs.later
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Inputs.layout
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Inputs.mk
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Inputs.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Inputs.natFrontier
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Inputs.nodeValues
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Inputs.pc
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Inputs.physical
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Inputs.pool
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Inputs.rec
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Inputs.recOn
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Inputs.rectangleValues
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Inputs.scalarFrontier
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.Inputs.source
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.TreeAt
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.budget
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.execution
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformFourierAxisOperationalCases.execution._proof_1_5
