import UniformActualCompleteClockTick
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformActualCompleteClockTick.axis_cost
#print axioms ExactFourierCircuits.UniformActualCompleteClockTick.execution
#print axioms ExactFourierCircuits.UniformActualCompleteClockTick.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformActualCompleteClockTick.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformActualCompleteClockTick.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformActualCompleteClockTick.execution._proof_1_4
