import UniformAxisCacheTail
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformAxisCacheLoopTail.program.eq_1
#print axioms ExactFourierCircuits.UniformAxisCacheTail.execution
#print axioms ExactFourierCircuits.UniformAxisCacheTail.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheTail.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformAxisCacheTail.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformAxisCacheTail.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformAxisCacheTail.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformAxisCacheTail.execution._proof_1_7
