import UniformFourierAxisCanonicalEvents
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformFourierAxisCanonicalEvents.boundary
#print axioms ExactFourierCircuits.UniformFourierAxisCanonicalEvents.boundaryLane
#print axioms ExactFourierCircuits.UniformFourierAxisCanonicalEvents.boundaryLane._proof_1
#print axioms ExactFourierCircuits.UniformFourierAxisCanonicalEvents.boundaryLane.eq_1
#print axioms ExactFourierCircuits.UniformFourierAxisCanonicalEvents.boundary_not_tree
#print axioms ExactFourierCircuits.UniformFourierAxisCanonicalEvents.boundary_not_tree._proof_1_1
#print axioms ExactFourierCircuits.UniformFourierAxisCanonicalEvents.eventsAt
#print axioms ExactFourierCircuits.UniformFourierAxisCanonicalEvents.eventsAt.eq_1
#print axioms ExactFourierCircuits.UniformFourierAxisCanonicalEvents.eventsAt_boundary
#print axioms ExactFourierCircuits.UniformFourierAxisCanonicalEvents.eventsAt_inactive
#print axioms ExactFourierCircuits.UniformFourierAxisCanonicalEvents.eventsAt_inactive._proof_1_1
#print axioms ExactFourierCircuits.UniformFourierAxisCanonicalEvents.eventsAt_inactive._proof_1_2
#print axioms ExactFourierCircuits.UniformFourierAxisCanonicalEvents.eventsAt_tree
#print axioms ExactFourierCircuits.UniformFourierAxisCanonicalEvents.family_boundary
#print axioms ExactFourierCircuits.UniformFourierAxisCanonicalEvents.family_boundary._proof_1_1
#print axioms ExactFourierCircuits.UniformFourierAxisCanonicalEvents.family_lane
#print axioms ExactFourierCircuits.UniformFourierAxisCanonicalEvents.family_lane._proof_1_2
#print axioms ExactFourierCircuits.UniformFourierAxisCanonicalEvents.family_lane._proof_1_3
#print axioms ExactFourierCircuits.UniformFourierAxisCanonicalEvents.family_lane._proof_1_4
#print axioms ExactFourierCircuits.UniformFourierAxisCanonicalEvents.inactive
#print axioms ExactFourierCircuits.UniformFourierAxisCanonicalEvents.instDecidableBoundaryAt_uniformFourierAxisCanonicalEvents
#print axioms ExactFourierCircuits.UniformFourierAxisCanonicalEvents.instDecidableTreeAt_uniformFourierAxisCanonicalEvents
