import UniformPreparedFFTMachine

#check ExactFourierCircuits.UniformPreparedFFTMachine.selected_execution
#check ExactFourierCircuits.UniformPreparedFFTMachine.execution
#check ExactFourierCircuits.UniformPreparedFFTMachine.prepared_execution

#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.row_execution_context
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.rootSetup
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.powerSetup
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.fftSetup
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.program
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.rootSetup_length
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.powerSetup_length
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.fftSetup_length
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.program_length
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.segment_code
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.row_code
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.root_code
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.power_code
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.fft_code
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.rootSetup_at
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.powerSetup_at
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.fftSetup_at
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.halt_at
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.powerBase
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.rootAddress
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.runtime
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.reset_placed
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.Entry
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.Sizes
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.rootSetup_spec
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.rootSetup_readable
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.rootSetup_peak
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.Sizes.withPC
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.sizes_root
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.powerSetup_spec
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.powerSetup_readable
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.powerSetup_peak
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.sizes_power
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.fftSetup_spec
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.fftSetup_readable
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.fftSetup_peak
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.Persistent
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.SetupFrame
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.setup_frame
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.row_persistent
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.root_persistent
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.power_persistent
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.fft_persistent
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.fft_contextFree
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.execution
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.wordBudget
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.wordBudget_bounds
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.wordBudget_power
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.runtime_log_bound
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.selected_execution
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.permutation_transport
#print axioms ExactFourierCircuits.UniformPreparedFFTMachine.prepared_execution
