import UniformLocalCacheSlotIteration
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.Cached.congr_simp
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.Inputs.congr_simp
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.Stored.congr_simp
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.iteration
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.iteration._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.iteration._proof_1_10
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.iteration._proof_1_15
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.iteration._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.iteration._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.iteration._proof_1_4
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.iteration._proof_1_5
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.iteration._proof_1_6
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.iteration._proof_1_7
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.iteration._proof_1_8
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.iteration._proof_1_9
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.runtimeBudget.congr_simp
