import UniformLocalCacheContextConductor
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.Banks
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.Banks.casesOn
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.Banks.constants
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.Banks.disabled
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.Banks.enabled
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.Banks.generated
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.Banks.inputs
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.Banks.mk
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.Banks.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.Banks.rec
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.Banks.recOn
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.Banks.rectangle
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.Banks.sources
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.C.program
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.L.program
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.context_code
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.execution
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.execution._proof_1_7
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.execution._proof_1_8
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.halt_at
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.halt_at._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.loop_code
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.program
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.program.eq_1
#print axioms ExactFourierCircuits.UniformLocalCacheContextConductor.program_length
