import UniformCalendarExplicitPreparedRender
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformCalendarExplicitPreparedRender.AxisSources
#print axioms ExactFourierCircuits.UniformCalendarExplicitPreparedRender.AxisSources._proof_1
#print axioms ExactFourierCircuits.UniformCalendarExplicitPreparedRender.AxisSources._proof_2
#print axioms ExactFourierCircuits.UniformCalendarExplicitPreparedRender.Sources
#print axioms ExactFourierCircuits.UniformCalendarExplicitPreparedRender.axis_matrix
#print axioms ExactFourierCircuits.UniformCalendarExplicitPreparedRender.forward_matrix
#print axioms ExactFourierCircuits.UniformCalendarExplicitPreparedRender.generatedFamily
#print axioms ExactFourierCircuits.UniformCalendarExplicitPreparedRender.generated_agreement
#print axioms ExactFourierCircuits.UniformCalendarExplicitPreparedRender.generated_matrix
#print axioms ExactFourierCircuits.UniformCalendarExplicitPreparedRender.reflected_matrix
#print axioms ExactFourierCircuits.UniformCalendarExplicitPreparedRender.render_matrix
#print axioms ExactFourierCircuits.UniformCalendarExplicitPreparedRender.tensor_render_matrix
