import UniformCalendarRenderSnapshot
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformCalendarRenderSnapshot.Family
#print axioms ExactFourierCircuits.UniformCalendarRenderSnapshot.renderFamily
#print axioms ExactFourierCircuits.UniformCalendarRenderSnapshot.rootEmbedding
#print axioms ExactFourierCircuits.UniformCalendarRenderSnapshot.rootEmbedding._proof_1
#print axioms ExactFourierCircuits.UniformCalendarRenderSnapshot.rootEmbedding._proof_2
#print axioms ExactFourierCircuits.UniformCalendarRenderSnapshot.rootEmbedding._proof_3
#print axioms ExactFourierCircuits.UniformCalendarRenderSnapshot.rootEmbedding._proof_4
#print axioms ExactFourierCircuits.UniformCalendarRenderSnapshot.rootEmbedding.congr_simp
#print axioms ExactFourierCircuits.UniformCalendarRenderSnapshot.transportFamily
#print axioms ExactFourierCircuits.UniformCalendarRenderSnapshot.transportFamily._proof_1
#print axioms ExactFourierCircuits.UniformCalendarRenderSnapshot.transported_union
#print axioms ExactFourierCircuits.UniformCalendarRenderSnapshot.transported_union_matrix
#print axioms ExactFourierCircuits.UniformCalendarRenderSnapshot.treeSnapshot_render
#print axioms ExactFourierCircuits.UniformCalendarRenderSnapshot.treeSnapshot_renderFamily
