import UniformFourierAxisGeometry
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.Geometry
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.Geometry.axisRowFit
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.Geometry.boundaryFit
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.Geometry.boundaryMerged
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.Geometry.boundaryPoolFit
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.Geometry.casesOn
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.Geometry.code
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.Geometry.directoryPermutation
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.Geometry.markersRow
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.Geometry.mergedPoolFit
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.Geometry.mk
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.Geometry.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.Geometry.natEndFit
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.Geometry.permutationWidths
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.Geometry.phaseRows
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.Geometry.radix
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.Geometry.rec
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.Geometry.recOn
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.Geometry.rowsPermutation
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.Geometry.selectedBoundary
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.Geometry.selectedPhase
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.Geometry.sourceBelow
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.Geometry.sourceFit
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.Geometry.widthsMarkers
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.axis_directory_before
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.axis_directory_before._proof_1_1
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.axis_row_fit
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.axis_row_fit._proof_1_1
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.geometry
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.geometry._proof_1_1
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.geometry._proof_1_10
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.geometry._proof_1_11
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.geometry._proof_1_2
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.geometry._proof_1_3
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.geometry._proof_1_4
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.geometry._proof_1_5
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.geometry._proof_1_6
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.geometry._proof_1_7
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.geometry._proof_1_8
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.geometry._proof_1_9
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.seed_source_fit
#print axioms ExactFourierCircuits.UniformFourierAxisGeometry.seed_source_fit._proof_1_1
