import UniformInitialCoreConjugateFrame
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformInitialCoreConjugateFrame.execution_header
#print axioms ExactFourierCircuits.UniformInitialCoreConjugateFrame.execution_header._proof_1_1
#print axioms ExactFourierCircuits.UniformInitialCoreConjugateFrame.execution_header._proof_1_10
#print axioms ExactFourierCircuits.UniformInitialCoreConjugateFrame.execution_header._proof_1_11
#print axioms ExactFourierCircuits.UniformInitialCoreConjugateFrame.execution_header._proof_1_2
#print axioms ExactFourierCircuits.UniformInitialCoreConjugateFrame.execution_header._proof_1_3
#print axioms ExactFourierCircuits.UniformInitialCoreConjugateFrame.execution_header._proof_1_4
#print axioms ExactFourierCircuits.UniformInitialCoreConjugateFrame.execution_header._proof_1_5
#print axioms ExactFourierCircuits.UniformInitialCoreConjugateFrame.execution_header._proof_1_6
#print axioms ExactFourierCircuits.UniformInitialCoreConjugateFrame.execution_header._proof_1_7
#print axioms ExactFourierCircuits.UniformInitialCoreConjugateFrame.execution_header._proof_1_8
#print axioms ExactFourierCircuits.UniformInitialCoreConjugateFrame.execution_header._proof_1_9
#print axioms ExactFourierCircuits.UniformInitialCoreConjugateFrame.program_keeps
#print axioms ExactFourierCircuits.UniformInitialCoreConjugateFrame.program_keeps._proof_1_2
#print axioms ExactFourierCircuits.UniformInitialCoreConjugateFrame.program_keeps._proof_1_3
#print axioms ExactFourierCircuits.UniformInitialCoreConjugateFrame.program_keeps._proof_1_4
#print axioms ExactFourierCircuits.UniformInitialCoreConjugateFrame.program_keeps._proof_1_5
#print axioms ExactFourierCircuits.UniformInitialCoreConjugateFrame.program_keeps._proof_1_6
#print axioms ExactFourierCircuits.UniformInitialCoreConjugateFrame.program_keeps._proof_1_7
#print axioms ExactFourierCircuits.UniformInitialCoreConjugateFrame.program_keeps._proof_1_8
#print axioms ExactFourierCircuits.UniformInitialCoreConjugateFrame.seed_boot_keeps
#print axioms ExactFourierCircuits.UniformInitialCoreConjugateFrame.seed_boot_keeps._proof_1_2
#print axioms ExactFourierCircuits.UniformInitialCoreConjugateFrame.seed_keeps
#print axioms ExactFourierCircuits.UniformInitialCoreConjugateFrame.seed_keeps._proof_1_2

open Lean Elab Command in
run_cmd do
 let env ← getEnv
 for (name, _) in env.constants.toList do
  if "_private.UniformInitialCoreConjugateFrame.".isPrefixOf name.toString then
   let axs ← collectAxioms name
   logInfo m!"{name} depends on axioms: {axs.toList}"
