import UniformMachine
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformMachine.BoundedExecution
#print axioms ExactFourierCircuits.UniformMachine.BoundedExecution.below
#print axioms ExactFourierCircuits.UniformMachine.BoundedExecution.below.casesOn
#print axioms ExactFourierCircuits.UniformMachine.BoundedExecution.below.halt
#print axioms ExactFourierCircuits.UniformMachine.BoundedExecution.below.next
#print axioms ExactFourierCircuits.UniformMachine.BoundedExecution.below.rec
#print axioms ExactFourierCircuits.UniformMachine.BoundedExecution.brecOn
#print axioms ExactFourierCircuits.UniformMachine.BoundedExecution.casesOn
#print axioms ExactFourierCircuits.UniformMachine.BoundedExecution.executes
#print axioms ExactFourierCircuits.UniformMachine.BoundedExecution.final_bound
#print axioms ExactFourierCircuits.UniformMachine.BoundedExecution.halt
#print axioms ExactFourierCircuits.UniformMachine.BoundedExecution.next
#print axioms ExactFourierCircuits.UniformMachine.BoundedExecution.rec
#print axioms ExactFourierCircuits.UniformMachine.BoundedExecution.recOn
#print axioms ExactFourierCircuits.UniformMachine.ComputesDFT
#print axioms ExactFourierCircuits.UniformMachine.Executes
#print axioms ExactFourierCircuits.UniformMachine.Executes.below
#print axioms ExactFourierCircuits.UniformMachine.Executes.below.casesOn
#print axioms ExactFourierCircuits.UniformMachine.Executes.below.halt
#print axioms ExactFourierCircuits.UniformMachine.Executes.below.next
#print axioms ExactFourierCircuits.UniformMachine.Executes.below.rec
#print axioms ExactFourierCircuits.UniformMachine.Executes.brecOn
#print axioms ExactFourierCircuits.UniformMachine.Executes.casesOn
#print axioms ExactFourierCircuits.UniformMachine.Executes.deterministic
#print axioms ExactFourierCircuits.UniformMachine.Executes.halt
#print axioms ExactFourierCircuits.UniformMachine.Executes.next
#print axioms ExactFourierCircuits.UniformMachine.Executes.positive
#print axioms ExactFourierCircuits.UniformMachine.Executes.positive._proof_1_1
#print axioms ExactFourierCircuits.UniformMachine.Executes.positive._proof_1_2
#print axioms ExactFourierCircuits.UniformMachine.Executes.rec
#print axioms ExactFourierCircuits.UniformMachine.Executes.recOn
#print axioms ExactFourierCircuits.UniformMachine.FieldOp
#print axioms ExactFourierCircuits.UniformMachine.FieldOp._sizeOf_1
#print axioms ExactFourierCircuits.UniformMachine.FieldOp._sizeOf_inst
#print axioms ExactFourierCircuits.UniformMachine.FieldOp.add
#print axioms ExactFourierCircuits.UniformMachine.FieldOp.add.elim
#print axioms ExactFourierCircuits.UniformMachine.FieldOp.add.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.FieldOp.casesOn
#print axioms ExactFourierCircuits.UniformMachine.FieldOp.ctorElim
#print axioms ExactFourierCircuits.UniformMachine.FieldOp.ctorElimType
#print axioms ExactFourierCircuits.UniformMachine.FieldOp.ctorIdx
#print axioms ExactFourierCircuits.UniformMachine.FieldOp.div
#print axioms ExactFourierCircuits.UniformMachine.FieldOp.div.elim
#print axioms ExactFourierCircuits.UniformMachine.FieldOp.div.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.FieldOp.mul
#print axioms ExactFourierCircuits.UniformMachine.FieldOp.mul.elim
#print axioms ExactFourierCircuits.UniformMachine.FieldOp.mul.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.FieldOp.noConfusion
#print axioms ExactFourierCircuits.UniformMachine.FieldOp.noConfusionType
#print axioms ExactFourierCircuits.UniformMachine.FieldOp.ofNat
#print axioms ExactFourierCircuits.UniformMachine.FieldOp.ofNat_ctorIdx
#print axioms ExactFourierCircuits.UniformMachine.FieldOp.rec
#print axioms ExactFourierCircuits.UniformMachine.FieldOp.recOn
#print axioms ExactFourierCircuits.UniformMachine.FieldOp.sub
#print axioms ExactFourierCircuits.UniformMachine.FieldOp.sub.elim
#print axioms ExactFourierCircuits.UniformMachine.FieldOp.sub.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.Instruction
#print axioms ExactFourierCircuits.UniformMachine.Instruction._sizeOf_1
#print axioms ExactFourierCircuits.UniformMachine.Instruction._sizeOf_inst
#print axioms ExactFourierCircuits.UniformMachine.Instruction.branchLT
#print axioms ExactFourierCircuits.UniformMachine.Instruction.branchLT.elim
#print axioms ExactFourierCircuits.UniformMachine.Instruction.branchLT.inj
#print axioms ExactFourierCircuits.UniformMachine.Instruction.branchLT.injEq
#print axioms ExactFourierCircuits.UniformMachine.Instruction.branchLT.noConfusion
#print axioms ExactFourierCircuits.UniformMachine.Instruction.branchLT.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.Instruction.casesOn
#print axioms ExactFourierCircuits.UniformMachine.Instruction.ctorElim
#print axioms ExactFourierCircuits.UniformMachine.Instruction.ctorElimType
#print axioms ExactFourierCircuits.UniformMachine.Instruction.ctorIdx
#print axioms ExactFourierCircuits.UniformMachine.Instruction.fieldBinary
#print axioms ExactFourierCircuits.UniformMachine.Instruction.fieldBinary.elim
#print axioms ExactFourierCircuits.UniformMachine.Instruction.fieldBinary.inj
#print axioms ExactFourierCircuits.UniformMachine.Instruction.fieldBinary.injEq
#print axioms ExactFourierCircuits.UniformMachine.Instruction.fieldBinary.noConfusion
#print axioms ExactFourierCircuits.UniformMachine.Instruction.fieldBinary.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.Instruction.halt
#print axioms ExactFourierCircuits.UniformMachine.Instruction.halt.elim
#print axioms ExactFourierCircuits.UniformMachine.Instruction.halt.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.Instruction.input
#print axioms ExactFourierCircuits.UniformMachine.Instruction.input.elim
#print axioms ExactFourierCircuits.UniformMachine.Instruction.input.inj
#print axioms ExactFourierCircuits.UniformMachine.Instruction.input.injEq
#print axioms ExactFourierCircuits.UniformMachine.Instruction.input.noConfusion
#print axioms ExactFourierCircuits.UniformMachine.Instruction.input.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.Instruction.jump
#print axioms ExactFourierCircuits.UniformMachine.Instruction.jump.elim
#print axioms ExactFourierCircuits.UniformMachine.Instruction.jump.inj
#print axioms ExactFourierCircuits.UniformMachine.Instruction.jump.injEq
#print axioms ExactFourierCircuits.UniformMachine.Instruction.jump.noConfusion
#print axioms ExactFourierCircuits.UniformMachine.Instruction.jump.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.Instruction.length
#print axioms ExactFourierCircuits.UniformMachine.Instruction.length.elim
#print axioms ExactFourierCircuits.UniformMachine.Instruction.length.inj
#print axioms ExactFourierCircuits.UniformMachine.Instruction.length.injEq
#print axioms ExactFourierCircuits.UniformMachine.Instruction.length.noConfusion
#print axioms ExactFourierCircuits.UniformMachine.Instruction.length.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.Instruction.loadNat
#print axioms ExactFourierCircuits.UniformMachine.Instruction.loadNat.elim
#print axioms ExactFourierCircuits.UniformMachine.Instruction.loadNat.inj
#print axioms ExactFourierCircuits.UniformMachine.Instruction.loadNat.injEq
#print axioms ExactFourierCircuits.UniformMachine.Instruction.loadNat.noConfusion
#print axioms ExactFourierCircuits.UniformMachine.Instruction.loadNat.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.Instruction.loadScalar
#print axioms ExactFourierCircuits.UniformMachine.Instruction.loadScalar.elim
#print axioms ExactFourierCircuits.UniformMachine.Instruction.loadScalar.inj
#print axioms ExactFourierCircuits.UniformMachine.Instruction.loadScalar.injEq
#print axioms ExactFourierCircuits.UniformMachine.Instruction.loadScalar.noConfusion
#print axioms ExactFourierCircuits.UniformMachine.Instruction.loadScalar.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.Instruction.natBinary
#print axioms ExactFourierCircuits.UniformMachine.Instruction.natBinary.elim
#print axioms ExactFourierCircuits.UniformMachine.Instruction.natBinary.inj
#print axioms ExactFourierCircuits.UniformMachine.Instruction.natBinary.injEq
#print axioms ExactFourierCircuits.UniformMachine.Instruction.natBinary.noConfusion
#print axioms ExactFourierCircuits.UniformMachine.Instruction.natBinary.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.Instruction.natLiteral
#print axioms ExactFourierCircuits.UniformMachine.Instruction.natLiteral.elim
#print axioms ExactFourierCircuits.UniformMachine.Instruction.natLiteral.inj
#print axioms ExactFourierCircuits.UniformMachine.Instruction.natLiteral.injEq
#print axioms ExactFourierCircuits.UniformMachine.Instruction.natLiteral.noConfusion
#print axioms ExactFourierCircuits.UniformMachine.Instruction.natLiteral.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.Instruction.noConfusion
#print axioms ExactFourierCircuits.UniformMachine.Instruction.noConfusionType
#print axioms ExactFourierCircuits.UniformMachine.Instruction.output
#print axioms ExactFourierCircuits.UniformMachine.Instruction.output.elim
#print axioms ExactFourierCircuits.UniformMachine.Instruction.output.inj
#print axioms ExactFourierCircuits.UniformMachine.Instruction.output.injEq
#print axioms ExactFourierCircuits.UniformMachine.Instruction.output.noConfusion
#print axioms ExactFourierCircuits.UniformMachine.Instruction.output.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.Instruction.rec
#print axioms ExactFourierCircuits.UniformMachine.Instruction.recOn
#print axioms ExactFourierCircuits.UniformMachine.Instruction.root
#print axioms ExactFourierCircuits.UniformMachine.Instruction.root.elim
#print axioms ExactFourierCircuits.UniformMachine.Instruction.root.inj
#print axioms ExactFourierCircuits.UniformMachine.Instruction.root.injEq
#print axioms ExactFourierCircuits.UniformMachine.Instruction.root.noConfusion
#print axioms ExactFourierCircuits.UniformMachine.Instruction.root.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.Instruction.scalarLiteral
#print axioms ExactFourierCircuits.UniformMachine.Instruction.scalarLiteral.elim
#print axioms ExactFourierCircuits.UniformMachine.Instruction.scalarLiteral.inj
#print axioms ExactFourierCircuits.UniformMachine.Instruction.scalarLiteral.injEq
#print axioms ExactFourierCircuits.UniformMachine.Instruction.scalarLiteral.noConfusion
#print axioms ExactFourierCircuits.UniformMachine.Instruction.scalarLiteral.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.Instruction.storeNat
#print axioms ExactFourierCircuits.UniformMachine.Instruction.storeNat.elim
#print axioms ExactFourierCircuits.UniformMachine.Instruction.storeNat.inj
#print axioms ExactFourierCircuits.UniformMachine.Instruction.storeNat.injEq
#print axioms ExactFourierCircuits.UniformMachine.Instruction.storeNat.noConfusion
#print axioms ExactFourierCircuits.UniformMachine.Instruction.storeNat.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.Instruction.storeScalar
#print axioms ExactFourierCircuits.UniformMachine.Instruction.storeScalar.elim
#print axioms ExactFourierCircuits.UniformMachine.Instruction.storeScalar.inj
#print axioms ExactFourierCircuits.UniformMachine.Instruction.storeScalar.injEq
#print axioms ExactFourierCircuits.UniformMachine.Instruction.storeScalar.noConfusion
#print axioms ExactFourierCircuits.UniformMachine.Instruction.storeScalar.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.NatOp
#print axioms ExactFourierCircuits.UniformMachine.NatOp._sizeOf_1
#print axioms ExactFourierCircuits.UniformMachine.NatOp._sizeOf_inst
#print axioms ExactFourierCircuits.UniformMachine.NatOp.add
#print axioms ExactFourierCircuits.UniformMachine.NatOp.add.elim
#print axioms ExactFourierCircuits.UniformMachine.NatOp.add.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.NatOp.casesOn
#print axioms ExactFourierCircuits.UniformMachine.NatOp.ctorElim
#print axioms ExactFourierCircuits.UniformMachine.NatOp.ctorElimType
#print axioms ExactFourierCircuits.UniformMachine.NatOp.ctorIdx
#print axioms ExactFourierCircuits.UniformMachine.NatOp.div
#print axioms ExactFourierCircuits.UniformMachine.NatOp.div.elim
#print axioms ExactFourierCircuits.UniformMachine.NatOp.div.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.NatOp.mod
#print axioms ExactFourierCircuits.UniformMachine.NatOp.mod.elim
#print axioms ExactFourierCircuits.UniformMachine.NatOp.mod.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.NatOp.mul
#print axioms ExactFourierCircuits.UniformMachine.NatOp.mul.elim
#print axioms ExactFourierCircuits.UniformMachine.NatOp.mul.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.NatOp.noConfusion
#print axioms ExactFourierCircuits.UniformMachine.NatOp.noConfusionType
#print axioms ExactFourierCircuits.UniformMachine.NatOp.ofNat
#print axioms ExactFourierCircuits.UniformMachine.NatOp.ofNat_ctorIdx
#print axioms ExactFourierCircuits.UniformMachine.NatOp.rec
#print axioms ExactFourierCircuits.UniformMachine.NatOp.recOn
#print axioms ExactFourierCircuits.UniformMachine.NatOp.sub
#print axioms ExactFourierCircuits.UniformMachine.NatOp.sub.elim
#print axioms ExactFourierCircuits.UniformMachine.NatOp.sub.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.Program
#print axioms ExactFourierCircuits.UniformMachine.Scalar
#print axioms ExactFourierCircuits.UniformMachine.Scalar._sizeOf_1
#print axioms ExactFourierCircuits.UniformMachine.Scalar._sizeOf_inst
#print axioms ExactFourierCircuits.UniformMachine.Scalar.casesOn
#print axioms ExactFourierCircuits.UniformMachine.Scalar.ctorIdx
#print axioms ExactFourierCircuits.UniformMachine.Scalar.dependent
#print axioms ExactFourierCircuits.UniformMachine.Scalar.mk
#print axioms ExactFourierCircuits.UniformMachine.Scalar.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformMachine.Scalar.mk.inj
#print axioms ExactFourierCircuits.UniformMachine.Scalar.mk.injEq
#print axioms ExactFourierCircuits.UniformMachine.Scalar.mk.noConfusion
#print axioms ExactFourierCircuits.UniformMachine.Scalar.mk.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.Scalar.noConfusion
#print axioms ExactFourierCircuits.UniformMachine.Scalar.noConfusionType
#print axioms ExactFourierCircuits.UniformMachine.Scalar.rec
#print axioms ExactFourierCircuits.UniformMachine.Scalar.recOn
#print axioms ExactFourierCircuits.UniformMachine.Scalar.value
#print axioms ExactFourierCircuits.UniformMachine.Scalar.zero
#print axioms ExactFourierCircuits.UniformMachine.State
#print axioms ExactFourierCircuits.UniformMachine.State._sizeOf_1
#print axioms ExactFourierCircuits.UniformMachine.State._sizeOf_inst
#print axioms ExactFourierCircuits.UniformMachine.State.casesOn
#print axioms ExactFourierCircuits.UniformMachine.State.ctorIdx
#print axioms ExactFourierCircuits.UniformMachine.State.mk
#print axioms ExactFourierCircuits.UniformMachine.State.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformMachine.State.mk.inj
#print axioms ExactFourierCircuits.UniformMachine.State.mk.injEq
#print axioms ExactFourierCircuits.UniformMachine.State.mk.noConfusion
#print axioms ExactFourierCircuits.UniformMachine.State.mk.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.State.natHeap
#print axioms ExactFourierCircuits.UniformMachine.State.natReg
#print axioms ExactFourierCircuits.UniformMachine.State.noConfusion
#print axioms ExactFourierCircuits.UniformMachine.State.noConfusionType
#print axioms ExactFourierCircuits.UniformMachine.State.outputs
#print axioms ExactFourierCircuits.UniformMachine.State.pc
#print axioms ExactFourierCircuits.UniformMachine.State.rec
#print axioms ExactFourierCircuits.UniformMachine.State.recOn
#print axioms ExactFourierCircuits.UniformMachine.State.rootOrders
#print axioms ExactFourierCircuits.UniformMachine.State.scalarHeap
#print axioms ExactFourierCircuits.UniformMachine.State.scalarReg
#print axioms ExactFourierCircuits.UniformMachine.StepResult
#print axioms ExactFourierCircuits.UniformMachine.StepResult._sizeOf_1
#print axioms ExactFourierCircuits.UniformMachine.StepResult._sizeOf_inst
#print axioms ExactFourierCircuits.UniformMachine.StepResult.casesOn
#print axioms ExactFourierCircuits.UniformMachine.StepResult.ctorElim
#print axioms ExactFourierCircuits.UniformMachine.StepResult.ctorElimType
#print axioms ExactFourierCircuits.UniformMachine.StepResult.ctorIdx
#print axioms ExactFourierCircuits.UniformMachine.StepResult.failed
#print axioms ExactFourierCircuits.UniformMachine.StepResult.failed.elim
#print axioms ExactFourierCircuits.UniformMachine.StepResult.failed.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.StepResult.halted
#print axioms ExactFourierCircuits.UniformMachine.StepResult.halted.elim
#print axioms ExactFourierCircuits.UniformMachine.StepResult.halted.inj
#print axioms ExactFourierCircuits.UniformMachine.StepResult.halted.injEq
#print axioms ExactFourierCircuits.UniformMachine.StepResult.halted.noConfusion
#print axioms ExactFourierCircuits.UniformMachine.StepResult.halted.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.StepResult.noConfusion
#print axioms ExactFourierCircuits.UniformMachine.StepResult.noConfusionType
#print axioms ExactFourierCircuits.UniformMachine.StepResult.rec
#print axioms ExactFourierCircuits.UniformMachine.StepResult.recOn
#print axioms ExactFourierCircuits.UniformMachine.StepResult.running
#print axioms ExactFourierCircuits.UniformMachine.StepResult.running.elim
#print axioms ExactFourierCircuits.UniformMachine.StepResult.running.inj
#print axioms ExactFourierCircuits.UniformMachine.StepResult.running.injEq
#print axioms ExactFourierCircuits.UniformMachine.StepResult.running.noConfusion
#print axioms ExactFourierCircuits.UniformMachine.StepResult.running.sizeOf_spec
#print axioms ExactFourierCircuits.UniformMachine.UniformDFTStatement
#print axioms ExactFourierCircuits.UniformMachine.WordBound
#print axioms ExactFourierCircuits.UniformMachine.WordBound.eq_1
#print axioms ExactFourierCircuits.UniformMachine.asymptoticCost
#print axioms ExactFourierCircuits.UniformMachine.asymptoticCost._proof_1
#print axioms ExactFourierCircuits.UniformMachine.evalField
#print axioms ExactFourierCircuits.UniformMachine.evalField.eq_1
#print axioms ExactFourierCircuits.UniformMachine.evalField.eq_2
#print axioms ExactFourierCircuits.UniformMachine.evalField.eq_3
#print axioms ExactFourierCircuits.UniformMachine.evalField.eq_4
#print axioms ExactFourierCircuits.UniformMachine.evalField.match_1
#print axioms ExactFourierCircuits.UniformMachine.evalField_div_prepared
#print axioms ExactFourierCircuits.UniformMachine.evalField_mul_rejects_data
#print axioms ExactFourierCircuits.UniformMachine.evalNat
#print axioms ExactFourierCircuits.UniformMachine.evalNat.match_1
#print axioms ExactFourierCircuits.UniformMachine.initial
#print axioms ExactFourierCircuits.UniformMachine.initial.eq_1
#print axioms ExactFourierCircuits.UniformMachine.initial_wordBound
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqFieldOp
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqFieldOp._proof_1
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqFieldOp._proof_2
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_1
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_10
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_11
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_12
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_13
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_14
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_15
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_16
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_17
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_18
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_19
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_2
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_20
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_21
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_22
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_23
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_24
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_25
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_26
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_27
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_28
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_29
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_3
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_30
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_31
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_32
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_33
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_34
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_35
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_36
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_37
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_38
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_39
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_4
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_40
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_41
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_42
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_43
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_44
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_45
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_46
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_47
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_5
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_6
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_7
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_8
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq._proof_9
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqInstruction.decEq.match_1
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqNatOp
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqNatOp._proof_1
#print axioms ExactFourierCircuits.UniformMachine.instDecidableEqNatOp._proof_2
#print axioms ExactFourierCircuits.UniformMachine.instReprFieldOp
#print axioms ExactFourierCircuits.UniformMachine.instReprFieldOp.repr
#print axioms ExactFourierCircuits.UniformMachine.instReprFieldOp.repr.match_1
#print axioms ExactFourierCircuits.UniformMachine.instReprNatOp
#print axioms ExactFourierCircuits.UniformMachine.instReprNatOp.repr
#print axioms ExactFourierCircuits.UniformMachine.instReprNatOp.repr.match_1
#print axioms ExactFourierCircuits.UniformMachine.next
#print axioms ExactFourierCircuits.UniformMachine.step
#print axioms ExactFourierCircuits.UniformMachine.step.match_1
#print axioms ExactFourierCircuits.UniformMachine.step.match_3
#print axioms ExactFourierCircuits.UniformMachine.step.match_5
#print axioms ExactFourierCircuits.UniformMachine.writeNat
#print axioms ExactFourierCircuits.UniformMachine.writeScalar

open Lean Elab Command in
run_cmd do
 let env ← getEnv
 for (name, _) in env.constants.toList do
  if "_private.UniformMachine.".isPrefixOf name.toString || name.toString == "ExactFourierCircuits.UniformMachine.Instruction.match_on_same_ctor._@.UniformMachine.3759734430._hygCtx._hyg.162" || name.toString == "ExactFourierCircuits.UniformMachine.Instruction.match_on_same_ctor.het._@.UniformMachine.3759734430._hygCtx._hyg.162" then
   let axs ← collectAxioms name
   logInfo m!"{name} depends on axioms: {axs.toList}"
