import UniformRecursiveLocalAllowance
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.affine_reserve
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.affine_reserve._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.count_le_serialized
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.count_le_serialized._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.count_le_serialized._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.directionTicks
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.direction_bound
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.exchange_pairs_le_data
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.exchange_pairs_le_data._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.exchange_record_bound
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.exchange_record_bound._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.exchange_record_bound._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.marker_record_bound
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.marker_record_bound._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.marker_record_bound._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.node_bound
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.padding_record_bound
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.padding_record_bound._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.padding_record_bound._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.producer_bound
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.producer_bound._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.recordAllowance
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.residual_record_bound
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.residual_record_bound._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.residual_record_bound._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.scalar_record_bound
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.scalar_record_bound._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.scalar_record_bound._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.schedule_allowance
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.serialized_length
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.suffix_bound
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.suffix_bound._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.tapeAllowance
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.tapeAllowance.eq_1
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.tape_bound
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.tape_bound._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.tape_formula
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.translation_record_bound
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.translation_record_bound._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.translation_record_bound._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.translation_rows_le_data
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.translation_rows_le_data._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.translation_rows_le_data._proof_1_2
