import UniformNativeScheduleMatrix
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformNativeScheduleMatrix.copies_array
#print axioms ExactFourierCircuits.UniformNativeScheduleMatrix.nativeCoordinates
#print axioms ExactFourierCircuits.UniformNativeScheduleMatrix.nativeCoordinates.eq_1
#print axioms ExactFourierCircuits.UniformNativeScheduleMatrix.nativeMatrix
#print axioms ExactFourierCircuits.UniformNativeScheduleMatrix.nativeMatrix.eq_1
#print axioms ExactFourierCircuits.UniformNativeScheduleMatrix.nativeMatrix_mul
#print axioms ExactFourierCircuits.UniformNativeScheduleMatrix.nativeMatrix_one
#print axioms ExactFourierCircuits.UniformNativeScheduleMatrix.native_copies
#print axioms ExactFourierCircuits.UniformNativeScheduleMatrix.spectatorCoordinates
#print axioms ExactFourierCircuits.UniformNativeScheduleMatrix.spectatorCoordinates.eq_1
#print axioms ExactFourierCircuits.UniformNativeScheduleMatrix.spectatorCoordinates_at
#print axioms ExactFourierCircuits.UniformNativeScheduleMatrix.spectatorLift
#print axioms ExactFourierCircuits.UniformNativeScheduleMatrix.spectatorLift_array
#print axioms ExactFourierCircuits.UniformNativeScheduleMatrix.spectatorLift_mul
#print axioms ExactFourierCircuits.UniformNativeScheduleMatrix.spectatorLift_one
#print axioms ExactFourierCircuits.UniformNativeScheduleMatrix.spectator_copies_array
