import UniformJointConditionalKernelContext
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.PhysicalGeometry
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.PhysicalGeometry.casesOn
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.PhysicalGeometry.length
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.PhysicalGeometry.mk
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.PhysicalGeometry.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.PhysicalGeometry.permutations
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.PhysicalGeometry.rec
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.PhysicalGeometry.recOn
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.PhysicalGeometry.volume
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.PhysicalGeometry.widths
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.actualReserveContext
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.addresses
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_1
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_10
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_11
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_12
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_13
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_14
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_15
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_16
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_17
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_18
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_19
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_2
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_20
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_21
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_22
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_23
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_24
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_25
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_26
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_27
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_28
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_29
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_3
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_30
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_4
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_5
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_6
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_7
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_8
#print axioms ExactFourierCircuits.UniformJointConditionalKernelContext.context._proof_9
