import UniformRecursivePreparedCoreSchedule
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformRecursiveCoreSchedule.execution_prepared
#print axioms ExactFourierCircuits.UniformRecursiveCoreSchedule.execution_prepared._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveCoreSchedule.execution_prepared._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveCoreSchedule.execution_prepared._proof_1_3
#print axioms ExactFourierCircuits.UniformRecursiveCoreSchedule.execution_prepared._proof_1_4
#print axioms ExactFourierCircuits.UniformRecursiveCoreSchedule.execution_prepared._proof_1_5
