import UniformActualCalendarDirectSeedValue
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.invH_zero
#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.mu_invH_ofOperation
#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.mu_ofOperation
#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.mu_ofOperation._proof_1_1
#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.seedCoefficients
#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.seedCoefficients._proof_1
#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.seedCoefficients.eq_1
#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.seedCoefficients_invH
#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.seed_operation_source
#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.seed_operation_source._proof_1
