import UniformJointCacheWorkspaceMachine
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.W.original
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.W.stride
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.W.work
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.boot
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.boot.eq_1
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.boot_code
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.boot_length
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.boot_value
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.exact_banks
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.execution
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.factors
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.factors.eq_1
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.factors_length
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.factors_small
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.factors_small._proof_1_4
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.factors_small._simp_1_2
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.factors_small._simp_1_3
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.factors_value
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.halt_at
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headerOps
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headerOps._f
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headerOps._sunfold
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headerOps._unsafe_rec
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headerOps.eq_1
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headerOps.eq_2
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headerOps.eq_def
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headerOps.match_1
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.header_code
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headers_frame
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headers_length
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headers_length._proof_1_4
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headers_natReg
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headers_natReg._proof_1_4
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headers_natReg._proof_1_5
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headers_safe
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headers_safe._proof_1_4
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headers_safe._proof_1_5
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headers_safe._proof_1_6
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headers_safe._proof_1_7
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headers_safe._proof_1_8
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headers_slab
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headers_slab._proof_1_4
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headers_slab._proof_1_5
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headers_slab._proof_1_6
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headers_value
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headers_value._proof_1_4
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headers_value._proof_1_5
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headers_value._proof_1_6
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headers_value._proof_1_7
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headers_value._proof_1_8
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.headers_value._proof_1_9
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.program
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.program.eq_1
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.program_length
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.result
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.result.eq_1
#print axioms ExactFourierCircuits.UniformJointCacheWorkspaceMachine.result_frame

open Lean Elab Command in
run_cmd do
 let env ← getEnv
 for (name, _) in env.constants.toList do
  if "_private.UniformJointCacheWorkspaceMachine.".isPrefixOf name.toString then
   let axs ← collectAxioms name
   logInfo m!"{name} depends on axioms: {axs.toList}"
