import UniformAxisCacheForestRetention
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformAxisCacheForestRetention.contents_withPC
#print axioms ExactFourierCircuits.UniformAxisCacheForestRetention.earlier
#print axioms ExactFourierCircuits.UniformAxisCacheForestRetention.earlier._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheForestRetention.earlier._proof_1_2
#print axioms ExactFourierCircuits.UniformAxisCacheForestRetention.earlier._proof_1_3
#print axioms ExactFourierCircuits.UniformAxisCacheForestRetention.earlier._proof_1_4
#print axioms ExactFourierCircuits.UniformAxisCacheForestRetention.endpoints_withPC
#print axioms ExactFourierCircuits.UniformAxisCacheForestRetention.inputs
#print axioms ExactFourierCircuits.UniformAxisCacheForestRetention.inputs._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheForestRetention.inputs._proof_1_2
#print axioms ExactFourierCircuits.UniformAxisCacheForestRetention.inputs._proof_1_3
#print axioms ExactFourierCircuits.UniformAxisCacheForestRetention.low_nat
#print axioms ExactFourierCircuits.UniformAxisCacheForestRetention.low_nat._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheForestRetention.low_nat._proof_1_2
#print axioms ExactFourierCircuits.UniformAxisCacheForestRetention.low_nat._proof_1_3
#print axioms ExactFourierCircuits.UniformAxisCacheForestRetention.semantic_withPC
#print axioms ExactFourierCircuits.UniformAxisCacheForestRetention.semantic_withPC._proof_1
#print axioms ExactFourierCircuits.UniformAxisCacheForestRetention.semantic_withPC._proof_10
#print axioms ExactFourierCircuits.UniformAxisCacheForestRetention.semantic_withPC._proof_2
#print axioms ExactFourierCircuits.UniformAxisCacheForestRetention.semantic_withPC._proof_3
#print axioms ExactFourierCircuits.UniformAxisCacheForestRetention.semantic_withPC._proof_4
#print axioms ExactFourierCircuits.UniformAxisCacheForestRetention.semantic_withPC._proof_5
#print axioms ExactFourierCircuits.UniformAxisCacheForestRetention.semantic_withPC._proof_6
#print axioms ExactFourierCircuits.UniformAxisCacheForestRetention.semantic_withPC._proof_7
#print axioms ExactFourierCircuits.UniformAxisCacheForestRetention.semantic_withPC._proof_8
#print axioms ExactFourierCircuits.UniformAxisCacheForestRetention.semantic_withPC._proof_9
