import UniformCacheTimingHeap
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_belowU
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_belowU._proof_1_1
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_belowU._proof_1_2
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_correction
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_correction._proof_1_1
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_correction_other
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_correction_other._proof_1_1
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_correction_other._proof_1_2
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_correction_other._proof_1_3
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_correction_other._proof_1_4
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_correction_other._proof_1_5
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_correction_other._proof_1_6
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_duration
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_duration._proof_1_1
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_duration._proof_1_2
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_duration._proof_1_3
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_outside
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_outside._proof_1_1
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_outside._proof_1_2
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_outside._proof_1_3
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_outside._proof_1_4
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_outside._proof_1_5
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_prefix
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_prefix._proof_1_1
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_prefix._proof_1_2
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_prefix._proof_1_3
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_prefix._proof_1_4
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_prefix._proof_1_5
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_prefix_other
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_prefix_other._proof_1_1
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_prefix_other._proof_1_2
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_prefix_other._proof_1_3
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_prefix_other._proof_1_4
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_prefix_other._proof_1_5
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_prefix_other._proof_1_6
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.output_prefix_other._proof_1_7
#print axioms ExactFourierCircuits.UniformCacheTimingHeap.value_eq
#print axioms ExactFourierCircuits.UniformCacheTimingNode.outputHeap.eq_1
#print axioms ExactFourierCircuits.UniformCacheTimingReference.bottomStep.eq_1
#print axioms ExactFourierCircuits.UniformCacheTimingReference.requestPrefix.eq_1
