import UniformRecursiveResidualRecordPreparation
import Lean

-- Inventory uses defining-module provenance, including generated/private names.
set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.direction_bound
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.direction_bound._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.direction_bound._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.edge_direction
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.execution
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.execution._proof_1_12
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.execution._proof_1_13
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.execution._proof_1_7
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.execution._proof_1_8
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.execution._proof_1_9
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.execution._simp_1_11
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.halt_at
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.halt_at._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.program
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.program.eq_1
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.program_length
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.reader_code
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.role_bound
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.role_bound._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.role_bound._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.setup
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.setup.eq_1
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.setup_code
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.setup_code._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveResidualRecordPreparation.setup_length
