import UniformJointKernelDiagonalFields
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformJointDiagonalContext.field_bound
#print axioms ExactFourierCircuits.UniformJointDiagonalContext.field_directory
#print axioms ExactFourierCircuits.UniformJointDiagonalContext.field_directory._proof_1_1
#print axioms ExactFourierCircuits.UniformJointDiagonalContext.field_lane
#print axioms ExactFourierCircuits.UniformJointDiagonalContext.field_natFresh
#print axioms ExactFourierCircuits.UniformJointDiagonalContext.field_natFresh._proof_1_1
#print axioms ExactFourierCircuits.UniformJointDiagonalContext.field_natInverse
#print axioms ExactFourierCircuits.UniformJointDiagonalContext.field_natInverse._proof_1_1
#print axioms ExactFourierCircuits.UniformJointDiagonalContext.field_natMetadata
#print axioms ExactFourierCircuits.UniformJointDiagonalContext.field_natMetadata._proof_1_1
#print axioms ExactFourierCircuits.UniformJointDiagonalContext.field_natPacking
#print axioms ExactFourierCircuits.UniformJointDiagonalContext.field_natPacking._proof_1_1
#print axioms ExactFourierCircuits.UniformJointDiagonalContext.field_natStack
#print axioms ExactFourierCircuits.UniformJointDiagonalContext.field_natStack._proof_1_1
#print axioms ExactFourierCircuits.UniformJointDiagonalContext.field_pools
#print axioms ExactFourierCircuits.UniformJointDiagonalContext.field_scalarBuffer
#print axioms ExactFourierCircuits.UniformJointDiagonalContext.field_scalarBuffer._proof_1_1
#print axioms ExactFourierCircuits.UniformJointDiagonalContext.field_scalarFinal
#print axioms ExactFourierCircuits.UniformJointDiagonalContext.field_scalarFresh
#print axioms ExactFourierCircuits.UniformJointDiagonalContext.field_scalarFresh._proof_1_1
#print axioms ExactFourierCircuits.UniformJointDiagonalContext.field_scalarNative
#print axioms ExactFourierCircuits.UniformJointDiagonalContext.field_scalarNative._proof_1_1
#print axioms ExactFourierCircuits.UniformJointDiagonalContext.field_scalarPacked
#print axioms ExactFourierCircuits.UniformJointDiagonalContext.field_scalarPacked._proof_1_1
#print axioms ExactFourierCircuits.UniformJointDiagonalContext.field_scalarTemporary
#print axioms ExactFourierCircuits.UniformJointDiagonalContext.field_scalarTemporary._proof_1_1
#print axioms ExactFourierCircuits.UniformJointDiagonalContext.field_source
#print axioms ExactFourierCircuits.UniformJointDiagonalContext.field_volume
