import UniformJointKernelCacheRetention
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformJointKernelCacheRetention.execution
#print axioms ExactFourierCircuits.UniformJointKernelCacheRetention.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformJointKernelCacheRetention.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformJointKernelCacheRetention.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformJointKernelCacheRetention.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformJointKernelCacheRetention.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformJointKernelCacheRetention.execution._proof_1_6
