import UniformOffsetPreparationMachine
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.BaseHeap
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.DInstruction
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.DProgram
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.LiteralReady
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.LiteralReady._sparseCasesOn_1
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.LiteralReady._sparseCasesOn_1.else_eq
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.LiteralReady.eq_1
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.LiteralReady.eq_2
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.LiteralReady.match_1
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.LiteralsReady
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.LiteralsReady._f
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.LiteralsReady._sunfold
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.LiteralsReady._unsafe_rec
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.LiteralsReady.eq_1
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.LiteralsReady.eq_2
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.LiteralsReady.eq_def
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.LiteralsReady.match_1
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.NatTable
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.Registers
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.Registers.eq_1
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.RootsReady
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.Values
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.bytecode
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.bytecode._f
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.bytecode._sunfold
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.bytecode._unsafe_rec
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.bytecode.eq_1
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.bytecode.eq_2
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.bytecode.eq_def
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.bytecode.match_1
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.bytecode_get
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.bytecode_length
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.bytecode_length._proof_1_4
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.bytecode_natTable
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.bytecode_natTable._proof_1_1
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.bytecode_natTable._proof_1_2
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.bytecode_natTable._proof_1_3
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.bytecode_natTable._proof_1_4
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.bytecode_natTable._proof_1_5
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.compile
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.compile._f
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.compile._sunfold
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.compile._unsafe_rec
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.compile.eq_1
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.compile.eq_2
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.compile.eq_def
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.compile.match_1
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.compileLinear
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.compileLinear_eq
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.compileReverse
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.compileReverse._f
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.compileReverse._sunfold
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.compileReverse._unsafe_rec
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.compile_last_get
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.compile_length
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.compile_prefix_get
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.compile_valid
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.compile_valid._proof_1_1
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.compile_valid._proof_1_2
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.compile_valid._proof_1_3
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.compile_valid._proof_1_7
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.compile_valid._proof_1_8
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.compile_valid._proof_1_9
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.empty_execution
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.instruction_addresses
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.instruction_addresses._proof_1_10
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.instruction_addresses._proof_1_8
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.instruction_addresses._proof_1_9
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.instruction_operands
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.instruction_operands._proof_1_1
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.instruction_operands._proof_1_10
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.instruction_operands._proof_1_2
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.interpreted_DAG
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.interpreted_DAG_frames
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.interpreted_DAG_frames._proof_1_1
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.interpreted_DAG_packed
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.interpreted_DAG_packed._proof_1_1
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.literals_heap_eq
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.lowerInstruction
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.lowerInstruction.eq_1
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.lowerInstruction.eq_2
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.lowerInstruction.eq_3
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.lowerInstruction.eq_4
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.lowerInstruction.eq_5
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.lowerInstruction.eq_6
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.lowerInstruction.match_1
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.natTable_prefix
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.program
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.program_eq
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.program_length
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.schedule_append
#print axioms ExactFourierCircuits.UniformOffsetPreparationMachine.values_output

open Lean Elab Command in
run_cmd do
 let env ← getEnv
 for (name, _) in env.constants.toList do
  if "_private.UniformOffsetPreparationMachine.".isPrefixOf name.toString then
   let axs ← collectAxioms name
   logInfo m!"{name} depends on axioms: {axs.toList}"
