import UniformCacheTimingExecution
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformCacheTimingExecution.directory_of_at
#print axioms ExactFourierCircuits.UniformCacheTimingExecution.execution
#print axioms ExactFourierCircuits.UniformCacheTimingExecution.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformCacheTimingExecution.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformCacheTimingExecution.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformCacheTimingExecution.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformCacheTimingExecution.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformCacheTimingExecution.visits
#print axioms ExactFourierCircuits.UniformCacheTimingReverseData.ordinal.eq_1
