import UniformRecursivePreparedResidualLoop
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.loop_prepared
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.loop_prepared._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.loop_prepared._proof_1_3
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.loop_prepared._proof_1_4
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.loop_prepared._proof_1_5
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.loop_prepared._proof_1_6
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.loop_prepared._simp_1_1
