import UniformRecursivePreparedResidualEdge
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformRecursiveResidualEdge.execution_prepared
#print axioms ExactFourierCircuits.UniformRecursiveResidualEdge.execution_prepared._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveResidualEdge.execution_prepared._proof_1_11
#print axioms ExactFourierCircuits.UniformRecursiveResidualEdge.execution_prepared._proof_1_12
#print axioms ExactFourierCircuits.UniformRecursiveResidualEdge.execution_prepared._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveResidualEdge.execution_prepared._proof_1_3
#print axioms ExactFourierCircuits.UniformRecursiveResidualEdge.execution_prepared._proof_1_4
#print axioms ExactFourierCircuits.UniformRecursiveResidualEdge.execution_prepared._proof_1_5
#print axioms ExactFourierCircuits.UniformRecursiveResidualEdge.execution_prepared._proof_1_6
#print axioms ExactFourierCircuits.UniformRecursiveResidualEdge.execution_prepared._proof_1_7
#print axioms ExactFourierCircuits.UniformRecursiveResidualEdge.execution_prepared._proof_1_8
#print axioms ExactFourierCircuits.UniformRecursiveResidualEdge.execution_prepared._proof_1_9
#print axioms ExactFourierCircuits.UniformRecursiveResidualEdge.execution_prepared._simp_1_10
