import UniformRecursiveResidualControlJoin
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformRecursiveResidualControlJoin.edge_done_finish
#print axioms ExactFourierCircuits.UniformRecursiveResidualControlJoin.edge_generic_finish
#print axioms ExactFourierCircuits.UniformRecursiveResidualControlJoin.edge_generic_finish._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveResidualControlJoin.edge_generic_finish._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveResidualControlJoin.mark_init_generic
#print axioms ExactFourierCircuits.UniformRecursiveResidualControlJoin.mark_init_generic._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveResidualControlJoin.mark_init_generic._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveResidualControlJoin.mark_init_generic._proof_1_3
#print axioms ExactFourierCircuits.UniformRecursiveResidualControlJoin.mark_init_generic._proof_1_4
#print axioms ExactFourierCircuits.UniformRecursiveResidualControlJoin.mark_init_generic._proof_1_5
#print axioms ExactFourierCircuits.UniformRecursiveResidualControlJoin.mark_init_generic._proof_1_6
#print axioms ExactFourierCircuits.UniformRecursiveResidualControlJoin.raw_entry_cursor
#print axioms ExactFourierCircuits.UniformRecursiveResidualControlJoin.raw_entry_cursor._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveResidualControlJoin.raw_entry_cursor._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveResidualControlJoin.raw_entry_cursor._proof_1_3
#print axioms ExactFourierCircuits.UniformRecursiveResidualControlJoin.raw_entry_cursor._proof_1_4
#print axioms ExactFourierCircuits.UniformRecursiveResidualControlJoin.raw_entry_cursor._proof_1_5
