import UniformDirectLeafForestLeafStep
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafEnd.finished.eq_1
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.StepFrame
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.StepFrame.casesOn
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.StepFrame.mk
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.StepFrame.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.StepFrame.natBefore
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.StepFrame.natHigh
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.StepFrame.outputs
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.StepFrame.rec
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.StepFrame.recOn
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.StepFrame.roots
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.StepFrame.scalarOutside
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.finish_execution
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.finish_execution._proof_1_1
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.finish_execution._proof_1_10
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.finish_execution._proof_1_11
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.finish_execution._proof_1_12
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.finish_execution._proof_1_13
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.finish_execution._proof_1_14
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.finish_execution._proof_1_15
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.finish_execution._proof_1_16
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.finish_execution._proof_1_2
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.finish_execution._proof_1_3
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.finish_execution._proof_1_4
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.finish_execution._proof_1_5
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.finish_execution._proof_1_6
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.finish_execution._proof_1_7
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.finish_execution._proof_1_8
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.finish_execution._proof_1_9
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.frame
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.frame._proof_1_1
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.frame._proof_1_2
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.frame._proof_1_3
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.frame._proof_1_4
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.frame._proof_1_5
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafStep.frame._proof_1_6
