import UniformGlobalCalendarDispatchLoop
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.callCount.eq_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.callTotal.eq_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.callTotal_cons
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.loop_execution
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.loop_execution._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.loop_execution._proof_1_10
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.loop_execution._proof_1_11
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.loop_execution._proof_1_12
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.loop_execution._proof_1_13
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.loop_execution._proof_1_14
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.loop_execution._proof_1_15
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.loop_execution._proof_1_3
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.loop_execution._proof_1_4
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.loop_execution._proof_1_5
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.loop_execution._proof_1_6
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.loop_execution._proof_1_7
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.loop_execution._proof_1_8
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.loop_execution._proof_1_9
