import UniformRecursiveNativeParent
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformRecursiveNativeParent.exchange_parent
#print axioms ExactFourierCircuits.UniformRecursiveNativeParent.exchange_parent._proof_1_4
#print axioms ExactFourierCircuits.UniformRecursiveNativeParent.exchange_parent._proof_1_5
#print axioms ExactFourierCircuits.UniformRecursiveNativeParent.exchange_parent._simp_1_2
#print axioms ExactFourierCircuits.UniformRecursiveNativeParent.exchange_parent._simp_1_3
#print axioms ExactFourierCircuits.UniformRecursiveNativeParent.marker_parent
#print axioms ExactFourierCircuits.UniformRecursiveNativeParent.marker_parent._proof_1_4
#print axioms ExactFourierCircuits.UniformRecursiveNativeParent.marker_parent._proof_1_5
#print axioms ExactFourierCircuits.UniformRecursiveNativeParent.marker_parent._simp_1_2
#print axioms ExactFourierCircuits.UniformRecursiveNativeParent.marker_parent._simp_1_3
#print axioms ExactFourierCircuits.UniformRecursiveNativeParent.parentRegisters
#print axioms ExactFourierCircuits.UniformRecursiveNativeParent.parentRegisters.eq_1
#print axioms ExactFourierCircuits.UniformRecursiveNativeParent.parent_congr
#print axioms ExactFourierCircuits.UniformRecursiveNativeParent.scalar_parent
#print axioms ExactFourierCircuits.UniformRecursiveNativeParent.scalar_parent._proof_1_4
#print axioms ExactFourierCircuits.UniformRecursiveNativeParent.scalar_parent._proof_1_5
#print axioms ExactFourierCircuits.UniformRecursiveNativeParent.scalar_parent._simp_1_2
#print axioms ExactFourierCircuits.UniformRecursiveNativeParent.scalar_parent._simp_1_3
#print axioms ExactFourierCircuits.UniformRecursiveNativeParent.translation_parent
#print axioms ExactFourierCircuits.UniformRecursiveNativeParent.translation_parent._proof_1_4
#print axioms ExactFourierCircuits.UniformRecursiveNativeParent.translation_parent._proof_1_5
#print axioms ExactFourierCircuits.UniformRecursiveNativeParent.translation_parent._proof_1_6
#print axioms ExactFourierCircuits.UniformRecursiveNativeParent.translation_parent._simp_1_2
#print axioms ExactFourierCircuits.UniformRecursiveNativeParent.translation_parent._simp_1_3
