import UniformLocalRectangleCachePreparation
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformLocalRectangleCachePreparation.C.program
#print axioms ExactFourierCircuits.UniformLocalRectangleCachePreparation.P.actual
#print axioms ExactFourierCircuits.UniformLocalRectangleCachePreparation.P.program
#print axioms ExactFourierCircuits.UniformLocalRectangleCachePreparation.cache_code
#print axioms ExactFourierCircuits.UniformLocalRectangleCachePreparation.execution
#print axioms ExactFourierCircuits.UniformLocalRectangleCachePreparation.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalRectangleCachePreparation.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalRectangleCachePreparation.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalRectangleCachePreparation.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformLocalRectangleCachePreparation.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformLocalRectangleCachePreparation.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformLocalRectangleCachePreparation.execution._proof_1_7
#print axioms ExactFourierCircuits.UniformLocalRectangleCachePreparation.execution._proof_1_8
#print axioms ExactFourierCircuits.UniformLocalRectangleCachePreparation.halt_at
#print axioms ExactFourierCircuits.UniformLocalRectangleCachePreparation.halt_at._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalRectangleCachePreparation.phase_code
#print axioms ExactFourierCircuits.UniformLocalRectangleCachePreparation.program
#print axioms ExactFourierCircuits.UniformLocalRectangleCachePreparation.program.eq_1
#print axioms ExactFourierCircuits.UniformLocalRectangleCachePreparation.program_length
