import UniformInputPermutationPreparation

#print axioms ExactFourierCircuits.UniformInputPermutationPreparation.destination
#print axioms ExactFourierCircuits.UniformInputPermutationPreparation.setup
#print axioms ExactFourierCircuits.UniformInputPermutationPreparation.setup_length
#print axioms ExactFourierCircuits.UniformInputPermutationPreparation.program
#print axioms ExactFourierCircuits.UniformInputPermutationPreparation.program_length
#print axioms ExactFourierCircuits.UniformInputPermutationPreparation.initial_code
#print axioms ExactFourierCircuits.UniformInputPermutationPreparation.setup_code
#print axioms ExactFourierCircuits.UniformInputPermutationPreparation.gather_code
#print axioms ExactFourierCircuits.UniformInputPermutationPreparation.halt_at
#print axioms ExactFourierCircuits.UniformInputPermutationPreparation.setup_registers
#print axioms ExactFourierCircuits.UniformInputPermutationPreparation.setup_nat
#print axioms ExactFourierCircuits.UniformInputPermutationPreparation.setup_heap
#print axioms ExactFourierCircuits.UniformInputPermutationPreparation.setup_natHeap
#print axioms ExactFourierCircuits.UniformInputPermutationPreparation.setup_outputs
#print axioms ExactFourierCircuits.UniformInputPermutationPreparation.setup_roots
#print axioms ExactFourierCircuits.UniformInputPermutationPreparation.ready_transport_below
#print axioms ExactFourierCircuits.UniformInputPermutationPreparation.setup_peak
#print axioms ExactFourierCircuits.UniformInputPermutationPreparation.word_setup
#print axioms ExactFourierCircuits.UniformInputPermutationPreparation.preparationBudget
#print axioms ExactFourierCircuits.UniformInputPermutationPreparation.preparation_execution
#print axioms ExactFourierCircuits.UniformInputPermutationPreparation.preparationBudget_isBigO_input
