import UniformLocalCacheSlotCursorMachine
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.args
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.casesOn
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.duration
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.eleven
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.five
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.index
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.intercept
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.mk
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.natStride
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.nine
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.one
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.rec
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.recOn
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.scalarStride
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.slope
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.three
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.total
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.transport
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.transport._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.transport._proof_1_10
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.transport._proof_1_11
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.transport._proof_1_12
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.transport._proof_1_13
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.transport._proof_1_14
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.transport._proof_1_15
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.transport._proof_1_16
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.transport._proof_1_17
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.transport._proof_1_18
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.transport._proof_1_19
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.transport._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.transport._proof_1_20
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.transport._proof_1_21
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.transport._proof_1_22
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.transport._proof_1_23
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.transport._proof_1_24
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.transport._proof_1_25
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.transport._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.transport._proof_1_4
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.transport._proof_1_5
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.transport._proof_1_6
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.transport._proof_1_7
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.transport._proof_1_8
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.transport._proof_1_9
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.Control.withPC
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.advance
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.advance.eq_1
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.advance_args
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.advance_control
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.advance_heaps
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.advance_length
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.advance_safe
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.advance_safe._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.advance_safe._proof_1_10
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.advance_safe._proof_1_11
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.advance_safe._proof_1_12
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.advance_safe._proof_1_13
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.advance_safe._proof_1_14
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.advance_safe._proof_1_15
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.advance_safe._proof_1_16
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.advance_safe._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.advance_safe._proof_1_20
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.advance_safe._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.advance_safe._proof_1_4
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.advance_safe._proof_1_5
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.advance_safe._proof_1_6
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.advance_safe._proof_1_7
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.advance_safe._proof_1_8
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.advance_safe._proof_1_9
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.at_ambient
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.at_height
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.at_pool
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.at_slot
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.at_time
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.at_zero
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot.eq_1
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot_args
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot_args._proof_1_10
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot_args._proof_1_11
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot_args._proof_1_12
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot_args._proof_1_13
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot_args._proof_1_14
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot_args._proof_1_15
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot_args._proof_1_4
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot_args._proof_1_5
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot_args._proof_1_6
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot_args._proof_1_7
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot_args._proof_1_8
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot_args._proof_1_9
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot_args._simp_1_2
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot_args._simp_1_3
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot_control
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot_control._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot_control._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot_control._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot_control._proof_1_4
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot_heaps
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot_length
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot_safe
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot_safe._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot_safe._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot_safe._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot_safe._proof_1_4
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.boot_safe._proof_1_6
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.control_count
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.cursorParameters
#print axioms ExactFourierCircuits.UniformLocalCacheSlotCursorMachine.cursorParameters.eq_1

open Lean Elab Command in
run_cmd do
 let env ← getEnv
 for (name, _) in env.constants.toList do
  if "_private.UniformLocalCacheSlotCursorMachine.".isPrefixOf name.toString then
   let axs ← collectAxioms name
   logInfo m!"{name} depends on axioms: {axs.toList}"
