import UniformGlobalMatchingScaleBankBridge
import Lean
set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformGlobalMatchingScaleBankBridge.incident_unique
#print axioms ExactFourierCircuits.UniformGlobalMatchingScaleBankBridge.nativeFactor
#print axioms ExactFourierCircuits.UniformGlobalMatchingScaleBankBridge.nativeFactor._proof_1
#print axioms ExactFourierCircuits.UniformGlobalMatchingScaleBankBridge.nativeFactor_left
#print axioms ExactFourierCircuits.UniformGlobalMatchingScaleBankBridge.nativeFactor_right
#print axioms ExactFourierCircuits.UniformGlobalMatchingScaleBankBridge.nativeFactor_unused
#print axioms ExactFourierCircuits.UniformGlobalMatchingScaleBankBridge.pool_coefficients
#print axioms ExactFourierCircuits.UniformGlobalMatchingScaleBankBridge.rowEdges
#print axioms ExactFourierCircuits.UniformGlobalMatchingScaleBankBridge.rowEdges._proof_1
#print axioms ExactFourierCircuits.UniformGlobalMatchingScaleBankBridge.rowEdges.congr_simp
#print axioms ExactFourierCircuits.UniformGlobalMatchingScaleBankBridge.rowEdges.eq_1
#print axioms ExactFourierCircuits.UniformGlobalMatchingScaleBankBridge.rowEdges_matching
#print axioms ExactFourierCircuits.UniformGlobalMatchingScaleBankBridge.rowEdges_range
#print axioms ExactFourierCircuits.UniformGlobalMatchingScaleBankBridge.rows_geometry
