import UniformRegistryActiveEnumeration
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformRegistryActiveEnumeration.enumeration
#print axioms ExactFourierCircuits.UniformRegistryActiveEnumeration.enumeration._proof_1
#print axioms ExactFourierCircuits.UniformRegistryActiveEnumeration.enumeration_event
#print axioms ExactFourierCircuits.UniformRegistryActiveEnumeration.events_map
#print axioms ExactFourierCircuits.UniformRegistryActiveEnumeration.indices
#print axioms ExactFourierCircuits.UniformRegistryActiveEnumeration.indices.eq_1
#print axioms ExactFourierCircuits.UniformRegistryActiveEnumeration.indices_mem
#print axioms ExactFourierCircuits.UniformRegistryActiveEnumeration.indices_mem._proof_1_4
#print axioms ExactFourierCircuits.UniformRegistryActiveEnumeration.indices_mem._proof_1_5
#print axioms ExactFourierCircuits.UniformRegistryActiveEnumeration.indices_mem._proof_1_6
#print axioms ExactFourierCircuits.UniformRegistryActiveEnumeration.indices_mem._proof_1_7
#print axioms ExactFourierCircuits.UniformRegistryActiveEnumeration.indices_mem._simp_1_2
#print axioms ExactFourierCircuits.UniformRegistryActiveEnumeration.indices_mem._simp_1_3
#print axioms ExactFourierCircuits.UniformRegistryActiveEnumeration.indices_nodup
#print axioms ExactFourierCircuits.UniformRegistryActiveEnumeration.membershipEquiv
#print axioms ExactFourierCircuits.UniformRegistryActiveEnumeration.membershipEquiv._proof_1
#print axioms ExactFourierCircuits.UniformRegistryActiveEnumeration.membershipEquiv._proof_2
#print axioms ExactFourierCircuits.UniformRegistryActiveEnumeration.membershipEquiv._proof_3
#print axioms ExactFourierCircuits.UniformRegistryActiveEnumeration.membershipEquiv._proof_4
#print axioms ExactFourierCircuits.UniformRegistryActiveEnumeration.membershipEquiv._proof_5
#print axioms ExactFourierCircuits.UniformRegistryActiveEnumeration.membershipEquiv._proof_6
