import UniformMatchingKernelGeometry
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformMatchingKernelGeometry.kernel_matrix
#print axioms ExactFourierCircuits.UniformMatchingKernelGeometry.kernel_matrix._proof_1_1
#print axioms ExactFourierCircuits.UniformMatchingKernelGeometry.kernel_matrix._proof_1_2
#print axioms ExactFourierCircuits.UniformMatchingKernelGeometry.kernel_matrix._proof_1_4
#print axioms ExactFourierCircuits.UniformMatchingKernelGeometry.localCoordinates
#print axioms ExactFourierCircuits.UniformMatchingKernelGeometry.localKernel
#print axioms ExactFourierCircuits.UniformMatchingKernelGeometry.local_on
#print axioms ExactFourierCircuits.UniformMatchingKernelGeometry.pair_entry
#print axioms ExactFourierCircuits.UniformMatchingKernelGeometry.pair_form
#print axioms ExactFourierCircuits.UniformMatchingKernelGeometry.position
#print axioms ExactFourierCircuits.UniformMatchingKernelGeometry.position._proof_1
#print axioms ExactFourierCircuits.UniformMatchingKernelGeometry.position._proof_2
#print axioms ExactFourierCircuits.UniformMatchingKernelGeometry.position._proof_3
#print axioms ExactFourierCircuits.UniformMatchingKernelGeometry.position_value
#print axioms ExactFourierCircuits.UniformMatchingKernelGeometry.singleCoordinate
#print axioms ExactFourierCircuits.UniformMatchingKernelGeometry.singleCoordinate._proof_1
#print axioms ExactFourierCircuits.UniformMatchingKernelGeometry.single_original
#print axioms ExactFourierCircuits.UniformMatchingKernelGeometry.singleton_entry
#print axioms ExactFourierCircuits.UniformMatchingKernelGeometry.singleton_entry._proof_1_1
#print axioms ExactFourierCircuits.UniformMatchingKernelGeometry.singleton_outside
#print axioms ExactFourierCircuits.UniformMatchingKernelGeometry.singleton_outside._proof_1_1
#print axioms ExactFourierCircuits.UniformMatchingKernelGeometry.singleton_width
#print axioms ExactFourierCircuits.UniformSectorTensor.localEntry.eq_1
