import UniformLocalStoredRequestLoopControl
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformLocalStoredRequestLoop.axisOperations
#print axioms ExactFourierCircuits.UniformLocalStoredRequestLoop.axisOperations.eq_1
#print axioms ExactFourierCircuits.UniformLocalStoredRequestLoop.axisOperations_length
#print axioms ExactFourierCircuits.UniformLocalStoredRequestLoop.axis_code
#print axioms ExactFourierCircuits.UniformLocalStoredRequestLoop.enter
#print axioms ExactFourierCircuits.UniformLocalStoredRequestLoop.enter._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalStoredRequestLoop.enter._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalStoredRequestLoop.entered
#print axioms ExactFourierCircuits.UniformLocalStoredRequestLoop.entered.eq_1
#print axioms ExactFourierCircuits.UniformLocalStoredRequestLoop.entered_axis
#print axioms ExactFourierCircuits.UniformLocalStoredRequestLoop.entered_control
#print axioms ExactFourierCircuits.UniformLocalStoredRequestLoop.entered_control._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalStoredRequestLoop.entered_control._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalStoredRequestLoop.entered_control._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalStoredRequestLoop.entered_control._proof_1_4
#print axioms ExactFourierCircuits.UniformLocalStoredRequestLoop.entered_heaps
#print axioms ExactFourierCircuits.UniformLocalStoredRequestLoop.entered_keeps
#print axioms ExactFourierCircuits.UniformLocalStoredRequestLoop.entered_pc
#print axioms ExactFourierCircuits.UniformLocalStoredRequestLoop.stop
#print axioms ExactFourierCircuits.UniformLocalStoredRequestLoop.stop._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalStoredRequestLoop.stop._simp_1_2
