import UniformFastPhysicalCRTCarryLoop
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCarryLoop.execution
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCarryLoop.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCarryLoop.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCarryLoop.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCarryLoop.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCarryLoop.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCarryLoop.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCarryLoop.execution._proof_1_7
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCarryLoop.execution._proof_1_8
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCarryLoop.update_outside
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCarryLoop.update_outside._proof_1_1
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCarryLoop.work_update
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCarryLoop.work_update._proof_1_1
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTCarryLoop.work_update._proof_1_2
