import UniformActualCalendarWitnessSlots
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformActualCalendarWitnessSlots.castPlacement
#print axioms ExactFourierCircuits.UniformActualCalendarWitnessSlots.chunkLayers_get
#print axioms ExactFourierCircuits.UniformActualCalendarWitnessSlots.chunkSlots
#print axioms ExactFourierCircuits.UniformActualCalendarWitnessSlots.chunkSlots._proof_1
#print axioms ExactFourierCircuits.UniformActualCalendarWitnessSlots.chunkSlots._proof_2
#print axioms ExactFourierCircuits.UniformActualCalendarWitnessSlots.chunkSlots_bound
#print axioms ExactFourierCircuits.UniformActualCalendarWitnessSlots.chunkSlots_get
#print axioms ExactFourierCircuits.UniformActualCalendarWitnessSlots.dag
#print axioms ExactFourierCircuits.UniformActualCalendarWitnessSlots.dag_depth
#print axioms ExactFourierCircuits.UniformActualCalendarWitnessSlots.dag_fanout
#print axioms ExactFourierCircuits.UniformActualCalendarWitnessSlots.matching
#print axioms ExactFourierCircuits.UniformActualCalendarWitnessSlots.matching._proof_1_1
#print axioms ExactFourierCircuits.UniformActualCalendarWitnessSlots.normalPlacement
#print axioms ExactFourierCircuits.UniformActualCalendarWitnessSlots.normalPlacement._proof_1
#print axioms ExactFourierCircuits.UniformActualCalendarWitnessSlots.normalPlacement._proof_2
#print axioms ExactFourierCircuits.UniformActualCalendarWitnessSlots.packLayers_get
#print axioms ExactFourierCircuits.UniformActualCalendarWitnessSlots.packLayers_get._simp_1_1
#print axioms ExactFourierCircuits.UniformActualCalendarWitnessSlots.packList_congr
#print axioms ExactFourierCircuits.UniformActualCalendarWitnessSlots.pack_relabel_cast
#print axioms ExactFourierCircuits.UniformActualCalendarWitnessSlots.size
#print axioms ExactFourierCircuits.UniformActualCalendarWitnessSlots.stored
#print axioms ExactFourierCircuits.UniformActualCalendarWitnessSlots.stored._proof_1_1
