import UniformSectorMetadataCountBridge
import Lean
set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.execution_arguments
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.execution_count
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.execution_count._proof_1_1
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.execution_count._proof_1_10
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.execution_count._proof_1_11
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.execution_count._proof_1_12
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.execution_count._proof_1_13
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.execution_count._proof_1_14
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.execution_count._proof_1_15
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.execution_count._proof_1_16
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.execution_count._proof_1_17
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.execution_count._proof_1_18
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.execution_count._proof_1_19
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.execution_count._proof_1_2
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.execution_count._proof_1_20
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.execution_count._proof_1_21
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.execution_count._proof_1_22
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.execution_count._proof_1_23
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.execution_count._proof_1_24
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.execution_count._proof_1_25
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.execution_count._proof_1_3
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.execution_count._proof_1_4
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.execution_count._proof_1_5
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.execution_count._proof_1_6
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.execution_count._proof_1_7
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.execution_count._proof_1_8
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.execution_count._proof_1_9
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.program_arguments
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.program_keeps_argument
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.relocate_arguments
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.writesArguments
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.writesArguments._sparseCasesOn_1
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.writesArguments._sparseCasesOn_1.else_eq
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.writesArguments.eq_1
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.writesArguments.eq_2
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.writesArguments.eq_3
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.writesArguments.eq_4
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.writesArguments.eq_5
#print axioms ExactFourierCircuits.UniformSectorMetadataCountBridge.writesArguments.match_1

open Lean Elab Command in
run_cmd do
 let env ← getEnv
 for (name, _) in env.constants.toList do
  if "_private.UniformSectorMetadataCountBridge.".isPrefixOf name.toString then
   let axioms ← collectAxioms name
   for ax in axioms do
    unless ax == ``propext || ax == ``Quot.sound || ax == ``Classical.choice do
     throwError m!"Nonstandard axiom {ax} in {name}"
   logInfo m!"{name} depends on axioms: {axioms.toList}"
