import UniformGlobalCalendarFactorMergeTable
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.entryValues
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.entryValues.eq_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.mergeHeap_frame
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.mergeHeap_frame._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.mergeHeap_frame._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.mergeHeap_get
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.mergeHeap_get._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.mergeHeap_get._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.mergeHeap_get._proof_1_3
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.mergeHeap_get._proof_1_4
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.produced_execution
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.produced_execution._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.produced_execution._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.produced_factors
