import UniformRecursiveResidualFiberValues
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformRecursiveBatchGroupMachine.groupCount.eq_1
#print axioms ExactFourierCircuits.UniformRecursiveResidualFiberValues.W
#print axioms ExactFourierCircuits.UniformRecursiveResidualFiberValues.complete_values
#print axioms ExactFourierCircuits.UniformRecursiveResidualFiberValues.flatten_fiber
#print axioms ExactFourierCircuits.UniformRecursiveResidualFiberValues.input
#print axioms ExactFourierCircuits.UniformRecursiveResidualFiberValues.input.eq_1
#print axioms ExactFourierCircuits.UniformRecursiveResidualFiberValues.representative
#print axioms ExactFourierCircuits.UniformRecursiveResidualFiberValues.representative._proof_1
#print axioms ExactFourierCircuits.UniformRecursiveResidualFiberValues.representative._proof_2
#print axioms ExactFourierCircuits.UniformRecursiveResidualFiberValues.representative.congr_simp
#print axioms ExactFourierCircuits.UniformRecursiveResidualFiberValues.representative_value
#print axioms ExactFourierCircuits.UniformRecursiveResidualFiberValues.representative_value_generic
#print axioms ExactFourierCircuits.UniformRecursiveResidualFiberValues.scatter_values
#print axioms ExactFourierCircuits.UniformRecursiveResidualFiberValues.selected_flat
#print axioms ExactFourierCircuits.UniformRecursiveResidualFiberValues.selected_flat._proof_1
#print axioms ExactFourierCircuits.UniformRecursiveResidualFiberValues.selected_flat._proof_2
#print axioms ExactFourierCircuits.UniformRecursiveResidualFiberValues.selected_values
#print axioms ExactFourierCircuits.UniformRecursiveResidualOutput.selected.congr_simp
