import UniformGlobalRoleScatterLoop
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformGlobalRoleScatterMachine.boot_cursor
#print axioms ExactFourierCircuits.UniformGlobalRoleScatterMachine.execution
#print axioms ExactFourierCircuits.UniformGlobalRoleScatterMachine.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalRoleScatterMachine.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalRoleScatterMachine.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformGlobalRoleScatterMachine.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformGlobalRoleScatterMachine.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformGlobalRoleScatterMachine.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformGlobalRoleScatterMachine.filled_transfer
#print axioms ExactFourierCircuits.UniformGlobalRoleScatterMachine.filled_transfer._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalRoleScatterMachine.filled_transfer._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalRoleScatterMachine.loop
#print axioms ExactFourierCircuits.UniformGlobalRoleScatterMachine.loop._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalRoleScatterMachine.loop._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalRoleScatterMachine.loop._proof_1_3
#print axioms ExactFourierCircuits.UniformGlobalRoleScatterMachine.loop._proof_1_4
#print axioms ExactFourierCircuits.UniformGlobalRoleScatterMachine.loop._proof_1_5
#print axioms ExactFourierCircuits.UniformGlobalRoleScatterMachine.loop._proof_1_6
#print axioms ExactFourierCircuits.UniformGlobalRoleScatterMachine.native_values
#print axioms ExactFourierCircuits.UniformGlobalRoleScatterMachine.outside_local
#print axioms ExactFourierCircuits.UniformGlobalRoleScatterMachine.outside_local._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalRoleScatterMachine.source_transfer
#print axioms ExactFourierCircuits.UniformGlobalRoleScatterMachine.source_transfer._proof_1_1
