import UniformLocalRectangleCacheBindings
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.enabledHeight.eq_1
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Bindings
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Bindings.casesOn
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Bindings.conjugates
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Bindings.enabled
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Bindings.falseColors
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Bindings.falseDirectory
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Bindings.falsePalette
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Bindings.falseRows
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Bindings.gates
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Bindings.height
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Bindings.mk
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Bindings.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Bindings.negative
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Bindings.rec
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Bindings.recOn
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Bindings.rectangle
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Bindings.slot
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Driver
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Driver.casesOn
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Driver.copies
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Driver.kind
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Driver.mk
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Driver.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Driver.originalDirectory
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Driver.radix
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Driver.rec
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Driver.recOn
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Driver.retained
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Driver.retained._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Driver.retained._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Driver.time
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.Driver.timeHigh
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.P.actual
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.actual_a
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.actual_e
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.banks_of_outputs
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.banks_of_outputs._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.coefficientBank
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.coefficientBank.eq_1
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.constants_of_operands
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.false_height
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_10
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_11
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_12
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_13
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_14
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_15
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_16
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_17
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_18
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_19
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_20
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_21
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_22
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_23
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_24
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_25
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_26
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_27
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_28
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_29
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_30
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_31
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_32
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_33
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_34
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_5
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_6
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_7
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_8
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._proof_1_9
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._simp_1_1
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.sources_of_cursor._simp_1_2
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.true_height
#print axioms ExactFourierCircuits.UniformLocalRectangleCacheBindings.update_height
#print axioms ExactFourierCircuits.UniformRankCrossReplayPreparationMachine.cross.eq_1
#print axioms ExactFourierCircuits.UniformSeedHeightPreparation.Config.gates.eq_1

open Lean Elab Command in
run_cmd do
 let env ← getEnv
 for (name, _) in env.constants.toList do
  if "_private.UniformLocalRectangleCacheBindings.".isPrefixOf name.toString then
   let axs ← collectAxioms name
   logInfo m!"{name} depends on axioms: {axs.toList}"
