import UniformAxisCacheTimingGeometry
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.wordBudget.eq_1
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.cap_lower
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.cap_lower._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.duration_cap
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.duration_cap._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.duration_fits
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.duration_fits._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.duration_fits._proof_1_3
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.duration_fits._proof_1_4
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.duration_fits._proof_1_5
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.duration_fits._proof_1_6
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.nodes_bound
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.producer_layout
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.producer_layout._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.producer_layout._proof_1_2
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.producer_layout._proof_1_3
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.producer_layout._proof_1_4
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.producer_layout._proof_1_5
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.producer_layout._proof_1_6
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.requests_bound
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.row_fits
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.row_fits._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.search_fits
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.source_gap
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.timing_layout
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.timing_layout._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.timing_layout._proof_1_2
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.timing_layout._proof_1_3
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.timing_layout._proof_1_4
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.timing_layout._proof_1_5
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.walk_length
#print axioms ExactFourierCircuits.UniformAxisCacheTimingGeometry.walk_length._simp_1_1
