import UniformBoundaryDiagonalMachine
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.Args
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.Args.arena
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.Args.casesOn
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.Args.lane
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.Args.mk
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.Args.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.Args.pool
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.Args.rec
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.Args.recOn
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.Args.seed
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.Args.time
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.avoids
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.axis
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.copySetup
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.copySetup_code
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.copySetup_length
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.copy_code
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.emptyEdges
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.empty_matching
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.empty_range
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.halt_at
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.head
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.head_code
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.head_length
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.nat_frame
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.pool_code
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.program
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.program.eq_1
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.program_length
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.slotSetup
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.slotSetup_code
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.slotSetup_length
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.slot_code
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.written
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.written_checked
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalMachine.written_checked._proof_1_1
