import UniformReflectedCalendarSource
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformReflectedCalendarSource.forward_source
#print axioms ExactFourierCircuits.UniformReflectedCalendarSource.forward_source._proof_1_3
#print axioms ExactFourierCircuits.UniformReflectedCalendarSource.forward_source._proof_1_4
#print axioms ExactFourierCircuits.UniformReflectedCalendarSource.forward_source._proof_1_5
#print axioms ExactFourierCircuits.UniformReflectedCalendarSource.forward_source._proof_1_6
#print axioms ExactFourierCircuits.UniformReflectedCalendarSource.forward_source._proof_1_7
#print axioms ExactFourierCircuits.UniformReflectedCalendarSource.forward_source._proof_1_8
#print axioms ExactFourierCircuits.UniformReflectedCalendarSource.forward_source._proof_1_9
#print axioms ExactFourierCircuits.UniformReflectedCalendarSource.upper_source
#print axioms ExactFourierCircuits.UniformReflectedCalendarSource.upper_source._proof_1_3
#print axioms ExactFourierCircuits.UniformReflectedCalendarSource.upper_source._proof_1_4
#print axioms ExactFourierCircuits.UniformReflectedCalendarSource.upper_source._proof_1_5
