import UniformForwardMatchingFactorFrame

-- Inventory uses the defining Lean module, including generated declarations.
set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.PreludeFrame
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.PreludeFrame.casesOn
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.PreludeFrame.high
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.PreludeFrame.mk
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.PreludeFrame.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.PreludeFrame.natHeap
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.PreludeFrame.outputs
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.PreludeFrame.rec
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.PreludeFrame.recOn
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.PreludeFrame.roots
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.PreludeFrame.saved
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.PreludeFrame.scalar
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.PreludeFrame.setup
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.PreludeFrame.setup._proof_1_1
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.PreludeFrame.setup._proof_1_2
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.PreludeFrame.setup._proof_1_3
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.PreludeFrame.setup._proof_1_4
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.PreludeFrame.setup._proof_1_5
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.PreludeFrame.setup._proof_1_6
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.PreludeFrame.withPC
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.PreludeFrame.zero
