import UniformRecursiveResidualDirectionLoop
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.Visit
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.Visit.below
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.Visit.below.casesOn
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.Visit.below.done
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.Visit.below.rec
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.Visit.below.step
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.Visit.brecOn
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.Visit.casesOn
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.Visit.done
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.Visit.rec
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.Visit.recOn
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.Visit.step
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.action
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.action.eq_1
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.action_basis
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.action_matrix
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.control_pc
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.directionCost
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.directionMatrix
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.directionMatrix._proof_1
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.indices
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.indices._f
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.indices._proof_1
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.indices._proof_2
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.indices._proof_3
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.indices._proof_4
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.indices._sunfold
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.indices._unsafe_rec
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.indices.congr_simp
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.indices.eq_1
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.indices.eq_2
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.indices.eq_def
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.indices.match_1
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.indices_all
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.indices_all._proof_1
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.indices_values
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.indices_visit
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.indices_visit._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.indices_visit._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.loop
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.loop._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.loop._proof_1_3
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.loop._proof_1_4
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.loop._proof_1_5
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.loop._proof_1_6
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.loop._simp_1_1
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.nativeWordMatrix_append
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.nativeWordMatrix_nil
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.next_execution
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.next_generic
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.setPC_frame
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.setPC_pc
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.signedWords
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.signedWords.eq_1
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.spectatorMatrix_mul
#print axioms ExactFourierCircuits.UniformRecursiveResidualDirectionLoop.spectatorMatrix_one

open Lean Elab Command in
run_cmd do
 let env ← getEnv
 for (name, _) in env.constants.toList do
  if "_private.UniformRecursiveResidualDirectionLoop.".isPrefixOf name.toString then
   let axs ← collectAxioms name
   logInfo m!"{name} depends on axioms: {axs.toList}"
