import UniformFinalAxisCacheRetention
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformFinalAxisCacheRetention.at_merged
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRetention.at_merged._proof_1_1
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRetention.family_interval
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRetention.family_interval._proof_1
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRetention.leaf_lower
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRetention.leaf_lower._proof_1
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRetention.leaf_lower._proof_1_1
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRetention.leaf_lower._proof_1_2
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRetention.merged
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRetention.merged._proof_1
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRetention.merged._proof_2
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRetention.merged_bounds
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRetention.merged_bounds._proof_1_1
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRetention.merged_transferred
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRetention.merged_transferred_events
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRetention.node_lower
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRetention.rectangle_lower
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRetention.rectangle_lower._proof_1_1
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRetention.transferred
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRetention.transferred_events
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRetention.transferred_merged
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRetention.transferred_merged._proof_1_1
#print axioms ExactFourierCircuits.UniformFinalAxisCacheRetention.transferred_reference
