import UniformLayerRestriction
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformLayerRestriction.Restricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.Restricted._f
#print axioms ExactFourierCircuits.UniformLayerRestriction.Restricted._sunfold
#print axioms ExactFourierCircuits.UniformLayerRestriction.Restricted._unsafe_rec
#print axioms ExactFourierCircuits.UniformLayerRestriction.Restricted.match_1
#print axioms ExactFourierCircuits.UniformLayerRestriction.ScheduleRestricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.ScheduleRestricted.eq_1
#print axioms ExactFourierCircuits.UniformLayerRestriction.StepRestricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.StepRestricted.match_1
#print axioms ExactFourierCircuits.UniformLayerRestriction.WordRestricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.WordRestricted.eq_1
#print axioms ExactFourierCircuits.UniformLayerRestriction.batchWords_restricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.correctionSchedule_restricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.diagonalStep_restricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.diagonalStep_restricted._simp_1
#print axioms ExactFourierCircuits.UniformLayerRestriction.direct_partial_restricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.direct_partial_restricted._proof_1_2
#print axioms ExactFourierCircuits.UniformLayerRestriction.direct_row_restricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.direct_row_restricted._simp_1_1
#print axioms ExactFourierCircuits.UniformLayerRestriction.direct_row_restricted._simp_1_2
#print axioms ExactFourierCircuits.UniformLayerRestriction.direct_shear_restricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.embedStep_restricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.embeddedWord_restricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.embedded_diagonal
#print axioms ExactFourierCircuits.UniformLayerRestriction.forwardCall_restricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.forwardCall_restricted._simp_1
#print axioms ExactFourierCircuits.UniformLayerRestriction.idle_restricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.idle_restricted._simp_1
#print axioms ExactFourierCircuits.UniformLayerRestriction.localShear_restricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.matchingLayers_restricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.parallel_restricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.render_restricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.serial_restricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.shearLayers_restricted
