import UniformGlobalCalendarDispatch
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.advance
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.advance_code
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.boot
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.boot_code
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.code_10
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.code_28
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.code_29
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.code_33
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.code_34
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.code_35
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.code_41
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.code_51
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.factorSetup
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.factorSetup_code
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.initSetup
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.main
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.main_length
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.phasePrinter
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.phasePrinter.eq_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.phasePrinter_length
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.phaseSetup
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.phaseSetup_code
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.program
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.program.eq_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.program_length
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.readEntry
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.readEntry_code
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.rowsReturn
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.rowsReturn_code
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.rowsSetup
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.rowsSetup_code
