import UniformAxisCacheTimingProgram
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformAxisCachePrepareProgram.destination.eq_1
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.axis_index_frame
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.changed
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.changed.eq_1
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.conductor_code
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.conductor_code._proof_1_2
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.conductor_keeps_axis_index
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.conductor_keeps_axis_index._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.destinations
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.destinations._sparseCasesOn_1
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.destinations._sparseCasesOn_1.else_eq
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.destinations.eq_1
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.destinations.eq_2
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.destinations.eq_3
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.destinations.eq_4
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.destinations.match_1
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.instDecidableChanged
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.instDecidableDestinations
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.instDecidableDestinations._proof_1
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.instDecidableDestinations._proof_10
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.instDecidableDestinations._proof_11
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.instDecidableDestinations._proof_12
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.instDecidableDestinations._proof_13
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.instDecidableDestinations._proof_14
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.instDecidableDestinations._proof_2
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.instDecidableDestinations._proof_3
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.instDecidableDestinations._proof_4
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.instDecidableDestinations._proof_5
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.instDecidableDestinations._proof_6
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.instDecidableDestinations._proof_7
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.instDecidableDestinations._proof_8
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.instDecidableDestinations._proof_9
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.instDecidableKeepsNatOfNatNat_uniformAxisCacheTimingProgram
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.prepare_code
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.producer_keeps_axis_index
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.program
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.program.eq_1
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.program_destinations
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.program_destinations._proof_1_4
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.program_destinations._proof_1_6
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.program_keeps
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.program_keeps_axis_index
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.program_keeps_axis_index._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.program_length
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.program_natOnly
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.relocate_keeps
#print axioms ExactFourierCircuits.UniformAxisCacheTimingProgram.terminal_keeps

open Lean Elab Command in
run_cmd do
 let env ← getEnv
 for (name, _) in env.constants.toList do
  if "_private.UniformAxisCacheTimingProgram.".isPrefixOf name.toString then
   let axs ← collectAxioms name
   logInfo m!"{name} depends on axioms: {axs.toList}"
