import UniformFinalAxisCacheIntervalRetention
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.family_interval
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.family_interval._proof_1
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.family_interval._proof_2
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.interval
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.interval._proof_1_1
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.interval._proof_1_10
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.interval._proof_1_11
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.interval._proof_1_12
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.interval._proof_1_13
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.interval._proof_1_14
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.interval._proof_1_15
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.interval._proof_1_2
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.interval._proof_1_3
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.interval._proof_1_4
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.interval._proof_1_5
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.interval._proof_1_6
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.interval._proof_1_7
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.interval._proof_1_8
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.interval._proof_1_9
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.leaf_permutation
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.leaf_permutation._proof_1
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.leaf_permutation._proof_1_1
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.leaf_permutation._proof_1_2
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.merged_transferred
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.merged_transferred._proof_1
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.merged_transferred._proof_2
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.merged_transferred_events
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.node_bounds
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.node_bounds._proof_1_1
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.rectangle_permutation
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.rectangle_permutation._proof_1_1
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.transferred
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.transferred._proof_1
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.transferred._proof_2
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.transferred._proof_3
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.transferred._proof_4
#print axioms ExactFourierCircuits.UniformFinalAxisCacheIntervalRetention.transferred_events
