import UniformRecursiveNativeTypedRecords
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.Frame
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.Frame.casesOn
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.Frame.constants
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.Frame.constants._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.Frame.constants._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.Frame.constants._proof_1_3
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.Frame.constants._proof_1_4
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.Frame.mk
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.Frame.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.Frame.natHeap
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.Frame.outputs
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.Frame.rec
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.Frame.recOn
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.Frame.roots
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.Frame.scalarHeap
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.exchange
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.exchange_frame
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.marker
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.marker_frame
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.marker_good
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.scalar
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.scalar_frame
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.scalar_frame._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.scalar_frame._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.translation
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.translation._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.translation._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.translation._proof_1_3
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.translation._proof_1_4
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.translation._proof_1_5
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.translation_frame
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.translation_frame._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveNativeTypedRecords.translation_frame._proof_1_2
