import UniformAxisCacheAllocationEnvelope
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.selected_wordBudget
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.selected_wordBudget._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.selected_wordBudget._proof_1_2
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.selected_wordBudget._proof_1_3
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.selected_wordBudget._proof_1_4
