import UniformAxisCacheAllocationExecution
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.Frame
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.Frame.casesOn
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.Frame.mk
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.Frame.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.Frame.natHeap
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.Frame.natReg
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.Frame.outputs
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.Frame.pc
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.Frame.rec
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.Frame.recOn
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.Frame.refl
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.Frame.roots
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.Frame.scalarHeap
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.Frame.scalarReg
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.Frame.trans
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.allowed
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.allowed.eq_1
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.block_frame
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.block_pc
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.boot_frame
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.boot_safe
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.boot_safe._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.capacity_safe
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.capacity_safe._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.control_safe
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.control_safe._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.duration_frame
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.duration_frame._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.execution
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.execution._proof_1_10
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.execution._proof_1_11
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.execution._proof_1_12
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.execution._proof_1_13
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.execution._proof_1_14
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.execution._proof_1_15
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.execution._proof_1_16
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.execution._proof_1_7
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.execution._proof_1_8
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.execution._proof_1_9
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.front_safe
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.front_safe._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.op_frame
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.op_frame._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.ordinary
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.ordinary._sparseCasesOn_1
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.ordinary._sparseCasesOn_1.else_eq
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.ordinary.eq_1
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.ordinary.eq_2
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.ordinary.eq_3
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.ordinary.match_1
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.peak_append
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.post_frame
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.post_safe
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.post_safe._simp_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.post_safe._simp_1_2
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.readable_append
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.readable_append._simp_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.scalar_safe
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.scalar_safe._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.time_safe
#print axioms ExactFourierCircuits.UniformAxisCacheAllocationMachine.time_safe._proof_1_1

open Lean Elab Command in
run_cmd do
 let env ← getEnv
 for (name, _) in env.constants.toList do
  if "_private.UniformAxisCacheAllocationExecution.".isPrefixOf name.toString then
   let axs ← collectAxioms name
   logInfo m!"{name} depends on axioms: {axs.toList}"
