import UniformLocalCacheTreeCoverage
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformLocalCacheTreeCoverage.currentRows
#print axioms ExactFourierCircuits.UniformLocalCacheTreeCoverage.currentRows.eq_1
#print axioms ExactFourierCircuits.UniformLocalCacheTreeCoverage.currentRows_length
#print axioms ExactFourierCircuits.UniformLocalCacheTreeCoverage.pendingRows
#print axioms ExactFourierCircuits.UniformLocalCacheTreeCoverage.pendingRows.eq_1
#print axioms ExactFourierCircuits.UniformLocalCacheTreeCoverage.pendingRows_append
#print axioms ExactFourierCircuits.UniformLocalCacheTreeCoverage.pendingRows_cons
#print axioms ExactFourierCircuits.UniformLocalCacheTreeCoverage.root_walk_kernel_coverage
#print axioms ExactFourierCircuits.UniformLocalCacheTreeCoverage.root_walk_rectangle_bound
#print axioms ExactFourierCircuits.UniformLocalCacheTreeCoverage.root_walk_rows
#print axioms ExactFourierCircuits.UniformLocalCacheTreeCoverage.root_walk_visitSum_bound
#print axioms ExactFourierCircuits.UniformLocalCacheTreeCoverage.task_decomposition
#print axioms ExactFourierCircuits.UniformLocalCacheTreeCoverage.visitedRows
#print axioms ExactFourierCircuits.UniformLocalCacheTreeCoverage.visitedRows.eq_1
#print axioms ExactFourierCircuits.UniformLocalCacheTreeCoverage.visitedRows_length
#print axioms ExactFourierCircuits.UniformLocalCacheTreeCoverage.walk_preserves_rows
