import UniformActualCalendarRectangleRegistry
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.base
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.block
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.block.eq_1
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.block_get
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.bounds
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.bounds._proof_1_1
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.data
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.data._proof_1
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.data._proof_2
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.family
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.family._proof_1
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.family._proof_10
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.family._proof_11
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.family._proof_2
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.family._proof_3
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.family._proof_4
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.family._proof_5
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.family._proof_6
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.family._proof_7
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.family._proof_8
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.family._proof_9
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.reserve_split
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.reserve_split._proof_1_1
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.reserve_split._proof_1_2
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleRegistry.reserve_split._proof_1_3
