import UniformDirectLeafForestGeometry
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformDirectLeafForestData.position.eq_1
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.Layout
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.Layout.axis
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.Layout.cacheEnd
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.Layout.casesOn
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.Layout.code
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.Layout.conjugate
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.Layout.conjugateDirectory
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.Layout.constants
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.Layout.descriptorEnd
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.Layout.descriptors
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.Layout.directory
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.Layout.entry
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.Layout.markers
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.Layout.mk
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.Layout.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.Layout.natEnd
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.Layout.natStride
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.Layout.original
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.Layout.rec
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.Layout.recOn
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.Layout.rows
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.Layout.scalarEnd
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.Layout.scalarStride
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.Layout.time
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.Layout.widths
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.config
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.config.eq_1
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.phase_layout
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.phase_layout._proof_1_10
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.phase_layout._proof_1_3
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.phase_layout._proof_1_4
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.phase_layout._proof_1_5
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.phase_layout._proof_1_6
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.phase_layout._proof_1_7
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.phase_layout._proof_1_8
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.phase_layout._proof_1_9
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.root_extent
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.root_extent._simp_1_1
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.root_leaf_duration
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.walk_extent
#print axioms ExactFourierCircuits.UniformDirectLeafForestGeometry.walk_extent._simp_1_1
