import UniformTransposeCalendarSnapshot
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformTransposeCalendarSnapshot.axisSnapshot
#print axioms ExactFourierCircuits.UniformTransposeCalendarSnapshot.axisSnapshot._proof_1
#print axioms ExactFourierCircuits.UniformTransposeCalendarSnapshot.axisSnapshot._proof_2
#print axioms ExactFourierCircuits.UniformTransposeCalendarSnapshot.axisSnapshot.eq_1
#print axioms ExactFourierCircuits.UniformTransposeCalendarSnapshot.axisSnapshot_matrix
#print axioms ExactFourierCircuits.UniformTransposeCalendarSnapshot.axisSnapshot_matrix._proof_1_3
#print axioms ExactFourierCircuits.UniformTransposeCalendarSnapshot.axisSnapshot_matrix._simp_1_2
#print axioms ExactFourierCircuits.UniformTransposeCalendarSnapshot.embedding
#print axioms ExactFourierCircuits.UniformTransposeCalendarSnapshot.embedding._proof_1
#print axioms ExactFourierCircuits.UniformTransposeCalendarSnapshot.embedding._proof_2
#print axioms ExactFourierCircuits.UniformTransposeCalendarSnapshot.embedding._proof_3
#print axioms ExactFourierCircuits.UniformTransposeCalendarSnapshot.events
#print axioms ExactFourierCircuits.UniformTransposeCalendarSnapshot.snapshot
#print axioms ExactFourierCircuits.UniformTransposeCalendarSnapshot.snapshot_matrix
