import UniformGlobalPackingChildPreparation
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformAllSectorTransposeMachine.slice.eq_1
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.execution
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.execution._proof_1_10
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.execution._proof_1_11
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.execution._proof_1_12
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.execution._proof_1_13
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.execution._proof_1_14
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.execution._proof_1_15
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.execution._proof_1_16
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.execution._proof_1_17
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.execution._proof_1_18
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.execution._proof_1_19
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.execution._proof_1_20
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.execution._proof_1_7
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.execution._proof_1_8
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.execution._proof_1_9
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.halt_at
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.packedValues
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.packedValues.eq_1
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.produced_source
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.produced_source._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.program
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.programFor
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.programFor.eq_1
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.program_length
#print axioms ExactFourierCircuits.UniformGlobalPackingChildPreparation.rows_withPC
