import UniformRecursiveRuntimeInventory
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformFixedCoefficientCodec.encodeTape.congr_simp
#print axioms ExactFourierCircuits.UniformRecursiveRuntimeInventory.append
#print axioms ExactFourierCircuits.UniformRecursiveRuntimeInventory.block
#print axioms ExactFourierCircuits.UniformRecursiveRuntimeInventory.boundary
#print axioms ExactFourierCircuits.UniformRecursiveRuntimeInventory.columns
#print axioms ExactFourierCircuits.UniformRecursiveRuntimeInventory.cons
#print axioms ExactFourierCircuits.UniformRecursiveRuntimeInventory.directions
#print axioms ExactFourierCircuits.UniformRecursiveRuntimeInventory.directions.eq_1
#print axioms ExactFourierCircuits.UniformRecursiveRuntimeInventory.directions_columns
#print axioms ExactFourierCircuits.UniformRecursiveRuntimeInventory.encoded_directions
#print axioms ExactFourierCircuits.UniformRecursiveRuntimeInventory.fixedInvocation_sum
#print axioms ExactFourierCircuits.UniformRecursiveRuntimeInventory.flatten
#print axioms ExactFourierCircuits.UniformRecursiveRuntimeInventory.macro_directions
#print axioms ExactFourierCircuits.UniformRecursiveRuntimeInventory.padding_transfer
#print axioms ExactFourierCircuits.UniformRecursiveRuntimeInventory.recursiveDirections
#print axioms ExactFourierCircuits.UniformRecursiveRuntimeInventory.recursiveDirections.eq_1
#print axioms ExactFourierCircuits.UniformRecursiveRuntimeInventory.schedule_directions
#print axioms ExactFourierCircuits.UniformRecursiveRuntimeInventory.terminal
#print axioms ExactFourierCircuits.UniformRecursiveRuntimeInventory.terminal_generic
