import UniformResidualNativeCoordinates
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.batchFibers
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.batchFibers._proof_1
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.batchFibers._proof_2
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.bitTransport
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.complete_batch_size
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.complete_batch_size._proof_1_1
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.coordinates_zero
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.encode_zero
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.nativeBatches
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.nativeBatches_apply
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.nativeBatches_array
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.nativeCopiedMatrix
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.nativeCopiedMatrix.eq_1
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.nativeCopied_array
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.nativeCopied_blocks
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.nativeFiber
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.nativeFiber.congr_simp
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.nativeFiber.eq_1
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.nativeFiber_coordinates
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.nativeFiber_other
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.nativeFiber_pivot
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.nativeFiber_representative_image
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.nativeFiber_selected_image
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.nativeFiber_xor
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.nativeFiber_zero
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.native_partition
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.representative
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.representative._proof_1
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.representative._proof_2
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.representative._proof_3
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.representative._proof_4
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.representative.eq_1
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.representativeColumns
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.representativeColumns.eq_1
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.representativeColumns_other
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.representative_other
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.representative_pivot
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.seed_batch_capacity
#print axioms ExactFourierCircuits.UniformResidualNativeCoordinates.seed_batch_capacity._proof_1_1
