import UniformGlobalCalendarSelectorBlocks
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.Loaded.duration
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.Stopped
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.Stopped.casesOn
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.Stopped.durationValue
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.Stopped.mk
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.Stopped.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.Stopped.pc
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.Stopped.rec
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.Stopped.recOn
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.Stopped.stopValue
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.Stopped.toLoaded
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.advance.eq_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.advance_execution
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.advance_execution._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.advance_execution._proof_1_3
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.advance_header
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.emit.eq_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.emit_execution
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.emit_execution._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.emit_execution._proof_1_3
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.emit_header
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.emit_heap
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.phase.eq_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.phase_execution
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.phase_execution._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.phase_execution._proof_1_3
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.phase_stopped
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.phase_value
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.stop.eq_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.stop_execution
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.stop_execution._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.stop_execution._proof_1_3
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.stop_stopped
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.storeSelection
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.storeSelection.eq_1
