import UniformTransposeMatchingRender
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.layers
#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.layers._proof_1
#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.layers.eq_1
#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.layers_length
#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.layers_matrix
#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.layers_matrix._simp_1_3
#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.layers_restricted
#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.layers_tick
#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.matching
#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.matching._proof_1
#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.matching.congr_simp
#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.matching.eq_1
#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.matching_length
#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.matching_matrix
#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.matching_phase
#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.matching_restricted
#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.swap2
#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.swap2._proof_1
#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.swap2.eq_1
#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.swappedPosition
#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.swappedPosition.congr_simp
#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.swappedPosition.eq_1
#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.swappedWord
#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.swappedWord.eq_1
#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.swappedWord_length
#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.swappedWord_matrix
#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.swappedWord_restricted
#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.swapped_blocks
#print axioms ExactFourierCircuits.UniformTransposeMatchingRender.swapped_upper
