import UniformAxisCachePreparationInputs
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformAxisCachePreparationInputs.execution
#print axioms ExactFourierCircuits.UniformAxisCachePreparationInputs.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCachePreparationInputs.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformAxisCachePreparationInputs.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformAxisCachePreparationInputs.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformAxisCachePreparationInputs.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformAxisCachePreparationInputs.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformAxisCachePreparationInputs.execution._proof_1_7
#print axioms ExactFourierCircuits.UniformAxisCachePreparationInputs.execution._proof_1_8
