import UniformGlobalDiagonalRowsIteration
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.iteration
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.iteration._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.load_row
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.load_row._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.load_row._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.placed_row
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.placed_row._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.placed_row._proof_1_10
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.placed_row._proof_1_11
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.placed_row._proof_1_12
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.placed_row._proof_1_13
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.placed_row._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.placed_row._proof_1_3
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.placed_row._proof_1_4
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.placed_row._proof_1_5
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.placed_row._proof_1_6
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.placed_row._proof_1_7
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.placed_row._proof_1_8
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.placed_row._proof_1_9
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.tick_row
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.tick_row._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.tick_row._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.tick_row._proof_1_3
