import UniformDirectLeafCacheLoopRetention
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_1
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_10
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_11
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_12
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_13
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_14
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_15
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_16
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_17
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_18
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_19
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_2
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_20
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_21
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_22
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_23
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_24
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_25
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_26
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_27
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_28
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_29
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_3
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_30
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_31
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_32
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_33
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_4
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_5
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_6
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_7
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_8
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._proof_9
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLoopRetention.result._simp_23
