import UniformSeedEdgeRetention
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Chunk.Outside
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Chunk.execution
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Chunk.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Chunk.execution._proof_1_10
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Chunk.execution._proof_1_11
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Chunk.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Chunk.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Chunk.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Chunk.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Chunk.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Chunk.execution._proof_1_7
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Chunk.execution._proof_1_8
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Chunk.execution._proof_1_9
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Height.Outside
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Height.execution
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Height.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Height.execution._proof_1_10
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Height.execution._proof_1_11
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Height.execution._proof_1_12
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Height.execution._proof_1_13
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Height.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Height.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Height.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Height.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Height.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Height.execution._proof_1_7
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Height.execution._proof_1_8
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Height.execution._proof_1_9
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Rank.Outside
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Rank.execution
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Rank.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Rank.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Rank.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Rank.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Rank.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Rank.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformSeedEdgeRetention.Rank.execution._proof_1_7
