import UniformJointInversePackingPreparation
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformJointInversePackingPreparation.addresses
#print axioms ExactFourierCircuits.UniformJointInversePackingPreparation.layout
#print axioms ExactFourierCircuits.UniformJointInversePackingPreparation.layout._proof_1
#print axioms ExactFourierCircuits.UniformJointInversePackingPreparation.layout._proof_2
#print axioms ExactFourierCircuits.UniformJointInversePackingPreparation.layout._proof_3
#print axioms ExactFourierCircuits.UniformJointInversePackingPreparation.layout._proof_4
#print axioms ExactFourierCircuits.UniformJointInversePackingPreparation.preparation
#print axioms ExactFourierCircuits.UniformJointInversePackingPreparation.preparation._proof_1
#print axioms ExactFourierCircuits.UniformJointInversePackingPreparation.preparation._proof_2
#print axioms ExactFourierCircuits.UniformJointInversePackingPreparation.preparation._proof_3
#print axioms ExactFourierCircuits.UniformJointInversePackingPreparation.preparation._proof_4
#print axioms ExactFourierCircuits.UniformJointInversePackingPreparation.preparation._proof_5
#print axioms ExactFourierCircuits.UniformJointInversePackingPreparation.preparation._proof_6
