import UniformRecursiveResidualGatherFrame
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._proof_1_10
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._proof_1_11
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._proof_1_12
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._proof_1_13
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._proof_1_14
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._proof_1_15
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._proof_1_16
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._proof_1_17
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._proof_1_18
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._proof_1_19
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._proof_1_20
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._proof_1_21
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._proof_1_22
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._proof_1_26
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._proof_1_27
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._proof_1_28
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._proof_1_29
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._proof_1_3
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._proof_1_30
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._proof_1_4
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._proof_1_5
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._proof_1_6
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._proof_1_7
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._proof_1_8
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._proof_1_9
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._simp_1_24
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.execution_frame._simp_1_25
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.gather_preserves_direction
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.gather_preserves_direction._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.gather_preserves_direction._simp_1_2
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.gather_preserves_direction._simp_1_3
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.gather_preserves_table
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.gather_preserves_table._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.gather_preserves_table._simp_1_2
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.gather_preserves_table._simp_1_3
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.keptRegisters
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.keptRegisters.eq_1
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.reader_avoids
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.reader_avoids._simp_1_2
#print axioms ExactFourierCircuits.UniformRecursiveResidualGatherFrame.reader_avoids._simp_1_3
