import UniformGlobalCalendarDispatchRouting
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.Decoded
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.Decoded._proof_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.Decoded._proof_2
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.Decoded._proof_3
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.Header.atPC
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.Loaded.atPC
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.PhaseEntry
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.PhaseEntry.match_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.control
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.prefix_execution
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.prefix_execution._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.route_execution
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.route_execution._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.route_execution._proof_1_10
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.route_execution._proof_1_11
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.route_execution._proof_1_12
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.route_execution._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.route_execution._proof_1_3
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.route_execution._proof_1_4
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.route_execution._proof_1_5
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.route_execution._proof_1_6
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.route_execution._proof_1_8
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.route_execution._proof_1_9
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.scaleLiteral
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.scaleLiteral.eq_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.scaleLiteral_code
#print axioms ExactFourierCircuits.UniformGlobalCalendarDispatch.scaleLiteral_code._proof_1_1
