import UniformLayeredReplay
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformLayeredReplay.LevelSafe
#print axioms ExactFourierCircuits.UniformLayeredReplay.OnLevel
#print axioms ExactFourierCircuits.UniformLayeredReplay.OnLevel.safe
#print axioms ExactFourierCircuits.UniformLayeredReplay.OnLevel.safe._proof_1_1
#print axioms ExactFourierCircuits.UniformLayeredReplay.colorOrdered
#print axioms ExactFourierCircuits.UniformLayeredReplay.colorOrdered.eq_1
#print axioms ExactFourierCircuits.UniformLayeredReplay.colorOrdered_action
#print axioms ExactFourierCircuits.UniformLayeredReplay.colorOrdered_perm
#print axioms ExactFourierCircuits.UniformLayeredReplay.degree_of_level
#print axioms ExactFourierCircuits.UniformLayeredReplay.degree_of_level._proof_1_3
#print axioms ExactFourierCircuits.UniformLayeredReplay.degree_of_level._simp_1_1
#print axioms ExactFourierCircuits.UniformLayeredReplay.degree_of_level._simp_1_2
#print axioms ExactFourierCircuits.UniformLayeredReplay.destinationUses
#print axioms ExactFourierCircuits.UniformLayeredReplay.layerOrder
#print axioms ExactFourierCircuits.UniformLayeredReplay.layerOrder_nodup
#print axioms ExactFourierCircuits.UniformLayeredReplay.layerOrder_perm
#print axioms ExactFourierCircuits.UniformLayeredReplay.mem_layerOrder
#print axioms ExactFourierCircuits.UniformLayeredReplay.run_perm
#print axioms ExactFourierCircuits.UniformLayeredReplay.safe_perm
#print axioms ExactFourierCircuits.UniformLayeredReplay.shear_commute
#print axioms ExactFourierCircuits.UniformLayeredReplay.sourceUses
