import UniformKernelSpectrumStorage
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.alphaBase
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.arena_before
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.arena_before._proof_1_1
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.arena_fit
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.arena_fit._proof_1_1
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.base
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.betaInverseBase
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.boundary_before
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.boundary_before._proof_1_1
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.caches_before
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.cell_below_source
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.cell_below_source._proof_1_1
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.end_eq
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.end_eq._proof_1_1
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.merged_before
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.merged_before._proof_1_1
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.merged_before._proof_1_2
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.nat_arena_before
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.nat_arena_before._proof_1_1
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.nat_arena_fit
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.nat_arena_fit._proof_1_1
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.nat_caches_before
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.nat_merged_before
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.nat_merged_before._proof_1_1
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.reserve
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.reserve._proof_1_1
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.reserve._proof_1_2
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.reserve._proof_1_3
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.reserve._proof_1_4
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.tables_adjacent
#print axioms ExactFourierCircuits.UniformKernelSpectrumStorage.tables_adjacent._proof_1_1
