import UniformCacheLowAxisExecution
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformAxisCacheAxisExecution.execution_low
#print axioms ExactFourierCircuits.UniformAxisCacheAxisExecution.execution_low._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheAxisExecution.execution_low._proof_1_2
#print axioms ExactFourierCircuits.UniformAxisCacheAxisExecution.execution_low._proof_1_3
