import UniformNormalizationMachine
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformNormalizationMachine.Frame
#print axioms ExactFourierCircuits.UniformNormalizationMachine.entry
#print axioms ExactFourierCircuits.UniformNormalizationMachine.entry.eq_1
#print axioms ExactFourierCircuits.UniformNormalizationMachine.head
#print axioms ExactFourierCircuits.UniformNormalizationMachine.head.eq_1
#print axioms ExactFourierCircuits.UniformNormalizationMachine.normalization_execution
#print axioms ExactFourierCircuits.UniformNormalizationMachine.normalization_execution._proof_1_1
#print axioms ExactFourierCircuits.UniformNormalizationMachine.normalization_execution._proof_1_10
#print axioms ExactFourierCircuits.UniformNormalizationMachine.normalization_execution._proof_1_11
#print axioms ExactFourierCircuits.UniformNormalizationMachine.normalization_execution._proof_1_12
#print axioms ExactFourierCircuits.UniformNormalizationMachine.normalization_execution._proof_1_13
#print axioms ExactFourierCircuits.UniformNormalizationMachine.normalization_execution._proof_1_18
#print axioms ExactFourierCircuits.UniformNormalizationMachine.normalization_execution._proof_1_19
#print axioms ExactFourierCircuits.UniformNormalizationMachine.normalization_execution._proof_1_2
#print axioms ExactFourierCircuits.UniformNormalizationMachine.normalization_execution._proof_1_20
#print axioms ExactFourierCircuits.UniformNormalizationMachine.normalization_execution._proof_1_21
#print axioms ExactFourierCircuits.UniformNormalizationMachine.normalization_execution._proof_1_7
#print axioms ExactFourierCircuits.UniformNormalizationMachine.normalization_execution._proof_1_8
#print axioms ExactFourierCircuits.UniformNormalizationMachine.normalization_execution._proof_1_9
#print axioms ExactFourierCircuits.UniformNormalizationMachine.numerator
#print axioms ExactFourierCircuits.UniformNormalizationMachine.numerator.eq_1
#print axioms ExactFourierCircuits.UniformNormalizationMachine.program
#print axioms ExactFourierCircuits.UniformNormalizationMachine.program.eq_1
#print axioms ExactFourierCircuits.UniformNormalizationMachine.program_length
#print axioms ExactFourierCircuits.UniformNormalizationMachine.rational_code
#print axioms ExactFourierCircuits.UniformNormalizationMachine.runtime
#print axioms ExactFourierCircuits.UniformNormalizationMachine.runtime.eq_1
#print axioms ExactFourierCircuits.UniformNormalizationMachine.runtime_log_bound
#print axioms ExactFourierCircuits.UniformNormalizationMachine.runtime_log_bound._proof_1_2
#print axioms ExactFourierCircuits.UniformNormalizationMachine.saved
#print axioms ExactFourierCircuits.UniformNormalizationMachine.saved.eq_1
#print axioms ExactFourierCircuits.UniformNormalizationMachine.startup_runs
#print axioms ExactFourierCircuits.UniformNormalizationMachine.startup_runs._proof_1_1
#print axioms ExactFourierCircuits.UniformNormalizationMachine.startup_runs._proof_1_2
#print axioms ExactFourierCircuits.UniformNormalizationMachine.startup_runs._proof_1_4
#print axioms ExactFourierCircuits.UniformNormalizationMachine.startup_runs._proof_1_6
#print axioms ExactFourierCircuits.UniformNormalizationMachine.startup_runs._proof_1_7
#print axioms ExactFourierCircuits.UniformNormalizationMachine.startup_runs._proof_1_9
#print axioms ExactFourierCircuits.UniformNormalizationMachine.stored
#print axioms ExactFourierCircuits.UniformNormalizationMachine.stored.eq_1
#print axioms ExactFourierCircuits.UniformNormalizationMachine.stored_bound
#print axioms ExactFourierCircuits.UniformNormalizationMachine.zeroed
#print axioms ExactFourierCircuits.UniformNormalizationMachine.zeroed.eq_1
