import UniformAllAxisSeedCost
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformAllAxisSeedCost.budget_axis_power
#print axioms ExactFourierCircuits.UniformAllAxisSeedCost.budget_axis_power._proof_1_1
#print axioms ExactFourierCircuits.UniformAllAxisSeedCost.budget_axis_power._proof_1_2
#print axioms ExactFourierCircuits.UniformAllAxisSeedCost.budget_axis_power._proof_1_3
#print axioms ExactFourierCircuits.UniformAllAxisSeedCost.budget_axis_power._proof_1_4
#print axioms ExactFourierCircuits.UniformAllAxisSeedCost.budget_axis_power._proof_1_5
#print axioms ExactFourierCircuits.UniformAllAxisSeedCost.budget_isBigO_axis_five
#print axioms ExactFourierCircuits.UniformAllAxisSeedCost.budget_isBigO_axis_five._proof_1_1
#print axioms ExactFourierCircuits.UniformAllAxisSeedCost.budget_isBigO_log_five
#print axioms ExactFourierCircuits.UniformAllAxisSeedCost.budget_isLittleO_input
#print axioms ExactFourierCircuits.UniformAllAxisSeedCost.fullBudget_isBigO_input
#print axioms ExactFourierCircuits.UniformAllAxisSeedCost.initialTraversalBudget_isBigO_input
#print axioms ExactFourierCircuits.UniformAllAxisSeedCost.runtime_isLittleO_input
#print axioms ExactFourierCircuits.UniformAllAxisSeedCost.workingLength_isBigO_input
#print axioms ExactFourierCircuits.UniformAllAxisSeedCost.workingLength_isBigO_input._proof_1_1
#print axioms ExactFourierCircuits.UniformAllAxisSeedPreparation.fullBudget.eq_1
#print axioms ExactFourierCircuits.UniformInitialTraversalPreparation.preparationBudget.eq_1
