import UniformAxisCacheCallerInstaller
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.Frame
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.Frame.casesOn
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.Frame.mk
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.Frame.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.Frame.natHeap
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.Frame.outputs
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.Frame.rec
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.Frame.recOn
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.Frame.registers
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.Frame.rootOrders
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.Frame.scalarHeap
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.Frame.scalarReg
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.Installed
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.Installed.allocation
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.Installed.casesOn
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.Installed.forest
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.Installed.mk
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.Installed.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.Installed.rec
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.Installed.recOn
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.Installed.timing
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.destinations
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.destinations.eq_1
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.execution
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.forestOps
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.forestOps.eq_1
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.frame
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.frame._simp_1_2
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.frame._simp_1_3
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.frame._simp_1_4
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.halt_at
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.installed
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.nine
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.ops
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.ops.eq_1
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.ops_code
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.ops_length
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.program
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.program_length
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.safe
#print axioms ExactFourierCircuits.UniformAxisCacheCallerInstaller.safe._proof_1_3
