import UniformGlobalCalendarSelected
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.mem_selected
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.mem_selected._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.mem_selected._proof_1_3
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.mem_selected._proof_1_4
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.mem_selected._proof_1_5
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.mem_selected._proof_1_6
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.mem_selected._proof_1_7
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.mem_selected._proof_1_8
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.mem_selected._simp_1_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.writeSelections_get
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.writeSelections_get._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.writeSelections_get._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.writeSelections_get._proof_1_3
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.writeSelections_get._proof_1_4
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.writeSelections_get._proof_1_5
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.writeSelections_get._proof_1_6
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.writeSelections_low
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.writeSelections_low._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.writeSelections_low._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalCalendarSelector.writeSelections_low._proof_1_3
