import UniformPhysicalCRTConsumerMachine
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.Frame
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.Frame.beforePC
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.Frame.casesOn
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.Frame.mk
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.Frame.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.Frame.natHeap
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.Frame.natReg
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.Frame.outputs
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.Frame.permutation
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.Frame.permutation._proof_1_1
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.Frame.permutation._proof_1_2
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.Frame.rec
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.Frame.recOn
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.Frame.roots
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.Frame.scalarReg
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.Frame.trans
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.Frame.withPC
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.Protected
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.alphaProgram
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.alphaProgram_length
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.alphaSetup
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.alphaSetup.eq_1
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.alpha_code
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.alpha_execution
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.alpha_execution._proof_1_1
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.alpha_execution._proof_1_10
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.alpha_execution._proof_1_6
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.alpha_execution._proof_1_7
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.alpha_execution._proof_1_8
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.alpha_execution._proof_1_9
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.alpha_frame
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.alpha_frame._proof_1_10
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.alpha_frame._proof_1_11
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.alpha_frame._proof_1_12
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.alpha_frame._proof_1_5
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.alpha_frame._proof_1_6
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.alpha_frame._proof_1_7
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.alpha_frame._proof_1_8
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.alpha_frame._proof_1_9
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.alpha_halt_at
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.alpha_peak
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.alpha_regs
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.alpha_setup_code
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.block_pc
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.block_pc._proof_1_4
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.execution
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.execution._proof_1_10
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.execution._proof_1_11
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.execution._proof_1_12
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.execution._proof_1_13
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.execution._proof_1_14
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.execution._proof_1_15
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.execution._proof_1_17
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.execution._proof_1_18
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.execution._proof_1_19
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.execution._proof_1_20
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.execution._proof_1_21
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.execution._proof_1_7
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.execution._proof_1_8
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.execution._proof_1_9
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.firstSetup
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.firstSetup.eq_1
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.first_code
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.first_frame
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.first_frame._proof_1_10
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.first_frame._proof_1_11
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.first_frame._proof_1_12
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.first_frame._proof_1_5
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.first_frame._proof_1_6
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.first_frame._proof_1_7
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.first_frame._proof_1_8
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.first_frame._proof_1_9
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.first_peak
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.first_regs
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.first_setup_code
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.halt_at
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.program
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.program_length
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.secondSetup
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.secondSetup.eq_1
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.second_code
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.second_frame
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.second_frame._proof_1_10
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.second_frame._proof_1_11
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.second_frame._proof_1_12
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.second_frame._proof_1_5
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.second_frame._proof_1_6
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.second_frame._proof_1_7
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.second_frame._proof_1_8
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.second_frame._proof_1_9
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.second_peak
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.second_regs
#print axioms ExactFourierCircuits.UniformPhysicalCRTConsumerMachine.second_setup_code

open Lean Elab Command in
run_cmd do
 let env ← getEnv
 for (name, _) in env.constants.toList do
  if "_private.UniformPhysicalCRTConsumerMachine.".isPrefixOf name.toString then
   let axs ← collectAxioms name
   logInfo m!"{name} depends on axioms: {axs.toList}"
