import UniformNativeTensorCoordinates
import Lean
set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformNativeTensorCoordinates.address_div_supra
#print axioms ExactFourierCircuits.UniformNativeTensorCoordinates.address_mod_dvd
#print axioms ExactFourierCircuits.UniformNativeTensorCoordinates.axisTransform_digits
#print axioms ExactFourierCircuits.UniformNativeTensorCoordinates.decoded_address_other
#print axioms ExactFourierCircuits.UniformNativeTensorCoordinates.decoded_address_other._proof_1_1
#print axioms ExactFourierCircuits.UniformNativeTensorCoordinates.decoded_address_other._proof_1_2
#print axioms ExactFourierCircuits.UniformNativeTensorCoordinates.ordinal_native_digit
#print axioms ExactFourierCircuits.UniformNativeTensorCoordinates.ordinal_native_replace
#print axioms ExactFourierCircuits.UniformNativeTensorCoordinates.ordinal_native_update
