import UniformHighDataConjugateMatchingPreparation
import Lean
set_option linter.auxLemma false
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.FullAction
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.LogicalPairs
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.M
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.execution
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.halt_at
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.halt_at._proof_1_1
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.logicalCoefficient
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.logicalCoefficient._proof_1
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.logicalCoefficient.eq_1
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.matched_full_action
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.matched_logical_pairs
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.matched_logical_pairs._proof_1_1
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.matching_arguments_transport
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.matching_arguments_transport._proof_1_1
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.matching_code
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.packing_code
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.pairLeft
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.pairLeft._proof_1
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.pairLeft._proof_2
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.pairLeft.eq_1
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.pairRight
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.pairRight._proof_1
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.pairRight._proof_2
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.pairRight.eq_1
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.program
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.program.eq_1
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.program_length
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.selected_count
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.spectrum_arguments_transport
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.spectrum_arguments_transport._proof_1_1
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.spectrum_arguments_transport._proof_1_10
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.spectrum_arguments_transport._proof_1_11
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.spectrum_arguments_transport._proof_1_12
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.spectrum_arguments_transport._proof_1_13
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.spectrum_arguments_transport._proof_1_14
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.spectrum_arguments_transport._proof_1_15
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.spectrum_arguments_transport._proof_1_16
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.spectrum_arguments_transport._proof_1_17
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.spectrum_arguments_transport._proof_1_18
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.spectrum_arguments_transport._proof_1_19
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.spectrum_arguments_transport._proof_1_2
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.spectrum_arguments_transport._proof_1_20
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.spectrum_arguments_transport._proof_1_21
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.spectrum_arguments_transport._proof_1_22
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.spectrum_arguments_transport._proof_1_5
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.spectrum_arguments_transport._proof_1_6
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.spectrum_arguments_transport._proof_1_7
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.spectrum_arguments_transport._proof_1_8
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.spectrum_arguments_transport._proof_1_9
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.spectrum_arguments_transport._simp_1_3
#print axioms ExactFourierCircuits.UniformHighDataConjugateMatchingPreparation.spectrum_arguments_transport._simp_1_4
open Lean Elab Command in
run_cmd do
 let env←getEnv
 for (name,_) in env.constants.toList do
  if "_private.UniformHighDataConjugateMatchingPreparation.".isPrefixOf name.toString then
   let axioms←collectAxioms name
   logInfo m!"'{name}' depends on axioms: {axioms.toList}"
   for ax in axioms do
    unless ax == `propext || ax == `Quot.sound || ax == `Classical.choice do
     throwError m!"Forbidden axiom {ax} in {name}"
