import UniformActualCacheRectangleSource
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformActualCacheRectangleSource.ListedSource
#print axioms ExactFourierCircuits.UniformActualCacheRectangleSource.S.Source
#print axioms ExactFourierCircuits.UniformActualCacheRectangleSource.append_source
#print axioms ExactFourierCircuits.UniformActualCacheRectangleSource.append_source._proof_1_1
#print axioms ExactFourierCircuits.UniformActualCacheRectangleSource.append_source._proof_1_2
#print axioms ExactFourierCircuits.UniformActualCacheRectangleSource.append_source._proof_1_3
#print axioms ExactFourierCircuits.UniformActualCacheRectangleSource.block
#print axioms ExactFourierCircuits.UniformActualCacheRectangleSource.block.eq_1
#print axioms ExactFourierCircuits.UniformActualCacheRectangleSource.block_length
#print axioms ExactFourierCircuits.UniformActualCacheRectangleSource.block_values
#print axioms ExactFourierCircuits.UniformActualCacheRectangleSource.block_values._proof_1_1
#print axioms ExactFourierCircuits.UniformActualCacheRectangleSource.block_values._proof_1_2
#print axioms ExactFourierCircuits.UniformActualCacheRectangleSource.blocks_source
#print axioms ExactFourierCircuits.UniformActualCacheRectangleSource.blocks_source._proof_1_2
#print axioms ExactFourierCircuits.UniformActualCacheRectangleSource.complete_cells
#print axioms ExactFourierCircuits.UniformActualCacheRectangleSource.entries
#print axioms ExactFourierCircuits.UniformActualCacheRectangleSource.entries.eq_1
#print axioms ExactFourierCircuits.UniformActualCacheRectangleSource.entries_length
#print axioms ExactFourierCircuits.UniformActualCacheRectangleSource.listed_source
#print axioms ExactFourierCircuits.UniformActualCacheRectangleSource.records
#print axioms ExactFourierCircuits.UniformActualCacheRectangleSource.records.eq_1
#print axioms ExactFourierCircuits.UniformActualCacheRectangleSource.rectangle_source
#print axioms ExactFourierCircuits.UniformActualCacheRectangleSource.rectangle_values
