import UniformLocalCacheTimingInitialization
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformLocalCacheTimingInitialization.Addresses
#print axioms ExactFourierCircuits.UniformLocalCacheTimingInitialization.Addresses.casesOn
#print axioms ExactFourierCircuits.UniformLocalCacheTimingInitialization.Addresses.durations
#print axioms ExactFourierCircuits.UniformLocalCacheTimingInitialization.Addresses.mk
#print axioms ExactFourierCircuits.UniformLocalCacheTimingInitialization.Addresses.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformLocalCacheTimingInitialization.Addresses.nodes
#print axioms ExactFourierCircuits.UniformLocalCacheTimingInitialization.Addresses.produced
#print axioms ExactFourierCircuits.UniformLocalCacheTimingInitialization.Addresses.produced._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalCacheTimingInitialization.Addresses.produced._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalCacheTimingInitialization.Addresses.produced._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalCacheTimingInitialization.Addresses.produced._proof_1_4
#print axioms ExactFourierCircuits.UniformLocalCacheTimingInitialization.Addresses.produced._proof_1_5
#print axioms ExactFourierCircuits.UniformLocalCacheTimingInitialization.Addresses.rec
#print axioms ExactFourierCircuits.UniformLocalCacheTimingInitialization.Addresses.recOn
#print axioms ExactFourierCircuits.UniformLocalCacheTimingInitialization.Addresses.requestStarts
#print axioms ExactFourierCircuits.UniformLocalCacheTimingInitialization.Addresses.requests
#print axioms ExactFourierCircuits.UniformLocalCacheTimingInitialization.Addresses.starts
#print axioms ExactFourierCircuits.UniformLocalCacheTimingInitialization.Addresses.withPC
#print axioms ExactFourierCircuits.UniformLocalCacheTimingInitialization.initialize_from_printed
#print axioms ExactFourierCircuits.UniformLocalCacheTimingInitialization.producer_initial_bank
