import UniformRecursiveTypedCostAllowance
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformRecursiveLocalAllowance.recordAllowance.eq_1
#print axioms ExactFourierCircuits.UniformRecursiveTypedCostAllowance.chargedTicks
#print axioms ExactFourierCircuits.UniformRecursiveTypedCostAllowance.chargedTicks._sparseCasesOn_1
#print axioms ExactFourierCircuits.UniformRecursiveTypedCostAllowance.chargedTicks.match_1
#print axioms ExactFourierCircuits.UniformRecursiveTypedCostAllowance.charged_nonpadding
#print axioms ExactFourierCircuits.UniformRecursiveTypedCostAllowance.charged_padding
#print axioms ExactFourierCircuits.UniformRecursiveTypedCostAllowance.core_padding_bound
#print axioms ExactFourierCircuits.UniformRecursiveTypedCostAllowance.core_padding_of_inventory
#print axioms ExactFourierCircuits.UniformRecursiveTypedCostAllowance.exchange_pairs
#print axioms ExactFourierCircuits.UniformRecursiveTypedCostAllowance.exchange_pairs._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveTypedCostAllowance.instruction_bound
#print axioms ExactFourierCircuits.UniformRecursiveTypedCostAllowance.list_bound
#print axioms ExactFourierCircuits.UniformRecursiveTypedCostAllowance.m_pred
#print axioms ExactFourierCircuits.UniformRecursiveTypedCostAllowance.m_three
#print axioms ExactFourierCircuits.UniformRecursiveTypedCostAllowance.marker_for_record
#print axioms ExactFourierCircuits.UniformRecursiveTypedCostAllowance.opcode_lt
#print axioms ExactFourierCircuits.UniformRecursiveTypedCostAllowance.paddingTicks
#print axioms ExactFourierCircuits.UniformRecursiveTypedCostAllowance.padding_at_width
#print axioms ExactFourierCircuits.UniformRecursiveTypedCostAllowance.padding_for_record
#print axioms ExactFourierCircuits.UniformRecursiveTypedCostAllowance.padding_named
#print axioms ExactFourierCircuits.UniformRecursiveTypedCostAllowance.sum_append_one
#print axioms ExactFourierCircuits.UniformRecursiveTypedCostAllowance.sum_map_bound
#print axioms ExactFourierCircuits.UniformRecursiveTypedCostAllowance.translation_rows
#print axioms ExactFourierCircuits.UniformRecursiveTypedCostAllowance.translation_rows._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveTypedCostAllowance.translation_rows._proof_1_2
