import UniformSeedConjugatePreservation
import Lean
set_option linter.auxLemma false
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Chunk.execution
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Chunk.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Chunk.execution._proof_1_10
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Chunk.execution._proof_1_11
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Chunk.execution._proof_1_12
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Chunk.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Chunk.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Chunk.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Chunk.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Chunk.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Chunk.execution._proof_1_7
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Chunk.execution._proof_1_8
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Chunk.execution._proof_1_9
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Fresh
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Fresh.casesOn
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Fresh.constants
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Fresh.convolution
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Fresh.depth
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Fresh.directory
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Fresh.fft
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Fresh.kernels
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Fresh.mk
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Fresh.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Fresh.negative
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Fresh.order
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Fresh.positive
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Fresh.rec
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Fresh.recOn
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Fresh.row
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Fresh.tape
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Height.execution
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Height.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Height.execution._proof_1_10
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Height.execution._proof_1_11
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Height.execution._proof_1_12
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Height.execution._proof_1_13
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Height.execution._proof_1_14
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Height.execution._proof_1_15
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Height.execution._proof_1_16
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Height.execution._proof_1_17
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Height.execution._proof_1_18
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Height.execution._proof_1_19
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Height.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Height.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Height.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Height.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Height.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Height.execution._proof_1_7
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Height.execution._proof_1_8
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Height.execution._proof_1_9
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.PrefixFrame
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.PrefixFrame.casesOn
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.PrefixFrame.conjugate
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.PrefixFrame.conjugate._proof_1_1
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.PrefixFrame.conjugate._proof_1_2
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.PrefixFrame.mk
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.PrefixFrame.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.PrefixFrame.nat
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.PrefixFrame.rec
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.PrefixFrame.recOn
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.PrefixFrame.scalar
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Rank.execution
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Rank.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Rank.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Rank.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Rank.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Rank.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Rank.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformSeedConjugatePreservation.Rank.execution._proof_1_7
open Lean Elab Command in
run_cmd do
 let env←getEnv
 for (name,_) in env.constants.toList do
  if "_private.UniformSeedConjugatePreservation.".isPrefixOf name.toString then
   let axioms←collectAxioms name
   logInfo m!"'{name}' depends on axioms: {axioms.toList}"
   for ax in axioms do
    unless ax == `propext || ax == `Quot.sound || ax == `Classical.choice do
     throwError m!"Forbidden axiom {ax} in {name}"
