import UniformRecursiveNativeEntries
import Lean

-- Inventory uses defining-module provenance, including generated/private names.
set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformRecursiveNativeEntries.UniformFixedNetworkMarkerMachine.embedded
#print axioms ExactFourierCircuits.UniformRecursiveNativeEntries.UniformFixedNetworkMarkerMachine.embedded._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveNativeEntries.UniformFixedNetworkMarkerMachine.entry
#print axioms ExactFourierCircuits.UniformRecursiveNativeEntries.UniformNativeExchangeRecordMachine.embedded
#print axioms ExactFourierCircuits.UniformRecursiveNativeEntries.UniformNativeExchangeRecordMachine.embedded._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveNativeEntries.UniformNativeExchangeRecordMachine.entry
#print axioms ExactFourierCircuits.UniformRecursiveNativeEntries.UniformNativeScalarRecordMachine.embedded
#print axioms ExactFourierCircuits.UniformRecursiveNativeEntries.UniformNativeScalarRecordMachine.embedded._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveNativeEntries.UniformNativeScalarRecordMachine.entry
#print axioms ExactFourierCircuits.UniformRecursiveNativeEntries.UniformNativeYRecordMachine.embedded
#print axioms ExactFourierCircuits.UniformRecursiveNativeEntries.UniformNativeYRecordMachine.embedded._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveNativeEntries.UniformNativeYRecordMachine.entry
