import UniformReplayPrint
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient._sizeOf_1
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient._sizeOf_inst
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient.casesOn
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient.ctorElim
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient.ctorElimType
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient.ctorIdx
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient.eval
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient.eval.eq_1
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient.eval.eq_2
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient.eval_negate
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient.negate
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient.negate.eq_1
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient.negate.eq_2
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient.noConfusion
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient.noConfusionType
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient.prepared
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient.prepared.elim
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient.prepared.inj
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient.prepared.injEq
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient.prepared.noConfusion
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient.prepared.sizeOf_spec
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient.rational
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient.rational.elim
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient.rational.inj
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient.rational.injEq
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient.rational.noConfusion
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient.rational.sizeOf_spec
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient.rec
#print axioms ExactFourierCircuits.UniformReplayPrint.Coefficient.recOn
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate._sizeOf_1
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate._sizeOf_inst
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.add
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.add.elim
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.add.inj
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.add.injEq
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.add.noConfusion
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.add.sizeOf_spec
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.casesOn
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.ctorElim
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.ctorElimType
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.ctorIdx
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.eval
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.eval.eq_1
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.eval.eq_2
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.eval.eq_3
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.eval.match_1
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.noConfusion
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.noConfusionType
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.rec
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.recOn
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.scale
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.scale.elim
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.scale.inj
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.scale.injEq
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.scale.noConfusion
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.scale.sizeOf_spec
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.sub
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.sub.elim
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.sub.inj
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.sub.injEq
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.sub.noConfusion
#print axioms ExactFourierCircuits.UniformReplayPrint.Gate.sub.sizeOf_spec
#print axioms ExactFourierCircuits.UniformReplayPrint.Program
#print axioms ExactFourierCircuits.UniformReplayPrint.Program._sizeOf_1
#print axioms ExactFourierCircuits.UniformReplayPrint.Program._sizeOf_inst
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.below
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.brecOn
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.brecOn.eq
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.brecOn.go
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.casesOn
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.ctorElim
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.ctorElimType
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.ctorIdx
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.eval
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.eval._f
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.eval._sunfold
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.eval.match_1
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.memorySweep
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.memorySweep._proof_1
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.memorySweep._proof_2
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.memorySweep.eq_1
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.memorySweep_length
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.memorySweep_spec
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.nil
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.nil.elim
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.nil.sizeOf_spec
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.noConfusion
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.noConfusionType
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.rec
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.recOn
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.step
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.step.elim
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.step.inj
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.step.injEq
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.step.noConfusion
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.step.sizeOf_spec
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.sweep
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.sweep._f
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.sweep._proof_1
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.sweep._proof_2
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.sweep._proof_3
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.sweep._proof_4
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.sweep._proof_5
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.sweep._sunfold
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.sweep._unsafe_rec
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.sweep.congr_simp
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.sweep.eq_1
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.sweep.eq_2
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.sweep.eq_def
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.sweep.match_1
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.sweep_length
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.sweep_length._proof_1_4
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.sweep_length._proof_1_5
#print axioms ExactFourierCircuits.UniformReplayPrint.Program.sweep_spec
#print axioms ExactFourierCircuits.UniformReplayPrint.ShearCode
#print axioms ExactFourierCircuits.UniformReplayPrint.ShearCode._sizeOf_1
#print axioms ExactFourierCircuits.UniformReplayPrint.ShearCode._sizeOf_inst
#print axioms ExactFourierCircuits.UniformReplayPrint.ShearCode.casesOn
#print axioms ExactFourierCircuits.UniformReplayPrint.ShearCode.coefficient
#print axioms ExactFourierCircuits.UniformReplayPrint.ShearCode.ctorIdx
#print axioms ExactFourierCircuits.UniformReplayPrint.ShearCode.different
#print axioms ExactFourierCircuits.UniformReplayPrint.ShearCode.dst
#print axioms ExactFourierCircuits.UniformReplayPrint.ShearCode.eval
#print axioms ExactFourierCircuits.UniformReplayPrint.ShearCode.eval.eq_1
#print axioms ExactFourierCircuits.UniformReplayPrint.ShearCode.eval_inverse
#print axioms ExactFourierCircuits.UniformReplayPrint.ShearCode.eval_sumInl
#print axioms ExactFourierCircuits.UniformReplayPrint.ShearCode.inverse
#print axioms ExactFourierCircuits.UniformReplayPrint.ShearCode.inverse.eq_1
#print axioms ExactFourierCircuits.UniformReplayPrint.ShearCode.mk
#print axioms ExactFourierCircuits.UniformReplayPrint.ShearCode.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformReplayPrint.ShearCode.mk.congr_simp
#print axioms ExactFourierCircuits.UniformReplayPrint.ShearCode.mk.inj
#print axioms ExactFourierCircuits.UniformReplayPrint.ShearCode.mk.injEq
#print axioms ExactFourierCircuits.UniformReplayPrint.ShearCode.mk.noConfusion
#print axioms ExactFourierCircuits.UniformReplayPrint.ShearCode.mk.sizeOf_spec
#print axioms ExactFourierCircuits.UniformReplayPrint.ShearCode.noConfusion
#print axioms ExactFourierCircuits.UniformReplayPrint.ShearCode.noConfusionType
#print axioms ExactFourierCircuits.UniformReplayPrint.ShearCode.rec
#print axioms ExactFourierCircuits.UniformReplayPrint.ShearCode.recOn
#print axioms ExactFourierCircuits.UniformReplayPrint.ShearCode.src
#print axioms ExactFourierCircuits.UniformReplayPrint.ShearCode.sumInl
#print axioms ExactFourierCircuits.UniformReplayPrint.ShearCode.sumInl._proof_1
#print axioms ExactFourierCircuits.UniformReplayPrint.broadcast
#print axioms ExactFourierCircuits.UniformReplayPrint.broadcast.eq_1
#print axioms ExactFourierCircuits.UniformReplayPrint.broadcastList
#print axioms ExactFourierCircuits.UniformReplayPrint.broadcastList._f
#print axioms ExactFourierCircuits.UniformReplayPrint.broadcastList._sunfold
#print axioms ExactFourierCircuits.UniformReplayPrint.broadcastList._unsafe_rec
#print axioms ExactFourierCircuits.UniformReplayPrint.broadcastList.eq_1
#print axioms ExactFourierCircuits.UniformReplayPrint.broadcastList.eq_2
#print axioms ExactFourierCircuits.UniformReplayPrint.broadcastList.eq_def
#print axioms ExactFourierCircuits.UniformReplayPrint.broadcastList.match_1
#print axioms ExactFourierCircuits.UniformReplayPrint.broadcastList_length
#print axioms ExactFourierCircuits.UniformReplayPrint.broadcastList_length._proof_1_4
#print axioms ExactFourierCircuits.UniformReplayPrint.broadcastList_spec
#print axioms ExactFourierCircuits.UniformReplayPrint.broadcastList_spec._simp_1_4
#print axioms ExactFourierCircuits.UniformReplayPrint.broadcastOne
#print axioms ExactFourierCircuits.UniformReplayPrint.broadcastOne._proof_1
#print axioms ExactFourierCircuits.UniformReplayPrint.broadcastOne.eq_1
#print axioms ExactFourierCircuits.UniformReplayPrint.broadcastOne.match_1
#print axioms ExactFourierCircuits.UniformReplayPrint.broadcastOne_length
#print axioms ExactFourierCircuits.UniformReplayPrint.broadcastOne_spec
#print axioms ExactFourierCircuits.UniformReplayPrint.broadcast_length
#print axioms ExactFourierCircuits.UniformReplayPrint.broadcast_spec
#print axioms ExactFourierCircuits.UniformReplayPrint.gateCode
#print axioms ExactFourierCircuits.UniformReplayPrint.gateCode.congr_simp
#print axioms ExactFourierCircuits.UniformReplayPrint.gateCode.eq_1
#print axioms ExactFourierCircuits.UniformReplayPrint.gateCode.eq_2
#print axioms ExactFourierCircuits.UniformReplayPrint.gateCode.eq_3
#print axioms ExactFourierCircuits.UniformReplayPrint.gateCode_length
#print axioms ExactFourierCircuits.UniformReplayPrint.gateCode_length._proof_1_7
#print axioms ExactFourierCircuits.UniformReplayPrint.gateCode_spec
#print axioms ExactFourierCircuits.UniformReplayPrint.instDecidableEqCoefficient
#print axioms ExactFourierCircuits.UniformReplayPrint.instDecidableEqCoefficient.decEq
#print axioms ExactFourierCircuits.UniformReplayPrint.instDecidableEqCoefficient.decEq._proof_1
#print axioms ExactFourierCircuits.UniformReplayPrint.instDecidableEqCoefficient.decEq._proof_2
#print axioms ExactFourierCircuits.UniformReplayPrint.instDecidableEqCoefficient.decEq._proof_3
#print axioms ExactFourierCircuits.UniformReplayPrint.instDecidableEqCoefficient.decEq._proof_4
#print axioms ExactFourierCircuits.UniformReplayPrint.instDecidableEqCoefficient.decEq._proof_5
#print axioms ExactFourierCircuits.UniformReplayPrint.instDecidableEqCoefficient.decEq._proof_6
#print axioms ExactFourierCircuits.UniformReplayPrint.instDecidableEqCoefficient.decEq._proof_7
#print axioms ExactFourierCircuits.UniformReplayPrint.instDecidableEqCoefficient.decEq.match_1
#print axioms ExactFourierCircuits.UniformReplayPrint.instReprCoefficient
#print axioms ExactFourierCircuits.UniformReplayPrint.instReprCoefficient.repr
#print axioms ExactFourierCircuits.UniformReplayPrint.instReprCoefficient.repr.match_1
#print axioms ExactFourierCircuits.UniformReplayPrint.reference
#print axioms ExactFourierCircuits.UniformReplayPrint.reference._proof_1
#print axioms ExactFourierCircuits.UniformReplayPrint.reference.congr_simp
#print axioms ExactFourierCircuits.UniformReplayPrint.reference.eq_1
#print axioms ExactFourierCircuits.UniformReplayPrint.reference.eq_2
#print axioms ExactFourierCircuits.UniformReplayPrint.reference.match_1
#print axioms ExactFourierCircuits.UniformReplayPrint.reference_length
#print axioms ExactFourierCircuits.UniformReplayPrint.reference_spec
#print axioms ExactFourierCircuits.UniformReplayPrint.replayCode
#print axioms ExactFourierCircuits.UniformReplayPrint.replayCode.eq_1
#print axioms ExactFourierCircuits.UniformReplayPrint.replayCode_length
#print axioms ExactFourierCircuits.UniformReplayPrint.replayCode_length._proof_1_2
#print axioms ExactFourierCircuits.UniformReplayPrint.replayCode_spec
#print axioms ExactFourierCircuits.UniformReplayPrint.reverseCode
#print axioms ExactFourierCircuits.UniformReplayPrint.reverseCode.eq_1
#print axioms ExactFourierCircuits.UniformReplayPrint.reverseCode_eval
#print axioms ExactFourierCircuits.UniformReplayPrint.reverseCode_length

open Lean Elab Command in
run_cmd do
 let env ← getEnv
 for (name, _) in env.constants.toList do
  if "_private.UniformReplayPrint.".isPrefixOf name.toString then
   let axs ← collectAxioms name
   logInfo m!"{name} depends on axioms: {axs.toList}"
