import UniformRecursiveBaseCallMachine
import Lean

-- Inventory uses defining-module provenance, including generated/private names.
set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformBinaryBatchCMachine.Changed.eq_1
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.batch_code
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.depth_bound
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.execution
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.execution._proof_1_10
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.execution._proof_1_11
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.execution._proof_1_12
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.execution._proof_1_13
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.execution._proof_1_14
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.execution._proof_1_15
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.execution._proof_1_16
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.execution._proof_1_17
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.execution._proof_1_19
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.execution._proof_1_21
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.execution._proof_1_22
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.execution._proof_1_23
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.execution._proof_1_24
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.execution._proof_1_25
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.execution._proof_1_26
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.execution._proof_1_27
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.execution._proof_1_7
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.execution._proof_1_8
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.frame_base_bound
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.frame_extent
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.halt_at
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.inc_code
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.increment
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.increment.eq_1
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.load_code
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.load_halt
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.popSetup
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.popSetup.eq_1
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.pop_code
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.pop_code._proof_1_4
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.preBatch_length
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.preLoad_length
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.preSave_length
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.prefix_length
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.product_bound
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.program
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.program.eq_1
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.program_length
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.pushSetup
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.pushSetup.eq_1
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.push_code
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.save_code
#print axioms ExactFourierCircuits.UniformRecursiveBaseCallMachine.save_halt
