import UniformScalarCopyDisjoint
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformScalarCopyMachine.execution_disjoint
#print axioms ExactFourierCircuits.UniformScalarCopyMachine.execution_disjoint._proof_1_1
#print axioms ExactFourierCircuits.UniformScalarCopyMachine.execution_disjoint._proof_1_2
#print axioms ExactFourierCircuits.UniformScalarCopyMachine.execution_disjoint._proof_1_3
#print axioms ExactFourierCircuits.UniformScalarCopyMachine.execution_disjoint._proof_1_4
#print axioms ExactFourierCircuits.UniformScalarCopyMachine.execution_disjoint._proof_1_5
#print axioms ExactFourierCircuits.UniformScalarCopyMachine.execution_disjoint._proof_1_6
#print axioms ExactFourierCircuits.UniformScalarCopyMachine.execution_disjoint._proof_1_7
#print axioms ExactFourierCircuits.UniformScalarCopyMachine.execution_disjoint._proof_1_8
#print axioms ExactFourierCircuits.UniformScalarCopyMachine.iteration_disjoint
#print axioms ExactFourierCircuits.UniformScalarCopyMachine.iteration_disjoint._proof_1_1
#print axioms ExactFourierCircuits.UniformScalarCopyMachine.iteration_disjoint._proof_1_10
#print axioms ExactFourierCircuits.UniformScalarCopyMachine.iteration_disjoint._proof_1_11
#print axioms ExactFourierCircuits.UniformScalarCopyMachine.iteration_disjoint._proof_1_12
#print axioms ExactFourierCircuits.UniformScalarCopyMachine.iteration_disjoint._proof_1_2
#print axioms ExactFourierCircuits.UniformScalarCopyMachine.iteration_disjoint._proof_1_3
#print axioms ExactFourierCircuits.UniformScalarCopyMachine.iteration_disjoint._proof_1_4
#print axioms ExactFourierCircuits.UniformScalarCopyMachine.iteration_disjoint._proof_1_5
#print axioms ExactFourierCircuits.UniformScalarCopyMachine.iteration_disjoint._proof_1_6
#print axioms ExactFourierCircuits.UniformScalarCopyMachine.iteration_disjoint._proof_1_7
#print axioms ExactFourierCircuits.UniformScalarCopyMachine.iteration_disjoint._proof_1_8
#print axioms ExactFourierCircuits.UniformScalarCopyMachine.iteration_disjoint._proof_1_9
#print axioms ExactFourierCircuits.UniformScalarCopyMachine.loop_disjoint
#print axioms ExactFourierCircuits.UniformScalarCopyMachine.loop_disjoint._proof_1_1
#print axioms ExactFourierCircuits.UniformScalarCopyMachine.loop_disjoint._proof_1_2
#print axioms ExactFourierCircuits.UniformScalarCopyMachine.loop_disjoint._proof_1_3
