import UniformAxisCacheForestSource
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.Source
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.Source.casesOn
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.Source.directory
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.Source.mk
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.Source.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.Source.printed
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.Source.rec
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.Source.recOn
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.Source.tables
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.directory_transport
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.directory_transport._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.directory_transport._proof_1_2
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.directory_transport._proof_1_3
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.of_ready
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.rectangle_bounds
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.rectangle_bounds._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.requests
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.requests._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.requests._proof_1_10
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.requests._proof_1_11
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.requests._proof_1_12
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.requests._proof_1_13
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.requests._proof_1_14
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.requests._proof_1_15
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.requests._proof_1_16
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.requests._proof_1_17
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.requests._proof_1_18
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.requests._proof_1_19
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.requests._proof_1_2
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.requests._proof_1_3
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.requests._proof_1_4
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.requests._proof_1_5
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.requests._proof_1_6
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.requests._proof_1_7
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.requests._proof_1_8
#print axioms ExactFourierCircuits.UniformAxisCacheForestSource.requests._proof_1_9
