import UniformLocalCacheContextExecution
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformLocalCacheContextMachine.execution
#print axioms ExactFourierCircuits.UniformLocalCacheContextMachine.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalCacheContextMachine.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalCacheContextMachine.final_heaps
#print axioms ExactFourierCircuits.UniformLocalCacheContextMachine.final_heaps._simp_1_1
#print axioms ExactFourierCircuits.UniformLocalCacheContextMachine.final_nat
#print axioms ExactFourierCircuits.UniformLocalCacheContextMachine.final_nat._proof_1_10
#print axioms ExactFourierCircuits.UniformLocalCacheContextMachine.final_nat._proof_1_4
#print axioms ExactFourierCircuits.UniformLocalCacheContextMachine.final_nat._proof_1_5
#print axioms ExactFourierCircuits.UniformLocalCacheContextMachine.final_nat._proof_1_6
#print axioms ExactFourierCircuits.UniformLocalCacheContextMachine.final_nat._proof_1_7
#print axioms ExactFourierCircuits.UniformLocalCacheContextMachine.final_nat._proof_1_8
#print axioms ExactFourierCircuits.UniformLocalCacheContextMachine.final_nat._proof_1_9
#print axioms ExactFourierCircuits.UniformLocalCacheContextMachine.final_nat._simp_1_1
#print axioms ExactFourierCircuits.UniformLocalCacheContextMachine.final_nat._simp_1_2
#print axioms ExactFourierCircuits.UniformLocalCacheContextMachine.final_nat._simp_1_3
#print axioms ExactFourierCircuits.UniformLocalCacheContextMachine.operations_safe
#print axioms ExactFourierCircuits.UniformLocalCacheContextMachine.operations_safe._simp_1_1
#print axioms ExactFourierCircuits.UniformLocalCacheContextMachine.peak_append
#print axioms ExactFourierCircuits.UniformLocalCacheContextMachine.readable_append
#print axioms ExactFourierCircuits.UniformLocalCacheContextMachine.readable_append._simp_1_1
#print axioms ExactFourierCircuits.UniformLocalCacheContextMachine.tail_heaps
#print axioms ExactFourierCircuits.UniformLocalCacheContextMachine.tail_safe
