import UniformLocalFactorDispatchExecution
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.BC.program.eq_1
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.FH.program.eq_1
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.IV.program.eq_1
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.execution
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.execution._proof_1_12
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.execution._proof_1_13
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.execution._proof_1_15
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.execution._proof_1_16
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.execution._proof_1_17
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.execution._proof_1_18
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.execution._proof_1_19
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.execution._proof_1_20
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.execution._proof_1_21
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.execution._proof_1_22
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.execution._proof_1_24
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.execution._proof_1_25
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.execution._proof_1_8
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.natEnd.eq_1
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.printedBase.eq_1
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.runtimeBudget.eq_1
