import UniformCalendarRenderMatching
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformCalendarRenderMatching.matching_tick
#print axioms ExactFourierCircuits.UniformCalendarRenderMatching.matching_tick._proof_1_1
#print axioms ExactFourierCircuits.UniformCalendarRenderMatching.matching_tick._proof_1_2
#print axioms ExactFourierCircuits.UniformCalendarRenderMatching.matching_tick._proof_1_3
#print axioms ExactFourierCircuits.UniformCalendarRenderMatching.matching_tick._proof_1_4
#print axioms ExactFourierCircuits.UniformCalendarRenderMatching.ordinary_tick
#print axioms ExactFourierCircuits.UniformCalendarRenderMatching.ordinary_tick._proof_1
#print axioms ExactFourierCircuits.UniformCalendarRenderMatching.ordinary_tick._proof_1_1
#print axioms ExactFourierCircuits.UniformCalendarRenderMatching.shearLayers_cons
