import UniformLocalFactorDispatchMachine
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.BC.program
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.FH.program
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.IV.program
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.all_relocate
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.beforeBroadcast
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.beforeBroadcast.eq_1
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.beforeBroadcast_length
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.beforeInverse
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.beforeInverse.eq_1
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.beforeInverseBody
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.beforeInverseBody.eq_1
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.beforeInverseBody_length
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.beforeInverse_length
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.boot
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.boot_code
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.boot_length
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.broadcast_branch
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.broadcast_code
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.broadcast_footprint
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.execution_nat
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.footprint_keeps
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.footprint_keeps._proof_1_7
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.forward_code
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.forward_footprint
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.halt_at
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.head
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.head.eq_1
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.head_length
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.inverseSetup
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.inverseSetup.eq_1
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.inverseSetup_code
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.inverse_branch
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.inverse_code
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.inverse_footprint
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.program
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.program.eq_1
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.program_keeps
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.program_keeps._proof_1_10
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.program_keeps._proof_1_11
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.program_keeps._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.program_keeps._proof_1_4
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.program_keeps._proof_1_5
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.program_keeps._proof_1_6
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.program_keeps._proof_1_7
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.program_keeps._proof_1_8
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.program_keeps._proof_1_9
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.program_keeps._simp_1_1
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.program_keeps._simp_1_2
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.program_length
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.protectedInstruction
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.protectedInstruction._sparseCasesOn_1
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.protectedInstruction._sparseCasesOn_1.else_eq
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.protectedInstruction.eq_1
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.protectedInstruction.eq_2
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.protectedInstruction.eq_3
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.protectedInstruction.eq_4
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.protectedInstruction.eq_5
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.protectedInstruction.match_1
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.protected_relocate

open Lean Elab Command in
run_cmd do
 let env ← getEnv
 for (name, _) in env.constants.toList do
  if "_private.UniformLocalFactorDispatchMachine.".isPrefixOf name.toString then
   let axs ← collectAxioms name
   logInfo m!"{name} depends on axioms: {axs.toList}"
