import UniformRecursivePreparedLargeChild
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformRecursiveLargeChild.execution_prepared
#print axioms ExactFourierCircuits.UniformRecursiveLargeChild.execution_prepared._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveLargeChild.execution_prepared._proof_1_2
