import UniformHighDataPackingPreparation
import Lean
set_option linter.auxLemma false
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.BankPlacement
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.BankPlacement.casesOn
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.BankPlacement.constants
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.BankPlacement.mk
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.BankPlacement.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.BankPlacement.negative
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.BankPlacement.of_matching
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.BankPlacement.of_matching._proof_1_1
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.BankPlacement.of_matching._proof_1_2
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.BankPlacement.of_matching._proof_1_3
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.BankPlacement.positive
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.BankPlacement.rec
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.BankPlacement.recOn
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.Frame
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.Frame.saved
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.Frame.saved._proof_1_1
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.Protected
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.RetentionPlacement
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.RetentionPlacement.casesOn
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.RetentionPlacement.conjugate
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.RetentionPlacement.directory
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.RetentionPlacement.mk
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.RetentionPlacement.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.RetentionPlacement.original
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.RetentionPlacement.rec
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.RetentionPlacement.recOn
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.canonical_execution
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.copy_code
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.execution
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.execution._proof_1_10
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.execution._proof_1_11
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.execution._proof_1_12
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.execution._proof_1_13
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.execution._proof_1_14
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.execution._proof_1_15
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.execution._proof_1_16
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.execution._proof_1_17
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.execution._proof_1_18
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.execution._proof_1_19
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.execution._proof_1_7
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.execution._proof_1_8
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.execution._proof_1_9
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.execution_retained
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.execution_retained._proof_1_1
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.execution_retained._proof_1_2
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.execution_retained._proof_1_3
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.execution_retained._proof_1_4
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.halt_at
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.halt_at._proof_1_1
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.packing_code
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.program
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.program.eq_1
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.program_length
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.seed_result_transport
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.seed_result_transport._proof_1_1
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.seed_result_transport._proof_1_10
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.seed_result_transport._proof_1_11
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.seed_result_transport._proof_1_12
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.seed_result_transport._proof_1_13
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.seed_result_transport._proof_1_14
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.seed_result_transport._proof_1_15
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.seed_result_transport._proof_1_16
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.seed_result_transport._proof_1_17
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.seed_result_transport._proof_1_18
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.seed_result_transport._proof_1_19
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.seed_result_transport._proof_1_2
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.seed_result_transport._proof_1_20
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.seed_result_transport._proof_1_21
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.seed_result_transport._proof_1_3
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.seed_result_transport._proof_1_4
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.seed_result_transport._proof_1_5
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.seed_result_transport._proof_1_6
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.seed_result_transport._proof_1_7
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.seed_result_transport._proof_1_8
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.seed_result_transport._proof_1_9
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.setup
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.setup.eq_1
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.setup_code
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.setup_frame
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.setup_frame._proof_1_10
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.setup_frame._proof_1_11
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.setup_frame._proof_1_12
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.setup_frame._proof_1_13
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.setup_frame._proof_1_2
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.setup_frame._proof_1_3
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.setup_frame._proof_1_4
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.setup_frame._proof_1_5
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.setup_frame._proof_1_6
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.setup_frame._proof_1_7
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.setup_frame._proof_1_8
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.setup_frame._proof_1_9
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.setup_length
#print axioms ExactFourierCircuits.UniformHighDataPackingPreparation.setup_safe
open Lean Elab Command in
run_cmd do
 let env←getEnv
 for (name,_) in env.constants.toList do
  if "_private.UniformHighDataPackingPreparation.".isPrefixOf name.toString then
   let axioms←collectAxioms name
   logInfo m!"'{name}' depends on axioms: {axioms.toList}"
   for ax in axioms do
    unless ax == `propext || ax == `Quot.sound || ax == `Classical.choice do
     throwError m!"Forbidden axiom {ax} in {name}"
