import UniformPreparedPayloadBridge
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformPreparedPayloadBridge.Cover
#print axioms ExactFourierCircuits.UniformPreparedPayloadBridge.Cover._proof_1
#print axioms ExactFourierCircuits.UniformPreparedPayloadBridge.actual_cover
#print axioms ExactFourierCircuits.UniformPreparedPayloadBridge.actual_cover._proof_1_1
#print axioms ExactFourierCircuits.UniformPreparedPayloadBridge.actual_cover._proof_1_2
#print axioms ExactFourierCircuits.UniformPreparedPayloadBridge.getD_present
#print axioms ExactFourierCircuits.UniformPreparedPayloadBridge.interval_unique
#print axioms ExactFourierCircuits.UniformPreparedPayloadBridge.interval_unique._proof_1_1
#print axioms ExactFourierCircuits.UniformPreparedPayloadBridge.interval_unique._proof_1_2
#print axioms ExactFourierCircuits.UniformPreparedPayloadBridge.inverse_source
#print axioms ExactFourierCircuits.UniformPreparedPayloadBridge.location
#print axioms ExactFourierCircuits.UniformPreparedPayloadBridge.location.congr_simp
#print axioms ExactFourierCircuits.UniformPreparedPayloadBridge.location_spec
#print axioms ExactFourierCircuits.UniformPreparedPayloadBridge.payload
#print axioms ExactFourierCircuits.UniformPreparedPayloadBridge.payload.congr_simp
#print axioms ExactFourierCircuits.UniformPreparedPayloadBridge.payload.eq_1
#print axioms ExactFourierCircuits.UniformPreparedPayloadBridge.payloadFin
#print axioms ExactFourierCircuits.UniformPreparedPayloadBridge.payloadFin._proof_1
#print axioms ExactFourierCircuits.UniformPreparedPayloadBridge.payload_at
#print axioms ExactFourierCircuits.UniformPreparedPayloadBridge.payload_at._proof_1_1
#print axioms ExactFourierCircuits.UniformPreparedPayloadBridge.payload_at._proof_1_2
#print axioms ExactFourierCircuits.UniformPreparedPayloadBridge.payload_at._proof_1_3
#print axioms ExactFourierCircuits.UniformPreparedPayloadBridge.payload_prepared
#print axioms ExactFourierCircuits.UniformPreparedPayloadBridge.payload_prepared._proof_1_1
#print axioms ExactFourierCircuits.UniformPreparedPayloadBridge.zero
