import UniformActualCalendarRetainedTreeAction
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformActualCalendarRetainedTreeAction.action
#print axioms ExactFourierCircuits.UniformActualCalendarRetainedTreeAction.action._proof_1
#print axioms ExactFourierCircuits.UniformActualCalendarRetainedTreeAction.action._proof_2
#print axioms ExactFourierCircuits.UniformActualCalendarRetainedTreeAction.action._proof_3
#print axioms ExactFourierCircuits.UniformActualCalendarRetainedTreeAction.selected_tree
#print axioms ExactFourierCircuits.UniformActualCalendarRetainedTreeAction.selected_tree._proof_1_1
#print axioms ExactFourierCircuits.UniformActualCalendarRetainedTreeAction.selected_tree._proof_1_3
#print axioms ExactFourierCircuits.UniformActualCalendarRetainedTreeAction.selected_tree._proof_1_4
#print axioms ExactFourierCircuits.UniformActualCalendarRetainedTreeAction.selected_tree._proof_1_5
#print axioms ExactFourierCircuits.UniformActualCalendarRetainedTreeAction.specified_tree
#print axioms ExactFourierCircuits.UniformReflectedFourierCalendar.full.congr_simp
