import UniformRecursivePreparedSmallBody
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformRecursiveSmallBody.execution_prepared
#print axioms ExactFourierCircuits.UniformRecursiveSmallBody.execution_prepared._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveSmallBody.execution_prepared._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveSmallBody.execution_prepared._proof_1_3
