import UniformLocalStoredRequestGeometry
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotGeometry.context.eq_1
#print axioms ExactFourierCircuits.UniformLocalStoredRequestGeometry.W.original
#print axioms ExactFourierCircuits.UniformLocalStoredRequestGeometry.W.stride
#print axioms ExactFourierCircuits.UniformLocalStoredRequestGeometry.binding
#print axioms ExactFourierCircuits.UniformLocalStoredRequestGeometry.phase_ends
#print axioms ExactFourierCircuits.UniformLocalStoredRequestGeometry.phase_layout
#print axioms ExactFourierCircuits.UniformLocalStoredRequestGeometry.prefixes
#print axioms ExactFourierCircuits.UniformLocalStoredRequestGeometry.prefixes._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalStoredRequestGeometry.prefixes._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalStoredRequestGeometry.prefixes._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalStoredRequestGeometry.prefixes._proof_1_4
#print axioms ExactFourierCircuits.UniformLocalStoredRequestGeometry.slots_before
#print axioms ExactFourierCircuits.UniformLocalStoredRequestGeometry.true_before
