import UniformRecursiveV2CostAllowance
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformRecursiveV2CostAllowance.actual_direction_bound
#print axioms ExactFourierCircuits.UniformRecursiveV2CostAllowance.actual_direction_bound._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveV2CostAllowance.directionLocal
#print axioms ExactFourierCircuits.UniformRecursiveV2CostAllowance.directionLocal_bound
#print axioms ExactFourierCircuits.UniformRecursiveV2CostAllowance.marker_record_bound
#print axioms ExactFourierCircuits.UniformRecursiveV2CostAllowance.marker_record_bound._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveV2CostAllowance.marker_record_bound._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveV2CostAllowance.padding_record_bound
#print axioms ExactFourierCircuits.UniformRecursiveV2CostAllowance.padding_record_bound._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveV2CostAllowance.residual_record_bound
#print axioms ExactFourierCircuits.UniformRecursiveV2CostAllowance.schedule_sum_charges
#print axioms ExactFourierCircuits.UniformRecursiveV2CostAllowance.sum_charge_formula
#print axioms ExactFourierCircuits.UniformRecursiveV2CostAllowance.sum_charges
#print axioms ExactFourierCircuits.UniformRecursiveV2CostAllowance.translation_record_bound
#print axioms ExactFourierCircuits.UniformRecursiveV2CostAllowance.translation_record_bound._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveV2CostAllowance.translation_record_bound._proof_1_2
