import UniformRecursiveNativeRecords
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.exchange_loop
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.exchange_loop._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.exchange_loop._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.exchange_loop._proof_1_3
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.exchange_pc
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.marker2_pc
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.marker6_pc
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.marker_loop
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.marker_loop._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.present_control
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.printed_control
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.scalar_loop
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.scalar_loop._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.scalar_loop._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.scalar_loop._proof_1_3
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.scalar_pc
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.translation_loop
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.translation_loop._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.translation_loop._proof_1_10
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.translation_loop._proof_1_11
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.translation_loop._proof_1_12
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.translation_loop._proof_1_13
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.translation_loop._proof_1_14
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.translation_loop._proof_1_15
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.translation_loop._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.translation_loop._proof_1_3
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.translation_loop._proof_1_4
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.translation_loop._proof_1_5
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.translation_loop._proof_1_6
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.translation_loop._proof_1_7
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.translation_loop._proof_1_8
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.translation_loop._proof_1_9
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.translation_pc
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.vector_exchange
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.vector_marker2
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.vector_marker6
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.vector_scalar
#print axioms ExactFourierCircuits.UniformRecursiveNativeRecords.vector_translation
