import UniformFinalClockOverhead
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformFinalClockOverhead.axesScanBudget
#print axioms ExactFourierCircuits.UniformFinalClockOverhead.axesScanBudget_bound
#print axioms ExactFourierCircuits.UniformFinalClockOverhead.axesScanBudget_bound._proof_1_1
#print axioms ExactFourierCircuits.UniformFinalClockOverhead.axesScanBudget_bound._proof_1_2
#print axioms ExactFourierCircuits.UniformFinalClockOverhead.axesScanBudget_bound._proof_1_3
#print axioms ExactFourierCircuits.UniformFinalClockOverhead.axesScanBudget_bound._proof_1_4
#print axioms ExactFourierCircuits.UniformFinalClockOverhead.axesScanBudget_isBigO_log_nine
#print axioms ExactFourierCircuits.UniformFinalClockOverhead.axesScanBudget_isBigO_log_nine._proof_1_1
#print axioms ExactFourierCircuits.UniformFinalClockOverhead.axisScanBudget
#print axioms ExactFourierCircuits.UniformFinalClockOverhead.axisScanBudget_bound
#print axioms ExactFourierCircuits.UniformFinalClockOverhead.axisScanBudget_bound._proof_1_1
#print axioms ExactFourierCircuits.UniformFinalClockOverhead.axis_scan_bound
#print axioms ExactFourierCircuits.UniformFinalClockOverhead.clockScanBudget
#print axioms ExactFourierCircuits.UniformFinalClockOverhead.clockScanBudget.eq_1
#print axioms ExactFourierCircuits.UniformFinalClockOverhead.clockScanBudget_isLittleO_input
#print axioms ExactFourierCircuits.UniformFinalClockOverhead.diagonal_extra_linear
#print axioms ExactFourierCircuits.UniformFinalClockOverhead.diagonal_extra_linear._proof_1_1
#print axioms ExactFourierCircuits.UniformFinalClockOverhead.horizon_isBigO_log_four
#print axioms ExactFourierCircuits.UniformFinalClockOverhead.horizon_isBigO_log_four._proof_1_1
#print axioms ExactFourierCircuits.UniformFinalClockOverhead.horizon_isBigO_log_four._proof_1_2
#print axioms ExactFourierCircuits.UniformFinalClockOverhead.radix_list_bounds
#print axioms ExactFourierCircuits.UniformFinalClockOverhead.radix_list_bounds._proof_1_1
#print axioms ExactFourierCircuits.UniformFinalClockOverhead.scanUnit
