import UniformTransposeCalendarGeometry
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformTransposeCalendarGeometry.calendar_bounds
#print axioms ExactFourierCircuits.UniformTransposeCalendarGeometry.calendar_bounds._proof_1_1
#print axioms ExactFourierCircuits.UniformTransposeCalendarGeometry.calendar_bounds._proof_1_10
#print axioms ExactFourierCircuits.UniformTransposeCalendarGeometry.calendar_bounds._proof_1_2
#print axioms ExactFourierCircuits.UniformTransposeCalendarGeometry.calendar_bounds._proof_1_3
#print axioms ExactFourierCircuits.UniformTransposeCalendarGeometry.calendar_bounds._proof_1_4
#print axioms ExactFourierCircuits.UniformTransposeCalendarGeometry.calendar_bounds._proof_1_5
#print axioms ExactFourierCircuits.UniformTransposeCalendarGeometry.calendar_bounds._proof_1_6
#print axioms ExactFourierCircuits.UniformTransposeCalendarGeometry.calendar_bounds._proof_1_7
#print axioms ExactFourierCircuits.UniformTransposeCalendarGeometry.calendar_bounds._proof_1_8
#print axioms ExactFourierCircuits.UniformTransposeCalendarGeometry.calendar_bounds._proof_1_9
#print axioms ExactFourierCircuits.UniformTransposeCalendarGeometry.calendar_positioned
#print axioms ExactFourierCircuits.UniformTransposeCalendarGeometry.calendar_separated
#print axioms ExactFourierCircuits.UniformTransposeCalendarGeometry.calendar_separated._proof_1_2
#print axioms ExactFourierCircuits.UniformTransposeCalendarGeometry.calendar_separated._proof_1_3
#print axioms ExactFourierCircuits.UniformTransposeCalendarGeometry.calendar_separated._proof_1_4
#print axioms ExactFourierCircuits.UniformTransposeCalendarGeometry.calendar_separated._simp_1_1
#print axioms ExactFourierCircuits.UniformTransposeCalendarGeometry.correction_band
#print axioms ExactFourierCircuits.UniformTransposeCalendarGeometry.correction_weight
#print axioms ExactFourierCircuits.UniformTransposeCalendarGeometry.stamp_bounds
#print axioms ExactFourierCircuits.UniformTransposeCalendarGeometry.stamp_bounds._proof_1_1
#print axioms ExactFourierCircuits.UniformTransposeCalendarGeometry.stamp_bounds._proof_1_2
#print axioms ExactFourierCircuits.UniformTransposeCalendarGeometry.stamp_property
#print axioms ExactFourierCircuits.UniformTransposeCalendarGeometry.stamp_separated
#print axioms ExactFourierCircuits.UniformTransposeCalendarGeometry.stamp_separated._proof_1_1
#print axioms ExactFourierCircuits.UniformTransposeCalendarGeometry.weight
