import UniformLocalCacheTimingMetadata
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformLocalCacheTimingMetadata.canonical_metadata
#print axioms ExactFourierCircuits.UniformLocalCacheTimingMetadata.current_row_dimensions
#print axioms ExactFourierCircuits.UniformLocalCacheTimingMetadata.current_row_dimensions._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalCacheTimingMetadata.nodeCount
#print axioms ExactFourierCircuits.UniformLocalCacheTimingMetadata.requestCount
#print axioms ExactFourierCircuits.UniformLocalCacheTimingMetadata.rootVisits
#print axioms ExactFourierCircuits.UniformLocalCacheTimingMetadata.root_ordinal
#print axioms ExactFourierCircuits.UniformLocalCacheTimingMetadata.root_row_budget
#print axioms ExactFourierCircuits.UniformLocalCacheTimingMetadata.root_row_budget._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalCacheTimingMetadata.root_source
#print axioms ExactFourierCircuits.UniformLocalCacheTimingMetadata.root_source._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalCacheTimingMetadata.root_width
#print axioms ExactFourierCircuits.UniformLocalCacheTimingMetadata.root_width._simp_1_1
#print axioms ExactFourierCircuits.UniformLocalCacheTimingMetadata.walk_widths
#print axioms ExactFourierCircuits.UniformLocalCacheTimingMetadata.walk_widths._simp_1_1
