import UniformGlobalDiagonalRowsPreparation

-- Include generated declarations in the closure audit.
set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.axes_bounds
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.axes_bounds._proof_1_4
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.axes_bounds._simp_1_1
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.axis.eq_1
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.boot.eq_1
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.boot_cursor
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.boot_frame
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.boot_frame._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.boot_frame._proof_1_3
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.boot_frame._proof_1_4
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.boot_frame._proof_1_5
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.boot_frame._proof_1_6
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.execution
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.execution._proof_1_7
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.execution_saved
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.execution_saved._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.execution_saved._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.execution_saved._proof_1_3
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.produced_banks
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.produced_banks._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.produced_banks._proof_1_2
#print axioms ExactFourierCircuits.UniformTensorMonomialMachine.Axis.mk.congr_simp
