import UniformGlobalTensorDiagonalPreparation
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.axes_identity
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.axes_identity._simp_1_1
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.diagonal_values
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_10
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_11
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_12
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_13
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_14
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_15
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_16
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_17
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_18
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_19
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_20
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_21
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_22
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_23
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_24
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_25
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_26
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_27
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_28
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_29
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_30
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_31
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_7
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_8
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.execution._proof_1_9
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.halt_at
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.halt_at._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.program
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.programFor
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.programFor.eq_1
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.program_length
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.rows_code
#print axioms ExactFourierCircuits.UniformGlobalTensorDiagonalPreparation.tensor_code
