import UniformInitializedKernelExecution
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformInitializedKernelExecution.after_header
#print axioms ExactFourierCircuits.UniformInitializedKernelExecution.after_header._proof_1_1
#print axioms ExactFourierCircuits.UniformInitializedKernelExecution.after_header._proof_1_2
#print axioms ExactFourierCircuits.UniformInitializedKernelExecution.code_space
#print axioms ExactFourierCircuits.UniformInitializedKernelExecution.code_space._proof_1_1
#print axioms ExactFourierCircuits.UniformInitializedKernelExecution.execution
#print axioms ExactFourierCircuits.UniformInitializedKernelExecution.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformInitializedKernelExecution.halt_at
#print axioms ExactFourierCircuits.UniformInitializedKernelExecution.halt_at._proof_1_1
#print axioms ExactFourierCircuits.UniformInitializedKernelExecution.halt_at._proof_1_2
#print axioms ExactFourierCircuits.UniformInitializedKernelExecution.header_code
#print axioms ExactFourierCircuits.UniformInitializedKernelExecution.kernel_code
#print axioms ExactFourierCircuits.UniformInitializedKernelExecution.programFor
#print axioms ExactFourierCircuits.UniformInitializedKernelExecution.programFor.eq_1
#print axioms ExactFourierCircuits.UniformInitializedKernelExecution.program_length
#print axioms ExactFourierCircuits.UniformInitializedKernelExecution.program_length._proof_1_2
#print axioms ExactFourierCircuits.UniformInitializedKernelExecution.ready_pc
#print axioms ExactFourierCircuits.UniformInitializedKernelExecution.return_space
#print axioms ExactFourierCircuits.UniformInitializedKernelExecution.return_space._proof_1_1
#print axioms ExactFourierCircuits.UniformInitializedKernelExecution.sectors_positive
#print axioms ExactFourierCircuits.UniformInitializedKernelExecution.sectors_positive._proof_1_1
#print axioms ExactFourierCircuits.UniformInitializedKernelExecution.shift_bound
#print axioms ExactFourierCircuits.UniformInitializedKernelExecution.shift_bound._proof_1_1
