import UniformDirectLeafCacheLeafFinal
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformDirectLeafCacheLeafFinal.final_leaf_time
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLeafFinal.final_partition
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLeafFinal.final_pool
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLeafFinal.final_time
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLeafFinal.records_elapsed
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLeafFinal.retained_conjugate
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLeafFinal.retained_conjugate._proof_1_1
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLeafFinal.retained_conjugate._proof_1_2
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLeafFinal.retained_original
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLeafFinal.retained_original._proof_1_1
#print axioms ExactFourierCircuits.UniformDirectLeafCacheLeafFinal.retained_original._proof_1_2
