import UniformActualCalendarRectangleProduced
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformActualCalendarRectangleEvent.actualEvent.congr_simp
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.Data
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.Data._sizeOf_1
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.Data._sizeOf_inst
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.Data.broadcast
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.Data.casesOn
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.Data.contents
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.Data.ctorIdx
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.Data.event
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.Data.event.eq_1
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.Data.layout
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.Data.mk
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.Data.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.Data.mk.inj
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.Data.mk.injEq
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.Data.mk.noConfusion
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.Data.mk.sizeOf_spec
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.Data.noConfusion
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.Data.noConfusionType
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.Data.produced
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.Data.produced._proof_1
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.Data.produced._proof_2
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.Data.produced._proof_3
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.Data.rec
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.Data.recOn
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.Data.slot
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.Data.witness
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.of_cached
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.phase
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.phase._proof_1
#print axioms ExactFourierCircuits.UniformActualCalendarRectangleProduced.phase.eq_1
