import UniformActualCalendarBroadcastCodes
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformActualCalendarBroadcastCodes.codeValue
#print axioms ExactFourierCircuits.UniformActualCalendarBroadcastCodes.codeValue.congr_simp
#print axioms ExactFourierCircuits.UniformActualCalendarBroadcastCodes.codeValue.eq_1
#print axioms ExactFourierCircuits.UniformActualCalendarBroadcastCodes.entries
#print axioms ExactFourierCircuits.UniformActualCalendarBroadcastCodes.entries.congr_simp
#print axioms ExactFourierCircuits.UniformActualCalendarBroadcastCodes.entries.eq_1
#print axioms ExactFourierCircuits.UniformActualCalendarBroadcastCodes.layer_entries
#print axioms ExactFourierCircuits.UniformActualCalendarBroadcastCodes.layer_entries._proof_1
#print axioms ExactFourierCircuits.UniformActualCalendarBroadcastCodes.occurrences
#print axioms ExactFourierCircuits.UniformActualCalendarBroadcastCodes.occurrences_entries
#print axioms ExactFourierCircuits.UniformActualCalendarBroadcastCodes.occurrences_entries._proof_1_3
#print axioms ExactFourierCircuits.UniformActualCalendarBroadcastCodes.occurrences_entries._proof_1_6
#print axioms ExactFourierCircuits.UniformActualCalendarBroadcastCodes.signed
#print axioms ExactFourierCircuits.UniformActualCalendarBroadcastCodes.signed.eq_1
