import UniformLocalCacheSlotPriorRetention
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.PriorRetention.execution
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.PriorRetention.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.PriorRetention.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.PriorRetention.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.PriorRetention.iteration
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.PriorRetention.iteration._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.PriorRetention.iteration._proof_1_10
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.PriorRetention.iteration._proof_1_12
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.PriorRetention.iteration._proof_1_13
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.PriorRetention.iteration._proof_1_14
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.PriorRetention.iteration._proof_1_15
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.PriorRetention.iteration._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.PriorRetention.iteration._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.PriorRetention.iteration._proof_1_4
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.PriorRetention.iteration._proof_1_5
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.PriorRetention.iteration._proof_1_6
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.PriorRetention.iteration._proof_1_7
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.PriorRetention.iteration._proof_1_8
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.PriorRetention.iteration._proof_1_9
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.PriorRetention.loop
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.PriorRetention.loop._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.PriorRetention.loop._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.PriorRetention.loop._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.PriorRetention.loop._proof_1_4
#print axioms ExactFourierCircuits.UniformLocalCacheSlotConductorMachine.PriorRetention.loop._proof_1_5
#print axioms ExactFourierCircuits.UniformLocalFactorDispatchMachine.natEnd.congr_simp
