import UniformFastPhysicalCRTInitialization
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.Data
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.Data.casesOn
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.Data.cells
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.Data.index
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.Data.mk
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.Data.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.Data.normal
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.Data.physical
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.Data.rec
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.Data.recOn
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.Data.weight
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.Outside
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.Work
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_constants
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_data
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_data._proof_1_1
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_data._proof_1_2
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_data._proof_1_3
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_data._proof_1_4
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_data._proof_1_5
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_frame
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_frame._proof_1_10
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_frame._proof_1_11
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_frame._proof_1_12
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_frame._proof_1_13
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_frame._proof_1_14
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_frame._proof_1_15
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_frame._proof_1_16
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_frame._proof_1_17
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_frame._proof_1_18
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_frame._proof_1_19
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_frame._proof_1_20
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_frame._proof_1_21
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_frame._proof_1_22
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_frame._proof_1_23
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_frame._proof_1_24
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_frame._proof_1_25
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_frame._proof_1_4
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_frame._proof_1_5
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_frame._proof_1_6
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_frame._proof_1_7
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_frame._proof_1_8
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_frame._proof_1_9
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_heap
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_outside
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_outside._proof_1_1
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_outside._proof_1_2
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_safe
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_safe._proof_1_1
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_safe._proof_1_16
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_safe._proof_1_2
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_values
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_values._proof_1_1
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.body_values._proof_1_2
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.boot_constants
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.boot_data
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.boot_data._proof_1_2
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.boot_frame
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.boot_frame._proof_1_2
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.boot_frame._proof_1_3
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.boot_frame._proof_1_4
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.boot_frame._proof_1_5
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.boot_frame._proof_1_6
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.boot_frame._proof_1_7
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.boot_frame._proof_1_8
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.entered
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.entered.eq_1
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.execution
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.execution._proof_1_14
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.execution._proof_1_15
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.execution._proof_1_16
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.init_loop
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.init_loop._proof_1_1
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.init_loop._proof_1_2
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.init_loop._proof_1_3
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.init_loop._proof_1_4
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.init_loop._proof_1_5
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.init_loop._proof_1_6
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.rowEnd
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.rowEnd.eq_1
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.row_execution
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.row_execution._proof_1_1
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.row_execution._proof_1_3
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTInitialization.row_execution._proof_1_5
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTMachine.boot.eq_1
#print axioms ExactFourierCircuits.UniformFastPhysicalCRTMachine.initBody.eq_1

open Lean Elab Command in
run_cmd do
 let env ← getEnv
 for (name, _) in env.constants.toList do
  if "_private.UniformFastPhysicalCRTInitialization.".isPrefixOf name.toString then
   let axs ← collectAxioms name
   logInfo m!"{name} depends on axioms: {axs.toList}"
