import UniformGlobalAxisDispatchExecution
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.PlacementArgs
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.PlacementArgs.axis
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.PlacementArgs.casesOn
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.PlacementArgs.directory
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.PlacementArgs.marker
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.PlacementArgs.mk
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.PlacementArgs.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.PlacementArgs.permutation
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.PlacementArgs.rec
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.PlacementArgs.recOn
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.PlacementArgs.widths
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.PlacementSafe
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.PlacementSafe.eq_1
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.PlacementSafe.match_1
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.actual_edges
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.execution
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.execution._proof_1_10
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.execution._proof_1_11
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.execution._proof_1_12
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.execution._proof_1_13
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.execution._proof_1_14
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.execution._proof_1_15
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.execution._proof_1_16
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.execution._proof_1_17
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.execution._proof_1_18
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.execution._proof_1_7
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.execution._proof_1_8
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.execution._proof_1_9
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.instDecidablePlacementSafe
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.instDecidablePlacementSafe._proof_1
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.instDecidablePlacementSafe._proof_2
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.instDecidablePlacementSafe._proof_3
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.placed_reset
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.placement_frame
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.placement_frame._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.placement_safe
#print axioms ExactFourierCircuits.UniformGlobalAxisDispatchExecution.placement_safe._proof_1_1

open Lean Elab Command in
run_cmd do
 let env ← getEnv
 for (name, _) in env.constants.toList do
  if "_private.UniformGlobalAxisDispatchExecution.".isPrefixOf name.toString then
   let axs ← collectAxioms name
   logInfo m!"{name} depends on axioms: {axs.toList}"
