import UniformResidualOrientationAllowance
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformResidualOrientationAllowance.directionTicks
#print axioms ExactFourierCircuits.UniformResidualOrientationAllowance.direction_bound
#print axioms ExactFourierCircuits.UniformResidualOrientationAllowance.direction_bound._proof_1_1
#print axioms ExactFourierCircuits.UniformResidualOrientationAllowance.padding_record_bound
#print axioms ExactFourierCircuits.UniformResidualOrientationAllowance.padding_record_bound._proof_1_1
#print axioms ExactFourierCircuits.UniformResidualOrientationAllowance.padding_record_bound._proof_1_2
#print axioms ExactFourierCircuits.UniformResidualOrientationAllowance.residual_record_bound
#print axioms ExactFourierCircuits.UniformResidualOrientationAllowance.residual_record_bound._proof_1_1
#print axioms ExactFourierCircuits.UniformResidualOrientationAllowance.residual_record_bound._proof_1_2
