import UniformDirectLeafForestLeafCall
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafCall.conjugate_transport
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafCall.constants_transport
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafCall.execution
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafCall.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafCall.execution._proof_1_10
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafCall.execution._proof_1_11
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafCall.execution._proof_1_12
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafCall.execution._proof_1_13
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafCall.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafCall.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafCall.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafCall.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafCall.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafCall.execution._proof_1_7
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafCall.execution._proof_1_8
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafCall.execution._proof_1_9
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafCall.original_transport
#print axioms ExactFourierCircuits.UniformDirectLeafForestLeafCall.source_transport
#print axioms ExactFourierCircuits.UniformDirectLeafHighLeafExecution.Result.congr_simp
