import UniformLocalDisabledHeightRetention
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformLocalDisabledHeightMachine.Retention.execution
#print axioms ExactFourierCircuits.UniformLocalDisabledHeightMachine.Retention.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalDisabledHeightMachine.Retention.execution._proof_1_10
#print axioms ExactFourierCircuits.UniformLocalDisabledHeightMachine.Retention.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalDisabledHeightMachine.Retention.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalDisabledHeightMachine.Retention.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformLocalDisabledHeightMachine.Retention.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformLocalDisabledHeightMachine.Retention.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformLocalDisabledHeightMachine.Retention.execution._proof_1_7
#print axioms ExactFourierCircuits.UniformLocalDisabledHeightMachine.Retention.execution._simp_1_8
#print axioms ExactFourierCircuits.UniformLocalDisabledHeightMachine.Retention.execution._simp_1_9
