import UniformGlobalCalendarFactorMerge
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.Factors
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.Header
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.Header.casesOn
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.Header.index
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.Header.laneReg
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.Header.mk
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.Header.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.Header.one
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.Header.output
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.Header.pc
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.Header.pool
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.Header.radix
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.Header.rec
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.Header.recOn
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.Header.source
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.Header.zero
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.Tail
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.body
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.body.eq_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.body_code
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.body_execution
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.body_execution._proof_1_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.body_execution._proof_1_2
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.body_execution._proof_1_4
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.body_header
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.body_heap
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.boot
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.boot_code
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.code_13
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.code_14
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.code_5
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.mergeHeap
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.mergeHeap._f
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.mergeHeap._sunfold
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.mergeHeap._unsafe_rec
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.mergeHeap.match_1
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.program
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.program_length
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.storeProduct
#print axioms ExactFourierCircuits.UniformGlobalCalendarFactorMerge.storeProduct.eq_1
