import UniformFinalClockRuntime
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Kept
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.allocator
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.casesOn
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.horizon
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.initialNat
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.initialScalar
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.mk
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.natEnd
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.pc
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.rec
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.recOn
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.role
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.role._proof_1_1
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.role._proof_1_2
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.scalarEnd
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.seed
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.transport
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.transport._proof_1_1
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.transport._proof_1_10
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.transport._proof_1_11
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.transport._proof_1_12
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.transport._proof_1_13
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.transport._proof_1_14
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.transport._proof_1_15
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.transport._proof_1_16
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.transport._proof_1_17
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.transport._proof_1_18
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.transport._proof_1_19
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.transport._proof_1_2
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.transport._proof_1_20
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.transport._proof_1_21
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.transport._proof_1_22
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.transport._proof_1_23
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.transport._proof_1_24
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.transport._proof_1_3
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.transport._proof_1_4
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.transport._proof_1_5
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.transport._proof_1_6
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.transport._proof_1_7
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.transport._proof_1_8
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.Runtime.transport._proof_1_9
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.constants
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.input
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.of_prefix
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.of_prefix._proof_1_1
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.of_prefix._proof_1_2
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.of_prefix._proof_1_3
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.of_prefix._proof_1_4
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.of_prefix._proof_1_5
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.of_prefix._proof_1_6
#print axioms ExactFourierCircuits.UniformFinalClockRuntime.of_prefix._proof_1_7

open Lean Elab Command in
run_cmd do
 let env ← getEnv
 for (name, _) in env.constants.toList do
  if "_private.UniformFinalClockRuntime.".isPrefixOf name.toString then
   let axs ← collectAxioms name
   logInfo m!"{name} depends on axioms: {axs.toList}"
