import UniformBorrowedCoordinateBridge
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformBorrowedCoordinateBridge.available_capacity
#print axioms ExactFourierCircuits.UniformBorrowedCoordinateBridge.available_values
#print axioms ExactFourierCircuits.UniformBorrowedCoordinateBridge.borrowed_values
#print axioms ExactFourierCircuits.UniformBorrowedCoordinateBridge.eligible_iff
#print axioms ExactFourierCircuits.UniformBorrowedCoordinateBridge.eligible_iff._proof_1_4
#print axioms ExactFourierCircuits.UniformBorrowedCoordinateBridge.eligible_iff._simp_1_1
#print axioms ExactFourierCircuits.UniformBorrowedCoordinateBridge.eligible_iff._simp_1_2
#print axioms ExactFourierCircuits.UniformBorrowedCoordinateBridge.embedding_eq
#print axioms ExactFourierCircuits.UniformBorrowedCoordinateBridge.finRange_values
#print axioms ExactFourierCircuits.UniformBorrowedCoordinateBridge.interval_separated
#print axioms ExactFourierCircuits.UniformBorrowedCoordinateBridge.interval_separated._proof_1_1
#print axioms ExactFourierCircuits.UniformBorrowedCoordinateBridge.mapped_natPorts_eq
#print axioms ExactFourierCircuits.UniformBorrowedCoordinateBridge.placement_eq
#print axioms ExactFourierCircuits.UniformBorrowedCoordinateBridge.placement_eq._proof_1
#print axioms ExactFourierCircuits.UniformBorrowedCoordinateBridge.placement_ext
#print axioms ExactFourierCircuits.UniformBorrowedCoordinateBridge.positions_interval
#print axioms ExactFourierCircuits.UniformBorrowedCoordinateBridge.positions_interval._proof_1_4
#print axioms ExactFourierCircuits.UniformBorrowedCoordinateBridge.positions_interval._proof_1_5
#print axioms ExactFourierCircuits.UniformBorrowedCoordinateBridge.positions_interval._proof_1_6
#print axioms ExactFourierCircuits.UniformBorrowedCoordinateBridge.positions_interval._simp_1_1
#print axioms ExactFourierCircuits.UniformBorrowedCoordinateBridge.positions_interval._simp_1_2
#print axioms ExactFourierCircuits.UniformChunkPortMachine.intervalEmbedding.congr_simp
#print axioms ExactFourierCircuits.UniformToeplitzChunkWord.Placement.mk.congr_simp
