import UniformProducedClockTickPrepared
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformProducedClockTickPrepared.budget
#print axioms ExactFourierCircuits.UniformProducedClockTickPrepared.execution
#print axioms ExactFourierCircuits.UniformProducedClockTickPrepared.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformProducedClockTickPrepared.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformProducedClockTickPrepared.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformProducedClockTickPrepared.family
#print axioms ExactFourierCircuits.UniformProducedClockTickPrepared.stored
