import UniformCalendarPreparationBounds
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformCalendarPreparationBounds.actual_plan_budget
#print axioms ExactFourierCircuits.UniformCalendarPreparationBounds.allAxesBudget
#print axioms ExactFourierCircuits.UniformCalendarPreparationBounds.all_axes_bound
#print axioms ExactFourierCircuits.UniformCalendarPreparationBounds.all_clocks_preparation
#print axioms ExactFourierCircuits.UniformCalendarPreparationBounds.calendarEntries
#print axioms ExactFourierCircuits.UniformCalendarPreparationBounds.capacity_mono
#print axioms ExactFourierCircuits.UniformCalendarPreparationBounds.capacity_mono._proof_1_1
#print axioms ExactFourierCircuits.UniformCalendarPreparationBounds.entries_bound
#print axioms ExactFourierCircuits.UniformCalendarPreparationBounds.factorTicks
#print axioms ExactFourierCircuits.UniformCalendarPreparationBounds.factor_bound
#print axioms ExactFourierCircuits.UniformCalendarPreparationBounds.factor_bound._proof_1_1
#print axioms ExactFourierCircuits.UniformCalendarPreparationBounds.factor_bound._proof_1_2
#print axioms ExactFourierCircuits.UniformCalendarPreparationBounds.matchingTicks
#print axioms ExactFourierCircuits.UniformCalendarPreparationBounds.matching_bound
#print axioms ExactFourierCircuits.UniformCalendarPreparationBounds.matching_bound._proof_1_1
#print axioms ExactFourierCircuits.UniformCalendarPreparationBounds.matching_bound._proof_1_2
#print axioms ExactFourierCircuits.UniformCalendarPreparationBounds.preparationBudget
#print axioms ExactFourierCircuits.UniformCalendarPreparationBounds.preparation_mono
#print axioms ExactFourierCircuits.UniformCalendarPreparationBounds.preparation_mono._proof_1_1
#print axioms ExactFourierCircuits.UniformCalendarPreparationBounds.preparation_mono._proof_1_2
#print axioms ExactFourierCircuits.UniformCalendarPreparationBounds.selected_axis_budget
#print axioms ExactFourierCircuits.UniformCalendarPreparationBounds.selection_sum
#print axioms ExactFourierCircuits.UniformCalendarPreparationBounds.selector_dispatch
