import UniformActualCalendarDirectSource
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.embed_source
#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.embed_source._proof_1
#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.embed_source._proof_2
#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.embed_source._proof_3
#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.pair_source
#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.pair_source._proof_1
#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.pair_source._proof_10
#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.pair_source._proof_2
#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.pair_source._proof_3
#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.pair_source._proof_4
#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.pair_source._proof_5
#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.pair_source._proof_6
#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.pair_source._proof_7
#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.pair_source._proof_8
#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.pair_source._proof_9
#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.scale_source
#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.scale_source._proof_1
#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.scale_source._proof_2
#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.scale_source._proof_3
#print axioms ExactFourierCircuits.UniformActualCalendarDirectSource.scale_source._proof_4
