import UniformBoundaryDiagonalCoreOutside
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformBoundaryDiagonalOutside.CoreResultOutside
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalOutside.CoreResultOutside.casesOn
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalOutside.CoreResultOutside.mk
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalOutside.CoreResultOutside.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalOutside.CoreResultOutside.natOutside
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalOutside.CoreResultOutside.rec
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalOutside.CoreResultOutside.recOn
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalOutside.CoreResultOutside.toCoreResult
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalOutside.execution_outside
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalOutside.execution_outside._proof_1_1
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalOutside.execution_outside._proof_1_2
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalOutside.execution_outside._proof_1_3
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalOutside.execution_outside._proof_1_4
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalOutside.execution_outside._proof_1_5
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalOutside.execution_outside._proof_1_6
#print axioms ExactFourierCircuits.UniformBoundaryDiagonalOutside.execution_outside._proof_1_7
