import UniformInitialTraversalPreparation
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformInitialTraversalPreparation.halt_at
#print axioms ExactFourierCircuits.UniformInitialTraversalPreparation.halt_at._proof_1_2
#print axioms ExactFourierCircuits.UniformInitialTraversalPreparation.head
#print axioms ExactFourierCircuits.UniformInitialTraversalPreparation.head.eq_1
#print axioms ExactFourierCircuits.UniformInitialTraversalPreparation.head_length
#print axioms ExactFourierCircuits.UniformInitialTraversalPreparation.initial_execution
#print axioms ExactFourierCircuits.UniformInitialTraversalPreparation.initial_execution._proof_1_1
#print axioms ExactFourierCircuits.UniformInitialTraversalPreparation.initial_execution._proof_1_2
#print axioms ExactFourierCircuits.UniformInitialTraversalPreparation.initial_execution._proof_1_3
#print axioms ExactFourierCircuits.UniformInitialTraversalPreparation.initial_execution._proof_1_4
#print axioms ExactFourierCircuits.UniformInitialTraversalPreparation.initial_execution._proof_1_5
#print axioms ExactFourierCircuits.UniformInitialTraversalPreparation.initial_execution._proof_1_6
#print axioms ExactFourierCircuits.UniformInitialTraversalPreparation.initial_execution._proof_1_7
#print axioms ExactFourierCircuits.UniformInitialTraversalPreparation.initial_execution._proof_1_8
#print axioms ExactFourierCircuits.UniformInitialTraversalPreparation.preparationBudget
#print axioms ExactFourierCircuits.UniformInitialTraversalPreparation.preparation_code
#print axioms ExactFourierCircuits.UniformInitialTraversalPreparation.preparation_code._proof_1_2
#print axioms ExactFourierCircuits.UniformInitialTraversalPreparation.program
#print axioms ExactFourierCircuits.UniformInitialTraversalPreparation.program.eq_1
#print axioms ExactFourierCircuits.UniformInitialTraversalPreparation.program_length
#print axioms ExactFourierCircuits.UniformInitialTraversalPreparation.traversalRuntime
#print axioms ExactFourierCircuits.UniformInitialTraversalPreparation.traversal_code
#print axioms ExactFourierCircuits.UniformInitialTraversalPreparation.word_setup
#print axioms ExactFourierCircuits.UniformInitialTraversalPreparation.word_setup._proof_1_1
#print axioms ExactFourierCircuits.UniformInitialTraversalPreparation.word_setup._proof_1_2
