import UniformForwardMatchingFactorHeaderExecution

-- Inventory uses the defining Lean module, including generated declarations.
set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformForwardMatchingFactorHeaderPreparation.coreResult
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorHeaderPreparation.coreResult._proof_1_1
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorHeaderPreparation.coreResult._proof_1_2
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorHeaderPreparation.execution
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorHeaderPreparation.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorHeaderPreparation.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorHeaderPreparation.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorHeaderPreparation.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorHeaderPreparation.execution._proof_1_5
