import UniformCalendarIterationFrame
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformCalendarIterationFrame.dispatch
#print axioms ExactFourierCircuits.UniformCalendarIterationFrame.dispatch._proof_1_1
#print axioms ExactFourierCircuits.UniformCalendarIterationFrame.dispatch._proof_1_10
#print axioms ExactFourierCircuits.UniformCalendarIterationFrame.dispatch._proof_1_11
#print axioms ExactFourierCircuits.UniformCalendarIterationFrame.dispatch._proof_1_12
#print axioms ExactFourierCircuits.UniformCalendarIterationFrame.dispatch._proof_1_13
#print axioms ExactFourierCircuits.UniformCalendarIterationFrame.dispatch._proof_1_14
#print axioms ExactFourierCircuits.UniformCalendarIterationFrame.dispatch._proof_1_15
#print axioms ExactFourierCircuits.UniformCalendarIterationFrame.dispatch._proof_1_16
#print axioms ExactFourierCircuits.UniformCalendarIterationFrame.dispatch._proof_1_2
#print axioms ExactFourierCircuits.UniformCalendarIterationFrame.dispatch._proof_1_3
#print axioms ExactFourierCircuits.UniformCalendarIterationFrame.dispatch._proof_1_4
#print axioms ExactFourierCircuits.UniformCalendarIterationFrame.dispatch._proof_1_5
#print axioms ExactFourierCircuits.UniformCalendarIterationFrame.dispatch._proof_1_6
#print axioms ExactFourierCircuits.UniformCalendarIterationFrame.dispatch._proof_1_7
#print axioms ExactFourierCircuits.UniformCalendarIterationFrame.dispatch._proof_1_8
#print axioms ExactFourierCircuits.UniformCalendarIterationFrame.dispatch._proof_1_9
#print axioms ExactFourierCircuits.UniformCalendarIterationFrame.preparation
#print axioms ExactFourierCircuits.UniformCalendarIterationFrame.preparation._proof_1_1
#print axioms ExactFourierCircuits.UniformCalendarIterationFrame.preparation._proof_1_2
#print axioms ExactFourierCircuits.UniformCalendarIterationFrame.preparation._proof_1_3
#print axioms ExactFourierCircuits.UniformCalendarIterationFrame.trans
