import UniformActualPreparedSectorRootBody
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformActualPreparedSectorRootBody.root_body
#print axioms ExactFourierCircuits.UniformActualPreparedSectorRootBody.root_body._proof_1_1
#print axioms ExactFourierCircuits.UniformActualPreparedSectorRootBody.root_body._proof_1_2
#print axioms ExactFourierCircuits.UniformActualPreparedSectorRootBody.root_body._proof_1_3
#print axioms ExactFourierCircuits.UniformActualPreparedSectorRootBody.root_body._proof_1_4
#print axioms ExactFourierCircuits.UniformActualPreparedSectorRootBody.root_body._proof_1_5
