import UniformForwardMatchingFactorHeaderCount
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformForwardMatchingFactorHeaderPreparation.execution_with_count
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorHeaderPreparation.execution_with_count._proof_1_1
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorHeaderPreparation.execution_with_count._proof_1_2
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorHeaderPreparation.execution_with_count._proof_1_3
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorHeaderPreparation.execution_with_count._proof_1_4
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorHeaderPreparation.execution_with_count._proof_1_5
