import UniformForwardMatchingFactorChunk

-- Inventory uses the defining Lean module, including generated declarations.
set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.AfterChunk
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.AfterChunk.casesOn
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.AfterChunk.count
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.AfterChunk.header
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.AfterChunk.high
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.AfterChunk.mk
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.AfterChunk.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.AfterChunk.outputs
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.AfterChunk.outside
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.AfterChunk.processed
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.AfterChunk.rec
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.AfterChunk.recOn
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.AfterChunk.roots
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.AfterChunk.saved
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.AfterChunk.scalar
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.AfterChunk.table
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.AfterChunk.withPC
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.AfterChunk.zero
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.after_chunk
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.after_chunk._proof_1_1
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.after_chunk._proof_1_2
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.chunk_execution
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.chunk_execution._proof_1_1
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.chunk_execution._proof_1_2
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.chunk_execution._proof_1_3
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.chunk_execution._proof_1_4
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.chunk_execution._proof_1_5
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.originalRows
#print axioms ExactFourierCircuits.UniformForwardMatchingFactorPreparation.originalRows._proof_1
