import UniformRecursiveResidualRoleSemantics
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformNativeRecordRoles.paddingAddress.congr_simp
#print axioms ExactFourierCircuits.UniformRecursiveResidualRoleSemantics.active_congr
#print axioms ExactFourierCircuits.UniformRecursiveResidualRoleSemantics.active_edge
#print axioms ExactFourierCircuits.UniformRecursiveResidualRoleSemantics.edge_values
#print axioms ExactFourierCircuits.UniformRecursiveResidualRoleSemantics.padded_record
#print axioms ExactFourierCircuits.UniformRecursiveResidualRoleSemantics.replaceRole
#print axioms ExactFourierCircuits.UniformRecursiveResidualRoleSemantics.replaceRole.eq_1
#print axioms ExactFourierCircuits.UniformRecursiveResidualRoleSemantics.replace_present
#print axioms ExactFourierCircuits.UniformRecursiveResidualRoleSemantics.replace_present._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursiveResidualRoleSemantics.replace_values
#print axioms ExactFourierCircuits.UniformRecursiveResidualRoleSemantics.roleMap
