import UniformCRT
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformCRT.address
#print axioms ExactFourierCircuits.UniformCRT.address.congr_simp
#print axioms ExactFourierCircuits.UniformCRT.address.eq_1
#print axioms ExactFourierCircuits.UniformCRT.address_crt
#print axioms ExactFourierCircuits.UniformCRT.address_lt
#print axioms ExactFourierCircuits.UniformCRT.cofactor
#print axioms ExactFourierCircuits.UniformCRT.cofactor.congr_simp
#print axioms ExactFourierCircuits.UniformCRT.cofactor_coprime
#print axioms ExactFourierCircuits.UniformCRT.cofactor_eq_div
#print axioms ExactFourierCircuits.UniformCRT.cofactor_mul
#print axioms ExactFourierCircuits.UniformCRT.component_specified_root
#print axioms ExactFourierCircuits.UniformCRT.crt_sum
#print axioms ExactFourierCircuits.UniformCRT.decode
#print axioms ExactFourierCircuits.UniformCRT.decode._proof_1
#print axioms ExactFourierCircuits.UniformCRT.decode.congr_simp
#print axioms ExactFourierCircuits.UniformCRT.decode.eq_1
#print axioms ExactFourierCircuits.UniformCRT.decode_encode
#print axioms ExactFourierCircuits.UniformCRT.encode
#print axioms ExactFourierCircuits.UniformCRT.encode.eq_1
#print axioms ExactFourierCircuits.UniformCRT.encode_decode
#print axioms ExactFourierCircuits.UniformCRT.fourier_phase
#print axioms ExactFourierCircuits.UniformCRT.idempotent
#print axioms ExactFourierCircuits.UniformCRT.idempotent.congr_simp
#print axioms ExactFourierCircuits.UniformCRT.idempotent.eq_1
#print axioms ExactFourierCircuits.UniformCRT.idempotent_lt
#print axioms ExactFourierCircuits.UniformCRT.idempotent_other
#print axioms ExactFourierCircuits.UniformCRT.idempotent_projection
#print axioms ExactFourierCircuits.UniformCRT.idempotent_self
#print axioms ExactFourierCircuits.UniformCRT.inverseDigit
#print axioms ExactFourierCircuits.UniformCRT.inverseDigit.congr_simp
#print axioms ExactFourierCircuits.UniformCRT.inverseDigit.eq_1
#print axioms ExactFourierCircuits.UniformCRT.inverseDigit_lt
#print axioms ExactFourierCircuits.UniformCRT.inverse_localOutput
#print axioms ExactFourierCircuits.UniformCRT.localOutput
#print axioms ExactFourierCircuits.UniformCRT.localOutput.congr_simp
#print axioms ExactFourierCircuits.UniformCRT.localOutput.eq_1
#print axioms ExactFourierCircuits.UniformCRT.localOutput_inverse
#print axioms ExactFourierCircuits.UniformCRT.localPermutation
#print axioms ExactFourierCircuits.UniformCRT.localPermutation._proof_1
#print axioms ExactFourierCircuits.UniformCRT.localPermutation._proof_2
#print axioms ExactFourierCircuits.UniformCRT.localPermutation._proof_3
#print axioms ExactFourierCircuits.UniformCRT.localPermutation._proof_4
#print axioms ExactFourierCircuits.UniformCRT.localPermutation._proof_5
#print axioms ExactFourierCircuits.UniformCRT.localPermutation._proof_6
#print axioms ExactFourierCircuits.UniformCRT.local_root_primitive
#print axioms ExactFourierCircuits.UniformCRT.matrix_factorization
#print axioms ExactFourierCircuits.UniformCRT.permutation
#print axioms ZMod.prodEquivPi.congr_simp
