import UniformCanonicalCacheSlotComplete
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotComplete.geometry
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotComplete.geometry._proof_1_1
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotComplete.geometry._proof_1_10
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotComplete.geometry._proof_1_2
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotComplete.geometry._proof_1_3
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotComplete.geometry._proof_1_4
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotComplete.geometry._proof_1_5
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotComplete.geometry._proof_1_6
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotComplete.geometry._proof_1_7
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotComplete.geometry._proof_1_8
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotComplete.geometry._proof_1_9
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotComplete.output_ends
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotComplete.output_ends._proof_1_1
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotComplete.output_ends._proof_1_2
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotComplete.output_ends._proof_1_3
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotComplete.output_ends._proof_1_4
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotComplete.output_ends._proof_1_5
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotComplete.output_ends._proof_1_6
#print axioms ExactFourierCircuits.UniformCanonicalCacheSlotComplete.widths
