import UniformAxisCachePreparationRetention
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.Core
#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.Core.casesOn
#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.Core.conjugate
#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.Core.header
#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.Core.metadata
#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.Core.mk
#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.Core.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.Core.operands
#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.Core.rec
#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.Core.recOn
#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.Core.seed
#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.Core.withPC
#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.frontier_above_slab
#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.frontier_above_slab._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.slab_above_seed_word
#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.slab_above_seed_word._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.transport
#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.transport._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.transport._proof_1_10
#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.transport._proof_1_11
#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.transport._proof_1_12
#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.transport._proof_1_2
#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.transport._proof_1_3
#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.transport._proof_1_4
#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.transport._proof_1_5
#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.transport._proof_1_6
#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.transport._proof_1_7
#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.transport._proof_1_8
#print axioms ExactFourierCircuits.UniformAxisCachePreparationRetention.transport._proof_1_9
