import UniformLayerScheduleRestriction
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformLayerRestriction.full_diagonalStep_restricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.full_diagonalStep_restricted._simp_1
#print axioms ExactFourierCircuits.UniformLayerRestriction.padded_restricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.preparedSchedule_restricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.sandwich_restricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.sandwich_restricted._simp_1_1
#print axioms ExactFourierCircuits.UniformLayerRestriction.sandwich_restricted._simp_1_2
#print axioms ExactFourierCircuits.UniformLayerRestriction.schedule_restricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.slot_restricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.specifiedSchedule_restricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.symmetric_restricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.symmetric_restricted._simp_1_1
#print axioms ExactFourierCircuits.UniformLayerRestriction.symmetric_restricted._simp_1_2
#print axioms ExactFourierCircuits.UniformLayerRestriction.transposeLayer_restricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.transposeStep_restricted
#print axioms ExactFourierCircuits.UniformLayerRestriction.transpose_restricted
#print axioms ExactFourierCircuits.UniformLayerSnapshot.synchronized_finite_snapshot
