import UniformInverseMatchingFactorResult
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.Result.factor_values
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.Result.pool_coefficients
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.Result.tensor_pool
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.Result.tensor_pool._simp_1_1
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.execution
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.poolEntry
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.poolEntry._proof_1
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.poolEntry._proof_2
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.poolEntry._proof_3
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.poolEntry.congr_simp
#print axioms ExactFourierCircuits.UniformInverseMatchingFactorPreparation.selectedValue
