import UniformJointDiagonalHeaderInstallation
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformJointAllocation.allocate.eq_1
#print axioms ExactFourierCircuits.UniformJointDiagonalHeaderInstallation.coefficient
#print axioms ExactFourierCircuits.UniformJointDiagonalHeaderInstallation.coefficient_fit
#print axioms ExactFourierCircuits.UniformJointDiagonalHeaderInstallation.coefficient_stack
#print axioms ExactFourierCircuits.UniformJointDiagonalHeaderInstallation.coefficient_stack._proof_1_1
#print axioms ExactFourierCircuits.UniformJointDiagonalHeaderInstallation.execution
#print axioms ExactFourierCircuits.UniformJointDiagonalHeaderInstallation.input
#print axioms ExactFourierCircuits.UniformJointDiagonalHeaderInstallation.pools_before
#print axioms ExactFourierCircuits.UniformJointDiagonalHeaderInstallation.pools_before._proof_1_1
#print axioms ExactFourierCircuits.UniformJointDiagonalHeaderInstallation.rows
#print axioms ExactFourierCircuits.UniformJointDiagonalHeaderInstallation.rows._proof_1
#print axioms ExactFourierCircuits.UniformJointDiagonalHeaderInstallation.rows._proof_2
#print axioms ExactFourierCircuits.UniformJointDiagonalHeaderInstallation.source_disjoint
