import UniformRecursivePaddingRecord
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformRecursivePaddingRecord.actual_good
#print axioms ExactFourierCircuits.UniformRecursivePaddingRecord.execution
#print axioms ExactFourierCircuits.UniformRecursivePaddingRecord.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursivePaddingRecord.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursivePaddingRecord.padding_parent
#print axioms ExactFourierCircuits.UniformRecursivePaddingRecord.padding_parent._proof_1_1
#print axioms ExactFourierCircuits.UniformRecursivePaddingRecord.padding_parent._proof_1_10
#print axioms ExactFourierCircuits.UniformRecursivePaddingRecord.padding_parent._proof_1_11
#print axioms ExactFourierCircuits.UniformRecursivePaddingRecord.padding_parent._proof_1_12
#print axioms ExactFourierCircuits.UniformRecursivePaddingRecord.padding_parent._proof_1_13
#print axioms ExactFourierCircuits.UniformRecursivePaddingRecord.padding_parent._proof_1_14
#print axioms ExactFourierCircuits.UniformRecursivePaddingRecord.padding_parent._proof_1_2
#print axioms ExactFourierCircuits.UniformRecursivePaddingRecord.padding_parent._proof_1_3
#print axioms ExactFourierCircuits.UniformRecursivePaddingRecord.padding_parent._proof_1_4
#print axioms ExactFourierCircuits.UniformRecursivePaddingRecord.padding_parent._proof_1_5
#print axioms ExactFourierCircuits.UniformRecursivePaddingRecord.padding_parent._proof_1_6
#print axioms ExactFourierCircuits.UniformRecursivePaddingRecord.padding_parent._proof_1_7
#print axioms ExactFourierCircuits.UniformRecursivePaddingRecord.padding_parent._proof_1_8
#print axioms ExactFourierCircuits.UniformRecursivePaddingRecord.padding_parent._proof_1_9
#print axioms ExactFourierCircuits.UniformRecursivePaddingRecord.padding_pc
#print axioms ExactFourierCircuits.UniformRecursivePaddingRecord.vector_padding
