import UniformRecursivePaddingUnitEdge
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformRecursivePaddingUnitEdge.action_unit
#print axioms ExactFourierCircuits.UniformRecursivePaddingUnitEdge.basisWord_unit
#print axioms ExactFourierCircuits.UniformRecursivePaddingUnitEdge.bottomLabel
#print axioms ExactFourierCircuits.UniformRecursivePaddingUnitEdge.bottomLabel._proof_1
#print axioms ExactFourierCircuits.UniformRecursivePaddingUnitEdge.bottomLabel._proof_2
#print axioms ExactFourierCircuits.UniformRecursivePaddingUnitEdge.bottomLabel._proof_3
#print axioms ExactFourierCircuits.UniformRecursivePaddingUnitEdge.dimension
#print axioms ExactFourierCircuits.UniformRecursivePaddingUnitEdge.edgeBits_unit
#print axioms ExactFourierCircuits.UniformRecursivePaddingUnitEdge.edgeBits_unit._simp_1_1
#print axioms ExactFourierCircuits.UniformRecursivePaddingUnitEdge.inverse
#print axioms ExactFourierCircuits.UniformRecursivePaddingUnitEdge.macro_fixed
#print axioms ExactFourierCircuits.UniformRecursivePaddingUnitEdge.macro_unit
#print axioms ExactFourierCircuits.UniformRecursivePaddingUnitEdge.residual_full
#print axioms ExactFourierCircuits.UniformRecursivePaddingUnitEdge.topLabel
#print axioms ExactFourierCircuits.UniformRecursivePaddingUnitEdge.topLabel._proof_1
#print axioms ExactFourierCircuits.UniformRecursivePaddingUnitEdge.unitBasis
#print axioms ExactFourierCircuits.UniformRecursivePaddingUnitEdge.unitBasis._proof_1
#print axioms ExactFourierCircuits.UniformRecursivePaddingUnitEdge.unitBasis._proof_2
#print axioms ExactFourierCircuits.UniformRecursivePaddingUnitEdge.unitBasis_value
#print axioms ExactFourierCircuits.UniformRecursivePaddingUnitEdge.unitEdge
#print axioms ExactFourierCircuits.UniformRecursivePaddingUnitEdge.unitEdge._proof_1
#print axioms ExactFourierCircuits.UniformRecursivePaddingUnitEdge.unitEdge._proof_2
#print axioms ExactFourierCircuits.UniformRecursivePaddingUnitEdge.vectors
