import UniformResidualGatherPreparation
import Lean
set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformResidualGatherPreparation.copy_code
#print axioms ExactFourierCircuits.UniformResidualGatherPreparation.execution
#print axioms ExactFourierCircuits.UniformResidualGatherPreparation.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformResidualGatherPreparation.execution._proof_1_10
#print axioms ExactFourierCircuits.UniformResidualGatherPreparation.execution._proof_1_11
#print axioms ExactFourierCircuits.UniformResidualGatherPreparation.execution._proof_1_12
#print axioms ExactFourierCircuits.UniformResidualGatherPreparation.execution._proof_1_13
#print axioms ExactFourierCircuits.UniformResidualGatherPreparation.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformResidualGatherPreparation.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformResidualGatherPreparation.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformResidualGatherPreparation.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformResidualGatherPreparation.execution._proof_1_7
#print axioms ExactFourierCircuits.UniformResidualGatherPreparation.execution._proof_1_8
#print axioms ExactFourierCircuits.UniformResidualGatherPreparation.execution._proof_1_9
#print axioms ExactFourierCircuits.UniformResidualGatherPreparation.halt_at
#print axioms ExactFourierCircuits.UniformResidualGatherPreparation.prepare_code
#print axioms ExactFourierCircuits.UniformResidualGatherPreparation.program
#print axioms ExactFourierCircuits.UniformResidualGatherPreparation.program.eq_1
#print axioms ExactFourierCircuits.UniformResidualGatherPreparation.program_length
#print axioms ExactFourierCircuits.UniformResidualGatherPreparation.setup
#print axioms ExactFourierCircuits.UniformResidualGatherPreparation.setup.eq_1
#print axioms ExactFourierCircuits.UniformResidualGatherPreparation.setup_code
