import UniformResidualAddressToggleMachine
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformBlockXorMachine.Changed.eq_1
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.Changed
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.Frame
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.Frame.casesOn
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.Frame.mk
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.Frame.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.Frame.natHeap
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.Frame.natReg
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.Frame.outputs
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.Frame.rec
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.Frame.recOn
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.Frame.roots
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.Frame.scalarHeap
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.Frame.scalarReg
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.execution
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.execution._proof_1_10
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.execution._proof_1_11
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.execution._proof_1_12
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.execution._proof_1_13
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.execution._proof_1_7
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.halt_at
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.head
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.head.eq_1
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.head_code
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.program
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.program_length
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.tail
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.tail.eq_1
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.tail_code
#print axioms ExactFourierCircuits.UniformResidualAddressToggleMachine.xor_code
