import TripleNetwork
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.ScalarNetwork.G.congr_simp
#print axioms ExactFourierCircuits.ScalarNetwork.R.congr_simp
#print axioms ExactFourierCircuits.TripleNetwork.Bank
#print axioms ExactFourierCircuits.TripleNetwork.Profile
#print axioms ExactFourierCircuits.TripleNetwork.State
#print axioms ExactFourierCircuits.TripleNetwork.State._sizeOf_1
#print axioms ExactFourierCircuits.TripleNetwork.State._sizeOf_inst
#print axioms ExactFourierCircuits.TripleNetwork.State.casesOn
#print axioms ExactFourierCircuits.TripleNetwork.State.center
#print axioms ExactFourierCircuits.TripleNetwork.State.ctorIdx
#print axioms ExactFourierCircuits.TripleNetwork.State.ext
#print axioms ExactFourierCircuits.TripleNetwork.State.ext.match_1
#print axioms ExactFourierCircuits.TripleNetwork.State.ext_iff
#print axioms ExactFourierCircuits.TripleNetwork.State.mk
#print axioms ExactFourierCircuits.TripleNetwork.State.mk._flat_ctor
#print axioms ExactFourierCircuits.TripleNetwork.State.mk.inj
#print axioms ExactFourierCircuits.TripleNetwork.State.mk.injEq
#print axioms ExactFourierCircuits.TripleNetwork.State.mk.noConfusion
#print axioms ExactFourierCircuits.TripleNetwork.State.mk.sizeOf_spec
#print axioms ExactFourierCircuits.TripleNetwork.State.noConfusion
#print axioms ExactFourierCircuits.TripleNetwork.State.noConfusionType
#print axioms ExactFourierCircuits.TripleNetwork.State.rec
#print axioms ExactFourierCircuits.TripleNetwork.State.recOn
#print axioms ExactFourierCircuits.TripleNetwork.State.side
#print axioms ExactFourierCircuits.TripleNetwork.State.x
#print axioms ExactFourierCircuits.TripleNetwork.State.y
#print axioms ExactFourierCircuits.TripleNetwork.axisCoordinates
#print axioms ExactFourierCircuits.TripleNetwork.bank_card
#print axioms ExactFourierCircuits.TripleNetwork.invocation
#print axioms ExactFourierCircuits.TripleNetwork.profile_card
#print axioms ExactFourierCircuits.TripleNetwork.reverseEdge
#print axioms ExactFourierCircuits.TripleNetwork.reverseEdge._proof_1
#print axioms ExactFourierCircuits.TripleNetwork.reverseEdge_involutive
#print axioms ExactFourierCircuits.TripleNetwork.reverseInvocation
#print axioms ExactFourierCircuits.TripleNetwork.reverseInvocation.eq_1
#print axioms ExactFourierCircuits.TripleNetwork.reverseRows
#print axioms ExactFourierCircuits.TripleNetwork.reverseRows.eq_1
#print axioms ExactFourierCircuits.TripleNetwork.reverseRows_identity
#print axioms ExactFourierCircuits.TripleNetwork.reverseRows_identity._abel_1_3
#print axioms ExactFourierCircuits.TripleNetwork.reverseStage
#print axioms ExactFourierCircuits.TripleNetwork.reverseStage.eq_1
#print axioms ExactFourierCircuits.TripleNetwork.reverseStage_identity
#print axioms ExactFourierCircuits.TripleNetwork.scalarNetwork
#print axioms ExactFourierCircuits.TripleNetwork.scalarNetwork._proof_1
#print axioms ExactFourierCircuits.TripleNetwork.scalarNetwork.eq_1
#print axioms ExactFourierCircuits.TripleNetwork.scalarNetwork_identity
#print axioms ExactFourierCircuits.TripleNetwork.slice
#print axioms ExactFourierCircuits.TripleNetwork.slice.eq_1
#print axioms ExactFourierCircuits.TripleNetwork.stage
#print axioms ExactFourierCircuits.TripleNetwork.stage.eq_1
#print axioms ExactFourierCircuits.TripleNetwork.stage_identity
#print axioms ExactFourierCircuits.TripleNetwork.swap
#print axioms ExactFourierCircuits.TripleNetwork.swap.eq_1
