import UniformActualCacheRectangleRetention
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformActualCacheRectangleRetention.Before
#print axioms ExactFourierCircuits.UniformActualCacheRectangleRetention.Before.casesOn
#print axioms ExactFourierCircuits.UniformActualCacheRectangleRetention.Before.counts
#print axioms ExactFourierCircuits.UniformActualCacheRectangleRetention.Before.mk
#print axioms ExactFourierCircuits.UniformActualCacheRectangleRetention.Before.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformActualCacheRectangleRetention.Before.permutation
#print axioms ExactFourierCircuits.UniformActualCacheRectangleRetention.Before.pool
#print axioms ExactFourierCircuits.UniformActualCacheRectangleRetention.Before.radix_eq
#print axioms ExactFourierCircuits.UniformActualCacheRectangleRetention.Before.ranges
#print axioms ExactFourierCircuits.UniformActualCacheRectangleRetention.Before.rec
#print axioms ExactFourierCircuits.UniformActualCacheRectangleRetention.Before.recOn
#print axioms ExactFourierCircuits.UniformActualCacheRectangleRetention.Before.rows
#print axioms ExactFourierCircuits.UniformActualCacheRectangleRetention.all_completed
#print axioms ExactFourierCircuits.UniformActualCacheRectangleRetention.complete
#print axioms ExactFourierCircuits.UniformActualCacheRectangleRetention.complete._proof_1_1
#print axioms ExactFourierCircuits.UniformActualCacheRectangleRetention.complete._proof_1_2
#print axioms ExactFourierCircuits.UniformActualCacheRectangleRetention.complete._proof_1_3
#print axioms ExactFourierCircuits.UniformActualCacheRectangleRetention.complete._proof_1_4
#print axioms ExactFourierCircuits.UniformActualCacheRectangleRetention.complete._proof_1_5
#print axioms ExactFourierCircuits.UniformActualCacheRectangleRetention.complete._proof_1_6
#print axioms ExactFourierCircuits.UniformActualCacheRectangleRetention.complete._proof_1_7
