import UniformNativeTerminalExchange
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.TerminalWords.points.eq_1
#print axioms ExactFourierCircuits.UniformNativeExchangeRecordMachine.Pair.mk.congr_simp
#print axioms ExactFourierCircuits.UniformNativeExchangeRecordMachine.actions.eq_1
#print axioms ExactFourierCircuits.UniformNativeTerminalExchange.actions_bank
#print axioms ExactFourierCircuits.UniformNativeTerminalExchange.actions_outside
#print axioms ExactFourierCircuits.UniformNativeTerminalExchange.actions_roleMatrix
#print axioms ExactFourierCircuits.UniformNativeTerminalExchange.exchange_pointwise
#print axioms ExactFourierCircuits.UniformNativeTerminalExchange.exchange_pointwise._simp_1_5
#print axioms ExactFourierCircuits.UniformNativeTerminalExchange.exchange_pointwise._simp_1_6
#print axioms ExactFourierCircuits.UniformNativeTerminalExchange.instDecidableEq_uniformNativeTerminalExchange
#print axioms ExactFourierCircuits.UniformNativeTerminalExchange.native_active_exchange_values
#print axioms ExactFourierCircuits.UniformNativeTerminalExchange.pair
#print axioms ExactFourierCircuits.UniformNativeTerminalExchange.pair._proof_1
#print axioms ExactFourierCircuits.UniformNativeTerminalExchange.pair._proof_2
#print axioms ExactFourierCircuits.UniformNativeTerminalExchange.pair.eq_1
#print axioms ExactFourierCircuits.UniformNativeTerminalExchange.pairs
#print axioms ExactFourierCircuits.UniformNativeTerminalExchange.pairs.eq_1
#print axioms ExactFourierCircuits.UniformNativeTerminalExchange.roleMatrix
#print axioms ExactFourierCircuits.UniformNativeTerminalExchange.roleMatrix.eq_1
#print axioms ExactFourierCircuits.UniformNativeTerminalExchange.roleMatrix_apply
#print axioms ExactFourierCircuits.UniformNativeTerminalExchange.rolePerm
#print axioms ExactFourierCircuits.UniformNativeTerminalExchange.rolePerm.eq_1
#print axioms ExactFourierCircuits.UniformNativeTerminalExchange.roleSign
#print axioms ExactFourierCircuits.UniformNativeTerminalExchange.roleSign.eq_1
#print axioms ExactFourierCircuits.UniformNativeTerminalExchange.roleSign.match_1
#print axioms ExactFourierCircuits.UniformNativeTerminalExchange.values_bank
#print axioms ExactFourierCircuits.UniformNativeTerminalExchange.values_outside
