import UniformProducedMatchingSlotDirectory
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformGlobalDiagonalRowsMachine.Pools.eq_1
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.F.Config
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.L.Row
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.L.Slot
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.Produced
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.Produced.casesOn
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.Produced.entry
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.Produced.execution
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.Produced.heap
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.Produced.mk
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.Produced.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.Produced.outputs
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.Produced.pc
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.Produced.permutation
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.Produced.prefixHeap
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.Produced.rec
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.Produced.recOn
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.Produced.registers
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.Produced.roots
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.Produced.row
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.Produced.ticks
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.Produced.widths
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.broadcast
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.broadcast._simp_1_1
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.broadcastAxis
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.broadcastPool
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.broadcastPool._proof_1
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.broadcastPool._proof_2
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.broadcastPool.congr_simp
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.broadcastPool.eq_1
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.edges_of_table
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.forward
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.forwardAxis
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.forwardAxis._proof_1
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.forwardAxis._proof_2
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.forwardAxis._proof_3
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.from_rows
#print axioms ExactFourierCircuits.UniformProducedMatchingSlotDirectory.rowAxis
#print axioms ExactFourierCircuits.UniformTensorDiagonalBankMachine.Coefficients.eq_1
