import UniformCacheLowWholePrefix
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformAxisCacheWholePrefix.rectangle_axis_low
#print axioms ExactFourierCircuits.UniformAxisCacheWholePrefix.rectangle_axis_low._proof_1_1
#print axioms ExactFourierCircuits.UniformAxisCacheWholePrefix.rectangle_axis_low._proof_1_2
#print axioms ExactFourierCircuits.UniformAxisCacheWholePrefix.rectangle_axis_low._proof_1_3
