import UniformCacheTimingBankStep
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformCacheTimingBankStep.Bank.pc
#print axioms ExactFourierCircuits.UniformCacheTimingBankStep.bank_step
#print axioms ExactFourierCircuits.UniformCacheTimingBankStep.bank_step._proof_1_1
#print axioms ExactFourierCircuits.UniformCacheTimingBankStep.bank_step._proof_1_2
#print axioms ExactFourierCircuits.UniformCacheTimingBankStep.bank_step._proof_1_3
#print axioms ExactFourierCircuits.UniformCacheTimingBankStep.bank_step._proof_1_4
#print axioms ExactFourierCircuits.UniformCacheTimingBankStep.bank_step._proof_1_5
#print axioms ExactFourierCircuits.UniformCacheTimingBankStep.bank_step._proof_1_6
#print axioms ExactFourierCircuits.UniformCacheTimingBankStep.bank_step._proof_1_7
#print axioms ExactFourierCircuits.UniformCacheTimingBankStep.bank_step._proof_1_8
#print axioms ExactFourierCircuits.UniformCacheTimingBankStep.outside
#print axioms ExactFourierCircuits.UniformCacheTimingBankStep.outside._proof_1_1
#print axioms ExactFourierCircuits.UniformCacheTimingBankStep.outside._proof_1_2
