import UniformProducedSectorChildABI
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.Args
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.Args.casesOn
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.Args.directory
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.Args.frontier
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.Args.index
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.Args.mk
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.Args.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.Args.rec
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.Args.recOn
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.GroupedSource
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.execution
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.execution._proof_1_7
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.execution._proof_1_8
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.execution_keeps
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.halt_at
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.halt_at._proof_1_1
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.halt_at._proof_1_2
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.producer_free
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.producer_keeps
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.program
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.programFor
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.programFor.eq_1
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.program_length
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.relocate_arguments
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup.eq_1
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_code
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_code._proof_1_1
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_code._proof_1_2
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_10
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_11
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_12
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_13
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_14
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_15
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_16
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_17
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_18
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_19
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_2
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_20
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_21
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_22
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_23
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_24
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_25
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_26
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_27
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_28
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_29
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_3
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_30
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_31
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_32
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_33
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_34
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_35
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_36
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_37
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_38
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_39
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_4
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_40
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_41
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_42
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_43
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_44
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_45
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_5
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_6
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_7
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_8
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_frame._proof_1_9
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_header
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_length
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_safe
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.setup_safe._proof_1_2
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.states
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.states.eq_1
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.writesArguments
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.writesArguments._sparseCasesOn_1
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.writesArguments._sparseCasesOn_1.else_eq
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.writesArguments.eq_1
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.writesArguments.eq_2
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.writesArguments.eq_3
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.writesArguments.eq_4
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.writesArguments.eq_5
#print axioms ExactFourierCircuits.UniformProducedSectorChildABI.writesArguments.match_1

open Lean Elab Command in
run_cmd do
 let env ← getEnv
 for (name, _) in env.constants.toList do
  if "_private.UniformProducedSectorChildABI.".isPrefixOf name.toString then
   let axs ← collectAxioms name
   logInfo m!"{name} depends on axioms: {axs.toList}"
