import UniformDirectLeafForestContents
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.Contents
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.Contents.cached
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.Contents.casesOn
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.Contents.counts
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.Contents.mk
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.Contents.mk._flat_ctor
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.Contents.ranges
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.Contents.rec
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.Contents.recOn
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.Contents.root
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.ofPost
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.slot_bounds
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.slot_bounds._proof_1_1
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.slot_bounds._proof_1_2
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.slot_bounds._proof_1_3
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.transport
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.transport._proof_1_1
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.transport._proof_1_10
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.transport._proof_1_11
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.transport._proof_1_12
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.transport._proof_1_13
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.transport._proof_1_14
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.transport._proof_1_15
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.transport._proof_1_2
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.transport._proof_1_3
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.transport._proof_1_4
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.transport._proof_1_5
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.transport._proof_1_6
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.transport._proof_1_7
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.transport._proof_1_8
#print axioms ExactFourierCircuits.UniformDirectLeafForestContents.transport._proof_1_9
