import UniformLocalStoredRectanglePreparation
import Lean

set_option linter.auxLemma false

#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.C.program
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.S.program
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.W.conjugate
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.W.control
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.W.falseColors
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.W.falseDirectory
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.W.falsePalette
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.W.falseRows
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.W.inverse
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.W.lowRow
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.W.original
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.W.work
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.W.z
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.cache_code
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.execution
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.execution._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.execution._proof_1_10
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.execution._proof_1_11
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.execution._proof_1_12
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.execution._proof_1_13
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.execution._proof_1_14
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.execution._proof_1_2
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.execution._proof_1_3
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.execution._proof_1_4
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.execution._proof_1_5
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.execution._proof_1_6
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.execution._proof_1_7
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.execution._proof_1_8
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.execution._proof_1_9
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.halt_at
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.halt_at._proof_1_1
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.program
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.program.eq_1
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.program_length
#print axioms ExactFourierCircuits.UniformLocalStoredRectanglePreparation.setup_code
