import DFTModelSavingPadding
import DFTModelSavingNativeScalar
import UniformRecursivePaddingRole

set_option autoImplicit false

/-! Paper E (adc7f), §2.6, Theorem 2.6, pp. 11–12. Padding constructs
the actual unit record for each ascending role, then uses the same residual
child program. Its direction table is generated by charged code. -/
namespace ExactFourierCircuits.DFTModelSavingNativePaddingValue
open OAI.PowerSaving OAI.PowerSaving.RAM OAI.PowerSaving.RAM.Ty
open DFTModelClockControl DFTModelSavingRecords
open UniformFixedNetworkScheduleMachine (Record)
noncomputable section
attribute [local irreducible] DFTModelSavingRecords.residual DFTModelSavingRecords.padding DFTModelCacheRecords.unit
  DFTModelSavingScalar.program DFTModelSavingY.program DFTModelRecursiveExchange.program
  UniformRecursiveSavingProgram.unitRecord

lemma withRole_patch (r : Record) (q role : ℕ) :
    DFTModelCacheRecords.withRole q role r=
      UniformRecursivePaddingControl.patchRecord r q role := rfl

/-- Keep the printer syntax abstract while removing only billing fields. -/
theorem roleWith_value (U : Prog false (p w w) (Ty.a w))
    (h : Handler Port) (rest i : ℕ) (raw : Tape ℕ) (old node : Node.T) :
    (DFTModelSavingPadding.roleBillWith U h rest i raw old node).val=
      (Code.run DFTModelSavingRecords.residual h
        (rest,((run U (raw.look 1 0,raw.look 3 0+i)).val,node))).val := rfl

theorem role_value (h : Handler Port) (q start rest i : ℕ)
    (raw : Tape ℕ) (old node : Node.T)
    (columns : raw.look 1 0=q) (dest : raw.look 3 0=start) :
    (DFTModelSavingPadding.roleBill h rest i raw old node).val=
      (Code.run DFTModelSavingRecords.residual h
        (rest,((run DFTModelCacheRecords.unit (q,start+i)).val,node))).val := by
  rw [DFTModelSavingPadding.roleBill,roleWith_value,columns,dest]

theorem dispatch_value (R rest : ℕ) (h : Handler Port) (raw : Tape ℕ) (node : Node.T)
    (opcode : raw.look 0 0=5) :
    (Code.run (dispatch R) h (rest,(raw,node))).val=
      (Code.run DFTModelSavingRecords.padding h (rest,(raw,node))).val := by
  unfold dispatch
  rw [DFTModelSavingNativeScalar.ifz_value]
  change (if raw.look 0 0=0 then _ else _)=_
  rw [opcode,ite_eq_right (by decide)]
  rw [DFTModelSavingNativeScalar.ifz_value]
  change (if raw.look 0 0-1=0 then _ else _)=_
  rw [opcode,ite_eq_right (by decide)]
  rw [DFTModelSavingNativeScalar.ifz_value]
  change (if raw.look 0 0-2=0 then _ else _)=_
  rw [opcode,ite_eq_right (by decide)]
  rw [DFTModelSavingNativeScalar.ifz_value]
  change (if raw.look 0 0-3=0 then _ else _)=_
  rw [opcode,ite_eq_right (by decide)]
  rw [DFTModelSavingNativeScalar.ifz_value]
  change (if raw.look 0 0-4=0 then _ else _)=_
  rw [opcode,ite_eq_right (by decide)]
  rw [DFTModelSavingNativeScalar.ifz_value]
  change (if raw.look 0 0-5=0 then _ else _)=_
  rw [opcode,ite_eq_left (by decide)]

end
end ExactFourierCircuits.DFTModelSavingNativePaddingValue
