import DFTModelCacheRectangleBudgetArithmetic

set_option autoImplicit false
namespace ExactFourierCircuits.DFTModelCacheRectangleBudget
open OAI.PowerSaving OAI.PowerSaving.RAM
open UniformLocalRectangleDescriptors UniformAllAxisSeedPreparation
noncomputable section

/-- The occurrence count is generated by the genuine colored matching. -/
theorem generated_count {B : ℕ} (p : UniformChunkMatchingPreparation.Parameters)
    (layout : UniformChunkMatchingPreparation.Layout p B)
    (ha:p.height.a≤UniformCrossHeightPreparationMachine.widthOf p.height)
    (he:p.height.e≤UniformCrossHeightPreparationMachine.widthOf p.height) :
    2*(UniformChunkMatchingPreparation.indices p
      (UniformChunkMatchingPreparation.crossWord p ha he)).length≤p.radix :=
  UniformMatchingAxisTableMachine.matching_capacity p.radix
    (UniformChunkMatchingPreparation.physicalEdges layout _
      (UniformChunkMatchingPreparation.cross_domain p ha he))
    (UniformChunkMatchingPreparation.physical_matching layout _
      (UniformChunkMatchingPreparation.cross_degree p ha he))
    (UniformChunkMatchingPreparation.physical_range layout _)

/-- A generated rectangle discharges all local sizes, including the actual
matching count. Only the master-root contribution remains explicit. -/
theorem canonical_budget {B : ℕ} (n : ℕ) (j : Fin (axisCount n)) (q : Row)
    (original : UniformSeedHeightPreparation.Config)
    (c : UniformLocalCacheSlotHeaderMachine.Parameters) (slot : UniformLocalCacheChronology.Slot)
    (source : DFTModelCacheRectanglePreparation.ProducedRow (radix n j) q)
    (layout : UniformChunkMatchingPreparation.Layout
      (DFTModelCacheRectangleMetadata.chunk q original c slot) B) :
    let p:=DFTModelCacheRectangleMetadata.chunk q original c slot
    let hw:=DFTModelCacheRectangleMetadata.chunk_widths source original c slot
    DFTModelCacheRectangleCaller.workBudget n j q original c slot
      (UniformChunkMatchingPreparation.indices p
        (UniformChunkMatchingPreparation.crossWord p hw.1 hw.2)).length≤
      localCoefficient*(radix n j+1)^8+rootWork (UniformMasterRootMachine.order n) := by
  dsimp only
  let p:=DFTModelCacheRectangleMetadata.chunk q original c slot
  let hw:=DFTModelCacheRectangleMetadata.chunk_widths source original c slot
  have count:=generated_count p layout hw.1 hw.2
  obtain ⟨_,_,_,_,_,_,_,fit,qr⟩:=DFTModelCacheRectangleMetadata.produced_local source
  have width:DFTModelCacheRectanglePreparation.width q≤8*radix n j:=
    (DFTModelCacheRectanglePreparation.produced_width source).2.2
  have height:DFTModelCacheRectanglePreparation.height q≤8*radix n j:=
    (UniformRadixTwoDAG.width_ge_height _).trans width
  have split:q.split≤radix n j:=by
    have h:=(DFTModelCacheRectanglePreparation.produced_geometry source).2.2.2.1
    omega
  have radixEq:p.radix=q.width:=rfl
  have countBound:(UniformChunkMatchingPreparation.indices p
    (UniformChunkMatchingPreparation.crossWord p hw.1 hw.2)).length≤radix n j:=by omega
  exact local_budget (radix n j) (UniformMasterRootMachine.order n) p
    (DFTModelCacheRectangleMetadata.kernel n j q original)
    (UniformChunkMatchingPreparation.indices p
      (UniformChunkMatchingPreparation.crossWord p hw.1 hw.2)).length
    (DFTModelCacheRectanglePreparation.height q) qr countBound
    height height (by change q.a+q.e≤_; omega) width split

/-- Work of the actual closed caller, with internally generated topology,
matching rows, coefficients and factors. No supplied cost/count/table. -/
theorem actual_work {B : ℕ} (n : ℕ) (hn : 0<n) (j : Fin (axisCount n)) (q : Row)
    (original : UniformSeedHeightPreparation.Config)
    (c : UniformLocalCacheSlotHeaderMachine.Parameters) (slot : UniformLocalCacheChronology.Slot)
    (source : DFTModelCacheRectanglePreparation.ProducedRow (radix n j) q)
    (layout : UniformChunkMatchingPreparation.Layout
      (DFTModelCacheRectangleMetadata.chunk q original c slot) B)
    (height : slot.depth≤8*DFTModelCacheRectanglePreparation.height q+6)
    (positive : original.C+UniformToeplitzCrossDAG.bankSize
      (DFTModelCacheRectanglePreparation.height q)≤original.negative)
    (negative : original.negative+UniformToeplitzCrossDAG.bankSize
      (DFTModelCacheRectanglePreparation.height q)≤original.constants) :
    let x:=DFTModelCacheRectangleCaller.genuineInput n j q original slot
    (run DFTModelCacheRectangleCaller.program x).valid ∧
    (run DFTModelCacheRectangleCaller.program x).work≤
      localCoefficient*(radix n j+1)^8+rootWork (UniformMasterRootMachine.order n) := by
  obtain ⟨_,_,_,valid,work,_⟩:=DFTModelCacheRectangleCaller.specification
    n hn j q original c slot source layout height positive negative
  exact ⟨valid,work.trans (canonical_budget n j q original c slot source layout)⟩

end
end ExactFourierCircuits.DFTModelCacheRectangleBudget
