import Lake
open Lake DSL

package ExactFourierCircuits where
  leanOptions := #[⟨`autoImplicit, false⟩]

require mathlib from git
  "https://github.com/leanprover-community/mathlib4.git" @ "d13f23b723b8a846827a245b89c10fc7d3f11612"

@[default_target] lean_lib OAI where
  roots := #[`OAI]
  globs := #[`OAI.+]

lean_lib KernelIdentities

lean_lib ProjectionIdentities

lean_lib ConstructiveBridge

lean_lib SavingBudget

lean_lib BinaryFrames

lean_lib BinaryTensor

lean_lib TypedKernelWords

lean_lib BinaryComplement

lean_lib DirectionalWords

lean_lib ExplicitSeedBudget

lean_lib ScalarNetwork

lean_lib FrameSpectrum

lean_lib TensorWords

lean_lib FrameCommutation

lean_lib TripleNetwork

lean_lib RoleWords

lean_lib FrameWords

lean_lib BinaryResiduals

lean_lib TripleCounting

lean_lib BinaryProjection

lean_lib BinaryColumns

lean_lib NetworkTerminal

lean_lib RoleFrameWords

lean_lib ScalarSupport

lean_lib RectangularWords

lean_lib StageFrames

lean_lib FramedScheduleWords

lean_lib ResidualBudget

lean_lib TensorFusion

lean_lib GateFrames

lean_lib PaddingWords

lean_lib ColumnSchedule

lean_lib TerminalWords

lean_lib TripleInvocationFrames

lean_lib TripleStageAction

lean_lib TripleSchedule

lean_lib TripleColumnAction

lean_lib InvocationBudget

lean_lib MasterBudget

lean_lib ColumnTerminalFlat

lean_lib ExplicitSeed

lean_lib UniformMachine

lean_lib UniformExponent

lean_lib UniformRoots

lean_lib UniformLocalShear

lean_lib UniformBatching

lean_lib UniformChirp

lean_lib UniformScalarPreparation

lean_lib UniformTraversal

lean_lib UniformWorkingLength

lean_lib UniformAsymptotics

lean_lib UniformCyclic

lean_lib UniformDiagonal

lean_lib UniformMachineRuns

lean_lib UniformCRT

lean_lib UniformTraversalMachine

lean_lib UniformSelectedCRT

lean_lib UniformDirectMachine

lean_lib UniformWorkingPreparation

lean_lib UniformPowerMachine

lean_lib UniformNewton

lean_lib UniformDirectBounds

lean_lib UniformNetworkCost

lean_lib UniformPreparationMachine

lean_lib UniformIntegerScalarMachine

lean_lib UniformCRTMachine

lean_lib UniformLinearMachine

lean_lib UniformSectorPacking

lean_lib UniformRadixTwoDAG

lean_lib UniformAssembly

lean_lib UniformDAGLowering

lean_lib UniformAssembledDirect

lean_lib UniformReplayPrint

lean_lib UniformPrimeMachine
lean_lib UniformRadixTwoMachine

lean_lib UniformWorkingMachine

lean_lib UniformColoring

lean_lib UniformDFSProgram

lean_lib UniformWorkingCompletion

lean_lib UniformLayeredReplay

lean_lib UniformContext

lean_lib UniformInPlaceMachine

lean_lib UniformConvolutionDAG

lean_lib UniformMasterRootMachine

lean_lib UniformPairMachine

lean_lib UniformFixedNetwork

lean_lib UniformReciprocalPreparation

lean_lib UniformCKernelPreparation

lean_lib UniformResidualFibers

lean_lib UniformShearPreparation

lean_lib UniformToeplitzCrossDAG

lean_lib UniformWorkspacePlanner

lean_lib UniformCConstantsMachine

lean_lib UniformDirectToeplitz

lean_lib UniformKernelSpectrumPreparation

lean_lib UniformPairDiagonalMachine

lean_lib UniformDAGLayers

lean_lib UniformHadamardPairMachine

lean_lib UniformBoundedAssembly

lean_lib UniformCRTHeaderMachine

lean_lib UniformRankKernelPreparation

lean_lib UniformToeplitzChunkWord

lean_lib UniformChirpTableMachine

lean_lib UniformRootTableMachine

lean_lib UniformChirpPreparation

lean_lib UniformBalancedToeplitz

lean_lib UniformPaddedInputMachine

lean_lib UniformPaddedInputPreparation

lean_lib UniformNewtonTableMachine

lean_lib UniformChirpKernelMachine

lean_lib UniformChirpKernelPreparation

lean_lib UniformChirpOutputMachine

lean_lib UniformReciprocalMachine

lean_lib UniformLocalFourierWord

lean_lib UniformCRTTraversalMachine

lean_lib UniformNatCopyMachine

lean_lib UniformNormalizationMachine

lean_lib UniformNormalizationPreparation

lean_lib UniformCommonSlots

lean_lib UniformChirpPointwiseMachine

lean_lib UniformCRTTraversalCycle

lean_lib UniformGlobalNatPreparation

lean_lib UniformLocalFourierLayers

lean_lib UniformInitialPreparation

lean_lib UniformPermutationMachine

lean_lib UniformPermutationInverseMachine

lean_lib UniformInputPermutationPreparation

lean_lib UniformLocalPreparationDAG

lean_lib UniformRadixInstructionMachine

lean_lib UniformTensorAddressMachine

lean_lib UniformPermutationInversePreparation

lean_lib UniformRadixRowTableMachine

lean_lib UniformRadixPowerBankMachine

lean_lib UniformRootExtractionMachine

lean_lib UniformGlobalLocalPreparation

lean_lib UniformLocalPreparationReferences

lean_lib UniformScalarCopyMachine

lean_lib UniformOffsetLinearMachine

lean_lib UniformInitialLocalPreparation

lean_lib UniformSynchronizedLayers

lean_lib UniformSectorTensor

lean_lib UniformMasterRootSeedDAG

lean_lib UniformPreparedFFTMachine

lean_lib UniformMasterSynchronizedLayers

lean_lib UniformDyadicRootBankMachine

lean_lib UniformLocalSeedTableMachine

lean_lib UniformFFTInputMachine

lean_lib UniformSectorNetworkAction

lean_lib UniformSelectedDFSMachine
lean_lib CheckUniformSelectedDFSMachineAxioms

lean_lib UniformAllAxisSeedPreparation
lean_lib CheckUniformAllAxisSeedPreparationAxioms

lean_lib UniformCRTTransferMachine
lean_lib CheckUniformCRTTransferMachineAxioms

lean_lib UniformInitialTraversalPreparation
lean_lib CheckUniformInitialTraversalPreparationAxioms

lean_lib UniformAllAxisSeedCost
lean_lib CheckUniformAllAxisSeedCostAxioms

lean_lib UniformDyadicConvolutionMachine
lean_lib CheckUniformDyadicConvolutionMachineAxioms

lean_lib UniformOffsetPreparationMachine

lean_lib CheckUniformOffsetPreparationMachineAxioms

lean_lib UniformDAGLiteralBankMachine

lean_lib CheckUniformDAGLiteralBankMachineAxioms

lean_lib UniformTensorMonomialMachine

lean_lib CheckUniformTensorMonomialMachineAxioms

lean_lib UniformDAGLeafPreparationMachine

lean_lib CheckUniformDAGLeafPreparationMachineAxioms

lean_lib UniformPreparationRowTableMachine
lean_lib CheckUniformPreparationRowTableMachineAxioms

lean_lib UniformTensorDiagonalBankMachine
lean_lib CheckUniformTensorDiagonalBankMachineAxioms

lean_lib UniformPreparedDAGMachine
lean_lib CheckUniformPreparedDAGMachineAxioms

lean_lib UniformBorrowedCoordinateMachine
lean_lib CheckUniformBorrowedCoordinateMachineAxioms

lean_lib UniformWorkspaceSearchMachine
lean_lib CheckUniformWorkspaceSearchMachineAxioms

lean_lib UniformAllAxisDiagonalPreparation
lean_lib CheckUniformAllAxisDiagonalPreparationAxioms

lean_lib UniformPreparedDAGConjugateMachine
lean_lib CheckUniformPreparedDAGConjugateMachineAxioms

lean_lib UniformZeroFreeDiagonalMachine
lean_lib CheckUniformZeroFreeDiagonalMachineAxioms

lean_lib UniformPreparedZeroFreeDAGMachine
lean_lib CheckUniformPreparedZeroFreeDAGMachineAxioms

lean_lib UniformSectorTraversalOrder
lean_lib CheckUniformSectorTraversalOrderAxioms

lean_lib UniformInitialDiagonalTensorMachine
lean_lib CheckUniformInitialDiagonalTensorMachineAxioms

lean_lib UniformConvolutionTopologyMachine
lean_lib CheckUniformConvolutionTopologyMachineAxioms

lean_lib UniformContiguousPowerBankMachine
lean_lib CheckUniformContiguousPowerBankMachineAxioms

lean_lib UniformSectorMetadataMachine
lean_lib CheckUniformSectorMetadataMachineAxioms

lean_lib UniformRankKernelMachine
lean_lib CheckUniformRankKernelMachineAxioms

lean_lib UniformKernelSpectrumMachine
lean_lib CheckUniformKernelSpectrumMachineAxioms

lean_lib UniformToeplitzCrossTopologyMachine
lean_lib CheckUniformToeplitzCrossTopologyMachineAxioms

lean_lib UniformDAGDepthMachine
lean_lib CheckUniformDAGDepthMachineAxioms

lean_lib UniformSectorPackingMachine
lean_lib CheckUniformSectorPackingMachineAxioms

lean_lib UniformDAGBucketMachine
lean_lib CheckUniformDAGBucketMachineAxioms

lean_lib UniformReplayCoefficientMachine
lean_lib CheckUniformReplayCoefficientMachineAxioms

lean_lib UniformGreedyColorMachine
lean_lib CheckUniformGreedyColorMachineAxioms

lean_lib UniformCrossShearTableMachine
lean_lib CheckUniformCrossShearTableMachineAxioms
lean_lib UniformMatchingAxisTableMachine
lean_lib CheckUniformMatchingAxisTableMachineAxioms

lean_lib UniformRankCrossPreparationMachine
lean_lib CheckUniformRankCrossPreparationMachineAxioms

lean_lib UniformColorLayerTableMachine

lean_lib CheckUniformColorLayerTableMachineAxioms

lean_lib UniformCrossDepthReplayPreparation

lean_lib CheckUniformCrossDepthReplayPreparationAxioms

lean_lib UniformRankCrossReplayPreparationMachine

lean_lib CheckUniformRankCrossReplayPreparationMachineAxioms

lean_lib UniformInverseShearTableMachine
lean_lib CheckUniformInverseShearTableMachineAxioms
