import UniformCacheTimingReference
set_option autoImplicit false
namespace ExactFourierCircuits.UniformCacheTimingBottomUp
open UniformLocalCacheTreeMachine UniformLocalCacheTreeExecution UniformLocalCacheTreeCoverage
open UniformLocalCacheTiming UniformCacheTimingWalk UniformCacheTimingReference
open UniformBalancedToeplitz UniformWorkspacePlanner
open UniformLocalRectangleDescriptors (emittedCount)

def Values (k : ℕ) (visits : List Visit) (d : ℕ→ℕ) : Prop :=
 ∀ i (hi : i<visits.length), d (k+i)=taskDuration visits[i].task

def Fresh (k len : ℕ) (d : ℕ→ℕ) : Prop :=
 ∀ j, k≤j → j<k+len → d j=0

lemma bottomStep_parent (k : ℕ) (q : Visit) (d : ℕ→ℕ)
 (positive : 0<k) (earlier : q.task.parent<k) :
 bottomStep k q d q.task.parent=max (d q.task.parent)
  (if q.task.width<2 ∨ selected q.task.width=0 then directDuration q.task.width else d k+correction q) := by
 unfold bottomStep
 split_ifs <;> simp_all only [Function.update_apply] <;> split_ifs <;> omega

/-- The reverse pass completes all subtree values and propagates only its root
maximum to the earlier parent. This is an internal proof invariant, derived
below for the canonical list generated by the real printer. -/
lemma numbered_bottom {v : ℕ} (P : Plan v) (hp : Canonical P)
 (o k c parent side : ℕ) (d : ℕ→ℕ)
 (proper : k=0 ∨ parent<k)
 (fresh : Fresh k (numbered P o k c parent side).length d) :
 let visits:=numbered P o k c parent side
 let out:=bottomUpFrom k visits d
 Values k visits out ∧
 (∀ j, (j<k ∨ k+visits.length≤j) → (k=0 ∨ j≠parent) → out j=d j) ∧
 (0<k → out parent=max (d parent) (treeDuration (ofPlan P o))) := by
 dsimp only
 induction P generalizing o k c parent side d with
 | direct v cap =>
  have leaf : v<2 ∨ selected v=0 := hp
  let q : Visit:=⟨⟨v,o,parent,side⟩,c⟩
  have value : bottomStep k q d k=directDuration v := by
   rw [bottomStep_self k q d proper]
   simp only [q,leaf,ite_true]
  refine ⟨?_,?_,?_⟩
  · intro i hi
    have iz:i=0:=by simp only [numbered,List.length_singleton] at hi;omega
    subst i
    change bottomStep k q d (k+0)=taskDuration q.task
    rw [Nat.add_zero,value,taskDuration_ofPlan (.direct v cap) hp o parent side]
    rfl
  · intro j outside away
    apply bottomStep_other k q d j (by simp only [numbered,List.length_singleton] at outside;omega) away
  · intro pos
    have earlier:parent<k:=by omega
    change bottomStep k q d parent=_
    rw [bottomStep_parent k q d pos earlier]
    simp only [q,leaf,ite_true,ofPlan,treeDuration]
 | split v hn hv L R ihL ihR =>
  let lc:=c+7*emittedCount v
  let ls:=numbered L o (k+1) lc k 0
  let rs:=numbered R (o+v/2) (k+1+ls.length) (lc+7*visitSum ls) k 1
  let q : Visit:=⟨⟨v,o,parent,side⟩,c⟩
  have shape : numbered (.split v hn hv L R) o k c parent side=q::(ls++rs):=rfl
  have length : (numbered (.split v hn hv L R) o k c parent side).length=1+ls.length+rs.length := by
   rw [shape,List.length_cons,List.length_append];omega
  have leafFalse : ¬(v<2 ∨ selected v=0):=by omega
  have rightFresh : Fresh (k+1+ls.length) rs.length d := by
   intro j low high
   apply fresh j (by omega)
   rw [length];omega
  have rh:=ihR hp.2.2 (o+v/2) (k+1+ls.length) (lc+7*visitSum ls) k 1 d
   (Or.inr (by omega)) rightFresh
  let dr:=bottomUpFrom (k+1+ls.length) rs d
  change Values (k+1+ls.length) rs dr ∧
   (∀j,(j<k+1+ls.length ∨ k+1+ls.length+rs.length≤j) → (k+1+ls.length=0 ∨ j≠k) → dr j=d j) ∧
   (0<k+1+ls.length → dr k=max (d k) (treeDuration (ofPlan R (o+v/2)))) at rh
  have leftFresh : Fresh (k+1) ls.length dr := by
   intro j low high
   calc
    dr j=d j:=rh.2.1 j (Or.inl (by omega)) (Or.inr (by omega))
    _=0:=fresh j (by omega) (by rw [length];omega)
  have lh:=ihL hp.2.1 o (k+1) lc k 0 dr (Or.inr (by omega)) leftFresh
  let dl:=bottomUpFrom (k+1) ls dr
  change Values (k+1) ls dl ∧
   (∀j,(j<k+1 ∨ k+1+ls.length≤j) → (k+1=0 ∨ j≠k) → dl j=dr j) ∧
   (0<k+1 → dl k=max (dr k) (treeDuration (ofPlan L o))) at lh
  have folded : bottomUpFrom k (numbered (.split v hn hv L R) o k c parent side) d=
    bottomStep k q dl := by
   rw [shape,bottomUpFrom,bottomUpFrom_append]
  have drk : dr k=treeDuration (ofPlan R (o+v/2)) := by
   have h:=rh.2.2 (by omega)
   have zero:=fresh k (le_refl k) (by rw [length];omega)
   simpa only [zero,Nat.zero_max] using h
  have dlk : dl k=max (treeDuration (ofPlan L o)) (treeDuration (ofPlan R (o+v/2))) := by
   have h:=lh.2.2 (by omega)
   simpa only [drk,Nat.max_comm] using h
  have value : bottomStep k q dl k=treeDuration (ofPlan (.split v hn hv L R) o) := by
   rw [bottomStep_self k q dl proper]
   have rows : correction q=rectanglesDuration (UniformLocalRectangleDescriptors.rows v o (selected v)) := by
    simp only [correction,currentRows,q,leafFalse,ite_false]
   simp only [q,leafFalse,ite_false,dlk,rows,ofPlan,treeDuration]
  rw [folded]
  refine ⟨?_,?_,?_⟩
  · change Values k (q::(ls++rs)) (bottomStep k q dl)
    intro i hi
    cases i with
    | zero =>
     simp only [Nat.add_zero,List.getElem_cons_zero]
     change bottomStep k q dl k=taskDuration ⟨v,o,parent,side⟩
     rw [taskDuration_ofPlan (.split v hn hv L R) hp o parent side]
     exact value
    | succ j =>
     have hj:j<ls.length+rs.length:=by simpa only [List.length_cons,List.length_append,Nat.succ_lt_succ_iff] using hi
     rw [List.getElem_cons_succ,bottomStep_other k q dl (k+(j+1)) (by omega) (by
      rcases proper with hz|hp
      · exact Or.inl hz
      · exact Or.inr (by dsimp [q];omega))]
     by_cases left:j<ls.length
     · rw [List.getElem_append_left left]
       have h:=lh.1 j left
       simpa only [Nat.add_assoc,Nat.add_comm,Nat.add_left_comm] using h
     · have right:j-ls.length<rs.length:=by omega
       rw [List.getElem_append_right (by omega)]
       have h:=rh.1 (j-ls.length) right
       have keep:=lh.2.1 (k+(j+1)) (Or.inr (by omega)) (Or.inr (by omega))
       rw [keep]
       rw [show k+(j+1)=k+1+ls.length+(j-ls.length) by omega]
       exact h
  · intro j outside away
    rw [bottomStep_other k q dl j (by rw [length] at outside;omega) away]
    rw [lh.2.1 j (by rw [length] at outside;omega) (Or.inr (by rw [length] at outside;omega))]
    exact rh.2.1 j (by rw [length] at outside;omega) (Or.inr (by rw [length] at outside;omega))
  · intro pos
    have earlier:parent<k:=by omega
    have keepL:=lh.2.1 parent (Or.inl (by omega)) (Or.inr (by omega))
    have keepR:=rh.2.1 parent (Or.inl (by omega)) (Or.inr (by omega))
    have keep : dl parent=d parent:=keepL.trans keepR
    rw [bottomStep_parent k q dl pos earlier,keep]
    congr 1
    have self:=bottomStep_self k q dl proper
    exact self.symm.trans value

/-- Every duration in the actual173 output's reverse pass equals the true
parallel-child/sequential-rectangle schedule duration. -/
lemma root_bottomUp (v o R i : ℕ)
 (hi:i<(walk (2*v+1) 0 R [⟨v,o,0,0⟩]).1.length) :
 bottomUp (walk (2*v+1) 0 R [⟨v,o,0,0⟩]).1 i=
 taskDuration (walk (2*v+1) 0 R [⟨v,o,0,0⟩]).1[i].task := by
 have hiN : i<(numbered (plan v) o 0 R 0 0).length:=by simpa only [root_walk_numbered] using hi
 have h:=numbered_bottom (plan v) (plan_canonical v) o 0 R 0 0 (fun _=>0) (Or.inl rfl)
  (by intro j low high;rfl)
 simpa only [root_walk_numbered,Nat.zero_add,bottomUp] using h.1 i hiN

end ExactFourierCircuits.UniformCacheTimingBottomUp
