import UniformSectorPaddingMachine
set_option autoImplicit false
namespace ExactFourierCircuits.UniformSectorPaddingPreparation
open UniformMachine UniformAssembly
open UniformTensorMonomialMachine
noncomputable section
/-- Ordinary packed source/directory/index headers4472..4474. Width, buffer
base and packed source offset are physically loaded from the real five-cell
record; helper25 receives no ready caller headers. -/
def setup:List Op:=[.literal 4476 1,.literal 4477 5,.mul 4478 4474 4477,
 .add 4478 4473 4478,.add 4478 4478 4476,.getNat 4460 4478,
 .add 4478 4478 4476,.getNat 4462 4478,.add 4478 4478 4476,
 .getNat 4479 4478,.add 4461 4472 4479]
-- Eleven setup instructions, twenty-five helper instructions, one final halt.
def programFor (W:ℕ):Program:=setup.map Op.code++
 (UniformSectorPaddingMachine.programFor W).map (relocate 11 36)++[.halt]
def program:Program:=programFor ExplicitSeedBudget.paddedRoles
lemma program_length (W:ℕ):(programFor W).length=37:=by
 simp only[programFor,List.length_append,List.length_map,
  UniformSectorPaddingMachine.program_length,List.length_singleton];rfl
lemma setup_code (W:ℕ):BlockAt setup (programFor W) 0:=by
 intro i hi;change i < 11 at hi;interval_cases i <;>rfl
lemma padding_code (W:ℕ):CodeAt (UniformSectorPaddingMachine.programFor W) (programFor W) 11 36:=by
 exact UniformRankCrossPreparationMachine.segment_code (setup.map Op.code) [.halt] _ 11 36 rfl
lemma halt_at (W:ℕ):(programFor W)[36]?=some .halt:=by
 unfold programFor
 rw[List.getElem?_append_right (by simp only[List.length_append,List.length_map,
  UniformSectorPaddingMachine.program_length];change 11+25 ≤ 36;omega)]
 simp only[List.length_append,List.length_map,UniformSectorPaddingMachine.program_length];rfl
structure Header (S E i:ℕ) (s:State):Prop where
 source:s.natReg 4472=S
 directory:s.natReg 4473=E
 index:s.natReg 4474=i
lemma setup_header {W S E A i:ℕ} {st:UniformSectorPacking.BlockState} {s:State}
 (h:Header S E i s) (cell:UniformSectorBatchDirectoryMachine.BatchCell W E A i st s):
 UniformSectorPaddingMachine.Header st.width (S+st.start) (A+W*st.start) (applyBlock setup s):=by
 rcases cell with ⟨_hq,hw,ha,hs,_ht⟩
 simp only[Nat.add_assoc] at hw ha hs
 constructor <;> simp[setup,applyBlock,Op.apply,writeNat,next,h.source,h.directory,h.index,
  hw,ha,hs,Nat.mul_comm i 5,Nat.add_assoc]
lemma setup_safe {W S E A i B:ℕ} {st:UniformSectorPacking.BlockState} {s:State}
 (h:Header S E i s) (cell:UniformSectorBatchDirectoryMachine.BatchCell W E A i st s)
 (readFit:E+5*(i+1) ≤ B) (sourceFit:S+st.start+st.width ≤ B) (wb:WordBound B s):
 readable setup s ∧peak setup s ≤ B:=by
 have hw:st.width ≤ B:=(wb.2.2.1 _ _ cell.2.1).2
 have ha:A+W*st.start ≤ B:=(wb.2.2.1 _ _ cell.2.2.1).2
 have hs:st.start ≤ B:=(wb.2.2.1 _ _ cell.2.2.2.1).2
 rcases cell with ⟨_hq,hwidth,haddress,hstart,_ht⟩
 simp only[Nat.add_assoc] at hwidth haddress hstart
 constructor
 · simp[setup,readable,Op.readable,Op.apply,writeNat,next,h.directory,h.index,
    hwidth,haddress,hstart,Nat.mul_comm i 5,Nat.add_assoc]
 · simp[setup,peak,Op.peak,Op.apply,writeNat,next,h.source,h.directory,h.index,
    hwidth,haddress,hstart,Nat.mul_comm i 5,Nat.add_assoc]
   omega

def Frame (s u:State):Prop:=u.natHeap=s.natHeap ∧u.outputs=s.outputs ∧u.rootOrders=s.rootOrders ∧
 (∀q,q≠32 → q≠126 → u.scalarReg q=s.scalarReg q) ∧
 ∀q,(q<147 ∨154 ≤ q) → (q<4460 ∨4463 ≤ q) → (q<4464 ∨4471 ≤ q) →
 (q<4476 ∨4480 ≤ q) → u.natReg q=s.natReg q
lemma setup_frame (s:State):Frame s (applyBlock setup s):=by
 refine ⟨rfl,rfl,rfl,fun _ _ _=>rfl,?_⟩
 intro q h0 h1 h2 h3
 simp (disch:=omega) [setup,applyBlock,Op.apply,writeNat,next]
lemma frame_compose {s u v:State} (h:Frame s u) (k:UniformSectorPaddingMachine.Frame u v):Frame s v:=
 ⟨k.1.trans h.1,k.2.1.trans h.2.1,k.2.2.1.trans h.2.2.1,
 fun q hq hj=>(k.2.2.2.1 q hq hj).trans (h.2.2.2.1 q hq hj),
 fun q h0 h1 h2 h3=>(k.2.2.2.2 q h0 h2).trans (h.2.2.2.2 q h0 h1 h2 h3)⟩
/-- Genuine five-cell directory + genuine packed source. All helper headers,
role0 moves and prepared zero padding are generated by this fixed program. -/
theorem execution {W S E A i total B n:ℕ} (st:UniformSectorPacking.BlockState)
 (v:Fin total → Scalar) (x:Fin n → ℂ) (s:State) (h:Header S E i s)
 (cell:UniformSectorBatchDirectoryMachine.BatchCell W E A i st s)
 (source:UniformSectorPaddingMachine.Source v S s) (fit:st.start+st.width ≤ total)
 (positive:0 < W) (roles:W ≤ B) (sep:S+total ≤ A) (buffer:A+W*total ≤ B)
 (readFit:E+5*(i+1) ≤ B) (code:37 ≤ B) (pc:s.pc=0) (wb:WordBound B s):
 ∃u,BoundedExecution (programFor W) n x B s (5*(W*st.width)+2*st.width+27) u ∧u.pc=36 ∧
 UniformSectorPaddingMachine.Prefix
  (fun t:Fin st.width=>v ⟨st.start+t.val,by have tt:=t.isLt;omega⟩)
  (A+W*st.start) (W*st.width) u ∧Frame s u ∧
 UniformSectorPaddingMachine.Outside (A+W*st.start) (W*st.width) s u:=by
 have aw:=Nat.mul_le_mul_left W fit
 have safe:=setup_safe h cell readFit (by omega) wb
 have first:=block_runs setup (programFor W) 0 n B x s (setup_code W) pc wb
  (by change 0+11 ≤ B;omega) safe.1 safe.2
 let ready:=setPC (applyBlock setup s) 0
 let localValues:Fin st.width → Scalar:=fun t=>v ⟨st.start+t.val,by have tt:=t.isLt;omega⟩
 have src:UniformSectorPaddingMachine.Source localValues (S+st.start) ready:=by
  intro t
  simpa only[ready,setPC,setup,applyBlock,Op.apply,writeNat,next,Nat.add_assoc] using
   source ⟨st.start+t.val,by have tt:=t.isLt;omega⟩
 obtain ⟨c,pad,cp,filled,frame,out,_sourceKept⟩:=UniformSectorPaddingMachine.execution (W:=W) (L:=st.width) (a:=S+st.start)
  (d:=A+W*st.start) (B:=B) (n:=n) localValues x ready
  (by
   have hh:=setup_header h cell
   exact ⟨hh.width,hh.source,hh.target⟩) src positive roles (by omega) (by nlinarith) (by omega) rfl
  (changePC_bound B _ 0 first.final_bound (by omega))
 have moved:=UniformBoundedAssembly.boundedExecution_placed (padding_code W)
  (by rw[UniformSectorPaddingMachine.program_length];omega) (by omega) pad
 have p:(applyBlock setup s).pc=11:=by rw[applyBlock_pc,pc];rfl
 rw[UniformMultiAxisSectorMetadataPreparation.placed_zero _ _ p] at moved
 let u:=setPC c 36
 have stop:BoundedExecution (programFor W) n x B u 1 u:=
  .halt moved.final_bound (by simp[step,u,setPC,halt_at])
 refine ⟨u,?_,rfl,filled,frame_compose (setup_frame s) frame,out⟩
 convert first.executes (moved.executes stop) using 1
 change 5*(W*st.width)+2*st.width+27=11+(5*(W*st.width)+2*st.width+15+1)
 omega
end
end ExactFourierCircuits.UniformSectorPaddingPreparation
