import UniformFinalPointwiseCRTCaller
import UniformFinalClockHeapTransform
import UniformFinalRoleClockValues
set_option autoImplicit false
namespace ExactFourierCircuits.UniformFinalMovementCaller
open UniformMachine UniformFinalNumericJoin UniformFinalMovementFrame UniformFinalMovementGeometry
open UniformSelectedPhysicalCRT
noncomputable section
local notation "c" => UniformActualGlobalConstants.constants
abbrev W:ℕ:=UniformRecursiveSelfCallMachine.W
abbrev sourceBase:=UniformFinalMovementGeometry.S
abbrev targetBase:=UniformFinalMovementGeometry.T

/-- Stored fields already generated by allocation and the charged outer
headers. No scalar/table result is included in this ordinary header. -/
structure Header (n:ℕ)(s:State):Prop where
 volume:s.natReg 103=V n
 source:s.natReg 6026=sourceBase n
 target:s.natReg 6025=targetBase n
 storage:s.natReg 7300=Q n
 alpha:s.natReg 7310=AP n
 inverse:s.natReg 7311=BI n

structure Tables (n:ℕ)(s:State):Prop where
 alpha:UniformGlobalNatPreparation.PermutationBank (V n) (AP n) s.natHeap (physicalAlpha n)
 inverse:UniformGlobalNatPreparation.PermutationBank (V n) (BI n) s.natHeap (physicalBeta n).symm

lemma Header.transport {n:ℕ}{s u:State}(h:Header n s)(frame:Frame n s u):Header n u:=
 ⟨(frame.saved _ (by omega) (by omega)).trans h.volume,
 (frame.high _ (by omega) (by omega) (by omega)).trans h.source,
 (frame.high _ (by omega) (by omega) (by omega)).trans h.target,
 (frame.high _ (by omega) (by omega) (by omega)).trans h.storage,
 (frame.high _ (by omega) (by omega) (by omega)).trans h.alpha,
 (frame.high _ (by omega) (by omega) (by omega)).trans h.inverse⟩

lemma Tables.transport {n:ℕ}{s u:State}(h:Tables n s)(frame:Frame n s u):Tables n u:=by
 constructor <;> rw[frame.natHeap]
 · exact h.alpha
 · exact h.inverse

/-- Save first-clock role1 under the actual selected allocation. All fit
conditions are discharged by the proved common word envelope. -/
theorem save {n:ℕ}(hn:0<n)(x:Fin n→ℂ)(f:Fin (V n)→ℂ)(s:State)
 (header:Header n s)(input:NumericValues (sourceBase n+V n) f s)
 (tags:∀j,(scalars (V n) (sourceBase n+V n) s j).dependent=false)
 (pc:s.pc=0)(wb:WordBound (B n) s):
 ∃u,BoundedExecution UniformKernelSpectrumCopy.program n x (B n) s (7*V n+9) u∧
 (∀j:Fin (V n),u.scalarHeap (Q n+j.val)=some (UniformPairMachine.prepared (f j)))∧
 Frame n s u∧UniformKernelSpectrumCopy.Frame (Q n) (V n) s u∧u.pc=14:=by
 dsimp only[sourceBase] at *
 have fit:=fits hn
 exact UniformFinalPreparedSpectrumSave.execution x f s input tags
  header.volume header.source header.storage (by have:=fit.adjacent;omega)
  fit.source (by have:=fit.adjacent;have:=fit.source;omega) (by have:=fit.code;omega) pc wb

/-- Actual pointwise multiplication followed by BI/AP movement, with exact
all-role inputs for the third clock. No desired final action is an input. -/
theorem pointwise_crt {n:ℕ}(hn:0<n)(x:Fin n→ℂ)
 (v:ℕ→Fin (V n)→Scalar)(y:Fin (V n)→ℂ)(s:State)
 (header:Header n s)(tables:Tables n s)
 (input:UniformRolePointwiseMachine.Source W (V n) (sourceBase n) v s)
 (prepared:∀j:Fin (V n),s.scalarHeap (Q n+j.val)=some (UniformPairMachine.prepared (y j)))
 (pc:s.pc=0)(wb:WordBound (B n) s):
 ∃p u,UniformSequentialExecution.LocalStages n (B n) x
  [UniformRolePointwiseMachine.program,UniformPhysicalCRTConsumerMachine.program]
  s ((9*V n+9)+(18*V n+18)) u∧
 NumericValues (sourceBase n) (fun j=>(v 0 j).value*y j) p∧
 (∀j:Fin (V n),u.scalarHeap (sourceBase n+j.val)=p.scalarHeap (sourceBase n+((physicalBeta n).symm (physicalAlpha n j)).val))∧
 (∀j:Fin (V n),u.scalarHeap (targetBase n+j.val)=p.scalarHeap (sourceBase n+((physicalBeta n).symm j).val))∧
 UniformRolePointwiseMachine.Source W (V n) (sourceBase n)
  (UniformFinalCRTRoleSource.values (UniformRolePointwiseMachine.multiplied v y)
   (physicalAlpha n) (physicalBeta n)) u∧
 (∀j:Fin (V n),u.scalarHeap (Q n+j.val)=some (UniformPairMachine.prepared (y j)))∧
 Frame n s u∧u.pc=33:=by
 dsimp only[sourceBase,targetBase,W] at *
 have fit:=fits hn
 have afterRoles:=roles_before_target hn
 have roles:0<UniformRecursiveSelfCallMachine.W:=
  lt_of_lt_of_le (by decide:0<2) UniformFinalRoleGeometry.roles_two
 exact UniformFinalPointwiseCRTCaller.execution x v y (physicalAlpha n) (physicalBeta n) s pc
  roles header.volume header.source header.target
  header.alpha header.inverse header.storage input prepared tables.alpha tables.inverse
  fit.adjacent.le fit.disjoint afterRoles (by have:=fit.target;omega) fit.target
  (by have:=fit.adjacent;have:=fit.source;omega) fit.alpha fit.inverse fit.beforeTarget fit.code wb

/-- The final CRT helper exposes the exact standard-output heap, including
tags, while retaining the protected prepared seed and calendar banks. -/
theorem final_crt {n:ℕ}(hn:0<n)(x:Fin n→ℂ)(f:Fin (V n)→ℂ)(s:State)
 (header:Header n s)(tables:Tables n s)(input:NumericValues (sourceBase n) f s)
 (pc:s.pc=0)(wb:WordBound (B n) s):
 ∃u,BoundedExecution UniformPhysicalCRTConsumerMachine.program n x (B n) s (18*V n+18) u∧
 (∀j:Fin (V n),u.scalarHeap (sourceBase n+j.val)=s.scalarHeap (sourceBase n+((physicalBeta n).symm (physicalAlpha n j)).val))∧
 (∀j:Fin (V n),u.scalarHeap (targetBase n+j.val)=s.scalarHeap (sourceBase n+((physicalBeta n).symm j).val))∧
 NumericValues (sourceBase n) (fun j=>f ((physicalBeta n).symm (physicalAlpha n j))) u∧
 NumericValues (targetBase n) (fun j=>f ((physicalBeta n).symm j)) u∧
 Frame n s u∧
 (∀a,(a<sourceBase n∨sourceBase n+V n≤a)→(a<targetBase n∨targetBase n+V n≤a)→u.scalarHeap a=s.scalarHeap a)∧
 UniformPhysicalCRTConsumerMachine.Frame s u∧u.pc=33:=by
 dsimp only[sourceBase,targetBase] at *
 have fit:=fits hn
 exact UniformFinalCRTMovement.execution x f (physicalAlpha n) (physicalBeta n) s pc
  header.volume header.source header.target header.alpha header.inverse input tables.alpha tables.inverse
  fit.disjoint (by have:=fit.source;omega) fit.target fit.alpha fit.inverse fit.beforeSource fit.beforeTarget
  (by have:=fit.code;omega) wb

end
end ExactFourierCircuits.UniformFinalMovementCaller
