import UniformLocalCacheTreeExecution

set_option autoImplicit false
namespace ExactFourierCircuits.UniformLocalCacheTreeCoverage
open UniformLocalCacheTreeMachine UniformWorkspacePlanner
open UniformLocalRectangleDescriptors (Row rows emittedCount)

/-- The local request list ignores physical parent identifiers; those identifiers
are carried and stored by the actual DFS execution theorem. -/
def pendingRows (tasks:List Task):List Row:=
 (tasks.map fun t=>(ofPlan (UniformBalancedToeplitz.plan t.width) t.offset).rectangles).flatten

def currentRows (t:Task):List Row:=
 if t.width<2 ∨selected t.width=0 then [] else rows t.width t.offset (selected t.width)

def visitedRows (visits:List Visit):List Row:=
 (visits.map fun q=>currentRows q.task).flatten

lemma task_decomposition (t:Task) (k:ℕ):
 (ofPlan (UniformBalancedToeplitz.plan t.width) t.offset).rectangles=
 currentRows t++pendingRows (children t k):=by
 rw [UniformBalancedToeplitz.plan]
 split
 · rename_i h
   simp only [ofPlan,Tree.rectangles,currentRows,children,ite_eq_left h,pendingRows,
    List.map_nil,List.flatten_nil,List.append_nil]
 · rename_i h
   simp only [ofPlan,Tree.rectangles,currentRows,children,ite_eq_right h,pendingRows,
    List.map_cons,List.map_nil,List.flatten_cons,List.flatten_nil,List.append_nil,List.append_assoc]

lemma pendingRows_append (ts us:List Task):pendingRows (ts++us)=pendingRows ts++pendingRows us:=by
 simp only [pendingRows,List.map_append,List.flatten_append]

lemma pendingRows_cons (t:Task) (ts:List Task):pendingRows (t::ts)=
 (ofPlan (UniformBalancedToeplitz.plan t.width) t.offset).rectangles++pendingRows ts:=rfl

lemma walk_preserves_rows (fuel k c:ℕ) (tasks:List Task):
 visitedRows (walk fuel k c tasks).1++pendingRows (walk fuel k c tasks).2=pendingRows tasks:=by
 induction fuel generalizing k c tasks with
 | zero=>simp [walk,visitedRows]
 | succ fuel ih=>
   cases tasks with
   | nil=>simp [walk,visitedRows,pendingRows]
   | cons t ts=>
     have tail:=ih (k+1) (c+7*emittedCount t.width) (children t k++ts)
     have decomp:=task_decomposition t k
     simp only [walk,visitedRows,List.map_cons,List.flatten_cons]
     change (currentRows t++visitedRows (walk fuel (k+1) (c+7*emittedCount t.width) (children t k++ts)).1)++
       pendingRows (walk fuel (k+1) (c+7*emittedCount t.width) (children t k++ts)).2=_
     rw [List.append_assoc,tail]
     rw [pendingRows_append,pendingRows_cons]
     rw [←List.append_assoc,←decomp]

lemma root_walk_rows (v o R:ℕ):
 visitedRows (walk (2*v+1) 0 R [⟨v,o,0,0⟩]).1=
 (ofPlan (UniformBalancedToeplitz.plan v) o).rectangles:=by
 have done:=walk_finished (2*v+1) 0 R [⟨v,o,0,0⟩] (by
  simpa only [List.map_cons,List.map_nil,List.sum_cons,List.sum_nil,Nat.add_zero] using taskWeight_root v o)
 have h:=walk_preserves_rows (2*v+1) 0 R [⟨v,o,0,0⟩]
 simpa only [done,pendingRows,List.map_nil,List.flatten_nil,List.append_nil,
  List.map_cons,List.flatten_cons] using h

/-- Every actual balanced request occurs in the directory generated by the
physical traversal; only preparation order changes. -/
lemma root_walk_kernel_coverage (v o R:ℕ):
 ((visitedRows (walk (2*v+1) 0 R [⟨v,o,0,0⟩]).1).map Row.kernel).Perm
 ((UniformLocalPreparationDAG.requests (UniformBalancedToeplitz.plan v) (le_refl v)).map requestKernel):=by
 rw [root_walk_rows]
 exact ofPlan_kernel_coverage _ _ _

lemma root_walk_rectangle_bound (v o R:ℕ):
 (visitedRows (walk (2*v+1) 0 R [⟨v,o,0,0⟩]).1).length≤v^2:=by
 rw [root_walk_rows]
 exact ofPlan_rectangles_length _ _

lemma currentRows_length(t:Task):(currentRows t).length=emittedCount t.width:=by
 unfold currentRows emittedCount
 split
 · rfl
 · exact UniformLocalRectangleDescriptors.rows_length _ _ _
lemma visitedRows_length(visits:List Visit):(visitedRows visits).length=
 UniformLocalCacheTreeExecution.visitSum visits:=by
 simp only [visitedRows,UniformLocalCacheTreeExecution.visitSum,List.length_flatten,
  List.map_map,Function.comp_def,currentRows_length]
lemma root_walk_visitSum_bound(v o R:ℕ):
 UniformLocalCacheTreeExecution.visitSum (walk (2*v+1) 0 R [⟨v,o,0,0⟩]).1≤v^2:=by
 rw [←visitedRows_length]
 exact root_walk_rectangle_bound v o R

end ExactFourierCircuits.UniformLocalCacheTreeCoverage
