import UniformSectorMetadataCountBridge
import UniformSectorBatchDirectoryMachine
set_option autoImplicit false
namespace ExactFourierCircuits.UniformProducedSectorBatchPreparation
open UniformMachine UniformAssembly
open UniformTensorMonomialMachine (setPC)
noncomputable section
/-- Actual124 metadata production followed continuously by actual33 batch
address production. Both helper halts become charged jumps; no phase callback. -/
def programFor (W:ℕ):Program:=
 UniformMultiAxisSectorMetadataPreparation.program.map (relocate 0 124)++
 (UniformSectorBatchDirectoryMachine.programFor W).map (relocate 124 157)++[.halt]
def program:Program:=programFor ExplicitSeedBudget.paddedRoles
lemma program_length (W:ℕ):(programFor W).length=158:=by
 simp only[programFor,List.length_append,List.length_map,
  UniformMultiAxisSectorMetadataPreparation.program_length,
  UniformSectorBatchDirectoryMachine.program_length,List.length_singleton]
lemma metadata_code (W:ℕ):CodeAt UniformMultiAxisSectorMetadataPreparation.program (programFor W) 0 124:=by
 exact UniformRankCrossPreparationMachine.segment_code []
  ((UniformSectorBatchDirectoryMachine.programFor W).map (relocate 124 157)++[.halt]) _ 0 124 rfl
lemma batch_code (W:ℕ):CodeAt (UniformSectorBatchDirectoryMachine.programFor W) (programFor W) 124 157:=by
 exact UniformRankCrossPreparationMachine.segment_code
  (UniformMultiAxisSectorMetadataPreparation.program.map (relocate 0 124)) [.halt] _ 124 157
  (by rw[List.length_map,UniformMultiAxisSectorMetadataPreparation.program_length])
lemma halt_at (W:ℕ):(programFor W)[157]?=some .halt:=by
 unfold programFor
 rw[List.getElem?_append_right (by simp only[List.length_append,List.length_map,
  UniformMultiAxisSectorMetadataPreparation.program_length,
  UniformSectorBatchDirectoryMachine.program_length];omega)]
 simp only[List.length_append,List.length_map,UniformMultiAxisSectorMetadataPreparation.program_length,
  UniformSectorBatchDirectoryMachine.program_length];rfl

/-- Real four-word axis rows and real width cells are inputs. Projection,
suffixes, sectors, count, and all five-cell batch records are generated by
this same executed program. Padding data and recursive action are not asserted. -/
theorem execution {W E A:ℕ} (as:List UniformSectorPackingMachine.PhysicalAxis)
 (L:UniformSectorMetadataMachine.Layout) (n a:ℕ) (x:Fin n→ℂ) (s:State)
 (hlen:as.length=L.ell) (hvolume:UniformSectorPackingMachine.physicalVolume as=L.total)
 (rows:UniformSectorPackingMachine.Rows as 0 a s) (widths:UniformSectorPackingMachine.Widths as s)
 (below:∀ax∈as,ax.widthsBase+ax.geometry.widths.length≤L.rows)
 (sep:a+4*L.ell≤L.rows) (entry:E+5*L.total≤L.B) (buffer:A+W*L.total≤L.B)
 (source:L.directory+3*L.total≤E) (roles:W≤L.B) (code:158≤L.B) (pc:s.pc=0)
 (count:s.natReg 102+1=L.ell) (ha:s.natReg 3201=a) (hd:s.natReg 3202=L.rows)
 (hs:s.natReg 3213=L.suffix) (ht:s.natReg 3214=L.stack) (hq:s.natReg 3215=L.directory)
 (he:s.natReg 4441=E) (hb:s.natReg 4442=A) (wb:WordBound L.B s):
 ∃ u, BoundedExecution (programFor W) n x L.B s
  (UniformSectorMetadataMachine.treeCost
    (UniformSectorMetadataMachine.counts (UniformMultiAxisSectorMetadataPreparation.metadataAxes as))+
   43*L.ell+24*(UniformSectorPacking.sectorStates (UniformSectorPackingMachine.physicalAxes as)).length+42) u ∧
 u.pc=157 ∧
 UniformSectorBatchDirectoryMachine.Written W E A
  (UniformSectorPacking.sectorStates (UniformSectorPackingMachine.physicalAxes as)).length
  (UniformSectorPacking.sectorStates (UniformSectorPackingMachine.physicalAxes as)) u ∧
 UniformSectorBatchDirectoryMachine.Table L.directory
  (UniformSectorPacking.sectorStates (UniformSectorPackingMachine.physicalAxes as)) u ∧
 u.natReg 464=(UniformSectorPacking.sectorStates (UniformSectorPackingMachine.physicalAxes as)).length ∧
 UniformMultiAxisSectorMetadataPreparation.Retention s u ∧
 (∀j,j<L.rows→u.natHeap j=s.natHeap j):=by
 obtain ⟨v,metaRun,vpc,header,dir,suffix,num,ret,low,outside⟩:=
  UniformSectorMetadataCountBridge.execution_count as L n a x s hlen hvolume rows widths below sep
   (by omega) pc count ha hd hs ht hq wb
 have movedM:=UniformBoundedAssembly.boundedExecution_placed (metadata_code W)
  (by rw[UniformMultiAxisSectorMetadataPreparation.program_length];omega) (by omega) metaRun
 rw[show placed 0 s=s by cases s;simp[placed]] at movedM
 let xs:=UniformSectorPacking.sectorStates (UniformSectorPackingMachine.physicalAxes as)
 let ready:=setPC v 0
 have rb:=changePC_bound L.B v 0 metaRun.final_bound (by omega)
 have args:=UniformSectorMetadataCountBridge.execution_arguments metaRun
 have readyHeader:UniformSectorBatchDirectoryMachine.Header L.directory E A xs.length ready:=by
  refine ⟨(args 3215 (by simp)).trans hq,?_,(args 4441 (by simp)).trans he,(args 4442 (by simp)).trans hb⟩
  simpa only[ready,setPC,xs,UniformSectorBatchDirectoryMachine.sector_count,
   UniformSectorMetadataMachine.counts,UniformMultiAxisSectorMetadataPreparation.metadataAxes_geometry] using num
 have countBound:xs.length≤L.total:=by
  have cap:=UniformSectorMetadataMachine.sector_count_le_volume
   (UniformMultiAxisSectorMetadataPreparation.metadataAxes as)
  simpa only[xs,UniformSectorBatchDirectoryMachine.sector_count,
   UniformSectorMetadataMachine.counts,UniformMultiAxisSectorMetadataPreparation.metadataAxes_geometry,
   UniformMultiAxisSectorMetadataPreparation.metadataAxes_volume,hvolume] using cap
 have fits:∀j,∀ (hj:j<xs.length),(xs[j]'hj).start+(xs[j]'hj).width≤L.total:=by
  simpa only[xs,hvolume] using UniformSectorBatchDirectoryMachine.sector_fits
   (UniformSectorPackingMachine.physicalAxes as)
 obtain ⟨v',batchRun,v'pc,filled,table,frame,out⟩:=
  UniformSectorBatchDirectoryMachine.execution xs x ready readyHeader
   (UniformSectorBatchDirectoryMachine.directory_table L xs v dir) fits
   (by omega) buffer (by omega) roles (by omega) rfl rb
 have movedB:=UniformBoundedAssembly.boundedExecution_placed (batch_code W)
  (by rw[UniformSectorBatchDirectoryMachine.program_length];omega) (by omega) batchRun
 rw[show placed 124 ready=setPC v 124 by cases v;rfl] at movedB
 let u:=setPC v' 157
 have stop:BoundedExecution (programFor W) n x L.B u 1 u:=
  .halt movedB.final_bound (by simp[step,u,setPC,halt_at])
 have batchRetention:UniformMultiAxisSectorMetadataPreparation.Retention v u:=
  ⟨frame.1,frame.2.1,frame.2.2.1,frame.2.2.2.1,
   fun i hi hj=>frame.2.2.2.2 i (by omega) (by omega)⟩
 refine ⟨u,?_,rfl,filled,table,?_,ret.trans batchRetention,?_⟩
 · convert movedM.executes (movedB.executes stop) using 1
   dsimp[xs]
   omega
 · exact (frame.2.2.2.2 464 (by omega) (by omega)).trans readyHeader.count
 · intro j hj
   have order:=L.rowsBelow
   have order1:=L.suffixBelow
   have order2:=L.stackBelow
   exact (out j (Or.inl (by omega))).trans (low j hj)
end
end ExactFourierCircuits.UniformProducedSectorBatchPreparation
