import UniformPhysicalCRTArithmetic
import UniformGenericPhysicalCoordinate
set_option autoImplicit false
namespace ExactFourierCircuits.UniformPhysicalCRTCoordinates
open UniformPhysicalCRTArithmetic UniformCRTTraversalCycle UniformGenericPhysicalCoordinate
open scoped BigOperators
noncomputable section

lemma list_digit (rs:List ℕ) (positive:∀r∈rs,0<r) (ds:∀j:Fin rs.length,Fin (rs.get j)) (j:Fin rs.length):
 ((listCoordinate rs ds).val/(rs.drop (j.val+1)).prod)%rs.get j=(ds j).val:=by
 induction rs with
 | nil=>exact Fin.elim0 j
 | cons r rs ih=>
  have tailpositive:∀q∈rs,0<q:=fun q h=>positive q (List.mem_cons_of_mem r h)
  have tp:0<rs.prod:=List.prod_pos tailpositive
  refine Fin.cases ?_ (fun j=>?_) j
  · change ((listCoordinate rs (fun i=>ds i.succ)).val+rs.prod*(ds 0).val)/rs.prod%r=(ds 0).val
    rw[Nat.add_mul_div_left _ _ tp,Nat.div_eq_of_lt (listCoordinate rs (fun i=>ds i.succ)).isLt]
    simp only[Nat.zero_add]
    apply Nat.mod_eq_of_lt
    simpa only[List.get_eq_getElem,List.getElem_cons_zero,Fin.val_zero] using (ds 0).isLt
  · change ((listCoordinate rs (fun i=>ds i.succ)).val+rs.prod*(ds 0).val)/
     (rs.drop (j.val+1)).prod%rs.get j=(ds j.succ).val
    let P:ℕ:=(rs.take j.val).prod
    let S:ℕ:=(rs.drop (j.val+1)).prod
    have sp:0<S:=List.prod_pos (fun q h=>tailpositive q (List.mem_of_mem_drop h))
    have product:rs.prod=P*(rs.get j*S):=by
     have h:=List.prod_take_mul_prod_drop rs j.val
     rw[List.drop_eq_getElem_cons j.isLt,List.prod_cons] at h
     exact h.symm
    have eq:rs.prod*(ds 0).val=S*((P*(ds 0).val)*rs.get j):=by rw[product];ring
    rw[eq,Nat.add_mul_div_left _ _ sp,Nat.add_mul_mod_self_right]
    exact ih tailpositive (fun i=>ds i.succ) j

lemma physical_digit {a:ℕ}(r:Fin a→ℕ) (hr:∀i,0<r i) (ds:∀i,Fin (r i)) (j:Fin a):
 digit r (physical r ds).val j=(ds j).val:=by
 let f:=((Equiv.piCongr (index r) (fun i=>finCongr (shape r i))).symm ds)
 let i:Fin (List.ofFn r).length:=(index r).symm j
 have positive:∀q∈List.ofFn r,0<q:=by
  intro q h
  obtain ⟨k,rfl⟩:=List.mem_ofFn.mp h
  exact hr k
 have h:=list_digit (List.ofFn r) positive f i
 have axis:index r i=j:=Equiv.apply_symm_apply _ j
 have hv:(physical r ds).val=(listCoordinate (List.ofFn r) f).val:=rfl
 have hi:i.val=j.val:=rfl
 have radix:(List.ofFn r).get i=r j:=(shape r i).trans (congrArg r axis)
 have fi:(f i).val=(ds j).val:=by
  dsimp only[f]
  simp only[Equiv.piCongr_symm_apply,castval]
  exact congrArg (fun k:Fin a=>(ds k).val) axis
 simpa only[digit,suffix,hv,hi,radix,fi] using h


/-- Reorder physical MSB ordinals into the concrete normal least-axis-first
ordinal generated by the existing CRT program. -/
def rho {a:ℕ}(r:Fin a→ℕ) (hr:∀i,0<r i):Fin (∏i,r i)≃Fin (∏i,r i):=
 (physical r).symm.trans (decodeEquiv r hr).symm
lemma rho_value {a:ℕ}(r:Fin a→ℕ) (hr:∀i,0<r i) (p:Fin (∏i,r i)):
 (rho r hr p).val=normal r p.val:=by
 change encoded r (fun i=>((physical r).symm p i).val)=encoded r (digit r p.val)
 congr 1
 funext i
 have h:=physical_digit r hr ((physical r).symm p) i
 rw[Equiv.apply_symm_apply] at h
 exact h.symm
end
end ExactFourierCircuits.UniformPhysicalCRTCoordinates
